### ISSUE TITLE
LCFS - Implement Notification Management Views

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#100]
**Description**: 
This ticket involves the implementation of new Notification Management views for the LCFS application. The task requires aligning these views with the existing FastAPI backend system. The implementation will follow the forthcoming wireframes closely, ensuring a consistent and user-friendly interface. Additionally, it involves updating any existing Notification Management class-based components to functional-based components in line with modern ReactJS best practices.

**Purpose**: 
The primary goal of this task is to enhance the frontend of the LCFS application by introducing Notification Management views.
IDIR analyst
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164099268?mode=m
IDIR manager
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164108362?mode=m
IDIR director
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164108363?mode=m
BCeID all
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164101848?mode=m

**Acceptance Criteria**: 
- [ ] Review and implement the new Notification Management views according to the provided wireframes.
- [ ] Convert all Notification Management class-based components to functional-based components following ReactJS conventions.
- [ ] Ensure seamless integration of the Notification Management views with the FastAPI backend, particularly with relevant API endpoints.
- [ ] Conduct thorough testing of the new Notification Management views, covering various user scenarios and operations.
- [ ] Confirm that all tests related to Notification Management pass successfully.
- [ ] Update project documentation and code comments to accurately reflect the changes made in the Notification Management system.

**Comment by airinggov** [comment]
Closed, work completed in card #118

**Comment by hamed-valiollahi** [comment]
@airinggov Hi Al, I've checked, and everything from this card has been implemented in #118. 👍
