### ISSUE TITLE
LCFS - Compliance report, internal workflow, Recommended by manager status, IDIR Director role

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1005]
Compliance report, internal workflow, Recommended by manager status, IDIR Director role

**Description:**  
The report will have two buttons to Issue assessment and Return to compliance manager. IDIR users in Analyst or Compliance manager roles will not see these buttons.

Once the Director has clicked the Issue assessment button the report is put into Assessed status, this transaction is recorded in the report history section above the compliance manger recommend info as per mock-up. Note the BCeID version displays different text.
IDIR version
•	Assessed [date time stamp] PST by [IDIR director first name, last name].

BCeID version (government staff names are not displayed on BCeID version, the Recommended history is also not displayed, see card #1006 )
•	Assessed [date time stamp] PST by the director under the Low Carbon Fuels Act.

The transaction ledger should be updated to capture the change in the suppliers compliance unit balance.

If the director clicks the return button the report will be put back into Recommended by analyst status for the compliance manger to action further. This action is not recorded in the report history. When the compliance manager recommends the report for the second time the original recommended history entry will be updated. This could be a different compliance manager so the name should also be updated if required.

**Wireframe:**  
https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/186169277

**Purpose and benefit to user:**  
The purpose of this workflow is to facilitate the review process for compliance reports by adding decision-making capabilities for the IDIR Director. The Director can either assess or return reports to a compliance manager, and the history of these actions will be appropriately recorded. This improves auditability and ensures that compliance reports are handled efficiently.

**Acceptance Criteria:**  
- [ ] Two buttons are available on the compliance report for IDIR Director role: Issue assessment and Return to compliance manager.
- [ ] The two buttons are only visible to IDIR Directors and not to users with Analyst or Compliance manager roles.
- [ ] Clicking the Issue assessment button changes the report status to "Assessed."
- [ ] A transaction is recorded in the report history section above the compliance manager recommendation, showing:  
  `Assessed <date time stamp> PST by <IDIR director first name, last name>.`
- [ ] Clicking the Return to compliance manager button changes the report status to "Recommended by analyst."
- [ ] No transaction is recorded in the report history for the return action.
- [ ] If the Compliance manager recommends the report again after it was returned, the original recommendation entry is updated, including the compliance manager’s name (if different).

**Development Checklist:**  
- [ ] Implement conditional visibility for Issue assessment and Return to compliance manager buttons, visible only to users with IDIR Director role.
- [ ] Create functionality to change the report status to "Assessed" when the Issue Assessment button is clicked.
- [ ] Log the transaction in the report history with a date, timestamp, and IDIR Director’s name.
- [ ] Create functionality to revert the report status to "Recommended by analyst" when the Return to compliance manager button is clicked, without logging the action.
- [ ] Update the Compliance manager recommendation entry upon subsequent recommendations, ensuring the manager's name is updated if necessary.

**Notes:**  

- Ensure that the workflow follows the role-specific visibility for actions. The history log should be automatically updated upon assessment but not for the return action.

- Date/Times are displayed in PST

**Comment by airinggov** [comment]
Everything works great but the Issue assessment button gives a 500 error

**Comment by Grulin** [comment]
The 500 error has been resolved, but the "issue assessment" and "return to compliance manager" buttons are missing for the director on the compliance report that has been recommended by the manager.
