### ISSUE TITLE
LCFS - Final assessed report, BCeID & IDIR

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1006]
**Description:**  
The final assessed report feature for both BCeID and IDIR systems will include updates to the report history box and assessment messages. For BCeID users, the report history box is renamed to "Assessment" and displays whether the organization has met renewable and low carbon fuel targets, as well as report history details like signing and submission information. A new button for creating supplemental reports is also introduced. IDIR users will see additional details, including the director's name in the assessment history.

**Wireframe:**  
[BCeID Wireframe](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/186573409/simulate/no-panels)  
[IDIR Wireframe](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/186182865/simulate/no-panels)

**Purpose and benefit to user:**  
For BCeID users, the updated assessment section provides clear feedback on whether fuel targets are met and offers easy access to create supplemental reports if needed. For IDIR users, the inclusion of the director's name in the assessment provides greater transparency.

**Acceptance Criteria:**  
- [ ] The "Report History" box in BCeID is renamed to "Assessment" and displays the correct fuel target messages based on the report status.
- [ ] The assessment message dynamically displays “has met” or “has not met” based on the report summary.
- [ ] BCeID report history includes timestamps for assessment and submission without displaying government staff names.
- [ ] A new card is present in BCeID allowing users to create supplemental reports, with the appropriate 30-day notice message.
- [ ] In IDIR, the assessment history includes the director’s name along with the date and timestamp of the assessment.

**Development Checklist:**  
- Update the report history box in the BCeID user interface.
- Implement dynamic messages for renewable and low carbon fuel target assessments.
- Ensure timestamps for report history are displayed correctly, without revealing government staff names in BCeID.
- Add a new card with a supplemental report button and notification text.
- Modify IDIR report history to include the director’s name in the assessment section.

**Notes:**  
Ensure that the status (met or not met) for fuel targets is determined automatically based on the report summary data. The government staff names should not be visible to BCeID users.

**Comment by Grulin** [comment]
Hi @prv-proton! Blocked from testing this one because of an error when accepting the report on the IDIR side with a director role:

![Image](https://github.com/user-attachments/assets/1d06fee8-4f68-4f10-9d05-1a730ac90db7)

500 is a permissions error, right? I definitely have my role set to "Director"

**Comment by Grulin** [comment]
Unable to test until bug identified in card #1129 has been fixed

**Comment by airinggov** [comment]
there are newer design changes in card 1071, closing this card as a result
