### ISSUE TITLE
LCFS - Implement and Configure Webpack for Frontend ReactJS Project

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#101]
**Describe the task**
This task involves implementing webpack in the frontend ReactJS project within the LCFS repository. If neccessary, eject the react-scripts build system in favour of webpack. Additionally, the `webpack.config.js` file needs to be configured to match the project’s specific build settings, ensuring optimal performance and build processes. Reference the webpack configuration currently being used in TFRS as a starting point, but ensure to use the latest version of webpack.

**Purpose**
The purpose of this task is to streamline and optimize the build process of the ReactJS frontend by implementing webpack. By configuring the `webpack.config.js` file according to the project’s requirements, the task aims to achieve faster build times, optimized asset handling, and an overall improved development and production workflow.

**Acceptance Criteria**
- [ ] Implement webpack in the frontend ReactJS project using the latest version of webpack.
- [ ] Configure the `webpack.config.js` file to align with the project's build settings.
- [ ] Reference the webpack configuration currently used in TFRS as a guide, but ensure optimizations and updates are made to leverage the latest webpack features.
- [ ] Ensure that the build process efficiently handles assets, code splitting, and optimization.
- [ ] Test the build process to validate that the webpack configuration is effective and error-free.
- [ ] Document the configuration and setup process within the project's documentation.
- [ ] Make sure the build and deployment work with docker image

**Additional context**
- During the configuration process, focus on achieving an optimized and efficient build process that caters to both development and production environments.
- Stay abreast of best practices and webpack documentation to ensure the configuration adheres to modern standards.
- Keep in mind that while the TFRS configuration serves as a reference, the goal is to utilize the most updated and optimized configuration possible with the latest version of webpack.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/101?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
