### ISSUE TITLE
LCFS - BUG - Internal status display on BCeID side

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1012]
**Describe the Bug**
Internal workflow statuses are incorrectly appearing on the Compliance report index page on the BCeID side. Specifically, two internal "Recommended" statuses are visible to users logged in with BCeID, but they should appear as "Submitted" instead.

![Image](https://github.com/user-attachments/assets/52935d56-9630-4f66-83c1-71172846ceb8)

**Expected Behaviour**
The two internal "Recommended" statuses should not be visible on the BCeID side. Instead, they should display as "Submitted" for users logged in with BCeID.

**Actual Behaviour**
The internal "Recommended" statuses are incorrectly appearing on the BCeID side, causing confusion for users who should only see the status as "Submitted."

**Implications**
This issue may lead to user confusion and potential misinterpretation of the workflow status, as BCeID users are seeing internal statuses that are not relevant to their role or permissions.

**Steps To Reproduce**
User/Role: BCeID User
1. Log in with a BCeID account.
2. Navigate to the Compliance report index.
3. Observe the internal workflow statuses (e.g., "Recommended") being shown instead of "Submitted."

**Comment by kevin-hashimoto** [comment]
supposedly fixed in #1005.
currently waiting on a deployment issue fix to confirm if this was fixed in the above ticket

**Comment by kevin-hashimoto** [comment]
confirmed resolved in #1005 and pushed to dev
