### ISSUE TITLE
LCFS - Summary table compare mode

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1013]
**Description:**
**Front-end work only as multiple summary snapshots are not available yet. Additional content in card regarding data loading is for context only.**

Create a new version of the Summary tables that allows users to compare historical versions of summary ‘snapshots’. The user can select between different versions of an assessed compliance report (e.g., early issuance and supplemental reports) using a select list. The select list will update the data in all three tables, and the column headings will reflect the selected report version. The Renewable Fuel Target Summary will allow users to view only one fuel type at a time, with a radio select to choose between Gasoline, Diesel, and Jet fuel.

**Wireframe:**
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/188313605

**Purpose and benefit to user:**
This feature will enable users to easily compare different versions of compliance reports, providing clarity and ease of access to historical data. Additionally, it allows users to focus on a specific fuel type when viewing the Renewable Fuel Target Summary, enhancing the user experience by displaying only relevant data.

**Acceptance Criteria:**
- [ ] Users can select between different report versions (e.g., early issuance, supplemental) using a select list.
- [ ] Upon selection, the data in all three tables is updated to reflect the chosen report version.
- [ ] Column headings update to indicate the version of the report summary.
- [ ] The Renewable Fuel Target Summary allows selection of one fuel type at a time (Gasoline, Diesel, or Jet fuel).
- [ ] The radio select functionality for choosing fuel types is implemented.

**Development Checklist:**
- [ ] Implement a select list that allows users to choose between different report versions.
- [ ] Ensure the select list updates data in all three summary tables.
- [ ] Update the column headings dynamically based on the selected report version.
- [ ] Implement radio select functionality to allow users to choose between Gasoline, Diesel, and Jet fuel in the Renewable Fuel Target Summary.
- [ ] Test to ensure data is correctly filtered and displayed based on user selections.

**Notes:**
- The radio select for fuel types should clearly highlight the chosen fuel type and update the summary table accordingly.

**Comment by Grulin** [comment]
Unable to submit a supplemental to test this card:
![Image](https://github.com/user-attachments/assets/b45a6676-e117-48cb-8ece-b0da31be02e6)

**Comment by dhaselhan** [comment]
The feature is currently available for testing at:
https://lcfs-dev.apps.silver.devops.gov.bc.ca/compare-reporting
