### ISSUE TITLE
LCFS - Can access data for other suppliers and internal data

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1014]
**Describe the Bug**
As a BCeID user viewing a compliance report or a transaction, it is possible to change the ID number in the URL and access reports/transactions from other suppliers. This presents a major security vulnerability, allowing unauthorized access to sensitive data.

I can also change URL id numbers in org pages and view any user including IDIR user info.

![Image](https://github.com/user-attachments/assets/ac4b29d0-ddbb-4c66-82c1-8f33952eaebf)

**Expected Behaviour**
A BCeID user should only be able to view compliance reports associated with their own account or permissions. Access to reports from other suppliers should be restricted and result in an error or access denied message.

Automated tests should be in place to ensure this never happens.

**Actual Behaviour**
By manually changing the ID number in the URL, a BCeID user can access compliance reports from other suppliers, which should be restricted to authorized users only.

This occurs with:
- admin adjustments
- initiative agreements
- compliance reports
- organization users (but not the transaction data)

It doesn't appear to happen with:
- credit transfers - although it throws an ugly Unexpected Application Error! that should be improved on.

- A blank screen within the standard header/footer would be acceptable for all instances (as and Unauthorized message may actually give the user some degree of info).

**Implications**
This issue poses a serious security risk, allowing users to view confidential reports from other suppliers. It violates data privacy regulations and could lead to significant data breaches.

**Steps To Reproduce**
User/Role: BCeID User
1. Log in with a BCeID account.
2. Navigate to one of your compliance reports.
3. In the URL, manually change the report ID to another supplier's report ID.
4. Observe that the other supplier's compliance report is accessible.

**Comment by Grulin** [comment]
Hi @airinggov. This seems to be fixed, but in testing I noted that the error message says "You do not have permission to view this user's information"

![Image](https://github.com/user-attachments/assets/ef573407-c684-4b1e-9a75-19b0e0ef0877)

You noted above a requirement that the screen should not give an error message and just show as blank. Is that still a requirement you prefer?

**Comment by airinggov** [comment]
@prv-proton @Grulin yes I think it would be better to just be blank, so give no error at all. An error message like this may provide information that we don't want to be giving out.

**Comment by prv-proton** [comment]
Thanks @airinggov for consignation. Should this be across or just for user view?

**Comment by airinggov** [comment]
Yes, I think for all unauthorized type error on the BCeID side. We don't display any error

**Comment by Grulin** [comment]
Thank you both for clarifying. Sending this card back for review.
