### ISSUE TITLE
LCFS - Refine summary lines 6 and 8 to avoid previous inputs from deleted fuel supply to persist

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1019]
**Describe the task**
Refine the behavior of summary lines 6 and 8 in the report summary to ensure that if the fuel supply is deleted or if the user switches between inputs on these lines, they reset to zero. Currently, if a user goes from an excess of renewable content (line 6 available) to no renewable content (line 8 available), the previously input deferred amount on line 6 remains locked in. If a user switches from an input on line 6 to an input on line 8, line 6 should reset to zero, and vice versa. Line 6 and line 8 should never both have values at the same time.

**Purpose**
To ensure that only one of line 6 or line 8 has an active input at any given time. Line 6 availability means they have exceeded their renewable requirement. 

Line 8 availability means they have not met their renewable requirement. 

Therefore, if an input remains in line 6 once the page is refreshed, but line 8 is also available, something has gone wrong. Line 6 should be zeroed out after a change like this. 

**Acceptance Criteria**

- [ ]  If a user deletes the fuel supply, both line 6 and line 8 should reset to zero.
- [ ]  If a user switches from an input on line 6 to line 8, line 6 should automatically reset to zero.
- [ ]  If a user switches from an input on line 8 to line 6, line 8 should automatically reset to zero.
- [ ]  Line 6 and line 8 should never both have active inputs simultaneously.
- [ ]  The functionality should be reviewed to ensure consistency and accuracy across all fuel supply scenarios.

**Additional context**
Coordinate with the development team to ensure that line 6 and line 8 are mutually exclusive, meaning that only one line can have an input at any time.

**Comment by dhaselhan** [comment]
There was an issue with our deployments for the last few days, (Friday till now) meaning that this fix was not correctly deployed previously.
If you re-test this now, it should zero out line 6/8 if there are any changes to the Fuel Supply.

**Comment by Grulin** [comment]
Still not working perfect. I input 100,000 L of renewable content, input the allowable amount to retain in line 6 and then changed the 100,000L to 1,000 L and the allowable amount to retain stayed locked in the line 6 field. Please see screenshot:

![Image](https://github.com/user-attachments/assets/f8f5ea9c-a1ff-4c9a-b474-29319b7d4341)

**Comment by dhaselhan** [comment]
Repeated the above steps on develop, and the field is resetting to 0 as expected whenever changes are made to the fuel supply. Let's try and meet tomorrow to go over this.

**Comment by Grulin** [comment]
Getting a 500 error on this one when I input the allowable retained amount in to line 6 and then click anywhere else on the page. If I refresh, the input for line 6 reverts back to zero. Tested for line 8 as well and get the same 500 error:
![Image](https://github.com/user-attachments/assets/f26c6175-0cdc-4afd-94e0-8814dcf75a67)

**Comment by dhaselhan** [comment]
Ready for a re-test!
