### ISSUE TITLE
LCFS - Design and Suggest an Optimized Data Model for Credit Transfer Tables

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#102]
**Describe the task**
Analyze the existing TFRS data model related to Credit Trades and design an optimized data model for all credit transfer-related database tables for the LCFS FastAPI system. The required tables are CreditTrade, CreditTradeComment, CreditTradeHistory, CreditTradeStatus, CreditTradeZeroReason, and CreditTradeType. Additionally, implement a new feature called Compliance Units, which changes the way credits and debits are handled to be one unit rather than separate entities. The focus should be on simplicity, optimization, and avoiding the iterative changes that stacked issues in the TFRS data model.

**Purpose**
The purpose of this task is to create a foundation for the credit transfer functionality within the LCFS system by designing a clean, simple, and optimized data model. This will enable more efficient and streamlined operations, laying the groundwork for the subsequent implementation of these models.

**Acceptance Criteria**
- [ ] Analyze the existing TFRS data model, focusing on Credit Trade related tables.
- [ ] Design a new, optimized data model for LCFS, focusing on simplicity and avoiding complexities that arose in the TFRS data model due to iterative changes.
- [ ] Clearly document the designed data model, highlighting the differences and optimizations compared to the TFRS model.
- [ ] Include diagrams or visual representations of the data model where appropriate.
- [ ] Review the designed data model with relevant stakeholders to ensure it meets the project requirements and standards.
- [ ] Rename all 'CreditTrade' tables to 'CreditTransfers'

**Additional context**
- The TFRS data model should serve as a reference, but the goal is to avoid complexities and issues that arose due to long iterative changes.
- The focus should be on creating a simple, clean, and optimized data model that can serve as a solid foundation for the credit transfer functionality within LCFS.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/102?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
