### ISSUE TITLE
LCFS - Re-add total (Renewable + Low Carbon Requirement) line to the compliance report summary

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1020]
**Describe the task**
Re-add the Total Non-Compliance Penalty Payable line to the "Non-Compliance Penalty Payable Summary" table in the Compliance Report Summary. This line was previously removed and needs to be restored to ensure that organizations can see the total penalty amount payable for non-compliance. It is the sum of the renewable requirement penalty line + the low carbon requirement penalty line).

https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/186573409/simulate/no-panels

**Purpose**
To ensure that the Non-Compliance Penalty Payable Summary table accurately reflects the total penalty payable for non-compliance. This is critical for organizations to understand their financial obligations if they fail to meet compliance requirements. Re-adding this line will provide clear visibility of the total penalty amount.

**Acceptance Criteria**

- [ ]  The Total Non-Compliance Penalty Payable line is re-added to the Non-Compliance Penalty Payable Summary table.
- [ ]  The total penalty amount is correctly calculated and displayed based on any non-compliance penalties incurred.
- [ ]  The Total Non-Compliance Penalty Payable line is reviewed for accuracy and consistency across all user views, including IDIR and BCeID users.

**Additional context**
Ensure that the Total Non-Compliance Penalty Payable line is clearly displayed and properly formatted in the summary table.

**Comment by Grulin** [comment]
Hi @dhaselhan. I can see the line has been re-added, but there is no content in the summary now:

![Image](https://github.com/user-attachments/assets/c1346489-cf7c-423c-bd97-0a58b110c940)

It should look like the non-compliance penalty summary in the wireframe:

![Image](https://github.com/user-attachments/assets/3364f9af-2cbb-4855-8fa8-424ce4bdb4ec)

**Comment by dhaselhan** [comment]
Looked into this, looks like someone broke all rows with currency hence why Row 21 is also missing.

**Comment by dhaselhan** [comment]
This was due to the changes to #985 
I am not sure on the process, do we re-open that ticket and fix it then re-test this ticket?

**Comment by dhaselhan** [comment]
Above bug has been fixed, ready for re-test.
