### ISSUE TITLE
LCFS - Implementation of Transfer Data Model in LCFS FastAPI System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#103]
**Description:**  
Implement the optimized data model designed for transfer and transaction related database tables in the LCFS FastAPI system.

**Objective:**  
Operationalize the transfer data model within the LCFS system using SQLAlchemy and Alembic. This ensures a robust and maintainable data layer for credit transfer functionality.

**Acceptance Criteria:**  
- [ ] Create SQLAlchemy models for the following database tables:
   - transaction
   - transaction_type
   - issuance
   - issuance_history
   - transfer
   - transfer_history
   - transfer_category
   - transfer_status
   - comment
- [ ] Define and implement relationships between tables:
   - transaction **has** a transaction_type
   - transaction **has** a issuance (optional)
   - transaction **has** a transfer (optional)
   - issuance **has many** issuance_histories
   - transfer **has many** transfer_histories
   - transfer **has** a transfer_category
   - transfer **has** a transfer_status
- [ ] Create Alembic migration scripts for database schema changes.
- [ ] Integrate new models into the existing FastAPI application.
- [ ] Outline CRUD operations for models and add placeholder methods for endpoints. Detailed business logic will be addressed in a subsequent ticket.
- [ ] Ensure all tests pass.
- [ ] Update documentation and add code comments to reflect changes.

**Additional Insights:**  
- Align implementation with the optimized data model design from the draw.io ERD file located in Teams.
- Handle database migrations effectively with Alembic.
- Coordinate integration within the FastAPI application with team members.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/103?planning-poker) with Zenhub @AlexZorkin @prv-proton @jig-patel

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
