### ISSUE TITLE
LCFS - Implement User Login History View for Administrators

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#1035]
**Description:** 
Create a new feature in the administration tab that displays a table view of user login history. This view will be accessible only to administrators and will utilize the AG Grid read-only table to display data from the user_login_history table.

**Purpose and benefit to user:**
This feature will assist administrators in resolving login issues for users by providing a comprehensive view of login attempts, success rates, and error messages. It will improve the efficiency of troubleshooting and support processes.

**Acceptance Criteria:**
- [ ] Given I am an administrator, When I navigate to the administration tab, Then I see a "User Login History" option
- [ ] Given I am an administrator, When I click on "User Login History", Then I see a table view populated with data from the user_login_history table
- [ ] Given I am a non-administrator user, When I access the administration tab, Then I do not see or have access to the "User Login History" view
- [ ] Given I am an administrator viewing the login history, When I interact with the table, Then I can sort, filter, and search the data
- [ ] Given I am an administrator, When I view the login history table, Then I see columns for all relevant fields from the UserLoginHistory model

**Development Checklist:**
- [ ] Implement backend API endpoint to fetch user login history data
- [ ] Create frontend component for the User Login History view using AG Grid
- [ ] Implement role-based access control to restrict view to administrators only
- [ ] Integrate the new component into the administration tab
- [ ] Implement sorting, filtering, and search functionality for the table
- [ ] Implement Pagination with ag grid
- [ ] Add appropriate error handling and loading states
- [ ] Write unit and integration tests for both frontend and backend
- [ ] Update documentation to include information about the new feature

**Notes:**
- The UserLoginHistory model contains the following fields to be displayed in the table:
  - user_login_history_id
  - keycloak_email
  - external_username
  - keycloak_user_id
  - is_login_successful
  - login_error_message
  - create_date
- Ensure that sensitive information is properly handled and displayed according to security best practices

**Comment by dhaselhan** [comment]
Idea:
This could be done as a Metabase report for less development effort
