### ISSUE TITLE
Upgrade deployed Python to 3.11

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1048]
Currently we are using 3.11 python locally, but using 3.9 on the deployed backend. We want to upgrade the backend to use the same 3.11 we are using locally.

**Comment by kuanfandevops** [comment]
@dhaselhan once the warning is confirmed can be ignored, will merge the change into the release branch

**Comment by kuanfandevops** [comment]
The upgrade has been completed.
