### ISSUE TITLE
LCFS - Determining carbon intensity option in compliance report fuel code option not available

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1049]
**Describe the Bug**
Come of the options in the fuel supply schedule column "Determining Carbon Intensity" is only working for some fuel types. Please refer to card #867 to see when the prescribed section should be reference, the default section and the fuel code section should be referenced. For most fuels, the default and the fuel code sections of the Act should be available to reference.

**Expected Behaviour**
When you select a fuel type, there should be an option of determining carbon intensity drop downs. Fossil-derived fuels are always the prescribed option, but everything else should have the default or the fuel code option.

**Actual Behaviour**
Currently, a lot of the fuel types only have the default option available in this column. 

**Implications**
The implication is that fuel codes are not available for some fuel types when inputting in the report.

This error may be due to there being no fuel codes available in the system yet. Please add the following active fuel codes in to LCFS Portal from TFRS. These fuel codes should also be added to the seed content. 22 chosen codes are currently active with an expiry date in the future and represent various fuel types with different CIs:

BCLCF102.5
BCLCF124.4
BCLCF125.4
BCLCF138.5
BCLCF143.4
BCLCF251.2
BCLCF266.2
BCLCF274.2
BCLCF286.2
BCLCF316.1
BCLCF317.2
BCLCF339.1
BCLCF353.2
BCLCF357.2
BCLCF362.1
BCLCF405.1
BCLCF423.1
BCLCF448.1
BCLCF475.1
BCLCF559.1
BCLCF561.0
BCLCF567.0

Taken from our website:https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/rlcf012_-_approved_carbon_intensities_-_current_9august2024.pdf

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to a fuel type
2. Scroll to the Determining carbon intensity column
3. Look at options available

**Comment by Grulin** [comment]
Some of the fuel types still don't have the "Fuel code" option available in the "Determining carbon intensity" column of the supply of fuel schedule of the compliance report. I thought this may be due to a fuel code not being in the system for that fuel type, but there is a CNG fuel code and a hydrogen fuel code currently in the system and those fuel types do not have a "Fuel code" option available. 

I will create a card about linking the fuel code CI's, but in the meantime, please make sure all fuels (except the fossil-derived fuels) have both a default and fuel code determining carbon intensity option available.

**Comment by dhaselhan** [comment]
Added more fuel codes for:
Alternative Jet Fuel
Electricity
Renewable Gasoline

For Jet Fuel and Renewable Gasoline I grabbed approved Fuel Codes from the document. For Electricity I just made one up.

Every Fuel Type should now be able to select both options and have a valid fuel code to use.

**Comment by Grulin** [comment]
Unfortunately still only getting the "default" determining carbon intensity option for CNG and hydrogen, as well as others:
![Image](https://github.com/user-attachments/assets/176b64c0-cea1-4693-96f1-c24537fb0cbf)
![Image](https://github.com/user-attachments/assets/315f6a74-ed99-464c-b60d-714d92fd0616)
![Image](https://github.com/user-attachments/assets/16933ac6-4e3d-468b-bb79-da1cc1222ac7)

**Comment by dhaselhan** [comment]
Okay, after another round of failing migrations and more fixes the Fuel Codes are in! Ready for a re-test.
