### ISSUE TITLE
LCFS - Implement Keycloak Logout and Redirection for Frontend Authentication Flow and Validate Access Control

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#105]
**Describe the Task**
This task involves implementing and finalizing the frontend authentication flow in our ReactJS application that utilizes Keycloak for user login and authorization. The implementation needs to include a functionality for Keycloak logout and a redirection URL post-logout. In addition to this, the developer assigned to this task is required to review all the frontend code related to Keycloak authentication flow and cross-verify it against the ITVR authentication flow. The task also entails ensuring that the compliance_reports view is adequately protected and only accessible post-successful login.

**Purpose**
- To provide a secure and seamless user experience by implementing an efficient authentication flow using Keycloak.
- To ensure that users are properly logged out and redirected, enhancing security and usability.
- To double-check the implemented authentication flow against ITVR to maintain consistency and adherence to established standards.
- To safeguard sensitive data by confirming that compliance_reports view is only accessible to authenticated users.

**Acceptance Criteria**
- [ ] The Keycloak logout functionality is implemented, and users are logged out of the application securely.
- [ ] After logout, users are redirected to a specified URL.
- [ ] The frontend Keycloak authentication flow code is reviewed and verified against the ITVR authentication flow.
- [ ] The compliance_reports view is confirmed to be accessible only after successful login.
- [ ] Documentation is updated to reflect the changes and implementations.
- [ ] The implemented flow is tested for different scenarios and is proven to be robust and secure.

**Additional Context**
- Keycloak is an open-source Identity and Access Management solution that our application is using for authentication.
- The ITVR authentication flow should serve as a reference for standards and best practices.
- Ensuring the security and restricted access to compliance_reports view is crucial for data protection and compliance.

**Comment by tim738745** [comment]
About configuring the logout redirect uri: The calling component can pass a redirect uri to the <Logout> component, but this is optional. By default, logging out will redirect to the page the user is currently on (location.href), and if this page is protected by authentication (the <RequireAuth> component in routes/index.js), then the user will be redirected to a specified, non-protected route (in the case of LCFS and ITVR, the route is /login). This is usually sufficient; if the developer that is developing a (frontend) view wants custom logout redirection behaviour, it is up to them to use <Layout> (which contains <Logout>) and pass a custom redirect uri to it.

About protecting the compliance_reports view: as long as <RequireAuth> is used (which it currently is), then the frontend view will be protected; of course, checks/protections should also be implemented around the associated backend endpoint.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
