### ISSUE TITLE
LCFS - TFRS teardown, IDIR

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1066]
**Description:**  

This work should be done in a new branch.

Remove the following items from various sections of the dashboard, main navigation, and organization pages:
- Remove from the dashboard:
  - All Organizations, Compliance Units widget (left column)
  - Transactions widget (center column)
  - File submissions widget (right column)
- Remove from the main navigation bar:
  - Transactions
  - File Submissions
- Remove from the Organizations index page:
  - Compliance Units and In Reserve columns from the table
- Remove from the individual Organization page:
  - Compliance Units and In Reserve info (top right)

All components being removed / turned off should be able to be reactivated easily if required later.

**Wireframe:**  
https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/188734158
https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/188742906

**Purpose and benefit to user:**  
Simplifies the user interface by removing unnecessary elements from the dashboard, navigation bar, and organization pages, improving the user experience and focusing on essential data.

**Acceptance Criteria:**  
- [ ] The "All Organizations, Compliance Units" widget is removed from the dashboard (left column).
- [ ] The "Transactions" widget is removed from the dashboard (center column).
- [ ] The "File submissions" widget is removed from the dashboard (right column).
- [ ] "Transactions" and "File Submissions" options are removed from the main navigation bar.
- [ ] The "Compliance Units" and "In Reserve" columns are removed from the Organizations index page table.
- [ ] The "Compliance Units" and "In Reserve" info are removed from the top right of individual Organization pages.
- [ ] The email Notifications component and pages should be retained

**Development Checklist:**  
- [ ] Remove the "All Organizations, Compliance Units" widget from the left column of the dashboard.
- [ ] Remove the "Transactions" widget from the center column of the dashboard.
- [ ] Remove the "File submissions" widget from the right column of the dashboard.
- [ ] Remove the "Transactions" and "File Submissions" links from the main navigation bar.
- [ ] Update the Organizations index page to remove the "Compliance Units" and "In Reserve" columns.
- [ ] Update the individual Organization page to remove "Compliance Units" and "In Reserve" information from the top right.

**Notes:**  
- Ensure that removing these elements does not affect any other dependencies or related functionalities.
- All components being removed / turned off should be able to be reactivated easily if required later.

**Comment by Grulin** [comment]
Some of the components are still visible in the TFRS dev environment. I have highlighted them in the screenshot. Also, it says "Director Review" when I have assigned myself an analyst role. Not sure why that would be:
![Image](https://github.com/user-attachments/assets/d5bc9192-82b7-40f6-9fd0-d1c6a9b1a3ea)

**Comment by hamed-valiollahi** [comment]
Thanks, Lindsy, for testing and reporting the issue. As far as I know, in the future, we need to tear down the TFRS. Please correct me if I'm mistaken.

There are a few front-end environmental variables that we can turn on to disable front-end features. I'm not sure if we need to do that immediately. Should we? As far as I know, Alex is the best person to decide on that.

Here are the variables. Currently, they are all set to `false`, which means the features are all visible:

```
'tear_down.bceid.widgets.balance': false,
'tear_down.bceid.widgets.feedback': false,
'tear_down.bceid.widgets.website': false,
'tear_down.bceid.widgets.creditTransactions': false,
'tear_down.bceid.widgets.fileSubmissions': false,
'tear_down.bceid.header.creditInformation': false,
'tear_down.bceid.navigation.transactions': false,
'tear_down.bceid.navigation.fileSubmissions': false,
'tear_down.bceid.navigation.helpLink': false,
'tear_down.bceid.organization.creditInformation': false,
'tear_down.bceid.organization.roles.fileSubmission': false,
'tear_down.bceid.organization.roles.creditTransfers': false,
'tear_down.idir.widgets.balance': false,
'tear_down.idir.widgets.creditTransactions': false,
'tear_down.idir.widgets.fileSubmissions': false,
'tear_down.idir.navigation.transactions': false,
'tear_down.idir.navigation.fileSubmissions': false,
'tear_down.idir.navigation.helpLink': false,
'tear_down.idir.organizations.tableColumns.complianceUnits': false,
'tear_down.idir.organizations.tableColumns.inReserve': false,
'tear_down.idir.organization.creditInformation': false
```

Apologies for not informing you! I thought it was a code change meant for future use.

**Comment by airinggov** [comment]
Thanks Hamed, we'll have to test this beforehand but we can schedule that maybe for our Bug session if we ever get around to that. I assume it is pretty easy to flip these flags.
