### ISSUE TITLE
LCFS - Director receives a 'Forbidden' error message when selecting 'Record transfer'

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1067]
**Describe the Bug**
When an IDIR user with the director role attempts to accept a credit transfer by selecting "Record transfer" on a transfer that has been recommended by an analyst, they receive a "Forbidden" message. This prevents the director from completing the process of recording the transfer, despite the transfer being properly recommended by the analyst.

**Expected Behaviour**
An IDIR user with the director role should be able to select "Record transfer" for a credit transfer that has been recommended by an analyst without encountering any errors.

**Actual Behaviour**
When a director attempts to record a recommended transfer, they receive a "Forbidden" message, preventing them from accepting or recording the transfer.

**Implications**
Directors are unable to fulfill their role in accepting and recording credit transfers, which disrupts the credit transfer process.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR
1. Log in as an IDIR user with the Director role.
2. Navigate to a credit transfer that has been recommended by an analyst.
3. Select "Record transfer".
4. Observe that a "Forbidden" message appears, preventing the Director from accepting and recording the transfer.

**Comment by dhaselhan** [comment]
Tested on Develop and not able to reproduce, may have been fixed from other changes.

**Comment by airinggov** [comment]
Can confirm no error message being displayed.
