### ISSUE TITLE
DevOps: Create OpenShift Policy for Cross-Namespace Communication between TFRS and LCFS

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#1077]
**Description**:
Create an OpenShift network policy to allow secure cross-namespace communication between TFRS and LCFS. TFRS needs to access the Redis instance in the LCFS namespace, while LCFS must communicate with the RabbitMQ instance in the TFRS namespace.

**Purpose**:
To enable TFRS to access Redis in LCFS and allow LCFS to consume RabbitMQ messages from TFRS, facilitating the exchange of compliance balance and transaction data.

**Development Requirements**:
- [ ] Create a network policy to allow TFRS namespace access to Redis in LCFS.
- [ ] Allow LCFS namespace to connect to RabbitMQ in TFRS.
- [ ] Ensure communication is restricted to the required services (Redis and RabbitMQ).

**Acceptance Criteria**:
- TFRS can access Redis in the LCFS namespace.
- LCFS can access RabbitMQ in the TFRS namespace.
- Communication is restricted to Redis and RabbitMQ ports

**Comment by kuanfandevops** [comment]
The network policies have been opened:
1. allow TFRS RabbitMQ to accept the access from LCFS Backend
2. allow LCFS Redis to accept the access from TFRS Backend
