### ISSUE TITLE
LCFS - Refinement of line 7 and 9 in the Compliance report summary

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1114]
**Describe the Bug**
In the Summary and Declaration section of the compliance report, inputs on line 7 and line 9 are persisting and do not save when edited. Currently, users are unable to modify these inputs and have them save after they have been initially entered, even though changes should be allowed until the report is submitted.

**Expected Behaviour**
- The inputs on line 7 and line 9 in the Summary and Declaration section should remain editable and re-saved until the report is submitted.
- Users should be able to modify the entries on these lines as necessary before the report submission.

**Actual Behaviour**
Once an input is entered on line 7 and line 9, it will not save when changed, preventing users from saving further changes, even though the report has not yet been submitted.

**Implications**
- Users are unable to update or correct the data on line 7 and line 9 before submitting the report, which could lead to incorrect or incomplete reporting.
- This limitation creates frustration for users who need to make adjustments to their compliance report before final submission.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID

1. Navigate to the Summary and Declaration section of a compliance report.
2. Enter data on line 7 and line 9.
3. Attempt to modify the input after saving, but before submitting the report.
4. Observe that the inputs are uneditable and persist as originally entered.

**Comment by Grulin** [comment]
These lines still allow me to input a change, but there still seems to be an issue with saving the new input. I'm getting a 422 error now when I input something new and then click any where else on the page. Still reverts back to previously saved numbers if I refresh the page:
![Image](https://github.com/user-attachments/assets/467e6be6-cce8-444a-be2e-c49ca5ed6f98)

**Comment by dhaselhan** [comment]
Lines 7/9 are now correctly persisting, however the are other bugs that will need to be fixed.
