### ISSUE TITLE
LCFS - Reformat In-App Notifications tied to Email Subscriptions into AG Grid Index format for BCeID and IDIR users

### ISSUE THREAD

**Issue by StuartGALL** [bcgov/lcfs#1135]
Description: Redesign in-app notifications linked to email notification subscriptions in the AG Grid Index format. The updated design should incorporate versions for both BCeID and IDIR users, including button functionality as specified in the provided wireframes.

BCeID Wireframe link: [[BCeID Wireframe](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/190425790?mode=m)]
IDIR Wireframe link: [[IDIR Wireframe](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/190425788?mode=m)]

Purpose and Benefit to the User: This design will improve notification clarity and interaction by standardizing in-app notifications in AG Grid Index format. Both BCeID and IDIR users will benefit from a unified and accessible notification experience that aligns with the email subscription updates.

Acceptance Criteria:
- [ ] In-app notifications are redesigned in the AG Grid Index format.
- [ ] Separate BCeID and IDIR versions are implemented with consistent styling and functionality.
- [ ] Button functionality reflects the actions specified in the wireframes (e.g., check all, mark as read, delete and reset).
- [ ] Cards are visually cohesive, with accessible typography, icons, and button placements.

Development Checklist:
- [ ] Review and apply AG Grid Index format guidelines to the notification layout.
- [ ] Customize design for BCeID and IDIR versions to ensure visual consistency.
- [ ] Implement button actions in accordance with wireframe specifications.
- [ ] Link wireframe prototype for team feedback and adjust based on usability testing.
- [ ] When the "Check all" button has been pressed, replace button with "Uncheck all".
- [ ] When nothing is checked, put "delete" button into inactive state.

Notes:
- Verify accessibility compliance.
- Ensure integration with existing notification and email subscription settings.

**Comment by airinggov** [comment]
@StuartGALL wireframe links don't seem to be working

**Comment by StuartGALL** [comment]
@airinggov Thanks Al, updated wireframes are working again
