### ISSUE TITLE
LCFS - Show TFRS Credit Assessments

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1167]
As a User of both TFRS and LCFS, I want to be able to understand how my TFRS compliance reports impact my balance in LCFS.

We now have cross communication between TFRS and LCFS, where LCFS is no aware of assessments completed in TFRS and their impact, however the user does not have a way to see / understand this information and their balance just changes.

We want to add X, so that the user can see these Transfers. 

**Acceptance Criteria:**
TODO

**Development Checklist:**
TODO

**Notes:**

**Comment by airinggov** [comment]
Potentially need a new transaction type in LCFS to record credit changes from CR assessments.

**Comment by airinggov** [comment]
These should come through from TFRS as Validation and Reduction transactions. I don't think we need to take action on this. We can confirm once we run the existing data imports.

**Comment by airinggov** [comment]
no longer need this ticket
