### ISSUE TITLE
LCFS - Review and refinement of compliance unit formula

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1176]
**Describe the task**
Review and refine the compliance unit calculation formula in the Compliance Report system (for all sections that use this formula to calculate compliance units). Currently, the compliance units are being calculated incorrectly, indicating potential errors in the formula's implementation or associated data inputs. The formula is as follows:

Compliance unit=(TCI×EER−(RCI+UCI))×EC/1,000,000

Where:

TCI = Target carbon intensity for the fuel, as per subsection (5)
EER = Energy effectiveness ratio of the fuel, as defined in ministerial regulations
RCI = Recorded carbon intensity of the fuel
UCI = Additional carbon intensity attributed to the use of the fuel, per ministerial regulations
EC = Energy content of the fuel in megajoules, as per ministerial regulations

Column N of the following spreadsheet includes an Excel version of the formula that can be used to test that the formula in the LCFS Portal is working correctly:

[Line by line fuel supply entry (1).xlsx](https://github.com/user-attachments/files/17685235/Line.by.line.fuel.supply.entry.1.xlsx)

**Purpose**
To ensure accurate compliance unit calculations for reporting and enforcement. Correcting this formula will support proper compliance evaluations and maintain the integrity of compliance reporting.

**Acceptance Criteria**

- [ ] Review the implementation of each variable (TCI, EER, RCI, UCI, EC) to confirm correct data sourcing and value accuracy.
- [ ] Verify the correct application of the formula in the compliance report calculation engine.
- [ ] Test with known values to confirm that the compliance unit calculation matches expected results.
- [ ] Confirm that updates are visible and functional for both IDIR and BCeID users.

**Additional context**

- This task is critical to ensure compliance units are calculated correctly in alignment with the Low Carbon Fuels Act and the associated regulations. Accurate calculations are essential for the fair enforcement of compliance measures and to avoid any discrepancies in reporting.
- Related to card #1194

**Comment by airinggov** [comment]
@AlexZorkin @Grulin  I've been testing this using BCeID LCFS10. I've been adding fuel supply to match the spreadsheet but ran into the duplicate line error. Waiting for card 1216 to be resolved to complete this testing. So far the compliance units are not aligning between the fuel supply schedule and the spreadsheet.

**Comment by Grulin** [comment]
I noticed this too, @AlexZorkin. All the line inputs look correct, so it looks like the formula may be the issue. We can meet next week to walk through this if you want? Plus the UCI inclusion will be added as well.
