### ISSUE TITLE
LCFS - Notifications Settings page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#118]
Out of scope, the actual email notifications.

**Description:**
Create email notifications subscription pages. Each checkbox will subscribe the user to receive an immediate email notification when a certain action (or action group) occur. Each IDIR role has a custom form. There is only one form for BCeID users. The BCeID form also has an option for the user to change their notification email. This email is saved in their profile but they may not have access to change their profile. 

This page is accessed from a Notifications link found as a select option under their name in the header bar.

**Wireframe:** 
BCeID users, any role
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/190423557/simulate/sitemap

IDIR Analyst  role
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/190423556/simulate/sitemap

IDIR Compliance Manager role
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/190423560/simulate/sitemap

IDIR Director role
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/190423559/simulate/sitemap

**Purpose and benefit to user:**  
This functionality allows users to customize the email notifications they receive based on specific actions or action groups relevant to their role. It helps users stay informed about critical updates and activities.

**Acceptance Criteria:**  
- [ ] Each checkbox should correspond to a specific action or action group and, when selected, subscribe the user to immediate email notifications for that action or group.
- [ ] There should be a tailored subscription form for each IDIR role (Analyst, Compliance Manager, Director).
- [ ] The BCeID form should include a field allowing users to change their notification email address, with changes saved in their profile.
- [ ] All forms should match the provided wireframes.
- [ ] Notification settings should be stored accurately and reflect user choices on subsequent visits to the page.

**Development Checklist:**  
- [ ] Implement the subscription checkboxes based on the specific actions or action groups defined for each IDIR role.
- [ ] Develop the single BCeID user form with a notification email field.
- [ ] Test form accessibility and role-based restrictions for BCeID and IDIR users.
- [ ] Validate that changes in email address and subscriptions are saved correctly.
- [ ] Ensure that all visual components align with the wireframes and UX designs.
 - [ ] Ensure that when a user has their role changed that the subscriptions are cleared.

**Notes:**  
Review each wireframe carefully to ensure all required elements and interactions are accurately implemented for each role.

**Comment by airinggov** [comment]
@hamed-valiollahi Looks great Hamed. Only issue I see is the alternate email address doesn't get saved in their profile here.

![Image](https://github.com/user-attachments/assets/f395a676-51c7-40b4-ac29-8e7acc7fb4a9)

**Comment by hamed-valiollahi** [comment]
@airinggov Thanks, Al, for testing and reporting the issue. I've made the changes, and it's now awaiting code review.
