### ISSUE TITLE
Setup RabbitMQ Env Vars for LCFS

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1183]
We want LCFS to be connected to the same RabbitMQ as TFRS so they can exchange messages. I have created the following vars in the settings file that are ready to be set via ENV vars.

    # Variables for RabbitMQ
    rabbitmq_host: str = "rabbitmq"
    rabbitmq_port: int = 5672
    rabbitmq_pass: str = "development_only"
    rabbitmq_user: str = "lcfs"
    rabbitmq_vhost: str = "lcfs"
    rabbitmq_transaction_queue: str = "transaction_queue"

So we will need to set the env vars:
LCFS_RABBITMQ_HOST
LCFS_RABBITMQ_PORT..
etc

**Comment by kuanfandevops** [comment]
This has been done. Ready for testing.
