### ISSUE TITLE
LCFS - BUG when reporting HDRD supply in the fuel supply grid

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1187]
**Describe the Bug**
In the Fuel Supply section, when attempting to save an entry for the fuel type HDRD, an error warning appears. After inputting the Fuel Type and Fuel Category and then selecting the Determining Carbon Intensity, an error message displays as "Error updating row." The Fuel Type, Fuel Category, and Determining Carbon Intensity columns are outlined in red, and the entry does not save.

**Expected Behaviour**

- Users should be able to enter values for Fuel Type, Fuel Category, and Determining Carbon Intensity for HDRD without errors.
- The row should save successfully after completing these inputs.

**Actual Behaviour**

- Upon selecting the Determining Carbon Intensity for HDRD, an error warning appears as "Error updating row."
- The Fuel Type, Fuel Category, and Determining Carbon Intensity columns are outlined in red.
- The entry does not save, preventing users from successfully adding HDRD as a fuel type.

![Image](https://github.com/user-attachments/assets/3f589ef1-67d2-419f-a127-995c32efa359)

**Implications**

- Users are unable to record HDRD fuel supply data, which impacts accurate reporting in the fuel supply table.
- This error prevents users from completing and saving necessary entries for compliance reporting.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID

1. Select HDRD as the Fuel Type and input the Fuel Category.
2. Select a Determining Carbon Intensity.
3. Attempt to save the row and observe the "Error updating row" message.
4. Note that the Fuel Type, Fuel Category, and Determining Carbon Intensity fields are outlined in red, and the entry does not save.

**Comment by areyeslo** [comment]
@Grulin can we check on dev the scenario?
![Image](https://github.com/user-attachments/assets/a0a8c029-2962-457a-bbaf-ad66ae0149f9)

**Comment by Grulin** [comment]
Hi @areyeslo. This bug does not seem to be occurring anymore. Thank you for catching this. I will close this ticket out.
