### ISSUE TITLE
LCFS - Restrict users from submitting a blank compliance report

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1198]
**Describe the task**
Implement a restriction that prevents BCeID users from submitting a blank compliance report. The system should verify that the report includes entries in at least one of the following sections before submission:

- Fuel Supply
- Export
- Allocation Agreements
- Notional Transfers
- Fuels for Other Use

Submitting only Final Supply Equipment (FSE) identification information is not sufficient to submit a report. If the report is blank or only contains FSE information, the submission should be blocked, and the user should receive a standardized error message prompting them to complete the required fields.

**Purpose**
To ensure data completeness and accuracy by preventing BCeID users from submitting blank compliance reports. This restriction will help maintain report quality and reduce the need for follow-up due to incomplete submissions.

**Acceptance Criteria**

- [ ] A system check prevents submission unless data is present in at least one of the following sections:
- Fuel Supply
- Export
- Allocation Agreements
- Notional Transfers
- Fuels for Other Use
- [ ] Submitting only FSE identification information is insufficient to submit a compliance report.
- [ ]  If a blank report or one with only FSE information is submitted, the system displays a standardized error message prompting the user to input the required fields.
- [ ]  The restriction applies only to BCeID users, and IDIR users are unaffected.
- [ ]  The Signing authority declaration checkbox is disabled by default when no content is added to the activity schedules.
- [ ] The Signing authority declaration checkbox becomes enabled only when content is added to at least one activity schedule.
- [ ] When the Signing authority declaration checkbox is in a disabled state, the text "You must report fuel activity information to sign and submit a report (FSE data alone is not sufficient)" is displayed under the Signing authority declaration heading and above the checkbox.
- [ ] The instructional text disappears when the Signing authority declaration checkbox is enabled.
- [ ] The disabled state of the checkbox and the instructional text behave consistently across all browsers and devices.
- [ ] Error messages or warnings are triggered if an attempt is made to submit the report without satisfying the criteria for enabling the checkbox.
- [ ]  The feature is tested across various scenarios to ensure compliance with the submission rules.

**Additional context**
Use the Signing authority declaration checkbox to prevent data submission. The checkbox should be disabled until content is added to one of the activity schedules. When the checkbox is in a disabled state, add the following text under the Signing authority declaration heading ,above the checkbox. "You must report fuel activity information to sign and submit a report (FSE data alone is not sufficient)."

**Comment by Grulin** [comment]
When I go to test this, as a BCeID user with all roles, I can select the signing authority declaration and hit submit report, and get the modal window to submit before I get this 500 error:
![Image](https://github.com/user-attachments/assets/8395cc39-3217-4168-99ce-52ab2a7e20d5)

I did see the green message advising that I can't submit a blank report once, but now I'm seeing this error. This is on test account LCFS4 in the dev environment

**Comment by dhaselhan** [comment]
Logged in as LCFS4 and was able to submit draft both reports without issue.
