### ISSUE TITLE
LCFS - Make status text black in the transaction history section of credit transfers 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#120]
**Title:**
Make status text black in the transaction history section of credit transfers 

**Description:**
Make the bold status text black across all status entries in the transaction history section of the view credit transfer. In TFRS, we use colours for some of the statuses. For example, we use green for Approved and red for Rescinded, Refused, and Declined. Transfers are no longer Approved/Declined, but rather Recorded/Not Recorded. In any case, we don't want to use colours (red/green) to further illustrate positive/negative statuses. Colours are already used in the bread crumb (red) for negative statuses. 

**Screenshots of TFRS implementation w/ colours**
Rescinded:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmsvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--111e7392c60b4649538c94faafd0442308b4e18b/Screenshot%202023-08-25%20Rescinded.png)

Refused: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm8vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--70e68b0c99d7f6d8794f2478e19e0a44d5d1516a/Screenshot%202023-08-25%20REfused.png)

Declined:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnMvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--338f7780f9c9aa170b53f05a28b104e9d0a40571/Screenshot%202023-08-25%20Declined.png)

Approved: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbncvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2545ed6919fe8e764ccea4dbd6076cfe9489be9a/Screenshot%202023-08-25%20Approved.png)

**Wireframe:** <link>

**Purpose and benefit to user:**
Improves readability of text and avoids further negativity for "negative" end states like rescinded and declined/not recorded. 

**Acceptance Criteria:**

- [ ] Given I am a <role>, When I am <doing something>, then <this happens>
- [ ] Given I am a <role>, When I am <doing something>, then <this happens>

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/120?planning-poker) with Zenhub @prv-proton
