### ISSUE TITLE
LCFS - Add UCI column to "Fuel supply" and "Export" sections of the compliance report

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1204]
**Describe the task**
Add a new column titled UCI to the Fuel Supply and Export schedules of Compliance Reporting. This column should be located immediately after the CI of Fuel column. When an option is selected in the End Use column, the UCI column should automatically populate with the numerical values specified in card #574.

**Wireframe:** <[Link](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/190867254)>

**Purpose**
To enhance the Fuel Supply and Export sections by including a UCI column that provides relevant numerical values based on the End Use selection, improving data accuracy and streamlining the compliance reporting process.

**Acceptance Criteria**

- [ ] Add a new column titled UCI in the Fuel Supply and Export sections after the CI of Fuel column.
- [ ]  The UCI column should populate automatically with the correct numerical values from card #574 based on the End Use selection.
- [ ]  Ensure that the populated values in the UCI column are accurate and consistent with the values specified in card #574.
- [ ]  Confirm that this feature works in both the Fuel Supply and Export sections and does not interfere with other fields or calculations.

**Additional context**
- related to card #1175

**Comment by Grulin** [comment]
@StuartGALL hi! This is the design ask I had related to adding a UCI column to the compliance report Fuel supply and Export sections. Please add a link to a wireframe once you have one ready to go. Thank you!

**Comment by dhaselhan** [comment]
We are currently not clear on exactly how Marine use will apply to LNG, so ticket is blocked

**Comment by dhaselhan** [comment]
For QA:
There are currently no fuel codes in the system setup to use UCI, so you may need to make a new one for testing.
