### ISSUE TITLE
LCFS - Add Fuel code and CI columns to Fuels for other use grid 

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1207]
**Describe the task**
Add three new columns to the Fuels for Other Use AG grid table in the compliance report. These columns should be located after the Fuel Category column and titled:

- Determining Carbon Intensity
- Fuel Code
- CI of Fuel

These columns should function exactly as they do in the Fuel Supply Reporting portion of the report:

- Determining Carbon Intensity: Should offer the same options (e.g., "Default" or "Fuel code").
- Fuel Code: Should display the same fuel code options as in the Fuel Supply Reporting section.
- CI of Fuel: Should either show a prescribed CI for fossil-derived fuel choices or, if a fuel code is selected, pull the CI from the Fuel Code Table.

These columns should follow the same restrictions, functionality, and options as in the Fuel Supply Reporting section and should be limited to the following fuel types:

- Alternative Jet Fuel
- Biodiesel
- Ethanol
- Fossil-Derived Diesel
- Fossil-Derived Gasoline
- Fossil-Derived Jet Fuel
- HDRD (Hydrotreated Renewable Diesel)
- Other Diesel Fuel
- Renewable Gasoline

**Wireframe**
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/173989423
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/173991003

**Purpose**
To ensure consistency across the compliance report by providing users with the same options and functionality for selecting and calculating carbon intensity values in the Fuels for Other Use section as in the Fuel Supply Reporting section.

**Acceptance Criteria**

- [ ] Add three new columns titled Determining Carbon Intensity, Fuel Code, and CI of Fuel after the Fuel Category column in the Fuels for Other Use AG grid table.
- [ ]  Determining Carbon Intensity column offers the same options ("Default" or "Fuel code") as in the Fuel Supply Reporting section.
- [ ]  Fuel Code column displays the same fuel code options as in the Fuel Supply Reporting section.
- [ ]  CI of Fuel column:

- Shows a prescribed CI for fossil-derived fuel types.
- Links to the correct CI from the Fuel Code Table if a fuel code is selected.

- [ ]  Ensure that functionality, restrictions, and data validation match the Fuel Supply Reporting section.
- [ ]  Limit the functionality to the specified fuel types only.

**Additional context**
Confirm that the additional columns integrate seamlessly with existing data inputs and validation processes.

**Comment by Grulin** [comment]
Hi @areyeslo I just noticed that the current version of the compliance report "Fuels for other use" section includes options for fuel type CNG, Electricity, hydrogen, LNG and propane. This should not be the case as these fuels are only subject to the low carbon fuel requirement and not reportable under this section (which only deals with fuels subject to the renewable requirement that were suitable for transportation use, but did not end up being used for transportation purposes). I noted the fuel types that should be included in the original card, but wanted to clarify here in case you were wondering why I only listed those fuels.

**Comment by airinggov** [comment]
@areyeslo Hi Arturo, have you made the update from Lindsy's comment above? I don't see the change in Dev

**Comment by airinggov** [comment]
@areyeslo Hi Arturo, the form isn't saving new records now either

![Image](https://github.com/user-attachments/assets/9817b732-e8dc-4a72-8f7e-b1d66ef156c9)

**Comment by areyeslo** [comment]
Let me check. Thank you for moving the ticket to be visible!

**Comment by airinggov** [comment]
@areyeslo Hi Arturo, some of the functionality isn't quite working yet as per

- Ensure that functionality, restrictions, and data validation match the Fuel Supply Reporting section

Certain fields should auto-populate based on Fuel type and Fuel category selections. Happy to look at it together if that helps.
