### ISSUE TITLE
Historical Data Entry feature redesign

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#121]
**Describe the task**
We want to explore redesign options for when we port over the HDE feature from TFRS to the LCFS system. 

Redesign elements include: 
- new name as 'Historical Data Entry' label doesn't accurately reflect the core purpose of the feature
- new labels for the different fields that accurately reflect the naming conventions of the new Act. For example, transfers are recorded not approved; credit transfers are now just transfers; part 3 awards are now initiative agreements; no use of the 'Commit' label since this is dev jargon rather than business language. 
- new UI design where the fields don't stretch so much across the screen
- Only show relevant fields for each transaction type, based on selection. For example, don't show 'Credits from' for non-transfer transactions; don't show dollar per credit for non-transfer transactions, etc.
- Add agreement date field to credit transfers; would we also need to add a drop-down for manual selection of categorization of the transfer? Or could the system do this automatically on approval.

Other design considerations:
- consider simplifying the process by getting rid of the queue
- accessibility considerations?

**Purpose**
Modernizing an old feature to align it with its current core purpose as well as new Act requirements & naming conventions. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by airinggov** [comment]
What role has access to this? If removing the queue, should the analyst create a transaction and now have the director complete the transaction? Or do we want the admin function to create and complete the transaction entirely?
