### ISSUE TITLE
LCFS - BUG - Duplicate row validation with End use

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1216]
**1. Describe the Bug**
This should not be throwing an error
![Image](https://github.com/user-attachments/assets/98bb62c8-9d38-4450-a4f4-868362326ba9)

**Expected Behaviour**
The End use should also be part of the duplicate row validation, having a different End use makes this a unique fuel.

**Actual Behaviour**
It doesn't appear End use is part of the duplicate row validation.

**Implications**
This prevents suppliers from reporting fuels accurately.

**************
**2. Spike**
**Problem Description**
After deleting a duplicate row, trying to input the same information, it is as if the error matching hasn't been cleared and a duplicate row error is given when it shouldn't be

![Image](https://github.com/user-attachments/assets/e1661beb-85ac-4d55-814a-87ad10da71cf)

**In order to**
Enable suppliers to report fuel data accurately without encountering erroneous duplicate errors, the system **needs to** validate rows.

**Solution Needs**
- Clear any residual matching errors when entries are deleted or modified to avoid incorrect duplicate error messages.

**Timebox**
Allocate up to 3 points to investigate and prototype a validation update for duplicate entries.

**Outcome**
- Identify whether additional logic or database adjustments are needed to prevent residual error matching.

**Additional Context**
- Current implications affect fuel reporting accuracy, impacting compliance and record-keeping for suppliers.
- Steps to reproduce the current issue may include:
  - Entering a fuel record with specific values.
  - Deleting and re-entering similar records with different values.

**Comment by airinggov** [comment]
@kevin-hashimoto  Still getting a duplicate row error on this

![Image](https://github.com/user-attachments/assets/6cb5f60a-4b73-4b97-9a0d-58a8c177caa2)

**Comment by airinggov** [comment]
@kevin-hashimoto  log in with LCFS10 if you want to try recreate this

**Comment by kevin-hashimoto** [comment]
@airinggov thats odd, I deleted the existing rows ( in the ui, not the db table ) and tried again and it seems to be working correctly.

I've added 3 rows with same values except for 'end use', deleted those and then added a row with the same value as the rows that were deleted.

![Image](https://github.com/user-attachments/assets/7a64a274-b75d-42fb-886a-207560e354d5)
![Image](https://github.com/user-attachments/assets/b04e567a-6738-42d9-87af-fca93fddae52)


Maybe something changed during one of the other PRs, let me know if this is still happening and we can hop on a call and walk through it
