### ISSUE TITLE
LCFS - BUG - Fuel supply display missing fields

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1217]
**Describe the Bug**
The Fuel supply display form on the report details section is missing values in Target CI and EER. Data is visible in the edit form.

![Image](https://github.com/user-attachments/assets/d90bd741-e824-4cbd-979c-e9f2e995e386)

**Expected Behaviour**
Data should be displayed in these columns.

**Actual Behaviour**
Important data is missing.

**Implications**  
Users cannot view critical data values (Target CI and EER) directly in the display form, leading to confusion and potential errors in fuel report assessment.

**Steps To Reproduce**  
User/Role: Report viewer  
1. Go to the report details section on the Fuel supply display form.  
2. Check the "Target CI" and "EER" columns.  
3. Observe that data values are missing in these columns.  
4. Open the edit form for the same report details section.  
5. Confirm that "Target CI" and "EER" data is present in the edit form.

**Comment by airinggov** [comment]
Still don't seem to be appearing

**Comment by Grulin** [comment]
Same for me. The EER value is showing on the view table, but the target CI is still not:

![Image](https://github.com/user-attachments/assets/d097ab0a-c727-4480-bd0a-435b13bd8883)
