### ISSUE TITLE
LCFS - Remove file submission roles and redistribute permissions to other roles

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#122]
**Describe the task**
We want to remove the File Submission roles for both IDIR and BCeID users and redistribute the file submission-specific permissions to the other roles. 

**IDIR users:**
- All other government roles should receive the specific permissions related file submissions, including 'view file submissions', 'link file submissions to compliance unit transactions', etc.
- Some of the other government roles already have these permissions
- The other government roles are: administrator, government analyst, government director, compliance manager

**BCeID users:**
- All fuel supplier roles can view file submissions
- Only certain fuel supplier roles can create new file submissions. These roles are: credit transfers, signing authority, compliance reporting, and managing users
- The one role that cannot create and submit new files submissions is the 'guest' role 

**Purpose**
Simplifying roles & permissions, in part based on user feedback

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by KericeRich** [comment]
Following the PostGres design on user roles a dev ticket will emerge to implement
