### ISSUE TITLE
LCFS - Add fuel code date validation logic

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1222]
**Describe the task**
Review the Fuel Code date restrictions for use in the compliance report to ensure that the system enforces the following rules:

1. A fuel code that has expired can be used within the year it expired and the following year, but not in the reporting period after that. (Ex. a fuel code that has expiry date of November 1st, 2023 can be used in 2023 and 2024, but not for reporting in 2025).

2. A fuel code cannot be used in the current reporting period if it does not become effective until a later period. (Ex. a fuel code that has an effective date of January 1st, 2025 cannot be used by a supplier submitting a report on March 31st, 2025 for the 2024 reporting period.)

**Purpose**
To validate and enforce correct fuel code logic in the compliance reporting system, ensuring that only valid fuel codes (approved and past effective date and within a reasonable time frame of expiry) are selectable. This ensures compliance with reporting standards and prevents the use of invalid fuel codes.

**Acceptance Criteria**

- [ ] Confirm that expired fuel codes are unavailable for selection in future compliance reports past the year of expiry +1. 
- [ ] Ensure that fuel codes with an effective date later than the current reporting period are unavailable for selection.
- [ ] Test the system to verify that only valid fuel codes are available based on their effective and 1 compliance period past their expiry date.
- [ ] Ensure proper error messages or restrictions are in place if a user attempts to select an invalid fuel code.

**Additional context**
- Previous addressed in card #969, but not fully implemented.
- Fuel codes are not expired by month, they are expired by the year, plus must be allowed to be reported in a following year to account for any delays in transportation of the fuel.

**Comment by dhaselhan** [comment]
Moved to block, we are not sure on the logic
