### ISSUE TITLE
LCFS - Develop Email Templates Using Nunjucks-like Syntax for Email Notifications

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#1224]
**Description:**

We need to create standardized email templates for our application's email notifications using Nunjucks-like syntax to ensure consistent variable substitution and branding. Each notification type should have its own specific content, but all emails should share a common wrapper that includes the LCFS branding with government colors.

This task involves:

- Collaborating with the business area to determine the ideal content for each notification type.
- Creating Nunjucks-like templates for each notification type, incorporating the agreed-upon content and placeholders for dynamic data.
- Developing a common email wrapper/template that can be reused across all notification emails to maintain consistent branding.
- Creating a mapping of notification types to their corresponding email templates and storing this in the email service folder for easy maintenance and scalability.

**Purpose and benefit to user:**

- **Consistent Branding:** Ensures all email communications reflect the LCFS identity and government standards, enhancing user trust and recognition.
- **Personalized Content:** Allows for dynamic insertion of user-specific information, making notifications more relevant and informative.
- **Efficiency:** Streamlines the process of sending notifications by using standardized templates, reducing development time for future notifications.
- **Maintainability:** Centralizes email content management, making it easier to update and maintain email templates as requirements evolve.

**Acceptance Criteria:**

- [ ] Given I am a **business stakeholder**, when collaborating with the developer, then I can provide the desired content for each notification type, ensuring it meets business needs.
- [ ] Given I am a **user**, when I receive an email notification, then the email includes LCFS branding with government colors and contains clear, relevant information specific to the notification type.
- [ ] Given I am a **developer**, when implementing email notifications, then I can use the standardized Nunjucks-like templates with variable substitution to generate emails efficiently.
- [ ] Given I am a **developer**, when I add or modify a notification type, then I can update the mapping and templates in the email service folder accordingly.

**Development Checklist:**

- [ ] **Design Common Email Wrapper:**
  - Develop a reusable email wrapper that includes LCFS branding elements and government colors.
  - Ensure the wrapper supports content injection for different notification types.
  
- [ ] **Create Nunjucks-like Email Templates:**
  - For each notification type, use generic email template using Nunjucks-like syntax.
  - Incorporate placeholders for dynamic content (e.g., transaction type, links).
  
- [ ] **Map Notification Types to Templates:**
  - Establish a mapping between notification types and their corresponding email templates.
  - Store this mapping within the email service folder for centralized access.
  
- [ ] **Implement Templates in Email Service:**
  - Integrate the templates into the email sending service of the application.
  - Ensure that the service correctly substitutes variables and renders the final email content.
  
- [ ] **Test Email Templates:**
  - Conduct thorough testing to verify that all templates render correctly with dynamic data.
  - Test emails across different email clients (e.g., Gmail, Outlook) and devices for compatibility.
  
- [ ] **Document Template Usage:**
  - Provide clear documentation on how to use and maintain the email templates.
  - Include guidelines for adding new notification types and templates in the future.

**Notes:**

- **Email Client Compatibility:** Ensure that all email templates are responsive and display correctly in various email clients and devices.
- **Accessibility:** Follow best practices for email accessibility, including proper use of alt text for images and readable font sizes.
- **Security:** Validate and sanitize all dynamic data inserted into email templates to prevent injection attacks.
- **Template Engine Verification:** Confirm whether the email service supports Nunjucks or if adjustments are needed for compatibility.
- **Version Control:** Store all templates and related configuration in the project's version control system for tracking and collaboration.
- **Future Scalability:** Design the system to easily accommodate additional notification types and templates as needed.

**Comment by Grulin** [comment]
![Image](https://github.com/user-attachments/assets/e68fb7e2-a2c9-4892-b312-e71ccd7de990)
