### ISSUE TITLE
LCFS - BUG New fuel code pre-populated with 100.0

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1233]
**Describe the Bug**
In the "Fuel code" column of a new fuel code entry, the default value "100.0" is incorrectly pre-filled. This field should automatically show the next whole number available by default. The current behavior requires users to delete the pre-filled value before entering a new fuel code, which can be frustrating, especially when inputting multiple lines of new fuel codes.

**Expected Behaviour**

- The "Fuel code" column field should show the next available whole number by default when adding a new fuel code.
- Users should not need to delete a pre-filled value before entering their input.

**Actual Behaviour**

- The Fuel Code column field is pre-filled with "100.0", requiring users to delete this value before entering a new fuel code.

**Implications**

- The pre-filled default value adds unnecessary steps and frustration for users, especially when adding multiple fuel codes.
- This could slow down data entry and reduce the efficiency of the system.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR analyst

1. Navigate to the Fuel Code Input Table.
2. Add a new fuel code entry.
3. Observe that the Fuel Code column field is pre-filled with the value "100.0".
4. Attempt to input a new fuel code and notice the need to first delete the default value.

**Comment by airinggov** [comment]
It was supposed to find the next available code. After the prefix is selected it would look up the next available code. But if they typed an existing code it would prompt the next available increment (like TFRS does).

**Comment by Grulin** [comment]
Hi @prv-proton  I confirmed with the engineering team that there is no assignment of fuel codes based on fuel type and that this should just suggest the next whole number available. So if 100.0 is taken, then it should suggest 101.0. If every whole number is taken from 100-500, then the next code it should suggest is 501.0.

**Comment by prv-proton** [comment]
Further to the above comment
>one more question, what will be the first whole number? should it start from 001.0 or 100?
>The very first fuel code approved in 2013 started at 101.0
>I think we should start with that

**Comment by airinggov** [comment]
Yes 100 is good for starting codes

**Comment by airinggov** [comment]
This is working well when loading the form for the New fuel code button. We need to implement the same logic when adding or selecting a prefix from the select list.
