### ISSUE TITLE
LCFS - Definition of red asterisk Ag grid

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1236]
**Describe the task**
Add a definition for the red asterisk on any AG grid input table using it. The definition should include an image of the red asterisk along with the text:

**"Indicates a required field"**

**The definition should be displayed:**

- Directly below the title "Add New Fuel Code(s)" when entering a new fuel code.
- Directly below the title "Edit Draft Fuel Code" when editing a draft fuel code.
- Directly below the subtitle "Report the fuel volumes supplied for various uses" in the compliance report Fuel supply schedule
- Directly below the subtitle "Report dates of supply for your FSE" in the compliance report FSE schedule
- Directly below the subtitle "Enter allocation agreement details below" in the compliance report Allocation agreement schedule.
- Directly below the subtitle "You must report fuel..." in the compliance report Export schedule.

**The red asterisk and the definition need to be added to the following schedule AG grids:**

Notional transfer- Definition should show under "Add new notional transfer(s)" and the red asterisks should be added to the beginning of the title for the following columns: 

- Legal name of trading partner
- Address for service
- Fuel category
- Received or transferred
- Quantity (L)

Fuels for other use- Definition should show under the "Add new other use(s)" title and the red asterisks should be added to the beginning of the title for the following columns:

- Fuel type
- Fuel category
- Quantity supplied
- Units
- Expected use

(Please also correct the first letter of the second word of these titles to be lower case letters to match the format of the rest of the portal)

**Purpose**
To ensure users understand the meaning of the red asterisks displayed next to mandatory fields. This clarification will improve user experience and reduce confusion about which fields are required.

**Acceptance Criteria**

Add a definition containing an image of the red asterisk and the text: *" Indicates a required field"**.

- [ ] Directly below the title "Add New Fuel Code(s)" when entering a new fuel code.
- [ ] Directly below the title "Edit Draft Fuel Code" when editing a draft fuel code.
- [ ] Directly below the subtitle "Report the fuel volumes supplied for various uses" in the compliance report Fuel supply schedule
- [ ] Directly below the subtitle "Report dates of supply for your FSE" in the compliance report FSE schedule
- [ ] Directly below the subtitle "Enter allocation agreement details below" in the compliance report Allocation agreement schedule.
- [ ] Directly below the subtitle "You must report fuel..." in the compliance report Export schedule.
- [ ] Add definition and red asterisks for the Notional transfers schedule
- [ ] Add definition and red asterisks to Fuels for other use schedule
- [ ] Format titles to ensure that only the first word is capitalized
- [ ] Test to ensure the definition appears correctly and consistently on both pages across all user interfaces 

**Additional context**

- Ensure the formatting of the definition aligns with existing UI design standards.
- Confirm the asterisk image matches the one used in the field labels.

**Comment by airinggov** [comment]
I see the asterisk for the required field have been added but not the "Indicates a required field" text. It should appear on the input form like these examples.

https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/173989423
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/180146525

**Comment by prv-proton** [comment]
> [@prv-proton](https://github.com/prv-proton) I see the asterisk for the required field have been added but not the "Indicates a required field" text. It should appear on the input form like these examples.
> 
> https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/173989423 https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/180146525

Thanks @airinggov, I didn't had the wireframe to refer to on this ticket, so went ahead with the current fix. Will try to fix the code as per the wireframe. Disadvantages to this approach I see is that from the development perspective, code gets repeated in multiple views

**Comment by airinggov** [comment]
@prv-proton sorry not sure what you mean. We just want to add the text to explain the red asterisk indicates a required field. No change to vaildation or the schedules.

**Comment by airinggov** [comment]
@prv-proton 

![Image](https://github.com/user-attachments/assets/007e4d02-aac1-44eb-b0fe-933e04a20517)

![Image](https://github.com/user-attachments/assets/0bc61b64-8706-4167-bae7-dd62fcd223cd)

**Comment by prv-proton** [comment]
> [@prv-proton](https://github.com/prv-proton) sorry not sure what you mean. We just want to add the text to explain the red asterisk indicates a required field. No change to vaildation or the schedules.

sorry @airinggov, it's my part of not being clear. I understand it's a simple informational note aimed at improving clarity for users. However, this implementation approach requires this text to be added manually in multiple views. 
my current approach was

- The explanatory text ("Indicates a required field") is now grid-specific and dynamically tied to the grid view.
- Whenever a grid contains fields marked with a red asterisk (*), this text will appear at the top-left of the grid automatically.
- This avoids the need to manually add the text to each individual grid or view.
![Image](https://github.com/user-attachments/assets/84ec84c6-5ccd-4e2b-a7c7-e6245a44d236)

**Comment by prv-proton** [comment]
I hope this explanation helps clarify my approach.  If not, I’m happy to connect and discuss further to ensure we align on the solution. Let me know how I can assist!

**Comment by airinggov** [comment]
@prv-proton oh great, I like the way you've done that. I'm just not seeing it for some reason

**Comment by prv-proton** [comment]
@airinggov , yes seems like migration issue in dev environment. Will try to fix it.
