### ISSUE TITLE
Add direct file upload capability when creating & submitting a compliance report

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#124]
**Description:**
Implement reusable component into compliance reporting

Give the ability for BCeID users to upload documents directly within a draft compliance report. Create card as per wireframe to have a File submission button that open the file upload component. Uploaded files will be displayed in an accordion like other schedules. It should be the first accordion under the Report Details heading.

**Wireframe:** 
https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/181352056/simulate/no-panels
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/187415800

**Purpose and benefit to user:**
Fuel suppliers can provide supporting documentation when submitting a compliance report. Currently they have to submit these documents through a separate file submission or email. 

**Acceptance Criteria:**
File Upload Functionality:
- [ ] The system allows BCeID users to upload documents directly within a draft compliance report.
- [ ] A "File Submission" button is present as per the wireframe design.
- [ ] Upon clicking the "File Submission" button, the file upload component modal is displayed. The modal can increase in height if required to show full list of files being uploaded.
- [ ] Uploaded files are successfully attached to the draft compliance report.

Accordion Display:
- [ ] Uploaded files are displayed in an accordion-style interface.
- [ ] The uploaded files section appears as the first topmost accordion under the "Report Details" heading.
- [ ] Users can expand and collapse the accordion to view or hide the uploaded files.

File Management:
- [ ] Users can delete or replace uploaded files within the draft compliance report (by returning to the upload utility page).
- [ ] The system stores the uploaded files securely and associates them with the correct compliance report.

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by Kailee-Douglas** [comment]
**User feedback**: feature requested by manager at LCFS Sprint Review on November 29, 2023

**Comment by dhaselhan** [comment]
Unblocked, Kuan has deployed ClamAV and made the buckets. Need to verify the ENV variables are set as we expected and working in Develop.
