### ISSUE TITLE
LCFS - Progress bar inconsistencies in different transfer statuses

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1250]
**Describe the task**
Ensure the progress bar at the top of all Transfer status pages is consistent. The correct progress pathway should be:
Draft →Sent → Submitted → Recorded

Currently:

- The Sent status page is not showing "Draft" in the progress bar.
- The Submitted status page is displaying the correct 4-state progress bar pathway (Draft →Sent → Submitted → Recorded).

**Purpose**
To maintain consistency in the progress bar across all Transfer status pages, ensuring that users can easily understand the status progression of a transfer.

**Acceptance Criteria**

- [ ] Update the progress bar on the Sent status page to display the correct pathway: Draft →Sent → Submitted → Recorded.
- [ ]  Ensure that the progress bar is consistent across all Transfer Status pages.
- [ ]  Test the progress bar for all transfer statuses (Draft, Sent, Submitted, Recorded) to confirm accurate display and functionality.

**Additional context**
Test the progress bar across different user roles (e.g., IDIR and BCeID users) and screen resolutions to ensure consistency.
Originally captured in card #213

**Comment by airinggov** [comment]
This may be okay in that the receiving party doesn't really need to see the Draft step on the progress bar
