### ISSUE TITLE
LCFS - Add additional choices to the Feedstock and finished fuel Transport mode fuel code option

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1252]
**Describe the task**
Edit "Marine" option to "Marine-domestic" and add "Marine-international" as selectable options in the Feedstock Transport Mode column and the finished fuel transport mode of the Fuel Code Input on the IDIR side.

**Purpose**
To expand the Feedstock Transport Mode and finished fuel transport mode options in the Fuel Code Input section to accommodate additional transport methods for feedstock, ensuring accurate data entry and alignment with real-world scenarios.

**Acceptance Criteria**

- [ ] Edit "Marine" to "Marine-domestic" as an option in the Feedstock Transport Mode column.
- [ ] Edit "Marine" to "Marine-domestic" as an option in the Finished Fuel Transport Mode column.
- [ ]  Add "Marine-international" as an option in the Feedstock Transport Mode column.
- [ ]  Ensure both options are displayed in the dropdown list for the Feedstock Transport Mode column in the Fuel Code Input section on the IDIR side.
- [ ]  Test to confirm the new options can be selected and saved correctly.
- [ ]  Verify that the changes do not impact other functionality or existing options in the Feedstock Transport Mode column.

**Additional context**

**Comment by Grulin** [comment]
Hi @areyeslo. Was this issue resolved? I still can't see the domestic/international changes unfortunately:
![Image](https://github.com/user-attachments/assets/63160af5-d905-4d12-99a0-39c860c12995)

**Comment by areyeslo** [comment]
Let me check, the migration was applied successfully but the changes are not in database. Something weird over there.

**Comment by areyeslo** [comment]
For some reason the migration did apply, I had to run again:
![Image](https://github.com/user-attachments/assets/909efcd6-1a42-42ea-9af7-a852a37e35c8)
