### ISSUE TITLE
LCFS - Add organization name to FSE identification grid input and view table

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1255]
**Describe the task**
Add a new column titled "Organization Name" as the first column in the FSE Identification Form in the compliance report. This column should:

- Be mandatory.
- Allow both letters and number characters for input.

**Purpose**
To capture the organization name as part of the FSE Identification Form, ensuring that each entry is clearly associated with an organization. This ensures that organizations that are allocating supply are able to identify the name of the organization(s) they are taking on the reporting obligation for. 

**Acceptance Criteria**

- [ ] Add a new column titled "Organization Name" as the first column in the FSE Identification Form.
- [ ]  The column must be mandatory, requiring input before the form can be submitted.
- [ ]  The column should allow the entry of letters and number characters.
- [ ]  Test the new column to ensure it functions correctly, including data validation for mandatory input and character restrictions.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by areyeslo** [comment]
@Grulin  just to confirm the column should be added as the first column in here:
![Image](https://github.com/user-attachments/assets/538de3d9-d7fe-4e86-af14-1892aa03871d)

**Comment by Grulin** [comment]
Correct, it should be the very first field (next to the "action" column)

**Comment by airinggov** [comment]
I removed the 
- [ ]  Include predictive text

as the majority of orgs won't have LCFS accounts

**Comment by airinggov** [comment]
@areyeslo Hi Arturo, the form isn't loading for me at all in Dev

**Comment by areyeslo** [comment]
@airinggov working now.
