### ISSUE TITLE
LCFS - BUG editing  a draft fuel code

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1256]
**Describe the Bug**
Refactor AG grid 

The editing feature of a draft fuel code is not functioning correctly. Currently, users are only able to choose a prefix, but all other fields in the AG grid are locked and cannot be edited. When editing a fuel code in draft mode, users should have the ability to adjust any field in the grid to ensure the accuracy of the data before submission.

**Expected Behaviour**

- When editing a draft fuel code, all fields in the AG grid should be editable, allowing users to make necessary adjustments.
- Changes made during editing should save correctly and update the draft fuel code.

**Actual Behaviour**

- Only the prefix field is editable in the AG grid when attempting to edit a draft fuel code.
- All other fields in the grid are locked, and no changes can be made.

See screenshot:
![Image](https://github.com/user-attachments/assets/94f4eab7-546e-4756-9ee6-b6c3f002064d)

**Implications**

- Users are unable to update or correct draft fuel codes, potentially leading to incomplete or inaccurate submissions.
- This issue disrupts the workflow, requiring users to create new entries instead of editing existing drafts.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR

1. Navigate to a draft fuel code in the Fuel Code Input Table.
2. Select the Edit option for the draft fuel code.
3. Attempt to edit fields in the AG grid.
4. Observe that only the prefix field is editable, while all other fields are locked.

**Comment by dhaselhan** [comment]
Quick notes:
* This is still using the deprecated BCGridCellEditor and is the only place left
* It still has a dedicated delete and save button which should probably be removed
