### ISSUE TITLE
LCFS - Sorting and filtering bug on Fuel Code view table

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1267]
**Describe the Bug**
The sorting/filtering function in the Fuel Code view table is only sorting the fuel codes displayed on the first page rather than applying the sort/filter to all fuel codes in the system. This results in an incomplete and inaccurate filter, as the user only sees results based on the fuel codes visible on the first page rather than across the entire dataset.

**Expected Behaviour**
- The sorting/filtering function should apply to all fuel codes in the system, regardless of which page they are displayed on.
- Sorting/filtering should provide accurate results that span all pages of the Fuel Code view table.

**Actual Behaviour**
- The sorting/filtering function only sorts and filters fuel codes displayed on the first page.
- Fuel codes not visible on the first page are excluded from the sorting results, leading to incomplete and inaccurate output.

**Implications**
- Users cannot reliably filter and sort fuel codes, making it difficult to find specific entries or analyze the data effectively.
- This limits the usability of the Fuel Code view table for large datasets spread across multiple pages.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR
1. Navigate to the Fuel Code view table.
2. Enter a sorting/filter query (e.g., search by Fuel Code or Facility).
3. Observe that the sort only applies to the codes displayed on the first page of the table.
4. Navigate to subsequent pages and note that the filter is not applied.

**Comment by dhaselhan** [comment]
There are issues with our current date filtering implementation, after talking to Al he has made the call to remove the filters for the date columns as they are more likely to be used for sorting.

**Comment by airinggov** [comment]
@dhaselhan hey Dan, looks great, only the Carbon Intensity filter doesn't seem to work.

Also, is it possible to remove the date filter box completely?
![Image](https://github.com/user-attachments/assets/6b754e83-b990-4411-b18f-db36fc9fa347)

**Comment by dhaselhan** [comment]
Hey Al, number filtering is being covered in #1350 . Ill remove the filters for the dates.
