### ISSUE TITLE
LCFS - Allocation agreement

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1283]
**Description:**The Allocation agreement schedule opens with no rows. The page should open with one active row to input, as per all other schedules.

**Wireframe:** 

![Image](https://github.com/user-attachments/assets/5e22c1a5-4167-4138-9c23-0fd701fb9b61)

**Purpose and Benefit to User:** 
Ensure consistency and ease of use across the platform by providing an active input row on page load. This improves the user experience and aligns the behavior of the Allocation Agreement schedule with other schedules.

**Acceptance Criteria:**
- [ ] The Allocation Agreement Schedule loads with one active input row by default.
- [ ] The active row is editable and ready for user input upon page load.
- [ ] Additional rows can still be added manually by the user as needed.

**Development Checklist:**
- [ ] Update the page initialization logic to include one active row on load.

**Notes:**

**Comment by airinggov** [comment]
@AlexZorkin hey Alex, this doesn't appear to be working yet. I have made a new card #1397 that may supersede this

**Comment by AlexZorkin** [comment]
This wasn't quite merged yet so its testable now.
