### ISSUE TITLE
LCFS- BUG in line 6, 7, 8 and 9 of the compliance reporting summary when deleted

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1287]
**Describe the Bug**
In the Compliance Reporting Summary, lines 7 and 9 are exhibiting incorrect behavior when a user deletes the input in these fields:

- If a user deletes the input in these fields, they receive an error message (#422).
- When the page is refreshed, the previous input reappears instead of saving as zero.
- However, if a user manually inputs "0", it will save correctly as zero.

The expected behavior is that deleting the input in these fields should automatically save as zero, and the user should not encounter an error.

**Expected Behaviour**
- A user should be able to delete the input in line 7 or line 9, navigate away from the report summary, and have the fields automatically save as zero.
- No error messages (e.g., #422) should occur during this process.
- The fields should retain the zero value after the user navigates back to the report summary.

**Actual Behaviour**
- Deleting the input in line 7 or line 9 causes a #422 error message.
- Refreshing the page reverts the fields to the previous input instead of saving them as zero.
- Manually entering "0" saves the value correctly.

**Implications**
- Users are unable to effectively clear inputs in line 7 and line 9, leading to frustration and potential reporting errors.
- The error and reversion behavior disrupts the expected workflow, creating inconsistencies in the compliance reporting process.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID

1. Navigate to the Compliance Reporting Summary.
2. Delete the input in line 7 or line 9.
3. Observe the #422 error message.
4. Refresh the page and observe that the previous input reappears.
5. Enter a "0" value in these fields and observe that it saves correctly.

**Comment by dhaselhan** [comment]
I believe the deleting bug also applies to 6 and 8, so 6, 7, 8, and 9.

**Comment by Grulin** [comment]
I still don't think this is working correctly. I entered these values in line 6, refreshed and they saved, deleted both of them and refreshed again and they reverted back to this (the volumes I had deleted):

![Image](https://github.com/user-attachments/assets/51a5d1d0-2992-4f8b-a056-dc9d214f3373)

**Comment by Grulin** [comment]
@dhaselhan You are correct, that resolved it. I'll think of how to deal with this for the user
