### ISSUE TITLE
LCFS - Setting to hide compliance units balance in heading

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#129]
**Description:**

Implement a feature allowing BCeID users to conceal their organization's compliance unit balance displayed in the main heading on every page. This can be controlled via an on/off toggle located in the settings section (accessed by clicking on the user's name, then settings, followed by a new sub-tab). The default setting will display the balance.

**Wireframe:** <link>
click eye icon
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/p/164328905/tfrs-2023/page-1?mode=fm

**Purpose and benefit to user:**
This feature responds to a BCeID user request. It enhances security by concealing sensitive business information (compliance balance) when users are in potentially insecure environments, such as open offices with third-party presence.

**Acceptance Criteria:**

1. **Given** I am a BCeID user, **When** I access the settings section, **Then** I should see an option to hide/show the compliance unit balance.
2. **Given** I am a BCeID user who has chosen to hide the balance, **When** I navigate across different pages, **Then** the balance should remain hidden until I choose to show it again.
3. **Given** I am a BCeID user who has chosen to show the balance, **When** I navigate across different pages or end the session, **Then** the balance should remain visible.

**Development Checklist:**

- **A.** Add a hide/show toggle for BCeID users to manage the visibility of the balance.
- **B.** Ensure that the implementation of this feature does not interfere with or break any other existing functionalities.
- **C.** Guarantee that the user's choice (hide/show) persists across different pages and sessions.

**Notes:**

- Ensure thorough testing of the toggle feature across various pages and scenarios.
- User experience should be seamless, with clear indications of the current state of the balance visibility.
- The implementation should align with existing design standards for consistency.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/129?planning-poker) with Zenhub @jig-patel @prv-proton

**Comment by Grulin** [comment]
When a BCeID user signs-in, the default setting should **display** the current compliance balance. Currently, the default setting when a BCeID user signs in is to hide the balance:



![Image](https://github.com/bcgov/lcfs/assets/156380046/8894616d-b59b-42ef-b448-8724e72ea716)
