### ISSUE TITLE
LCFS - Filter out inactive users by default in the user tables

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#130]
**Description:**
Implement a default filter to hide inactive users in the user tables, applicable to both BCeID and IDIR users. Introduce a checkbox labeled 'active', selected by default, to toggle the visibility of inactive users. When unchecked, both active and inactive users will be displayed.

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/p/164329808/tfrs-2023/bceid-org-details-and-users?mode=fm

**Purpose and Benefit to User:**
The filter aims to declutter the user table by hiding inactive users, addressing user feedback about the visibility of inactive users causing confusion regarding their access to the system.

**Acceptance Criteria:**
1. Given I am a logged-in user, When I navigate to the user tables, Then only active users should be displayed by default.
2. Given I am a logged-in user, When I uncheck the 'active' checkbox, Then both active and inactive users should be displayed.

**Development Checklist:**
A. Implement a default filter to hide inactive users on the user tables.
B. Create a checkbox for toggling the visibility of inactive users.
C. Update user table UI to match the provided wireframe.

**Notes:**
Consider user feedback during implementation to ensure that the new filter functionality aligns with the users' expectations and improves their experience.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/130?planning-poker) with Zenhub @prv-proton @jig-patel

**Comment by kevin-hashimoto** [comment]
completed as part of #174

**Comment by Grulin** [comment]
Filter is working, and is on by deafult when you view users on the IDIR side. 
The "active" default **is not** on when you first visit the organization page on the BCeID side. Please see screenshot for BCeID view when you first view the user table for an organization:



![Image](https://github.com/bcgov/lcfs/assets/156380046/a54e956d-2781-41f5-85e6-e36e997696ee)
