### ISSUE TITLE
LCFS - BUG AG Grid copy and paste function for FSE section in compliance report

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1301]
**Describe the Bug**
The copy and paste function in the AG Grid works correctly for all columns in the FSE section except for the Latitude and Longitude columns. When testing the copy and paste functionality, these two columns fail to accept pasted values, while all other columns handle pasted data as expected. Once I click on the field, it shows the correct value, but until I click on the field it continues to say "Invalid number". The Latitude and Longitude columns should also support the copy and paste function to streamline data entry.

**Expected Behaviour**
Users should be able to copy and paste values into the Latitude and Longitude columns in the AG Grid, just like the other columns in the FSE section.

**Actual Behaviour**
The Latitude and Longitude columns do not accept pasted values, while the other columns in the AG Grid function correctly.

![Image](https://github.com/user-attachments/assets/c57a0063-c1e0-424c-9f2c-7a3227ecf62c)

Used this Excel sheet to test:
[Testing of FSE form copy and paster.xlsx](https://github.com/user-attachments/files/17939830/Testing.of.FSE.form.copy.and.paster.xlsx)

**Implications**
Users are unable to use the copy and paste feature to quickly input data into the Latitude and Longitude columns, resulting in inefficient workflows and increased manual entry effort. Also, this restricts the user from being able to save as the form shows an error. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID

1. Navigate to the FSE section in the AG Grid.
2. Attempt to copy a value from another source (e.g., spreadsheet, text file).
3. Attempt to paste the same value into the Latitude or Longitude columns, along with all the other values in the form.
4. Observe that the pasted value does not populate the field for the Lat or Long columns

Note: I input 500 rows of data and it all worked well, populating all 500 rows except for these two columns

**Comment by Grulin** [comment]
Hi @prv-proton, I'm still getting the invalid number error for the lat and long coordinates when I copy and paste:

![Image](https://github.com/user-attachments/assets/acb5153f-9fc9-446b-9e78-7ccd57e69b0b)

**Comment by prv-proton** [comment]
> Hi [@prv-proton](https://github.com/prv-proton), I'm still getting the invalid number error for the lat and long coordinates when I copy and paste:
> 
> ![Image](https://github.com/user-attachments/assets/acb5153f-9fc9-446b-9e78-7ccd57e69b0b)
> 
> I couldn't save the error, but I have this template for testing if it is helpful: [Testing of FSE form copy and paster.xlsx](https://github.com/user-attachments/files/18065229/Testing.of.FSE.form.copy.and.paster.xlsx)

Hi @Grulin , looks like there was a problem in code deployment. It's working now, can you please retry and confirm.

**Comment by Grulin** [comment]
It's working perfect now. Thanks, @prv-proton
