### ISSUE TITLE
LCFS - Fuel code number

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1303]
**Description:**  
Currently, the functionality for assigning a new fuel code number works well when the form is loaded using the "New fuel code" button. The same functionality should be extended to when a user clicks the "Add row" and "Duplicate row" buttons. 

**Wireframe:**  
N/A (or attach a relevant wireframe if available).

**Purpose and benefit to user:**  
This update ensures consistency in the behavior of the application across different entry points, reducing user confusion and enhancing the user experience by automating the assignment of new fuel codes in all relevant scenarios.

**Acceptance Criteria:**  
- [ ] When a user clicks the "Add row" button, the form should assign the next available fuel code number based on default prefix and updated if the prefix is updated from the dropdown list
- [ ] When a user clicks the "Duplicate row" icon, the form should assign the next available fuel code number based on prefix that was duplicated and updated if the prefix is updated from the dropdown list
- [ ] The process for assigning the fuel code number should mirror the existing functionality when using the "New fuel code" button.  

**Development Checklist:**  
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the "Add row" button is clicked based on default prefix (BCLCF) to insert next fuel code number.
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the "Duplicate row" icon is clicked based on default prefix (BCLCF) to insert next fuel code number.
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the user changes the Prefix selection.

**Notes:**

**Comment by airinggov** [comment]
![Image](https://github.com/user-attachments/assets/70bf56f3-5b60-4e1f-9d26-ae5229b40449)

@hamed-valiollahi The fuel code number assigned after using the duplicate row function is not incrementing, even after interacting with the Prefix select it doesn't update.

Also the Duplicate row function put the new row above the existing record, it should be below.

**Comment by hamed-valiollahi** [comment]
@airinggov Thank you, Al, for testing! It's weird, as it was working without the issues you mentioned. It's probably a conflict with other tickets. I'll fix this issue.
