### ISSUE TITLE
LCFS - Remove or hide roles for inactive users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#131]
**Description:**
- Remove roles or perhaps hide the display of roles in UI for users that are inactive (whatever is easier)
- A inactive users roles are displayed in the user tables for both BCeID and IDIR users, when you click on an individual user to view their specific profile, and when editing an individual user. 
- 

**Wireframe:** <link>
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/p/164331526/tfrs-2023/bceid-org-details-and-users-inactive?mode=fm

**Purpose and benefit to user:**
- Several organizations have implemented a practice of stripping a BCeID user of all of their roles and then giving them the Guest role when marking them as inactive (as part of the revoking access process)
- User research indicates that some BCeID users find that marking a user as inactive is not enough to revoke their access and they don't like seeing how they still have all of these different roles assigned to them in the main user tables
- So as an added precaution they switch their role to Guest only
- Removing (or hiding) roles for inactive users will better communicate to users that a specific user is not able to take any actions in the system

**Acceptance Criteria:**

- [x] Given I am a BCeID/IDIR, When I am viewing inactive users then roles they were holding on to shouldn't be visible.

**Development Checklist:**
- [ ] Consider LCFS #130

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/131?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by Grulin** [comment]
Card #178 must be resolved to be able to test IDIR side. Also requires access to BCeID user account to test on that side.
