### ISSUE TITLE
TFRS - Unit Test for Scenario 3 Compliance Unit Balance Change from Assessment

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#132]
### Description:
In light of the recent issue found with Scenario 3's 'Compliance Unit Balance Change from Assessment' field, we need a dedicated unit test to ensure that the value in this field is always correctly computed and displayed to the end-users. This test will ensure that any future changes to our codebase won't reintroduce this problem.

### Acceptance Criteria:
1. The unit test should focus on Scenario 3's reporting.
2. The test must validate that when the organization doesn't have any balance to reduce, the 'Compliance Unit Balance Change from Assessment' should show a zero value.
3. In the case of Jan-release, report ID 1155, Org name: FS6, the test should confirm that the balance change from the assessment field should describe the actual balance change that will be applied to the account when the report is assessed.
4. If the field shows any value other than zero in this scenario, the test should fail, alerting the developer of an inconsistency.

### Steps:
1. Initialize a report with properties consistent with Scenario 3, such as report ID 1155, Org name: FS6.
2. Mock the necessary services, ensuring the organization doesn't have any balance to reduce.
3. Run the report assessment logic.
4. Validate that the 'Compliance Unit Balance Change from Assessment' field displays a value of zero.
5. If it does not, the unit test should throw an error or fail, highlighting the discrepancy.

### Note:
Ensure that this unit test runs as part of our regular CI/CD pipeline so that it checks against any future changes made to the system.

**Comment by justin-lepitzki** [comment]
Nothing to test on the front end
