### ISSUE TITLE
LCFS - Label update for Transaction column options in the Allocation agreement section of the compliance report

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1321]
**Describe the task**
Update the "Transaction" column name to "Responsibility" and the options in the Allocation Agreement to replace "Purchased" and "Sold" with more accurate terms:

- Sold --->"Allocated to"
- Purchased ----->"Allocated from"

These updated options reflect the transfer of responsibility for reporting, avoiding confusion caused by the terms "Purchased" and "Sold", which may incorrectly imply a financial transaction.

**Purpose**
To improve clarity and accuracy in the Allocation agreement by aligning terminology with the actual nature of the transaction, ensuring users understand that this involves the transfer of reporting responsibility, not a sale or purchase.

**Acceptance Criteria**
- [ ]  Rename column from 'Transaction' to "Responsibility"
- [ ]  Replace "Sold" with "Allocated to" in the Responsibility column.
- [ ]  Replace "Purchased" with "Allocated from" in the Responsibility column.
- [ ]  Validate that the updated options appear correctly in the dropdown list for the Responsibility column.
- [ ]  Test to ensure the functionality of the dropdown and saved selections remain unaffected by these changes.
- [ ]  Confirm that the updated terminology is reflected across all user roles (e.g., IDIR and BCeID users).

**Additional context**

**Comment by dhaselhan** [comment]
Good catch Al, turns out there was also values on the front end when adding new rows. Fixed and ready for re-test.
