### ISSUE TITLE
LCFS - Improve Number Filtering

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1350]
As a user I want to be able to filter my tables by entering the start of a number.

For example:
Entering 32 in the filter should return:
32
32.1
32.17
322

It should not return:
132

* Create a new number filter that applies a startsWith filter
* Implement the startsWith filter on the backend for numbers

**Comment by hamed-valiollahi** [comment]
@dhaselhan Thank you, Daniel, for creating this ticket. Just to confirm, should this apply to all tables? Does it also include table row IDs?

**Comment by dhaselhan** [comment]
This should be applied to all number/int/float columns in each grid. I don't believe we show rowIds in the ui, where can we filter them?

**Comment by hamed-valiollahi** [comment]
Thanks, Daniel, for the clarification. You're right! Sorry for the confusion. I meant "Row ID" in the Audit Log table, but it's not the actual row ID. 👍

**Comment by hamed-valiollahi** [comment]
For testing purposes, these are the columns affected by this change:

BCeID:
- Transactions (Units, Value per unit)

IDIR:
- Transactions (Units, Value per unit)
- Fuel Codes (Iteration, Carbon Intensity)
- Administration > User Login History (User Login History ID)
- Administration > Audit Log (Row ID)

Let me know if anything else needs to be included!
