### ISSUE TITLE
LCFS - Privacy and legal disclaimers

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#137]
**Description:**
Have disclaimers in the application for: 
- Privacy - disclaimer to remind users not to provide / input personal information about themselves or others 
- Legal - disclaimer to inform users that the information contained in the app does not replace or constitute legal advice. Liability disclaimer provided by legal. 

**Legal Disclaimer:** 
- Visible to BCeID users only
- Disclaimer: "This information does not replace or constitute legal advice. Users are responsible for ensuring compliance with the Low Carbon Fuels Act and Regulations."

**Privacy Disclaimer:**
- Visible to both IDIR and BCeID users 
- Disclaimer: For security and privacy reasons, please don't share personal information on this website.

**Screenshot of ZEVA example:** https://drive.google.com/file/d/1U94QpKLf540aiiG4V3fu55E4U4T9JG1a/view?usp=sharing

**Purpose and benefit to user:**
Help ensure that private information is not shared, stored, or disclosed in our application. Remind stakeholders of their responsibility to comply with the LCFA. 

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, Disclaimer banner should be provided at the bottom of all the pages.
- [ ] Given I am a IDIR user, Separate private disclaimer banner should be visible to IDIR users.

**Development Checklist:**
- [ ] **Implement Legal Disclaimer Banner for BCeID Users:**
  - Create and position the legal disclaimer banner at the bottom of all BCeID user pages.
- [ ] **Implement Privacy Disclaimer Banner for All Users:**
  - Develop a privacy disclaimer banner visible to both IDIR and BCeID users, ensuring prominent placement.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/137?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @kevin-hashimoto
