### ISSUE TITLE
LCFS - Creation of Frontend Login View for LCFS Application

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#138]
**Task Description:**
Develop a frontend login view that accommodates users intending to sign in with BCEID or IDIR credentials. The interface should be aesthetically pleasing with a notable background image, prominently featuring the text 'Low Carbon Fuel Standard.'

**Purpose:**
This task is paramount for establishing a user-friendly entry point to the Low Carbon Fuel Standard system, promoting accessibility while ensuring a clear brand identity. The inviting and professional appearance of the login view encourages user trust and interaction.

**Acceptance Criteria:**
1. Design an interface that includes an option for users to proceed with BCEID or IDIR. This view can work similarly to the TFRS login view.
2. Incorporate an attractive background in the design, adhering to the aesthetic standards of the Low Carbon Fuel Standard.
3. Ensure the 'Low Carbon Fuel Standard' text is visibly displayed on the login view.
4. The user experience should be intuitive and straightforward, preventing any possible user confusion.
5. Internet Explorer Popup from the TFRS page should be maintained in LCFS

**Additional Context:**
- The design should align with the Low Carbon Fuel Standard branding guidelines to maintain visual consistency.
- The system's frontend should be built with consideration for future backend integrations.

This task, focusing on frontend development, forms the foundation for a secure, efficient, and user-centric application, emphasizing the importance of 'Low Carbon Fuel Standard' in every user's interaction.

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/138?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
BC government image galleries: 
1) http://gdu.gcpe.gov.bc.ca/content/photos/
2) https://gww.th.gov.bc.ca/MediaGallery/Search

Contains images that we can use for our homepage. Can explore other options but we have to confirm that we can use it for free (no fees or copyright issues) and that it is a neutral image that doesn't favour one fuel, stakeholder, groups of stakeholders over others.

**Comment by AlexZorkin** [comment]
closed for redundancy
