### ISSUE TITLE
 LCFS - User and Role Tables Completion

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#139]
**Task Description:**
Complete the User and Role tables in the LCFS FastAPI application, leveraging SQLAlchemy and Alembic. This task focuses on refining table structures, defining relationships, and integrating them into the existing system.

**Purpose:**
To solidify the foundation for user access and role-based permissions in the LCFS system, ensuring system integrity and facilitating future feature expansions.

**Acceptance Criteria:**
1. Perfect the SQLAlchemy models for User and Role tables, aligning with system requirements.
2. Define clear relationships between User and Role tables, including necessary foreign keys.
3. Craft Alembic migration scripts for reliable database updates.
4. Integrate the models into the FastAPI application.
5. Outline basic CRUD operations for User and Role management, with placeholder methods in routes.
6. Pass all relevant integration and unit tests.
7. Update pertinent documentation reflecting the new changes.

**Additional Context:**
- Adherence to the data model design from the previous ticket is crucial.
- Attention to detail in Alembic migrations is essential to maintain data integrity.
- Collaborate effectively to ensure seamless integration with the FastAPI application.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
