### ISSUE TITLE
LCFS - BUG - Error when editing Application date in Fuel code

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1393]
**Describe the Bug:**
When attempting to edit the Application Date in the draft code (103 in DEV), the system throws an error: "Unexpected Application Error! r.isValid is not a function."

**Expected Behaviour:**
Editing the Application Date should allow the user to update the date field without encountering any errors.

**Actual Behaviour:**
The system displays an error message, "Unexpected Application Error! r.isValid is not a function," and prevents the user from successfully editing the Application Date.

**Implications:**
- Users cannot update the Application Date

**Steps To Reproduce:**
1. User/Role: IDIR\Analyst.
2. Go to the Fuel code tab.
3. Open draft code 103.
4. Attempt to edit the Application Date field.
5. Observe the error: "Unexpected Application Error! r.isValid is not a function."

**Additional Context:**

**Comment by dhaselhan** [comment]
This is the same cause as the bugs in #1267 so these will be fixed in the same MR

**Comment by airinggov** [comment]
working, can close. Getting a funny 'phantom' pill when selecting Finished fuel transport (prevent the line from saving) but I can make a new card for that

![Image](https://github.com/user-attachments/assets/5048b555-77bc-4bb6-9714-19aff3766907)
