### ISSUE TITLE
TFRS - Enhance Messaging to Sync Compliance Reports from TFRS to LCFS

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#1395]
## Description  
This enhancement introduces a messaging-based synchronization mechanism ensuring that compliance reports created or updated in TFRS are immediately known to LCFS. Previously, LCFS only received messages related to transactions upon a compliance report reaching certain states (e.g., Director approval). With this change, when a compliance report is created in TFRS, a corresponding message is published to a queue that LCFS consumes. LCFS then creates a local compliance_report entry in advance, enabling seamless handling of subsequent events, such as placing credits "in reserve" or linking approved credit trades.

## Purpose and Benefit  
By proactively sharing compliance report information from TFRS to LCFS:  
- LCFS maintains an up-to-date reference of all compliance reports.  
- When a report transitions to a submitted or approved state in TFRS, LCFS can immediately attach transactions or credits to the correct compliance_report record.  
- Reduces complexity and ensures synchronous data integrity between TFRS and LCFS.

## Acceptance Criteria  
- Creation Message: When a compliance report is created in TFRS, a message is published to a designated compliance_report_queue with essential details (tfrs_compliance_report_id, organization_id, compliance_period_id, report_type, nickname).  
- LCFS Record Creation: Upon receiving the message, LCFS creates a corresponding compliance_report record with a compliance_report_group_uuid and version=0 if it represents the original report.  
- Subsequent Updates: When TFRS later submits or approves the compliance report, LCFS already has the reference and can create "In reserve" transactions or other compliance-unit related changes without delay.  
- Error Handling: Failures in message publishing or consumption are logged. The system continues to process other messages.  
- Documentation & Schema: The message schema and code usage are documented.

```python
## Message Schema Example  
{  
 "tfrs_compliance_report_id": 1234,  
 "organization_id": 567,  
 "compliance_period_id": 89,  
 "report_type": "Compliance Report",  
 "nickname": "Initial Report",  
 "timestamp": "2024-01-15T12:34:56Z"  
}
```
## Development Checklist  
1. Message Schema Definition:  
   Define a JSON schema for compliance_report messages, including fields for TFRS report ID, organization, compliance period, report type, and nickname.

2. Message Publishing in TFRS:  
   In ComplianceReportService (TFRS side), after creating a compliance report, publish a message:  
   from api.services.ComplianceReportMessageService import ComplianceReportMessageService  
```python
   class ComplianceReportService:  
       @staticmethod  
       def create_compliance_report(organization_id, compliance_period_id, report_type, nickname=None):  
           compliance_report = ComplianceReport.objects.create(  
               organization_id=organization_id,  
               compliance_period_id=compliance_period_id,  
               type=ComplianceReportType.objects.get(the_type=report_type),  
               nickname=nickname  
           )  
           ComplianceReportMessageService.send_compliance_report_message(  
               tfrs_id=compliance_report.id,  
               organization_id=organization_id,  
               compliance_period_id=compliance_period_id,  
               report_type=report_type,  
               nickname=nickname  
           )  
           return compliance_report
```
3. Message Consumption in LCFS:  
   In LCFS, implement a consumer that listens to compliance_report_queue:  
```python
   import json, uuid  
   from lcfs.db.models import ComplianceReport  
   def on_compliance_report_message(ch, method, properties, body):  
       message = json.loads(body)  
       tfrs_id = message["tfrs_compliance_report_id"]  
       org_id = message["organization_id"]  
       period_id = message["compliance_period_id"]  
       report_type = message["report_type"]  
       nickname = message.get("nickname")  
       lcfs_report = ComplianceReport(  
           compliance_period_id=period_id,  
           organization_id=org_id,  
           compliance_report_group_uuid=str(uuid.uuid4()),  
           version=0,  
           nickname=nickname  
       )  
       lcfs_report.save()  
       print(f"Created LCFS compliance_report for TFRS ID {tfrs_id}")
```
4. Transaction Integration:  
   With LCFS aware of compliance_reports from their inception, "In reserve" transactions or other updates can be applied immediately upon status changes.

5. Error Handling and Logging:  
   Implement try-except around message operations and log failures. Retry or queue dead-letter logic as needed.

6. Testing:  
   - Create a compliance report in TFRS and verify a message is published.  
   - Ensure LCFS consumes the message and creates a compliance_report entry.  
   - Submit and approve the compliance report in TFRS; verify LCFS can create "In reserve" transactions.  
   - Test edge cases (missing fields, network issues).

7. Documentation:  
   Document message flows, queue configurations, and code integration. Include diagrams and examples of normal and exceptional flows.

## Notes  
This approach ensures LCFS has prior knowledge of compliance reports referenced by transactions or approvals in TFRS. By maintaining a synchronized state, both systems can operate efficiently, providing a more reliable and consistent compliance management experience.

**Comment by dhaselhan** [comment]
Talked to Alex:

We are going to be adding legacy_id to compliance reports in LCFS to indicate which ones are from TFRS to control certain behaviour. This also keeps us from needing to worry about auto-increment IDs clashing on each system.

**Comment by dhaselhan** [comment]
Sync is working on Dev!
