### ISSUE TITLE
LCFS - Identify Functional Testing Framework for LCFS Application

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#140]
**Task Description:**
Evaluate and select a functional testing framework that integrates with our backend's pytest and frontend's Jest. The framework should support end-to-end testing, ensuring comprehensive quality assurance.

**Purpose:**
To establish a robust testing process, ensuring the application's functionality aligns with user expectations, thereby enhancing reliability and user satisfaction.

**Acceptance Criteria:**
1. Analyze potential frameworks compatible with pytest and Jest.
2. Assess scalability, ease of use, and support for each option.
3. Compile a comparative analysis highlighting each framework's strengths and weaknesses.
4. Recommend the most suitable framework with rationale.
5. Gather team feedback for the final decision.
6. Outline a preliminary integration plan.

**Additional Context:**
- Integration with existing tests and learning curve should influence the choice.
- Input from frontend and backend teams is crucial for a balanced decision.

Selecting the right functional testing framework will fortify our application's reliability through thorough quality checks.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/140?planning-poker) with Zenhub @jig-patel @prv-proton

**Comment by prv-proton** [comment]
https://applitools.com/blog/what-is-applitools/#:~:text=Applitools%20provides%20an%20end-to-end%20software%20testing%20platform%20powered,and%20Digital%20Transformation%20teams.%20What%20does%20Applitools%20do%3F

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
