### ISSUE TITLE
LCFS - Error saving edits to Allocation agreement data

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1401]
**Describe the Bug:**
Edits made to rows in the Allocation Agreement input form are not saving. Attempting to save changes results in an error, and the data remains unchanged.

**Expected Behaviour:**
Edits to rows in the Allocation Agreement input form should be saved successfully without any errors.

**Actual Behaviour:**
- When attempting to save changes to a row, an error occurs.
- The edits are not saved, and the original data remains unchanged.
![Image](https://github.com/user-attachments/assets/2e10e8c5-17d6-41a0-8c5b-fe67c9ff003e)

**Implications:**
- Users are unable to update Allocation Agreement data, potentially leading to incomplete or inaccurate compliance reports.

**Steps To Reproduce:**
1. User/Role: BCeID user
2. Navigate to the Allocation Agreement input form.
3. Make edits to any row.
4. Observe the error and verify that the changes are not saved.

**Additional Context:**

**Comment by dhaselhan** [comment]
It is normal to get 422s while the row is invalid or incomplete, but it should be showing an error message for what is required. Was the label stuck saying Updating Row?

**Comment by airinggov** [comment]
Yes the row was complete/valid but it hung on Updating row
