### ISSUE TITLE
LCFS - Add Liveness Probe Health Checks

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1406]
As a developer, I want to know when LCFS is down so we can take action if needed.

https://docs.openshift.com/container-platform/4.15/applications/application-health.html

Health check is available at /api/health on the backend

We want to add a health check to the Python API that can ensure it is up and available. This will auto restart failing pods and give us better oversight of our uptime.

**Comment by kuanfandevops** [comment]
This is done. 

Received the health check through livenessProb, here is the backend log:
INFO: 10.97.12.1:41548 - "GET /api/health HTTP/1.1" 200 OK
