### ISSUE TITLE
LCFS - Schedules, Fuel code validation

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1429]
**Description:**  
For the 4 schedules input forms:
1. Fuel supply
2. Export fuel
3. Allocation agreement
4. Other use

If the option 'Fuel code - section 19 (b) (i)' is selected under 'Determining carbon intensity', the 'Fuel code' cell must become mandatory. It should not pass validation or allow saving until a valid fuel code is selected. If only one fuel code exists, it should auto-populate. If multiple fuel codes exist, no default value should be set; the user must explicitly select one.

**Wireframe:**  
Not applicable.

**Purpose and benefit to user:**  
This ensures accurate and complete data entry for determining carbon intensity, reducing errors and enhancing compliance with validation rules.

**Acceptance Criteria:**  
- [ ] When 'Fuel code - section 19 (b) (i)' is selected in the 'Determining carbon intensity' dropdown:
  - [ ] The 'Fuel code' cell becomes mandatory.
  - [ ] Saving the form without selecting a 'Fuel code' triggers a validation error.
- [ ] If only one fuel code exists:
  - [ ] The 'Fuel code' cell auto-populates with that code.
- [ ] If multiple fuel codes exist:
  - [ ] No default fuel code is pre-selected.
  - [ ] The user is required to manually select a fuel code before saving.

**Development Checklist:**  
- [ ] Implement logic to make the 'Fuel code' cell mandatory when 'Fuel code - section 19 (b) (i)' is selected.
- [ ] Configure auto-population of 'Fuel code' when only one option exists.
- [ ] Prevent auto-selection when multiple fuel codes are available; enforce manual selection.
- [ ] Add validation error messaging for unselected mandatory 'Fuel code'.
- [ ] Apply these rules to all 4 schedules: Fuel supply, Export fuel, Allocation agreement, and Other use input forms.
- [ ] Test scenarios with single and multiple fuel codes to ensure correct behavior.

**Notes:**  
- Confirm the list of fuel codes and their availability across different schedules.
- Ensure error messages are user-friendly and clearly indicate the requirement to select a 'Fuel code'.

**Comment by airinggov** [comment]
Hi @hamed-valiollahi , when the Fuel code select activates it should turn white but it remain grey, can it be fixed so that it turns white when active?

**Comment by hamed-valiollahi** [comment]
Hi @airinggov, thank you for reporting the issue. I’ve created a PR to resolve it.
