### ISSUE TITLE
LCFS - Implement Fuel Table Model in FastAPI using SQLAlchemy and Alembic

### ISSUE THREAD

**Issue by jig-patel** [bcgov/lcfs#143]
**Task Description:**
Complete the Fuel tables in the LCFS FastAPI application, leveraging SQLAlchemy and Alembic. This task focuses on refining table structures, defining relationships, and integrating them into the existing system.

Go to the below link -> fuel tab
https://app.diagrams.net/

There is also change/removal of the field name in table. Please refer to drawing from above link and keep in mind those changes while implementing model in FastAPI.

**Purpose:**
To solidify the foundation for user access and role-based permissions in the LCFS system, ensuring system integrity and facilitating future feature expansions.

**Acceptance Criteria:**
1. Perfect the SQLAlchemy models for Fuel tables, aligning with system requirements.
2. Below are the table name  change
- Fuel Class Category to Fuel Category
- Approved Fuel Type to Fuel Type
3. Below are the table that we are going to remove
- Approved Fuel class category
- default carbon intensity category
- default density category
- energy effectiveness ratio category
- petroleum carbon intensity category
4. Define clear relationships between Fuel type, category etc, including necessary foreign keys.
5. Craft Alembic migration scripts for reliable database updates.
6. Integrate the models into the FastAPI application.
7. Outline basic CRUD operations for Fuel related routes from the existing TFRS project, with placeholder methods in routes. 
8. Pass all relevant integration and unit tests.
9. Update pertinent documentation reflecting the new changes.

**Additional Context:**
- Adherence to the data model design from the previous ticket is crucial.
- Attention to detail in Alembic migrations is essential to maintain data integrity.
- Collaborate effectively to ensure seamless integration with the FastAPI application.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/143?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
