### ISSUE TITLE
LCFS - Show red toast on network errors

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#1441]
As a tester of LCFS, I want to know as soon as a network failure happens so I can better report issues to developers.

Currently network errors fail silently, often leaving the loading spinner or updating message. We want to use react material toast handler to show failure toasts when a 400+ response is received.

**Comment by airinggov** [comment]
hi @kevin-hashimoto , is error 422 just a validation error? Can we exclude those from the toast?
