### ISSUE TITLE
LCFS - Review of the renewable content requirement summary section of the compliance report

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1448]
**Describe the task**
This card is meant to review the Renewable Requirement Summary of the compliance report to ensure that the correct fuel types are being pulled in to the correct lines from the correct sections of the compliance report. 

- *Note* Allocation agreements and FSE identification forms are declaration forms only and do not get included in the summary section of the compliance report. Volumes identified in these forms will again be reported in fuel supply section. 

The renewable content requirement section of the summary are reported as **volumes** of fuel

**The 3 fuel category descriptions**
Diesel - 4% renewable requirement
Gasoline – 5% renewable requirement
Jet- 0% renewable requirement (no penalties for renewable requirement until 2028 when the renewable requirement will be 1%)

**Line 1 of the summary** - This line displays the total volume of non-renewable fuel supplied for the compliance period as reported. 
Pulls this data from the following report sections: “Supply of fuel” and “Fuels for Other Use” only. 
Fuel types included in line 1

1. Fossil-derived diesel
2. Fossil-derived gasoline
3. Fossil-derived jet fuel

**Line 2 of the summary** - This line displays the total volume of renewable fuel supplied for the compliance period 
Pulls this data from the following report sections: “Fuel Supply” and “Fuels for other use” only
Fuel types included in line 2
Eligible renewable fuel types are:

1.  for gasoline category = renewable gasoline, ethanol, renewable naphtha, other; 
2.  for diesel category = biodiesel, HDRD, other diesel fuel, other; 
3.  for jet fuel category = alternative jet fuel, other

- Line 3 of the summary totals line 1+2 and seems to be working.
- Line 4 of the summary table calculates the percentage of renewable requirement (Line 3 x category percentage 0.04 diesel, 0.05 gasoline, 0 for jet until 2028) 
- Line 5 pulls data from notional transfer section of report (dealt with in card #733)
- Line 6 through 9 are working
- Line 10 is a total of the lines listed in the summary form and seems to be working
- Line 11 is dealt with in card #738 and seems to be working

**Purpose**
Some of the lines, particularly line 2, seem to be including fuel volumes it should not. This needs to be reviewed now that the reporting sections are working well. 

**Acceptance Criteria**
- [ ] Ensure that lines 1 and 2 are pulling the correct fuel types from the correct sections of the compliance report.
- [ ] Confirm that any line that includes a formula pulling totals from lines within the summary are working as expected
- [ ] Confirm that jet category renewable requirement is 0% until the 2028 reporting period.

**Additional context**
Lots of testing of different reporting scenarios should be able to help with this summary review.

**Comment by airinggov** [comment]
@kevin-hashimoto Hey Kevin, what was the result of your review?

**Comment by kevin-hashimoto** [comment]
@airinggov found that 'other diesel' was being calculated into line 1 and not included in line 2. ended up fixing some other calculation errors for those 2 lines as well.

**Comment by airinggov** [comment]
@Grulin Hi Lindsy, you might want to review when you return
