### ISSUE TITLE
LCFS - Implementation of Organization Data Model in LCFS FastAPI System

### ISSUE THREAD

**Issue by prv-proton** [bcgov/lcfs#145]
**Describe the task**
Implement the optimized data model designed for organization-related database tables in the LCFS FastAPI system using SQLAlchemy and Alembic. This includes creating models, defining relationships, and integrating them into the existing FastAPI application.

**Purpose**
This task aims to operationalize the data model designed for Organizations within the LCFS system. By implementing the models using SQLAlchemy and managing database migrations with Alembic, this ensures a robust and maintainable data layer for Organizations functionality.

**Acceptance Criteria**
- [ ] Create SQLAlchemy models based on the optimized data model design for Organization-related database tables.
- [ ] Define relationships and foreign keys between the models.
- [ ] Create Alembic migration scripts to handle database schema changes.
- [ ] Integrate the models into the existing FastAPI application.
- [ ] 'Outline' the CRUD operations for the models where necessary, leave in placeholder methods in the routes for all required endpoints. We will finish the business logic in a follow-up ticket.
- [ ] Ensure all tests pass successfully.
- [ ] Update documentation and code comments as necessary to reflect the changes and implementation process.
Make following changes to the data model.
- [ ] Delete Organization Actions Type and Organization History
- [ ] Split the Organization Address into two tables Organization Address and Organization Attorney address.
- [ ] Convert the Organization Balance table into SQL VIEW where the balance is calculated from the transactions data.  
- [ ] Ensure the Updates creates a new record for every change in Organization Address & Organization Attorney address tables.
- [ ] Organization Status and types to load are mentioned in the template.      

**Additional context**
- Adherence to the data model design from the template created in [Data Model](https://github.com/bcgov/lcfs/blob/feat/prashanth-add-data-model-template/LCFS_ERD.drawio)
- Care should be taken to ensure that database migrations are handled efficiently and effectively using Alembic.
- Coordinate with team members to ensure proper integration within the FastAPI application.

**Comment by KericeRich** [comment]
To be updated as per the new legislation, will come back to estimate once the update is made.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/145?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton @hvalioll

**Comment by justin-lepitzki** [comment]
Nothing to test
