### ISSUE TITLE
LCFS - Update Data Models for Document (File Submission) in LCFS FastAPI System

### ISSUE THREAD

**Issue by hamed-valiollahi** [bcgov/lcfs#146]
**Description:**
Implement the optimized data model designed for File Submission related database tables in the LCFS FastAPI system.

**Objective:**
Operationalize the file submission data model within the LCFS system using SQLAlchemy and Alembic. This ensures a robust and maintainable data layer for file submission functionality.

**Acceptance Criteria:**
"Document" data models needs to be renamed to "File Submission".

Rename the following SQLAlchemy models corresponding to these database tables:
- "Document Type" must be renamed to "File Submission Category"

Remove the following SQLAlchemy models for these database tables (Foreign keys must also be removed):
- "Document Credit Trade" model
- "Document File" model
- "Document Category" model

Update the following fields in the SQLAlchemy models for these database tables:
- In the "File Submission" model, the "milestone" field must be renamed to "designated action"

The following changes for default statuses in the "File Submission Status" needs to be applied.
- Remove "Received"
- Rename "Cancelled" to "Deleted"

Apply the following changes to File Submission Categories:
- Remove the "Received" category.

Implement the following changes for File Submission Categories:
- Rename the "Application" category to "Initiative Agreement Application"
- Rename the "Evidence" category to "Initiative Agreement Evidence"
- Rename the "Records" category to "Compliance Report"

**Additional Insights:**
- Align implementation with the optimized data model design from the draw.io ERD file located in Teams.
- Handle database migrations effectively with Alembic.
- Coordinate integration within the FastAPI application with team members.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/146?planning-poker) with Zenhub @jig-patel @prv-proton
