### ISSUE TITLE
LCFS - BUG - Decimals

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1462]
**Describe the Bug:** 
Fuel volume and compliance unit numbers in the Summary should not display decimal points (currency/dollar figures can have 2 decimals).

![Image](https://github.com/user-attachments/assets/3d55fe72-f5cd-4282-9e3c-5f001fbf89ba)

**Expected Behaviour:** 
- Numbers (Fuel volume and compliance unit numbers) in the Summary should not display decimal points.
- Currency figures can display decimals.

**Actual Behaviour:** 
- Decimal points are being shown for numbers in the Summary section where they are not required.
- This creates an inconsistent and unnecessary level of precision for non-currency values.

**Steps To Reproduce:** 
**User/Role:** Any user accessing compliance report Summary section.

**Comment by dhaselhan** [comment]
Blocked pending a meeting with Al and Lindsy to verify where / when we should be rounding

**Comment by dhaselhan** [comment]
Decision was made to round the non money line numbers in the front end to whole integers.
