### ISSUE TITLE
LCFS - Update Fuel code explanation on IDIR side

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1469]
**Describe the task**
Update the Fuel Code section to include the following explanatory wording:

"Draft fuel codes are saved automatically when all mandatory fields have been entered and validated. Click “Approve code” to make it available in compliance reporting."

This explanation provides users with clear guidance on how the fuel code process works, emphasizing the need for complete information and the automatic save functionality.

Wireframe: https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/194526694?mode=dm

**Purpose**
To improve user understanding of the fuel code process by explaining how draft entries are saved, the requirements for validation, and when approved fuel codes become available for use in compliance reporting.

**Acceptance Criteria**
- [ ] Add the explanatory wording to the Fuel Code section:
"Draft fuel codes are saved automatically when all mandatory fields have been entered and validated. Click “Approve code” to make it available in compliance reporting."
- [ ]  Ensure the wording is prominently displayed and formatted consistently with the rest of the section.
- [ ]  Validate that the explanation improves clarity without disrupting the layout or functionality of the Fuel Code section.
- [ ]  Test the update for proper display across all user roles (e.g., IDIR and BCeID users) and devices.

**Additional context**

**Comment by airinggov** [comment]
@prv-proton sorry Prashanth but can you change the word 'mandatory' to 'required'? It works better with the other note...* indicates a required field
