### ISSUE TITLE
LCFS - Implement Notification Data Model in FastAPI System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#150]
**Description:**  
Implement the optimized data model designed for "Notifications" related database tables in the LCFS FastAPI system.

**Objective:**  
Operationalize the notifications data model within the LCFS system using SQLAlchemy and Alembic. This ensures a robust and maintainable data layer for notifications functionality.

**Acceptance Criteria:**  
- [ ] Create SQLAlchemy models for the following database tables:
   - Notification_channel_subscription
   - notification_type
   - notification_message (fields to be defined later)
- [ ] Define and implement relationships between tables:
   - `notification_message` is linked to `notification_type` **by** `notification_type_id`
   - `notification_channel_subscription` is linked to `notification_type` **by** `notification_type_id`
   - `notification_channel_subscription` is linked to `notification_channel` **by** `channel_id`
- [ ] Create Alembic migration scripts for database schema changes.
- [ ] Integrate new models into the existing FastAPI application.
- [ ] Outline CRUD operations for models and add placeholder methods for endpoints. Detailed business logic will be addressed in a subsequent ticket.
- [ ] Ensure all tests pass.
- [ ] Update documentation and add code comments to reflect changes.

**Additional Insights:**  
- Align implementation with the new data model design. Detailed diagrams can be created and referenced if necessary.
- Handle database migrations effectively with Alembic.
- Coordinate integration within the FastAPI application with team members.

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/150?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
