### ISSUE TITLE
LCFS - Implementation of Compliance Report data models in FastAPI SQLAlchemy and Alembic migrations

### ISSUE THREAD

**Issue by prv-proton** [bcgov/lcfs#151]
**Describe the task**
Implement the optimized data model designed for organization-related database tables in the LCFS FastAPI system using SQLAlchemy and Alembic. This includes creating models, defining relationships, and integrating them into the existing FastAPI application.

**Purpose**
This task aims to operationalize the data model designed for Compliance Report Main tables within the LCFS system. By implementing the models using SQLAlchemy and managing database migrations with Alembic, this ensures a robust and maintainable data layer for Compliance reporting functionality.

**Acceptance Criteria**
- [ ] Create SQLAlchemy models based on the optimized data model designed for compliance report-related database tables.
- [ ] Define relationships and foreign keys between the models.
- [ ] Create Alembic migration scripts to handle database schema changes.
- [ ] Integrate the models into the existing FastAPI application.
- [ ] 'Outline' the CRUD operations for the models where necessary, leave in placeholder methods in the routes for all required endpoints. We will finish the business logic in a follow-up ticket.
- [ ] Ensure all tests pass successfully.
- [ ] Update documentation and code comments as necessary to reflect the changes and implementation process.
Make following changes to the data model.
- [ ] Main Compliance Report will now have a child tables Schedule A, B and C along with Summary without reference to respective record tables. All the data columns from the record tables will be moved to Main tables of respective Schedules.
- [ ] Schedule D and its respective lookup tables are no longer required, hence shall be not implemented.
- [ ] Instead of Exclusion Agreement table, we shall now implement Allocation Agreement table

**Additional context**
- Adherence to the data model design from the template created in [Data Model](https://github.com/bcgov/lcfs/blob/main/LCFS_ERD.drawio)
- Care should be taken to ensure that database migrations are handled efficiently and effectively using Alembic.
- Coordinate with team members to ensure proper integration within the FastAPI application.

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/151?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @kevin-hashimoto

**Comment by AlexZorkin** [comment]
Data model table to create:

![Image](https://github.com/bcgov/lcfs/assets/47334977/e515dca0-09f9-4a2f-8af8-e65edef689d4)
