### ISSUE TITLE
LCFS - Fuel code 'Add row' button not working as intended

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1510]
**Describe the Bug**
In the Fuel Code Input Table, clicking the "Add Row" button while entering information into the first available row results in the following issues:

1. A new row is not added to the table.
2. All information entered in the first row is cleared, even if the data was fully or partially entered.

The "Add Row" functionality should allow users to add a new row at any point without affecting the data already entered in the existing rows.

**Expected Behaviour**
- Users should be able to click "Add Row" at any point while entering information into a fuel code line without losing data in the existing rows.
- A new row should be added to the table when the "Add Row" button is clicked.

**Actual Behaviour**
- Clicking "Add Row" while entering data in the first row does not add a new row.
- The first row's information is cleared, causing users to lose all previously entered data.

**Implications**
Users cannot effectively add new rows while entering data, leading to frustration and potential loss of information.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR
1. Navigate to the Fuel Code Input Table.
2. Enter information into the first available row of the table.
3. Click the "Add Row" button while the information is partially or fully entered in the first row.
4. Observe that no new row is added, and all entered information in the first row is cleared.

**Comment by hamed-valiollahi** [comment]
I tested this issue on the dev environment, and it worked as expected without any problems.
