### ISSUE TITLE
LCFS - LNG end use label correction of wording

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1514]
**Describe the task**
Update the wording of the LNG End Use option in the Fuel Supply Section to correct the percentage range. The current option:

"Compression-ignition engine - Marine, with methane slip reduction kit - Operated within 51 to 75% of load range"

should be updated to:
"Compression-ignition engine - Marine, with methane slip reduction kit - Operated within **26** to 75% of load range."

**Purpose**
To ensure the LNG End Use option reflects the correct operational percentage range for compliance and reporting accuracy.

**Acceptance Criteria**
- [ ] Update the LNG End Use option wording to:
"Compression-ignition engine - Marine, with methane slip reduction kit - Operated within 26 to 75% of load range."
- [ ]  Verify that the updated wording appears correctly in the dropdown menu or field where this option is listed.
- [ ]  Test the change to confirm that it applies consistently across all user roles (e.g., IDIR and BCeID users).
- [ ]  Ensure the updated wording is visible and properly formatted in all reporting sections where the LNG End Use option is referenced.

**Additional context**
Please ensure no other LNG End Use options are affected by this update.

**Comment by airinggov** [comment]
@Grulin you might want to confirm this too Lindsy, I'm not sure why it isn't the same for both similar options
