### ISSUE TITLE
LCFS - Create home page with banner for when user logs in

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#153]
**Describe the task:**
Develop a home page featuring a banner displayed when a user logs in. While we've imported SCSS styling from a different project as a foundation, it requires adjustments to fit our current needs. The primary focus should be ensuring the styling aligns with the overall aesthetic of the LCFS platform.

**Screenshot reference:**
[Google Drive Screenshot](https://drive.google.com/file/d/1ZWBjc4Pt8dLn1g5HsPTFyQl2NbaZeGBI/view?usp=drive_link)

**Purpose:**
Provide a visually appealing and intuitive landing page for users upon successful login, enhancing user experience and giving them a clear starting point within the platform.

**Acceptance Criteria:**
- [ ] The imported SCSS styling is seamlessly integrated and no remnants of incompatible styling remain.
- [ ] The banner is prominently displayed, consistent with the provided screenshot's design and dimensions.
- [ ] Ensure responsiveness and cross-browser compatibility of the newly styled home page.

**Additional context:**
The recently imported styling serves as a baseline and may not directly align with LCFS's branding and design philosophy. This task will involve both leveraging the existing SCSS and making necessary customizations to achieve the desired look and feel.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/153?planning-poker) with Zenhub @hvalioll @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
