### ISSUE TITLE
LCFS - Show organization name in top banner

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#154]
**Description:**
- **Objective**: Display the organization name in the top banner of the application.
- **User Categories**:
  - **BCeID users**: Show the operating name.
  - **IDIR users**: Display "Government of British Columbia."
- **Wireframe**: [Link to wireframe](https://drive.google.com/file/d/1xWXX6Er1YIAZ5oio9X60HH5tvDnSsMAA/view?usp=sharing).
- **Purpose/Benefit**: This feature ensures users, especially agents representing multiple organizations, confirm they are logged in as the correct entity.

**Acceptance Criteria:**
1. Display the organization name for BCeID users in the top right of the dashboard, as per the wireframe.
2. Display "Government of British Columbia" for IDIR users in the same location.
3. Ensure this feature does not disrupt the dashboard layout or other functionalities.

**Development Checklist:**
- [ ] Implement the logic to fetch and display the organization name for BCeID users.
- [ ] Implement similar logic for IDIR users, ensuring "Government of British Columbia" is displayed.

**Additional Notes:**
- Consider responsive design to ensure the feature adapts well across different screen sizes.
- Review the implementation against the provided wireframe for design accuracy.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/154?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton
