### ISSUE TITLE
LCFS - Show organization balance in top banner

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#156]
**Description:** 
Show organization compliance balance in top banner in front-end for BCeID users. 

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165579190/simulate/sitemap

Note that functionality to hide the balance, as shown with the eye icon in the wireframe, is handled in a different card #129 

**Purpose and benefit to user:** Can easily see compliance standing on every page while navigating the application

**Acceptance Criteria:**

- [ ] Given I am logged in with a BCeID, when I view the top banner, it should accurately reflect my organization's total balance and reserved balance.

**Development Checklist:**
- [ ] The necessary APIs have already been implemented.

**Notes:**

**Comment by justin-lepitzki** [comment]
I believe this functionality is covered in a different card. Will need to confirm once we have the LCFS portal set up

**Comment by Grulin** [comment]
Compliance balance is showing '0' for all BCeID accounts. They should be reflecting the real-time accurate balance in the top right hand corner of the screen instead of '0':


![Image](https://github.com/bcgov/lcfs/assets/156380046/d4ac9919-e85a-4614-9700-414bf59a9d3d)

**Comment by Grulin** [comment]
1) Completed a new transfer from start to finish between LCFS Org 1 and LCFS Org 2 and the balances did not adjust to reflect the 20 compliance unit difference for either organization:


![Image](https://github.com/bcgov/lcfs/assets/156380046/447b39e7-c6ba-4aa8-a590-da8924e12077)


2) There should be a comma in compliance unit balance as shown in the wireframe: 

![Image](https://github.com/bcgov/lcfs/assets/156380046/5fc98e1b-341b-4f96-8fff-b2bd87275211)

**Comment by Grulin** [comment]
Still missing point #2 in the comment above. No comma in the compliance unit balance :(
