### ISSUE TITLE
LCFS - User can logout 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#157]
**Description:**
User can logout of the application. This is for the front-end drop-down. 

**Wireframe:** [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0s0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f84186568b1ce1f15012db90e1efe07c26c2817/Screenshot%20logout%20edit.png)

**Purpose and benefit to user:** User can securely end session when they are done using the application 

**Acceptance Criteria:**

- [ ] Given I am a IDIR user, When I am click on logout button i should be able to logout and redirect to login page.
- [ ] Given I am a BCeID user, When I am click on logout button i should be able to logout and redirect to login page.

**Development Checklist:**
- [ ] A Add Logout button on dashboard. 
- [ ] B Implement logic to logout user
- [ ] C Once User is logged out, redirect them to login page.

**Notes:**

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/157?planning-poker) with Zenhub @jig-patel @prv-proton @AlexZorkin @kevin-hashimoto @hamed-valiollahi

**Comment by AlexZorkin** [comment]
closed for redundancy
