### ISSUE TITLE
LCFS - Create Organizations page for IDIR users 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#160]
**Description:**
Create Organizations page for IDIR users. 

- Nav bar and main heading: Organizations
- Can use Material UI table, should be same as other tables (e.g., user table) for consistency
- four columns: Organization name, Balance, In reserve, Registered
- Created organizations will be populated in this table, similar to TFRS
- Default sort is alphabetical
- Material UI table should be accessible in that you can tab through the rows & it shows up in the screen reader
- Implement breadcrumb navigation on this page

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164769377

**Purpose and benefit to user:**
Will facilitate the management of organizations by government

**Acceptance Criteria:**

- [ ] Given I am a IDIR User, When I am clicking and Organizations page, then I should be able to see all the organizations details like name, balance of compliance units, compliance units that are in reserve and status of registration.
- [ ] Sorted based on Organization name in alphabetical order in ascending order.
- [ ] Newly created organization details should be updated as and when they're added.

**Development Checklist:**
- [ ] Create a view in UI to show the details of Organizations for IDIR user.
- [ ] Follow common table design after finalizing.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/160?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas  @airinggov can we get a wireframe for this one?

**Comment by airinggov** [comment]
isn't that this one?
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164769377

**Comment by justin-lepitzki** [comment]
Yes! Sorry I should have looked through the wireframes before asking for one. Thanks Al!

**Comment by justin-lepitzki** [comment]
3 points left

**Comment by Grulin** [comment]
- Four columns: Organization name, Balance, In reserve, Registered. Formatting does not cover the entire box. user can expand the columns to fit the table, but it does not stay this way.
- Default sort is alphabetical, but sorting "status" function and download buttons scramble the numbers in "compliance units' and 'in reserve' columns every time you use them. 
- 'Organization name' column does not change when filter is applied for a status, but numbers in other columns do change. 
- Implement breadcrumb navigation on this page



![Image](https://github.com/bcgov/lcfs/assets/156380046/0231d7a2-ad94-4633-842a-6696c003b768)



![Image](https://github.com/bcgov/lcfs/assets/156380046/f2904737-5c1c-4817-9d42-82d04c3344bf)

**Comment by AlexZorkin** [comment]
![Image](https://github.com/bcgov/lcfs/assets/47334977/37825346-edcf-4519-adf7-9c07b603b295)

**Comment by kevin-hashimoto** [comment]
@AlexZorkin fixed in #222
