### ISSUE TITLE
LCFS - IDIR users can create new Organizations

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#161]
**Description:**
IDIR users can create new organizations. 

- Add Create organization button on the IDIR Organizations page
- Button is only visible to IDIR users with the Administrator role
- Develop the 'create organization' page, see wireframe
- make certain fields required
- Save and back buttons
- Clicking on the Save button adds the record to the database and the entry appears in the react table on the Organizations page; it also takes the user back to the Organizations page and the user can see the organization in the Organizations react table
- Back button takes the user back to the Organizations page
- Includes "same as..." check boxes that allow the user to indicate that their legal and operating names are the same, and that their address for service and record keeping address are the same. 
- Telephone number is free form text to allow for users to input extensions

**Organization information: required fields**
- Legal name of organization
- Operating name of organization
- Telephone number
- Address for service (postal address)
- Email address
- Address in B.C. at which records are maintained
- Supplier type

**Organization information: optional fields**
- Company profile, EDRMS record #

**Wireframe:** 
- New organization button: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164769377
- Create org page: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164728479/simulate/no-panels

**Purpose and benefit to user:**
Allows IDIR user to create new organizations

**Acceptance Criteria:**

- [ ] Given I am a IDIR user, When I am clicking Organization details, then  should be able to create an organization.

**Development Checklist:**
- [ ] Test coverage both on UI and backend.

**Notes:**

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/161?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Make sure organizations are created and persisted to the database.

**Comment by Grulin** [comment]
Still showing a "error occurred" message when all fields are filled out and 'Save' is pressed:


![Image](https://github.com/bcgov/lcfs/assets/156380046/318620d4-a9dd-454e-a2f9-0153255527c1)

**Comment by hamed-valiollahi** [comment]
@Grulin Thanks Lindsy, for testing and reporting the issue. I investigated the issue, It looks like you don't have the right permissions. You need both Government and Administrator roles on your IDIR account, but right now, you only have the Transfer role.

Please reach out to Alex regarding this matter and let either him or me know which roles you would like to add to your account.

If you encounter a similar issue with other routes, you can inspect the API response from the 'Network' tab of DevTools. While the creation of an organization should not be visible for your account, it may happen again for other routes.

![Image](https://github.com/bcgov/lcfs/assets/2143103/00a11730-cb79-44bb-873a-0f0e7fddbc1f)

Please let me know if you have any questions!

**Comment by Grulin** [comment]
Thank you @hamed-valiollahi and @AlexZorkin. I need to have the government analyst and the administrator roles please:
![image](https://github.com/bcgov/lcfs/assets/156380046/87a25270-88d3-4639-aef0-45bd379b6c60)

The "transfer" ability should only be available to BCeID users. Thank you.
