### ISSUE TITLE
LCFS - Organization information is visible on an Organization Details page 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#162]
**Description:**
Add organization information to Organization Details page 

Display the following elements for both BCeID and IDIR users:
- Legal name of organization
- Operating name of organization (if different than legal name)
- Telephone number of organization
- Address for service, including postal address in B.C. and email address 
- Address in B.C. at which records are maintained (if different than address for service)

Display the following elements for BCeID users only: 
- A disclaimer below the address fields that says, "Email lcfs@gov.bc.ca to update address information."

**Wireframe:** 

- https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164329808
- **NOTE:** This card does not include the Users functionality that is displayed in the above wireframe, including the New user button, show inactive users, and the user table. These features will be handled in separate cards.

**Purpose and benefit to user:**
Provides information about the organization. This information will then be displayed within a compliance report (future work) as this info is required by the legislation

**Acceptance Criteria:**

- [x] Given I am a BCeID user, When I enter Organization Details page, then I can view the organization information and a disclaimer below the address fields that instructs on how to update address information.
- [x] Given I am a IDIR user, When I enter Organization Details page, then I want to see organization information without the disclaimer regarding address updates.

**Development Checklist:**
- [ ] Design and create a React component to encapsulate the organization information section.
- [ ] Implement feature flag to show or hide the disclaimer based on the user's type (BCeID or IDIR).
- [ ] Integrate the organization information component into the Organization Details page.

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/162?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton
