### ISSUE TITLE
TFRS - Rebase Release-2.11.0 into Main-Release-Jan-2024

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#164]
**Description:**
Rebase the "release-2.11.0" branch into "main-release-jan-2024" to ensure the incorporation of recent changes and improvements from the previous release into the upcoming "main-release-jan-2024."

**Tasks:**

Rebase "release-2.11.0" into "main-release-jan-2024."
Resolve merge conflicts if any arise during the rebase.
Test and validate the rebased code.
Update documentation and release notes to reflect the changes.
Coordinate with the QA team for additional testing.
Adjust deployment plans as needed.

**Acceptance Criteria:**

Successful rebase of "release-2.11.0" into "main-release-jan-2024" with resolved merge conflicts.
Validated and stable code.
Updated documentation.
QA validation completed.
Deployment plans adjusted.

Completion of these tasks ensures that the improvements and fixes from "release-2.11.0" are integrated into "main-release-jan-2024" for the upcoming release.

**Comment by justin-lepitzki** [comment]
Nothing for me to test
