### ISSUE TITLE
LCFS - Users table for BCeID users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#166]
**Describe the task**

Create Users table on Organization page

- five columns: Name, Role(s), Email, Phone, Status
- Users associated with this organization will be populated in this table, similar to TFRS
- Can use Material UI table, should be same as other tables (e.g., user table) for consistency
- five columns: Name, Role(s), Email, Phone, Status
- Default sort is alphabetical
- Material UI table should be accessible in that you can tab through the rows and view on a screen reader
- Implement breadcrumb navigation on this page

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164774350/simulate/no-panels

**Purpose**
Main table for users and user management for BCeID users

**Acceptance Criteria**
- [ ] As a BCeID user, while on the organization page, display a users table that consists of columns: Name, Role(s), Email, Phone, Status 
- [ ] Table should pull and display users from the organization
- [ ] table is screen reader accessible
- [ ] filtering of columns works. default is alphabetical ascending
- [ ] clicking on breadcrumbs leads to its respective pages

**Additional context**
- reference #168 ( similar table ui )
- choose consistent mui table ( team discussion )

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/166?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Requires BCeID access to LCFS Portal to test

**Comment by Grulin** [comment]
![Image](https://github.com/bcgov/lcfs/assets/156380046/55e4aac9-39f8-4adc-9ff3-44a7814a153a)

**Comment by Grulin** [comment]
Fixed by #176

**Comment by Grulin** [comment]
Not showing BCeID user table with BCeID access. I checked on the IDIR side and made this user, Jane Doe, has a managing user status for the LCFS1 test account and also added a second user to this account from the IDIR side. Only an error "request failed with status code 403. Please contact your administrator" is showing in place of the table. 

- Also unable to add a new user from this page, despite being a BCeID managing user. 

- Please also remove "Please contact your administrator" from error message."

Please see screenshot for error message:


![Image](https://github.com/bcgov/lcfs/assets/156380046/0b139d32-d3c7-453c-9a73-229d75cf7701)

**Comment by prv-proton** [comment]
Added fixes for the issues found above.
