### ISSUE TITLE
LCFS - Users table for IDIR users 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#168]
**Describe the task**

Users table for IDIR users: 

- Create Administration page and link in the main nav bar
- Create users subpage on the Administration page
- Can use Material UI table, should be same as other tables (e.g., user table) for consistency
- five columns: Name, Role(s), Email, Phone, Status
- IDIR users will be populated in this table, similar to TFRS
- Default sort is alphabetical
- Material UI table should be accessible in that you can tab through the rows and view on a screen reader
- Implement breadcrumb navigation on this page

**Wireframe:** [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1126b2835fd8caf76989f449a740bf4a5dd50d9b/Screenshot%202023-10-31%20IDIR%20users%20page.png)

**Purpose**
Main table for users and user management within Government

**Acceptance Criteria**
- [ ] admin page ui is built
- [ ] Main nav includes 'administration' and leads to admin page
- [ ] 'Users' tab on admin page displays a table consisting of users
- [ ] table is screen reader accessible
- [ ] filtering of columns works. default is alphabetical
- [ ] clicking on breadcrumbs leads to its respective pages

**Additional context**
- choose consistent mui table ( team discussion )

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/168?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton
