### ISSUE TITLE
LCFS - Style bottom nav bar for government websites to LCFS site

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#170]
**Describe the task**
- Add the bottom government nav bar to the LCFS website
- Bar persists on every page
- Visible to both IDIR & BCeID users

**Links:** 

Home: URL of LCFS dev, test, prod 
About this site: https://gov.bc.ca/lowcarbonfuels
Disclaimer: http://gov.bc.ca/disclaimer/
Privacy: http://gov.bc.ca/privacy/
Accessibility: http://gov.bc.ca/webaccessibility/
Copyright: http://gov.bc.ca/copyright
Contact Us: Page to be created in another card

Screenshot: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3lSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f431808f427d4fb75a7b0b38b91b395f42d232d3/Screenshot%202023-11-01%20Bottom%20nav%20bar.png)

**Purpose**
Align with government standards, look & feel for government websites

**Acceptance Criteria**
- [ ] create ui component for bottom navigation
- [ ] Ui component follows government standards
- [ ] Add links to ui component
- [ ] Ensure all links are working properly

**Additional context**
- Use material ui (MUI) component library as template

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/170?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton
