### ISSUE TITLE
LCFS - Create Contact Us page 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#171]
**Describe the task**
1) Create a Contact Us page that can be accessed by clicking on the 'Contact Us' link in the bottom nav bar (see Word doc for content and exact styling)
2) Create a "Trouble logging in?" hyperlink on the bottom on the LCFS login page, which links to the new Contact Us page created in step 1 (see mock-up)

- Implement breadcrumb navigation on this page

Note: Creating the bottom nav bar is handled in a different card (# 170). 

**Wireframe:** 

HERE IS THE WORD DOC OF CONTENT: [LCFS - Create Contact Us page  (Issue #171).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWU1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eed2b42320260d64c38fbda49edef77c6b5b9975/LCFS%20-%20Create%20Contact%20Us%20page%20%20%28Issue%20%23171%29.docx)

HERE IS THE MOCK-UP OF THE LCFS LOGIN PAGE WITH THE NEW HYPERLINK
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemE1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86316fad8cf5da2d730e1212c28d510c64feb78f/LCFS%20login%20page%20-%20trouble%20logging%20in.png)

**Links:**
1) See Word doc for all the hyperlinks within the Contact Us page
2) The "Trouble logging in?" link on the login page will link to the new Contact Us page

**Purpose**
Creates an easily accessible page for users to know how to get help from different resources

**Acceptance Criteria**
- [x] Create a new hyper link on login page 
- [x] Create contact us page component and when use click on trouble login in link it should it take it to contact us page.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas, @airinggov 

Not sure if we want to spruce up our contact us page. I used a screenshot from TFRS for the "wireframe" but we could design something a bit more visually appealing. What do you think?

**Comment by Kailee-Douglas** [comment]
I didn't realize we can utilize our own page for the Contact Us link in the BC Gov standard footer. That would be great. And yes, I'd like to "freshen up" our LCFS contact page. Off the top of my head, from the original page, I would like:

- consistent formatting with emails/phone numbers
- consistency with hyperlink placement
- clarity on who does what and when to contact each organization for help or feedback, particularly if this Contact Us page is the same for both IDIR and BCeID users

Wireframe to come.

**Comment by Kailee-Douglas** [comment]
Hi, I drafted updates to the Contact Us page that I would like to review with you before posting here. Main point of clarification is the user journey. If the Contact Us page is accessible through the footer (after the user has entered the LCFS app since there's no footer on our homepage) then adding contact info for IDIR and BCeID account questions is basically moot. If the user had issues with their IDIR and BCeID then they wouldn't get into the app to be able to see those organization's contact info for help.

**Comment by Kailee-Douglas** [comment]
[LCFS - Create Contact Us page  (Issue #171).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVM1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba2fa5af11102fb1f9211a02db004f003f717b85/LCFS%20-%20Create%20Contact%20Us%20page%20%20%28Issue%20%23171%29.docx)

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/171?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton
