### ISSUE TITLE
LCFS - Clean up ERD and send PDF to Sashi for review

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#172]
**Describe the task**
Following our Postgres database discussion, we have created an ERD for the LCFS database. This task is to create a copy of the current version of the ERD file and clean it up by removing deleted tables and fields, finish changing labels, etc. Once revised, we will want to save a copy (PDF?) to send to our data architect Sashi Das for review & comment. 

As a first step, the PO will review the ERD for label changes and will then inform the team when this ticket is ready to be executed. 

- Need to add prefex (e.g., org changed to org_id)

**Purpose**
Work required to finish ERD to ultimately receive feedback from our data architect on LCFS database design.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/172?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @hvalioll

**Comment by justin-lepitzki** [comment]
I have finished reviewing the ERD and adjusting some of the labels & statuses. It is ready to be cleaned up and made into a PDF for Sashi's review. The file can be found in MS Teams Files: Team LCFS channel > General > LCFS Database; filename is "LCFS_ERD_Justin-Edits.drawio".
