### ISSUE TITLE
LCFS - Create new IDIR users 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#175]
**Description:**

Create new IDIR users:

- New user button on the Users sub-tab within the Administration page (see dependencies below for the cards to create these pages)
- Button only visible to IDIR users with the Administrator role
- Clicking on the button takes the user to the 'New User' page (see wireframe)
- Certain fields are required while other fields are optional; see wireframe for which fields are required vs. optional
- Telephone number is free form text to allow for users to input extensions
- User can be assigned role(s), they are stackable
- Clicking on the Save button adds the user to the database and they are then visible in the associated User react table in the UI; it also takes them back to the Users sub-page
- Clicking on the Back button takes the user back to the Users sub-page; no records are saved in the database
- Implement breadcrumb navigation on this page

Note: The status radio buttons and access control for logging in (active / inactive) will be handled in a different card

**Wireframe:**
- New user button: https://github-production-user-asset-6210df.s3.amazonaws.com/132306457/280809091-4b14936b-a85d-4d43-a7f1-52b583facedf.png
- New user page: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164316070/simulate/no-panels

**Purpose and benefit to user:**
IDIR users can add new users to government to help complete required tasks

**Acceptance Criteria:**

- [x] Given I am an IDIR user with an Administrator role, when I navigate to the Users sub-tab within the Administration page, then I should see a 'New User' button.
- [x] Given I click on the 'New User' button, when I am taken to the 'New User' page, then I should be able to fill out required and optional fields as indicated on the wireframe.
- [ ] Given I have entered all the necessary information on the 'New User' page, when I click the 'Save' button, then the new user should be added to the database, shown in the User react table, and I should be redirected back to the Users sub-page.
- [ ] Given I am on the 'New User' page, when I click the 'Back' button, then I should return to the Users sub-page without any new records being saved in the database.
- [ ] Given I am on the 'New User' page, when I interact with the page, then the breadcrumb navigation should reflect the path taken to arrive at this page.

**Development Checklist:**
- [ ] Create a New user button on the User sub-tab in Administration page.
- [ ] Button should only be visible to Idir use with admin role.
- [ ] Certain fields are option and some are required. Please check wireframe . 
- [ ]  User would have role and can be assigned. Role is not part of this ticket but this ticket is depended on role creation ticket.
- [ ]  Click on save button create user entry in database and it should be visible to User table list on UI and also takes them back to user page. Back button should take you back to User table page.
- [ ]  Implement breadcrumb navigation on this page

**Notes:**

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov could we get a wireframe for the New User button on the IDIR side (Administration > Users sub-tab)? Here is a screenshot of the design from TFRS:  [New User IDIR](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f01244d1e8f78b22db57f0453a743a46371544ac/Screenshot%202023-11-03%20New-User-IDIR.png). You'll notice it has a little drop-down next to it, which allows the user to add a new fuel supplier user from this page. I'd like to remove this drop-down and functionality as our gov't users say they don't add fuel supplier users this way (instead they go to the Org details page after first creating a new organization.

**Comment by Kailee-Douglas** [comment]
Here is a mock-up based on the current UI and component. Going forward, I assume we will start creating design components from the MUI library?

<img width="571" alt="Updated New IDIR User button" src="https://github.com/bcgov/lcfs/assets/132306457/4b14936b-a85d-4d43-a7f1-52b583facedf">

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/175?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/175?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
2 points left

**Comment by Grulin** [comment]
Unable to add 'New User' to organization account because field "Last Name" doesn't allow for any text to be saved. Continues to show error. 



![Image](https://github.com/bcgov/lcfs/assets/156380046/9f6b4098-42ce-4b40-b24c-6f84b629ef1a)

**Comment by Grulin** [comment]
- "Last Name" validation is persisting.
- Unable to add 'New User' to organization account because clicking on the 'Save' button does not add the user to the database and they are not then visible in the associated User react table in the UI.
- Certain fields are required while other fields are optional; see wireframe for which fields are required vs. optional
- Implement breadcrumb navigation on this page not complete.
- Title 'Add/Edit User ' should instead read "Add/Edit IDIR User"



![Image](https://github.com/bcgov/lcfs/assets/156380046/608f1762-9cc0-4b76-b1bb-1e91bc69fb04)

**Comment by AlexZorkin** [comment]
- Update frontend validation to work with Yup schema validation.

**Comment by Grulin** [comment]
I can fill out all required information (tested using a real IDIR user name and email) and received a blank error when I hit 'save'. I deleted the IDIR information for screenshot privacy after I received the error. Please see screenshot below:

![Image](https://github.com/bcgov/lcfs/assets/156380046/8d5f173a-2f97-430d-98e8-7f0d9d6d1f38)

**Comment by Grulin** [comment]
@justin-lepitzki I tested this issue and the only thing missing is the breadcrumb navigation. Does that matter for adding an IDIR user? I don't see it as necessary for this add IDIR user page. Please let me know what you think.

**Comment by justin-lepitzki** [comment]
@Grulin I think we should add the breadcrumbs for these pages, for consistency and ease of navigation / orientation within the app. I believe our decision to add breadcrumbs to pages was made after this work was already completed (at least the first version of implementation). I recommend that we create a new card for adding the page navigation breadcrumbs to these three (?) areas, rather than move these cards back. It can be a single "task" card and then we can work with Al to update the respective wireframes.
