### ISSUE TITLE
LCFS - View User page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#176]
**Description:**
Develop a View User page accessible to both BCeID and IDIR users. This page will be visible upon clicking on a user row in the respective User tables and will display detailed information about the user. The page should also include breadcrumb navigation for enhanced user experience.

Screenshot of View user page in TFRS: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--632245afd6fbe20dac8d915cc40ec03642dbb329/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-users-view-33-2023-11-03-13_45_47.png)

**Wireframe of View User Page for LCFS:**
- https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164810157

**Purpose and benefit to user:**
The View User page serves as a landing page for detailed information about individual users. This will pave the way for future enhancements such as adding a User Activity table to provide a transparent record of user actions within the application.

**Acceptance Criteria:**
- [x] Given I am an authorized user, When I click on a user row in the User table, then I should be redirected to the View User page displaying that user's information.
- [ ] Given I am on the View User page, When I navigate through the page, then I should see breadcrumb navigation aiding in my understanding of the page hierarchy and navigation.

**Development Checklist:**
- [x] Design and implement the View User page for both BCeID and IDIR users.
- [x] Ensure the page displays all relevant user information clearly and accurately.
- [x] Implement breadcrumb navigation on the View User page.
- [x] Ensure compatibility and consistency with the existing UI/UX design of the application.
- [ ] Write unit tests for the view loading and displaying relevant information.

Notes:
- Security and privacy considerations are paramount; ensure that user information is displayed in compliance with data protection regulations.
- The design team needs to finalize the breadcrumb navigation terms and update the wireframes accordingly.
- Close coordination with the UX/UI team is necessary for seamless integration with the existing application design.

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov Wireframe for view user page redesign

**Comment by Kailee-Douglas** [comment]
This should be done with the MUI components? I added the MUI library to UXPin and can see how it deviates from the BC Gov Design System on the DevHub

**Comment by airinggov** [comment]
Do we need an intermediary page between the user list on the org page and the edit user page? Can we not go from the list directly to the edit user page? For users without admin access they would only see the info on the user list / org page.

**Comment by justin-lepitzki** [comment]
@airinggov possibly? We would have to figure out where to put other information that would be lost if you didn't have a "view user" page, such as their job title, mobile phone, and user activity. The first two could potentially be added to the user list on the org page (two additional columns) but the user activity column is a larger component that I'm not sure where we could relocate. Thoughts?

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov I think we've settled on keeping this page so can we create a wireframe for displaying the user information. Do we to change the style a bit here? Doesn't have to be drastic but we do have an opportunity to tweak the layout if desired.

**Comment by Kailee-Douglas** [comment]
@justin-lepitzki your thoughts on this mock
![Current mockup for View User page (Issue #176)](https://github.com/bcgov/lcfs/assets/132306457/03f50165-a63e-4476-b4f0-2b7d765b0737)
up?

**Comment by justin-lepitzki** [comment]
Looks good @Kailee-Douglas ! Can we make one tweak: change the label 'Role:' to 'Role(s):'

I noticed that when a user has more than one role it still says the singular Role:

**Comment by Kailee-Douglas** [comment]
Here you are, @justin-lepitzki 

![More current mockup for View User page (Issue #176)](https://github.com/bcgov/lcfs/assets/132306457/647b26f1-f25c-4ba4-8d6a-899d6a663ba6)

I can add the UX Pin link after Al looks at it, too. Functionality to highlight for the dev work: columns autoadjusted to fit width of content (within reason), and rows autosorted by newest first. I did not add a filter option, which is present in other tables, and may or may not be valuable here. Also, does it need a download function?

We discussed breadcrumbs earlier. Depending on our decision around that, we can quickly add a breadcrumb on the top.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/176?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/176?planning-poker) with Zenhub @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Unable to fully test view of detailed information about the user until card #174 has been resolved

**Comment by Grulin** [comment]
BCeID view of organization tab shows organization details, but does not show any user table.  Shows error "Request failed with status code 403. Please contact your administrator".  Please also remove "please contact your administrator" from error prompt:


![Image](https://github.com/bcgov/lcfs/assets/156380046/5e3e6742-8911-4d3d-bf5e-26be78ee0cb6)
