### ISSUE TITLE
LCFS - Edit existing users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#178]
**Description:**

The ability to edit existing user's information: 
- Pencil icon next to the user's name on the View User page (see wireframe)
- Clicking on the pencil icon takes you to the edit user page (see wireframe)
- User information is already pre-populated from the database
- User information is editable
- Clicking on the Save button updates the user's information in the database and takes them back to the View users page
- Implement breadcrumb navigation on this page

**Wireframe:**
- Pencil icon on the View Users page: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164810157 
- Edit user page (IDIR): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164316070/simulate/no-panels
- Edit user page (BCeID): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164314016/simulate/no-panels

**Purpose and benefit to user:**
Enables user information to be adjusted as it changes over time

**Acceptance Criteria:**

- [ ] Given I am a <role>, When I am <doing something>, then <this happens>
- [ ] Given I am a <role>, When I am <doing something>, then <this happens>

**Development Checklist:**
- [ ] A Create pencil icon next to user's name on the User view page
- [ ] B click on pencil icon takes you to edit user page and make sure user information is already populated from DB
- [ ] C clicking on save button should update record in database and takes them back to users page and should show updated record on user view page.

**Notes:**

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov this was only needs a wireframe to add a pencil icon on the view users page. Think the wireframe for card #176 needs to be done first

**Comment by Kailee-Douglas** [comment]
Can we consider adding a button like the one currently in TRFS? It would be more noticeable to users and more helpful with text in the button.

<img width="69" alt="Edit button" src="https://github.com/bcgov/lcfs/assets/132306457/d7b4d8e3-6af9-4e1a-933e-9306ebf35070">

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/178?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Unable to test until #174 is resolved.
