### ISSUE TITLE
LCFS - Implement Keycloak Automatic Session Renewal in LCFS Frontend

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#182]
**Describe the task**
Implement automatic session renewal using Keycloak in our frontend ReactJS application LCFS.

**Purpose**
The current session duration provided by our provider is 5 minutes, which is quite short. This task aims to ensure seamless user experience by renewing sessions automatically, thus avoiding frequent re-authentication prompts. By tracking the session length and renewing it once it expires, we can provide an uninterrupted experience to the user.

**Acceptance Criteria**
- [ ] Modify the Keycloak configuration to enable session monitoring.
- [ ] Implement a mechanism to track the session expiry time.
- [ ] Once the session expires, automatically renew the session without user interaction.
- [ ] Ensure that the user's current state in the application is preserved post-renewal.
- [ ] Perform thorough testing to verify that session renewal happens smoothly.
- [ ] Add Documentation into the main app readme explaining how session renewal works in LCFS

**Additional context**
- The session renewal mechanism must be robust enough to handle scenarios where the user may have multiple tabs or windows of the application open.
- Consideration must be given to error handling to manage any failures in session renewal gracefully.

**Code Examples**

Here is an example of how the session renewal feature could be integrated into our existing Keycloak setup:

```javascript
import React, { useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactKeycloakProvider } from '@react-keycloak/web';
import { QueryClient, QueryClientProvider } from 'react-query';
import { getKeycloak, keycloakInitOptions } from './keycloak';
import App from './App';
import Loading from './components/Loading';

import './styles/index.scss';
import 'bootstrap/dist/css/bootstrap.css';

const queryClient = new QueryClient();
const keycloak = getKeycloak();
const root = document.getElementById('root');

// Function to renew session
const renewSession = (minValidity) => {
  keycloak.updateToken(minValidity)
    .then((refreshed) => {
      if (refreshed) {
        console.log('Token was successfully refreshed');
      } else {
        console.warn('Token is still valid');
      }
    })
    .catch(() => {
      console.error('Failed to refresh the token, or the session has expired');
    });
};

// Function to setup session renewal checks
const setupSessionRenewal = () => {
  const sessionStatus = keycloak.tokenParsed?.session_state;
  const expiresIn = keycloak.tokenParsed?.exp - Math.ceil(new Date().getTime() / 1000);

  if (sessionStatus && expiresIn) {
    console.log(`Session expires in ${expiresIn} seconds. Setting up auto-renewal.`);
    setInterval(() => renewSession(5), expiresIn * 1000); // 5 seconds before expiry
  } else {
    console.error('Cannot determine session state or expiry from the token.');
  }
};

if (root) {
  createRoot(root).render(
    <ReactKeycloakProvider
      authClient={keycloak}
      initOptions={keycloakInitOptions}
      onTokens={setupSessionRenewal} // Setup renewal on token initialization
      LoadingComponent={<Loading />}
    >
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </ReactKeycloakProvider>
  );
}

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/182?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
This is automated in the latest release of our application. Archiving ticket.
