### ISSUE TITLE
LCFS - Implement E2E Tests for User Login and Data Retrieval with Cypress

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#184]
**Describe the task**
Implement end-to-end tests using the Cypress testing framework to validate the user login flow and database record retrieval. These tests should simulate a real user logging in through the UI, checking the functionality of our authentication middleware, and confirming that the user can successfully retrieve their records from the database.

**Purpose**
This task ensures the reliability and security of our user login and data retrieval processes. End-to-end tests will help catch potential regressions or issues early in the development cycle, improving the overall quality of our application and user experience.

**Acceptance Criteria**
- [ ] Set up Cypress with the necessary configurations for our project.
- [ ] Create a test that navigates to the login page, performs a successful login with test credentials, and verifies redirection to the user dashboard.
- [ ] Validate that the user's database record is correctly retrieved and displayed on the dashboard after login.
- [ ] Implement negative test cases to verify that incorrect credentials are handled properly and display an appropriate error message.
- [ ] Ensure all tests are properly cleaned up after execution to maintain data integrity and state.
- [ ] Integrate the new Cypress tests into our existing CI/CD pipeline.
- [ ] Update project documentation to include these new tests and instructions for running them.

**Additional context**
- The tests should mock or use test user data to prevent interaction with real user accounts.
- The `/current-user` endpoint and the existing authentication middleware are crucial components of these tests and should be thoroughly vetted.
- Cypress best practices should be followed to maintain test quality and efficiency.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/184?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
