### ISSUE TITLE
LCFS - Download User Information

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#187]
**Description:**
- Enable the ability to download BCeID user information from the Organizations page into a spreadsheet
- IDIR users only 
- User information to download includes: Last name, First name, Email, BCeID User ID, Title, Phone, Mobile, Status, Role(s), Organization name
- File type = .xls
- Workbook name format: BC-LCFS-bceid-YYYY-MM-DD.xls, where YYYY-MM-DD is the day the file was downloaded
- Worksheet name: BCeID Users
- Spreadsheet columns should be formatted to give adequate spacing for the information displayed
- Add excel icon within the button (see screenshot below); note that this is not shown in the wireframe below but we would like to display the excel icon. 
- The button label switches to "Downloading..." after the user clicks on the button and the sheet is being downloaded (loading). The button then switches back to the regular label after it has downloaded. 

**Note:** This feature is near identical to the one that exists in TFRS

**Wireframe:** 
- UXPin: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164769377/simulate/no-panels
- Screenshot of spreadsheet: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9BQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0578d2d48ca3cabc08bcd7dde94c5963ca1a5678/Screenshot%202023-11-09%20bceid%20users%20download%20as%20xls.png)

- Excel icon within the download button (from TFRS): [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3262732bd9c2692d8107a83b2c11904867287ff/Screenshot%202023-11-09%20Download%20buttons%20in%20TFRS.png)
- "Downloading..." button example from TFRS: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25BQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad6083ea4ff801dd9d36a0856db8243ae0e876f8/Screenshot%202023-11-09%20Downloading....png)

**Purpose and benefit to user:**
IDIR users can easily and efficiently download a list of BCeID users and their respective contact information. 

**Acceptance Criteria:**

- [ ] Given the IDIR users are logged in, they should be able to see the button to download User Information.
- [ ] Downloaded file should be in "xls" format maintaining the same column information as the TFRS.
- [ ] When the file is taking longer time to download ensure the spinning button is shown until the download is complete.

**Development Checklist:**
- [ ] Refer to #186 and implement similar logic for User Information.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/187?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Test comment

**Comment by prv-proton** [comment]
![grid_container](https://github.com/bcgov/lcfs/assets/130073308/98fe3af9-b9de-4a4f-9c45-3267d8342e3d)

**Comment by AlexZorkin** [comment]
Throwing an error: "Failed to download user information". Click on button and receive error message.

**Comment by AlexZorkin** [comment]
![Image](https://github.com/bcgov/lcfs/assets/47334977/59bedd1d-6bb9-47f9-9da7-20d01761dc8e)
