### ISSUE TITLE
LCFS - Transactions page & table

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#190]
**Ticket Completion: LCFS - Transactions Page & Table #190**

**Description:**

Develop a new Transactions page featuring a detailed transactions table. This page should be accessible to both IDIR and BCeID users. Notably, BCeID users will only have visibility over transactions associated with their respective organization. The table should include the following columns, arranged from left to right: ID, Compliance Period, Type, Units From, Units To, Number of Units, Value per Unit, Status, and Last Updated On. The default sorting of the table should be by the latest ID in descending order. Ensure that the column widths are adequately formatted to display transaction information clearly. Implement selectable and searchable drop-downs for columns associated with a look-up table. The table should be server-side to optimize performance. Additionally, disable search/filtering options for the 'Units From' and 'Units To' columns. A reference screenshot of a react table from TFRS can be found in a private Zenhub image.

**Screenshot of react table from TFRS:** [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d6f238a8f4659ad9765491488b80276f8b96dc5/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-2023-11-09-16_17_24.png)

**Purpose and Benefit to User:**

This feature enables users to efficiently view and manage transactions related to their organization, enhancing the user experience by providing a comprehensive and easy-to-navigate interface.

**Acceptance Criteria:**

1. **Given** I am a BCeID user, **When** I access the Transactions page, **Then** I should only be able to view transactions related to my organization.
2. **Given** I am an IDIR user, **When** I access the Transactions page, **Then** I should be able to view all transactions.

**Development Checklist:**

- Implement the Transactions table using ag-grid for a dynamic and responsive design.
- Utilize BCDataGridServer or equivalent for server-side pagination and data handling to ensure efficient performance and scalability.
- Ensure that the table is responsive and accessible, with a focus on readability and ease of use.
- Conduct thorough testing across various devices and browsers to ensure compatibility and functionality.

**Notes:**

- Prioritize user experience by ensuring the interface is intuitive and user-friendly.
- Implement appropriate security measures to ensure that users can only access data relevant to their organization.
- Coordinate with the design team to ensure consistency with the overall application aesthetic and usability standards.

**Comment by justin-lepitzki** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/190?planning-poker) with Zenhub @hamed-valiollahi

**Comment by Grulin** [comment]
Currently the default sorting of the table is by the latest ID in ascending order (newest transaction goes to the end of the table).
The default sorting of the table should be by the latest ID in descending order.
