### ISSUE TITLE
LCFS - IDIR users can filter transactions by organization

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#192]
**Description:**

- IDIR users can easily filter transactions by an organization on the transactions page
- When filtering by an organization, the user can see the organization's compliance balance 
- Filtering is maintained when navigating away from the page and then returning (within a single session)
- Searchable & selectable field
- Filtering should be done in such a way that the user doesn't have to know the exact spelling of the organization (e.g., drop down menu)

**TFRS implementation:**
This feature is implemented in TFRS, but with less functionality than the requirements listed above. For example, the menu is a straight selectable drop-down rather than a searchable & selectable field. 

- Screenshot 1: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38a32c5c432a0890103009f8c05803ff6714fc0e/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-2023-11-10-15_10_41.png)

- Screenshot 2: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11d6c31aee90e2cf08ad8a6a9d451ecda2558c1d/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-2023-11-10-09_32_10.png)

- Screenshot 3: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cebe2796ed235ecfcb3a9ebb9d3d6ffef312ab13/Screenshot%202023-11-10%20list%20view.png)

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164908210
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164923037
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164924925

**Purpose and benefit to user:**
IDIR users can quickly and easily see all transactions for a specific organization (and the organization's compliance balance)

**Acceptance Criteria:**

- [x] As an IDIR user, When I click the dropdown, I am able to scroll through a list of organizations and select an organization
- [x] As an IDIR user, When I click the dropdown, I am able to search/input an organizations name and have the list show the results. I am then able to select the organization.
- [x] When an organization is selected, the table should show any transactions where the "compliance units from" and "compliance units to" is the selected organization

**Development Checklist:**
- [ ] dropdown is clickable
- [ ] dropdown has search functionality
- [ ] style dropdown(?)
- [ ] on selection of an organization , filter data to only include the specific query

**Notes:**
- [ ] For standalone searchable dropdowns. possibly use MUI (?) (alternative: react-select).
- [ ] possibly just use AG grid table filtering functionality if it is sufficient for our uses

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov need a wireframe for this one. Current design and placement seems to work well for users in TFRS.

**Comment by kevin-hashimoto** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/192?planning-poker) with Zenhub @kevin-hashimoto @AlexZorkin @hamed-valiollahi @prv-proton @jig-patel

**Comment by Kailee-Douglas** [comment]
As discussed at backlog refinement, consider a selectable and searchable drop-down.

**Comment by justin-lepitzki** [comment]
Looks great @Kailee-Douglas ! With respect to #2, the functionality you describe exists in TFRS, where it only downloads the transactions for the filtered organization when one is selected. I would like to maintain this functionality as I have found it very useful. With respect to #3, I am fine with this and don't see an issue with the filtering components missing for those two columns. 

Should we create a second wireframe showing when an organization is selected? We have the screenshot from TFRS but it might be helpful to have the wireframe with this new design.

**Comment by Kailee-Douglas** [comment]
Hi @justin-lepitzki , how is this? https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164923037/simulate/no-panels
