### ISSUE TITLE
LCFS - Add BCeID and IDIR roles to the corresponding database table(s)

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#194]
**Describe the task**
Add BCeID and IDIR roles to the corresponding database table(s). 

**IDIR (Government) Roles:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164316070/simulate/no-panels

Administrator — can add/edit IDIR users and assign roles and add/edit organizations, BCeID users and assign roles
Analyst — can make recommendations on transfers, transactions and compliance reports, manage file submissions and add/edit fuel codes
Compliance Manager — can make recommendations on compliance reports
Director — can assess compliance reports and approve transactions

**BCeID Roles:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164314016/simulate/no-panels

Manage Users — can add/edit BCeID users and assign roles
Transfer — can create/save transfers and submit files
Compliance Reporting — can create/save compliance reports and submit files
Signing Authority — can sign and submit compliance reports to government and transfers to trade partners/government
Read Only — can view transactions, compliance reports and files

**Purpose**
Roles are fundamental to access control within the system

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/194?planning-poker) with Zenhub @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
