### ISSUE TITLE
LCFS - Show Organization Details on BCeID dashboard

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#208]
**Description:**
Show the organization details on BCeID dashboard:

- Show operating name of organization
- Show address for service
- Show organization telephone and email
- "Users" link to Organization page 
- "Create new BCeID account" links to [https://www.bceid.ca/](https://www.bceid.ca/)

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164908212/simulate/no-panels

**Purpose and benefit to user:**
User is displayed their organization information

**Acceptance Criteria:**
- [ ] Given I am a BCeID user, when I access my dashboard, then I should see the organization's details listed above as well as Users and Create new BCeID account links.
- [ ] Given I am a BCeID user, when I click on the "Users" link, then it should redirect me to the Organization page.
- [ ] Given I am a BCeID user, when I click on the "Create new BCeID account" link, then it should direct me to [https://www.bceid.ca/](https://www.bceid.ca/)

**Development Checklist:**
- [ ] Implement a UI component to display the organization's details.
- [ ] Include the component to the dashboard page.

**Notes:**

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas @airinggov the wireframe I included is based on this mockup from UX pin (https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164349076/simulate/sitemap). Can we revise the mockup of the Organization Details portion of the BCeID dashboard to include the organization telephone number and email (these are new info requirements from the new Act). See org details page for example info: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164329808/simulate/sitemap

**Comment by Kailee-Douglas** [comment]
@justin-lepitzki  here is an updated mock-up for your review: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164908212

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/208?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @jig-patel @prv-proton @AlexZorkin

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas can we add the grey / white contrast into the wireframe? The current screenshot in the card description has it over the whole page, but I think we should have it around the white box of the Organization Details widget/box. 

Example: https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0cabb69d229e140fe90a85ab728d9f1262f2444/Dashboard-BCeID-Org_Details.png

**Comment by Kailee-Douglas** [comment]
Hello @justin-lepitzki  is this what you are envisioning? https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164908212/simulate/no-panels

As we gradually add more content, we can update the size of the grey contrast in new associated mock-ups.

**Comment by justin-lepitzki** [comment]
@Kailee-Douglas looks great! I have updated the wireframe link. Thank you :)

**Comment by Grulin** [comment]
Requires access to BCeID user account to test.
