### ISSUE TITLE
LCFS - Transfer details dynamic sentence on new transfer page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#214]
**Description:**
- Develop the transfers details sentence that allows the user to input information about the transfer, including the quantity of compliance units (credits) being transferred, the organization receiving the credits (i.e., the transferee), the fair market value of any consideration, in CAD $ (i.e., price per unit). 
- All three input fields are required
- Quantity field restrictions: must be a number, must be positive (cannot be negative), must be a whole number (no decimals)
- Select an organization: drop-down menu where the user can select a transfer partner, list is curated to show organizations within the database that are registered, list does not show one's own organization. Note that the registration functionality is handled in a different [card lcfs #222](https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/lcfs/222)
- Fair market value of any consideration, in CAD (i.e., price per unit) restrictions: must be a number, must be a positive number (cannot be negative), decimals are allowed but restrict to no more than two decimal places
- The total value at the end of the sentence is dynamic: it defaults / starts at $0.00 but then updates as the user inputs the required information. The calculation is quantity of units multiplied by the price per unit.
- See wireframe for sentence structure/language and messaging within input fields

Note: similar functionality as listed above exists in TFRS transfer feature

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164975114/simulate/no-panels

**Purpose and benefit to user:**
Allows the user to enter the required information for initiating a transfer

**Acceptance Criteria:**

- [ ] Given I am a BCeID user I should have the option to enter the transfer value and to choose the organization that I want to transfer.

**Development Checklist:**
- [ ] fair market value needs to be added to the data model and name the column as price_per_unit.

**Notes:**

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/214?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Requires access to BCeID user account to test.

**Comment by Grulin** [comment]
Input fields are working, but there is a little bit of left over text in the introductory sentence "&nbsp". Please see screenshot:


![Image](https://github.com/bcgov/lcfs/assets/156380046/e7b15d07-70d8-48b3-ba4d-92a12d08bc5c)
