### ISSUE TITLE
LCFS - Agreement date feature on new transfer page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#216]
**Description:**
To implement the Agreement date feature on the new transfer page. Note that this feature is identical to the one we recently developed in TFRS; therefore, code from TFRS should be able to be reused? 
- input field where the user has to select a date
- use date picker component for date selection
- restrict date selection from picker component to not allow the selection of a future date (i.e., only able to select today or a date in the past)
- user can enter date manually if desired
- restrict formatting to yyyy-mm-dd
- have input field show yyyy-mm-dd to help the user understand the formatting required

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162954828/simulate/no-panels

**Purpose and benefit to user:**
Enables the user to indicate the date on which the written agreement (contract) for the transfer was reached, which is a legislative requirement. 

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, I should be able to select the agreement date from the date picker with similar functionality to that in TFRS.

**Development Checklist:**
- [ ] Refer TFRS implementation.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/216?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @prv-proton
