### ISSUE TITLE
LCFS - Signing Authority declaration on new transfer page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#218]
**Description:**
To develop the Signing Authority Declaration section on the new transfer page: 
- This section is only visible to users with the Signing Authority role
- Checkbox component
- Declaration statement: "I confirm that records evidencing each matter reported under section 18 of the Low Carbon Fuel (General) Regulation are available on request."

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162954828/simulate/no-panels

**Purpose and benefit to user:**
The declaration is the mechanism used for having a user "sign off" on the transfer. They essentially put their name on it and agree that the information provided in the transfer is accurate and that required record keeping practices are following. Making this section only visible to the Signing Authority role enables a separation of duties if desired by the organization; one user with the transfers role can create the transfer where a different user (with the Signing Authority role) can review and sign off on it. 

## Acceptance Criteria
- [x] Given I am a user with the Signing Authority role, when I access the new transfer page, then the Signing Authority Declaration section should be visible.
- [x] Given I am a user without the Signing Authority role, when I access the new transfer page, then the Signing Authority Declaration section should not be visible.
- [x] The checkbox and declaration statement should match the provided wireframe in appearance and functionality.

## Development Checklist
- [ ] A. Ensure the visibility of the Signing Authority Declaration section is restricted to users with the Signing Authority role.
- [ ] B. Integrate the checkbox component as per the design specifications in the wireframe.
- [ ] C. Accurately implement the declaration statement text and ensure its functionality with the checkbox.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/218?planning-poker) with Zenhub @jig-patel @prv-proton
