### ISSUE TITLE
LCFS - Save draft of new transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#219]
**Description:**
Develop the functionality to save a draft of a new transfer: 

- Save Draft button
- Requires the three Transfer Details inputs (quantity, select organization, price per unit) to not be blank / be filled out / selected
- Requires the user to enter an agreement date in the Agreement date feature, and that date to be today's date or earlier (cannot be a future date)
- Quantity cannot be more than the organization has in its current balance minus the units that are in reserve 
- Clicking the Save Draft button creates the transaction and sets the status to Draft
- Creating the transaction assigns an ID number to the transfer (i.e., a transaction ID number, similar to TFRS functionality where every transaction is given a unique ID number, sequential order).
- A success alert appears ([Material UI examples](https://mui.com/material-ui/react-alert))
- The user is returned to the transaction page where the transaction is visible at the top of the transactions table
- The transaction row for the transfer is highlighted in yellow

Validation messages: 
- Quantity, price per unit, and agreement date fields: "Please fill out this field."
- Select an Organization: "Please select a transfer partner."
- Not enough compliance units (quantity is more than the organization has in its current balance minus the units that are in reserve): "Your organization does not have enough compliance units for this transfer."

**Wireframes & screenshots:** 

- New transfer page (wireframe): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162954828/simulate/no-panels
- Example of front-end validation (TFRS screenshot): [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be7e866030ef1885c170c68b5e2d881ada49196a/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-add-2023-11-23-11_26_00.png)
- Example of Transactions table row highlight feature (TFRS screenshot): [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae596cd4959fb31aa8ded386b7d819dbadb95822/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-2023-11-23-11_41_11.png)

**Purpose and benefit to user:**
Allows the BCeID user to save a draft of the transfer to be processed later and/or by a different user 

**Acceptance Criteria:**

- [x] Given I am a BCEID user, should be able to save the transfer to database.
- [ ] Given I am a BCeID user, the data I entered should be validated before saving to the database.

**Development Checklist:**
- [ ] Validation framework discussion would be required.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/219?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
When attempting to save a draft transfer, a BCeID user with signing authority gets the following error after pressing 'Save Draft' button: "Error occurred while submitting. Please retry. For ongoing issues, contact support". 

Please see screen shots below:



![Image](https://github.com/bcgov/lcfs/assets/156380046/cf01b4e1-7a23-4947-9bbc-7e399379c430)



![Image](https://github.com/bcgov/lcfs/assets/156380046/54b1c2c0-84bd-45f2-b8ac-621d28230e31)

**Comment by Grulin** [comment]
Save draft feature is working, but there is no validation that restricts organization from selling more compliance units than they have available. 

Still requires the component that notes an organization does not have enough compliance units (quantity is more than the organization has in its current balance minus the units that are in reserve): "Your organization does not have enough compliance units for this transfer."

Please see screenshot that allowed me to selling substantially more compliance units that the organization has:


![Image](https://github.com/bcgov/lcfs/assets/156380046/b053624e-0c95-4eea-9ae1-ad38c3812bc1)

**Comment by Grulin** [comment]
Validation of organization balance will be addressed on another card #477
