### ISSUE TITLE
LCFS - Send transfer to transfer partner organization

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#220]
**Description:**
Develop the ability for an organization to send a new/draft transfer to another organization. 
- Sign and send button
- Clicking on the button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the new/draft transfer screen
- Clicking on the sign and send button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page where the transaction is visible at the top of the transactions table, (3) The transaction row for the transfer is highlighted in yellow, and (4) the transfer status is changed to Sent
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- With a sent status, the transfer should now be visible to the transfer partner organization in their transaction table. So both organizations that are party to the transfer can view the transfer. 
- The transfer breadcrumb is updated to the 'Sent' part of the process
- A transaction history record is saved to the database and visible in the UI when viewing the transfer: Signed and sent on [Month DD, YYYY] by [User] of [Organization]. This record is based on the user with the Signing Authority role that clicked the Sign and sent button. 

**Data Validation & restrictions:**
Being able to sign and send a transfer needs to have the following restrictions: 
- Requires the Signing Authority role
- Requires completion of the Signing Authority Declaration (i.e., check boxes checked)
- Requires the three Transfer Details inputs (quantity, select organization, price per unit) to not be blank / be filled out / selected
- Requires the user to enter an agreement date in the Agreement date feature, and that date to be today's date or earlier (cannot be a future date)
- Quantity cannot be more than the organization has in its current balance minus the units that are in reserve

**Validation Messaging:**
May be dependent on front-end vs. back-end validation:

- Does not have the Signing Authority role: "The Signing Authority role is required to sign and send a transfer to another organization."
- Has Signing Authority role but has not completed the Signing Authority declaration section: "Please complete the Signing Authority declaration."
- Quantity, price per unit, and agreement date fields: "Please fill out this field."
- Select an Organization: "Please select a transfer partner."
- Not enough compliance units (quantity is more than the organization has in its current balance minus the units that are in reserve): "Your organization does not have enough compliance units for this transfer."

**Confirmation Modal Window:**
Provides a summary of the transfer details/information:
- Wireframe (screenshot): [Image](https://github.com/bcgov/lcfs/assets/131904954/52547ced-c5ed-42c2-affd-8b75ba37ac07)
- Compliance units from: the organization creating the new transfer
- Compliance units to: the transfer partner who will be receiving the compliance units
- Number of units to be transferred, value per unit, total value, agreement date: information entered by the user on the new transfer page
- Adhere to formatting / styling in wireframe/screenshot

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164975114/simulate/no-panels

**Purpose and benefit to user:**
Ability to initiate a transfer and send it to another organization for review & acceptance

**Acceptance Criteria:**

- [ ] Given I am a <role>, When I am <doing something>, then <this happens>
- [ ] Given I am a <role>, When I am <doing something>, then <this happens>

**Development Checklist:**
- [x] A Create Sign and send button.
- [x] B Clicking on the button should bring up confirmation modal window. Create common modal component
- [x] C Clicking on the cancel button on Modal should bring back to transfer page.
- [x] D Clicking on sign and send on Modal should give you success alert message and should bring to transaction page where the transaction should be visible with its status. 
- [ ] E Make sure all the validation (front end/backend) works
- [x] F make sure after transaction is successful, it shows correct status on transaction page.
- [ ] G make sure the transaction history record is saved in the database 

**Notes:**

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/220?planning-poker) with Zenhub @jig-patel @prv-proton
