### ISSUE TITLE
LCFS - Transfer registration flag feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#222]
**Description:**
To develop the transfer registration flag feature that controls whether an organization can buy and sell credits. A registered organization (yes flag) can buy and sell credits whereas a unregistered organization (no flag) cannot buy/sell credits. 

- Radio button on the edit organization page (see wireframes below)
- Yes / no options; only one can be selected
- Selection is required
- yes/no flag shows up in Organizations table for IDIR users and on the Organization Details page, accessible to both BCeID and IDIR users (see wireframes below)
- Organization Details page includes explanatory sentence in addition to yes/no: (1) Yes — A registered organization is able to transfer compliance units. (2) No — An organization must be registered to transfer compliance units.
- Functionality when flag is Yes: BCeID users with the transfers role within the organization can see the New Transfer button (see [card #212](https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/lcfs/212)) on the transactions page; the organization shows up in the curated list of transfer partners when creating a new transfer (see [card #214](https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/lcfs/214))
- Functionality when flag is No: no user within the organization can see the New Transfer button on the transactions page (i.e., cannot initiate a new transfer); the organization does not show up in the curated list of transfer partners when creating a new transfer (see [card #214](https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/lcfs/214)), meaning another organization cannot send them a transfer proposal. 

**Wireframes:**
- Edit organization page (IDIR only): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164728479/simulate/no-panels
- Organizations main table (IDIR only): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164769377/simulate/no-panels
- Organization Details page (BCeID & IDIR): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164329808/simulate/no-panels
- New transfer page (BCeID only): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164975114/simulate/no-panels
- New Transfer button on transactions page (screenshot): [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG4rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1386bd882710b11972d531d70f43d4b93e04d3a6/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-2023-11-21-15_27_18.png)
- Select Organization on New Transfer page (curated list of registered orgs): [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHYrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b70889848368e67859efa57f0009c199e4649eec/Screenshot%202023-11-22%20Select%20org%20transfer.png)

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [x] Given I am an IDIR user, when I access the Edit Organization page, then I should see the option to select a 'Yes/No' radio button for the transfer registration flag.
- [x] Given I am an IDIR user, when I view the Organizations table, then the 'Yes/No' flag status of each organization should be visible.
- [x] Given I am a BCeID or IDIR user, when I access the Organization Details page, then I should see the 'Yes/No' flag along with the explanatory sentence about registration status.
- [x] Given I am a BCeID user with transfer role, when the organization's flag is 'Yes', then I should see the 'New Transfer' button and find the organization in the transfer partners list.
- [x] Given I am a BCeID user initiating a new transfer, when I access the list of transfer partners, then organizations with the transfer registration flag set to 'No' should not appear in the curated list.

**Development Checklist:**
- [x] Implement radio button on the Edit Organization page. Ensure selecting either 'Yes' or 'No' is required.

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/222?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
As an unregistered BCeID user organization, my organization does not show up as an option to send transfers to, but I can still sign and send a transfer as an unregistered organization and the transfer is still visible and actionable by the purchasing organization. 

An unregistered BCeID user organization should not be able to initiate, save or sign and send a new transfer.
