### ISSUE TITLE
LCFS - Implement Role-Based Access Control on FastAPI Endpoints using Custom Decorator

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#226]
**Describe the task**
Implement role-based access control on FastAPI endpoints using a custom `role_required` decorator to validate user roles. This involves creating a decorator that checks a user's role against the required roles for an endpoint and applying this decorator to the relevant endpoints in our User management controller.

**Purpose**
To enhance the security and integrity of our system by ensuring that only users with appropriate roles can access specific functionalities, ensuring compliance with access control policies.

**Acceptance Criteria**
- [ ] Develop the `role_required` decorator function to verify a user's role.
- [ ] Apply the `role_required` decorator to existing endpoints in the User management controller, specifying required roles.
- [ ] Test endpoints to ensure correct access control based on user roles.
- [ ] Ensure proper error responses are returned when access is denied.
- [ ] Update unit tests for new role-based access control functionality.
- [ ] Document the implementation and usage of `role_required` in the codebase.

**Additional context**
- Utilize the existing middleware that injects the user into the request for role validation in the `role_required` decorator.
- Include the decorator in the codebase for use across different endpoints.

**Decorator Example**

```python
from functools import wraps
from fastapi import HTTPException, Request

def role_required(*roles):
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            request = None
            for arg in args:
                if isinstance(arg, Request):
                    request = arg
                    break
            
            if request is None:
                raise HTTPException(status_code=400, detail="Request object not found")

            user = request.user  # Assuming user is injected into request by middleware
            if user.role not in roles:
                raise HTTPException(status_code=403, detail="Insufficient permissions")

            return await func(*args, **kwargs)
        return wrapper
    return decorator
```

**Usage Example**

```python
@router.get("/current", response_model=UserBase, status_code=status.HTTP_200_OK)
@role_required("Admin", "User")  # Example roles
async def get_current_user(request: Request, response: Response = None) -> UserBase:
    # Endpoint logic here
```

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/226?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
