### ISSUE TITLE
LCFS - View transfer screen

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#227]
**Description:**
This ticket involves the development of the 'View Transfer' screen for the LCFS system. Once a draft transfer has been sent to the second organization (the transfer partner), the transfer's status changes to 'Sent' and becomes visible to both organizations involved in the transfer. This screen will display various details about the sent transfer, including the transfer ID, comments, transaction history, and the date of the written agreement. The design of this screen must reflect these changes and provide the necessary information in a clear and accessible manner.

Key Features:
- Transfer details are displayed but are no longer editable.
- The breadcrumb indicates the 'Sent' stage.
- A description of the pending transfer is prominently displayed.
- The transfer ID is visible at the top of the page.
- A comment section for users to view and add comments.
- A new transaction history section showing all relevant transfer activities.
- Date of the written agreement displayed in the transaction history.
- A record indicating "signed and sent" is visible in the transaction history.
- Wireframe reference: [UXPin Wireframe](https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165000525/simulate/sitemap).

**Purpose and Benefit to User:**
This view screen is essential for users to monitor and manage pending transfers. It serves as the central interface for users to understand the current status of their transfers and to perform subsequent actions based on their roles and the transfer's progress.

**Acceptance Criteria:**
- Given I am a user with viewing privileges, when I access the 'View Transfer' screen, then I should see the transfer's status as 'Sent' along with all the detailed information as described.
- Given I am a user with specific role privileges, when I view the 'View Transfer' screen, then the appropriate action buttons and functionalities should be available to me based on my role.

**Development Checklist:**
- A. Implement the 'View Transfer' screen as per the provided wireframe.
- B. Ensure transfer details are visible but not editable.
- C. Integrate the transaction history section with real-time data updates.

**Notes:**
- The development team should work closely with the UI/UX designers to ensure the screen layout matches the provided wireframe.
- Special attention should be given to user role management to ensure the correct display of buttons and functionalities.
- Testing should include verifying that all information displayed is accurate and up-to-date, especially in the transaction history section.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/227?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Requires access to two BCeID user accounts to test.
