### ISSUE TITLE
LCFS - Delete a draft transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#228]
**Description:**
The ability to delete a draft transfer:

- When viewing a draft transfer
- There is a Delete Draft button
- Clicking on the button brings up a confirmation modal window
- Clicking on the Cancel button within the modal window takes the user back to the draft transfer
- Clicking on the Delete Draft button deletes the draft (i.e., hides it in the UI) and takes the user back to the Transactions page; the transfer is no longer visible in the Transactions table
- A success alert should appear (alert from Material UI: https://mui.com/material-ui/react-alert/
- Users must have the Transfers role to delete draft transfers
- Once draft is deleted it should change it status in delete in DB and shouldn't display on UI.

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164927056/simulate/no-panels

**Screenshot of confirmation modal window:** [Image](https://github.com/bcgov/lcfs/assets/131904954/efd1edc5-3de9-4625-ae77-be4cda388601)

**Purpose and benefit to user:**
Users can delete draft transfers if they no longer wish to execute the transfer

**Acceptance Criteria:**

- [ ] Given I am a <role>, When I am <doing something>, then <this happens>
- [ ] Given I am a <role>, When I am <doing something>, then <this happens>

**Development Checklist:**
- [x] A Create delete draft button when on edit transfer page
- [x] B Make sure user who has transfer role are able to delete the transfer
- [x] C Make sure to change the status to delete in DB and not completely delete the entry in db. On UI, we should display the transfer whose status is not deleted.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/228?planning-poker) with Zenhub @jig-patel @prv-proton
