### ISSUE TITLE
LCFS - Edit a draft transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#230]
**Description:**
Creating the ability to edit a draft transfer. Once a new transfer is saved as a draft, the user is returned to the main transactions table. If a user then clicks on the draft transfer in the transaction table:

- they are taken to the edit transfer screen, which is the same as the new transfer screen but with the user inputted details of the transfer already pre-populated in the different input fields. 
- The user is able to change these input values and save as a draft, which will overwrite the previously saved input data
- The user is able to sign and send the transfer if they have the right role (Signing Authority); note the sign and send functionality will be developed in card #220; this bullet here is simply to note that the button should be visible on this page
- The transfer ID (e.g., transaction ID) is visible at the top of the page
- Only users with the Transfers role can edit the details of a transfer; other BCeID users can view draft transfer but are not able to edit the details. 

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164927056/simulate/no-panels

**Purpose and benefit to user:**
Users can change the details of their draft transfers prior to executing them.

**Acceptance Criteria:**

- [x] Given I am a BCeID user, and I'm on transfer role then I should be able to edit the Draft transfer.
- [x] Given I am a BCeID user but not on transfer role, then shouldn't be able to edit but still be able to access and view the transfer in read only mode.

**Development Checklist:**
- [ ] Role based implementation is required.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/230?planning-poker) with Zenhub @prv-proton @jig-patel

**Comment by Grulin** [comment]
The transfer ID (e.g., transaction ID) is not visible at the top of the page.

What the current edit transfer page shows:

![Image](https://github.com/bcgov/lcfs/assets/156380046/6c48b010-2959-4819-bb55-f44f3641e790)

Example for how the transfer ID # should be showing on the edit transfer page:

![Image](https://github.com/bcgov/lcfs/assets/156380046/1f648280-41e4-4ffc-a247-719120360e60)

**Comment by Grulin** [comment]
Acceptance criteria not met:
Given I am a BCeID user but not on transfer role, then shouldn't be able to edit but still be able to access and view the transfer in read only mode.

As a BCeID user, I am still able to edit and save a transfer without being assigned the 'transfer' role to my user profile.

**Comment by Grulin** [comment]
As a BCeID user with the 'signing authority' only role, I can correctly only save it or sign and send it. But when I select 'Save draft', the green validation message I receive is incorrect. It should say 'Draft transfer successfully saved'. See screenshot for current incorrect validation message:

![Image](https://github.com/bcgov/lcfs/assets/156380046/681c06b3-7823-4df7-be8f-c7f853930bfa)


As a BCeID user with the 'transfer' only role, I can edit a draft transfer, but when I select 'Save draft', I received a Failed 500 error:


![Image](https://github.com/bcgov/lcfs/assets/156380046/fe3b9fa4-5212-4612-bd31-135b671b1d5c)

**Comment by Grulin** [comment]
Still getting an error when I select "save draft". The new input for compliance units field is not persisting after I hit 'save draft'. It continues to revert back to the previously saved input and I get the following error (please see screenshot):



![Image](https://github.com/bcgov/lcfs/assets/156380046/fd25d9e8-0d44-4066-8055-1ad4435d9ab1)

**Comment by prv-proton** [comment]
> Still getting an error when I select "save draft". The new input for compliance units field is not persisting after I hit 'save draft'. It continues to revert back to the previously saved input and I get the following error (please see screenshot):
> 
> ![Image](https://private-user-images.githubusercontent.com/156380046/319294613-fd25d9e8-0d44-4066-8055-1ad4435d9ab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODAyNjksIm5iZiI6MTcxMjE3OTk2OSwicGF0aCI6Ii8xNTYzODAwNDYvMzE5Mjk0NjEzLWZkMjVkOWU4LTBkNDQtNDA2Ni04MDU1LTFhZDQ0MzVkOWFiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMTMyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTE2OGNiOGQwNjZlZTc4N2UwNTI3MDA5NGQ2YzY4Y2EyMWU5OTMxYzFjOGVmZmU2YTRkYmRmYTliYzc0OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ebcCcJt6Hxjf9lm_M7uKz1wz18Q5Q13Qtx9T5EQB47M)

@Grulin, This was related to issue with user role, it had the government role attached to it. Have removed it from DB now it should work.
