### ISSUE TITLE
LCFS - Feasibility Study for Migrating LCFS from Webpack to Vite.js

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#231]
**Problem Description** 
**In order to** enhance performance and improve the development experience, **our development team needs to** convert the LCFS application from webpack to a more modern web bundling system, specifically Vite.js.

**Solution Needs**
- The new solution must ensure compatibility with existing project dependencies and configurations.
- The build and deployment process should be as efficient or more than the current webpack setup.
- Minimal to no disruption to the current development workflow during transition.
- Documentation and training resources for the team on Vite.js.

**Timebox**
- We are committing 5 points of research and implementation.

**Expected Outcome**
The expected outcome of this research includes:
- A comprehensive assessment on the feasibility of using Vite.js with our current project setup.
- Performance benchmarks comparing Vite.js and webpack in our specific use case.
- A preliminary migration plan outlining key steps and potential challenges.
- Recommendations on whether to proceed with the migration based on findings.
- If successful, identification of immediate next steps for the migration process.
- If unsuccessful, alternative recommendations and a discussion of next steps with the team.

**Additional Context**
- Review Vite.js documentation: [Vite.js Official Website](https://vitejs.dev/)
- Analyze current webpack configurations and identify core functionalities that need to be replicated in Vite.js.

**Outcome**
- vitejs will speed up startup times compared to webpack (up to 18x faster on some benchmarks)
- hmr instead of full rebuilds/refreshes
- production build speed increase ( up to 5x on some benchmarks)
- production build size decrease ( up to 10% decrease in bundle size on some benchmarks )
- benchmarks
  - https://kinsta.com/blog/vite-vs-webpack/#5-build-time-and-bundle-size
  - https://esbuild.github.io/ (vite uses esbuild under the hood )
- simplify build config files ( can keep mostly everything stock with vite )
- uses rollup under the hood. Can use rollup plugins as well as create your own if needed
- webpack equivalent plugins for vite
- mostly a drop-in replacement with a few minor considerations:
  - `process.env` -> `import.meta.env`
  - If importing SVG as react components, will need to use decorator plus `?react` suffix on imports
  - jsx extension for react components
- vitest as a drop in for jest for our unit tests. better integration with vite. 
- for integration, we can just remove webpack and install vite.
- preliminary docker setup with vite already done
- migration steps:
  - It would be beneficial to clean up some folders/files and other configs while we're at it. Standardization tasks should be done early to avoid having to make more changes down the line.
    - eslint
    - package.json
    - include pre commit scripts with husky or other packages?
    - folder structure cleanup?
    - code standardization cleanup?
  - create a new temporary folder to house the new front end.
  - initialize a vite react template
  - move over key configurations ( eslint, docker, cypress etc)
  - test configurations on example components to make sure everything works properly
  - start moving over our front end code and test as we go

**Comment by justin-lepitzki** [comment]
5 points left

**Comment by AlexZorkin** [comment]
Outcome looks great. Nice assessment.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
