### ISSUE TITLE
LCFS - Develop Routing Map for Application

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#237]
**Describe the Task**
Develop a comprehensive routing map for the LCFS application. This involves creating structured URL routes for various entities within the system, including but not limited to organizations, users, and transfers. The task requires identifying all necessary entities, determining the required URL structures for each (e.g., viewing, editing), and implementing these routes in a consistent and logical manner.

**Purpose**
The implementation of a well-defined routing map is crucial for building proper navigation and developer background knowledge. It ensures a clear and consistent path for accessing different parts of the application, thereby improving usability and maintainability. This structured approach also aids in better organization of the app's architecture and can assist in future scalability.

**Acceptance Criteria**
- [ ] Compile a comprehensive list of all entities requiring URL routes (e.g., organizations, users, transfers).
- [ ] Develop a standardized URL route structure for each entity, including base access (e.g., `/organizations`), individual item access (e.g., `/organizations/:id`), and edit functionalities (e.g., `/organizations/:id/edit`).
- [ ] Implement these URL routes in the front-end codebase, ensuring they are logically organized and consistently structured.
- [ ] Conduct thorough testing to ensure all routes function as expected and adhere to the specified patterns.
- [ ] Use placeholder component for any undeveloped views.

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/237?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
