### ISSUE TITLE
LCFS - Implement Accessibility Testing in Cypress with cypress-axe and axe-core 

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#239]
**Describe the Task**
Integrate `cypress-axe` and `axe-core` into our existing Cypress end-to-end testing framework to conduct automated accessibility testing. This task involves setting up these tools within our test suite, creating sample tests to validate their functionality, and ensuring that they can identify common accessibility issues in our frontend application.

**Purpose**
The purpose of this task is to enhance the accessibility of our frontend application by automatically detecting potential accessibility issues early in the development cycle. This integration will help in ensuring compliance with key web accessibility standards like WCAG and Section 508, making our application more inclusive and user-friendly.

**Acceptance Criteria**
- [ ] Successfully install and configure `cypress-axe` and `axe-core` in the project.
- [ ] Develop and implement sample Cypress test cases that utilize `cypress-axe` to perform accessibility checks.
- [ ] Ensure the integrated tools are compatible with the existing Cypress test cases and do not introduce any disruptions.
- [ ] Document the setup process and guidelines for using `cypress-axe` and `axe-core` for future reference.
- [ ] Conduct a review session with the team to demonstrate the usage and benefits of the integrated accessibility testing tools.

**Additional Context**
- Focus on identifying and addressing common accessibility issues that could affect user experience and compliance.
- The setup and test cases should serve as a foundation for expanding accessibility testing across the application.
- Additional training or knowledge sharing sessions may be required to bring the entire team up to speed on accessibility testing best practices.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
