### ISSUE TITLE
LCFS - Migration from Webpack to Vite.js for Enhanced React.js Development Experience

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#240]
**Describe the Task**
Transition the application's build and development environment from Webpack to Vite.js. This task involves setting up Vite.js as the new build tool and development server, configuring it to work seamlessly with our existing React.js application, and ensuring all current functionalities are supported in the new setup.

**Purpose**
The primary purpose of this task is to enhance the developer experience by leveraging Vite.js's faster build times and more efficient development server. Moving to Vite.js is expected to significantly improve application start-up times, hot module replacement (HMR) efficiency, and overall development workflow.

**Acceptance Criteria**
- [ ] Successfully replace Webpack with Vite.js in the project setup.
- [ ] Configure Vite.js to support all current React.js features and project dependencies.
- [ ] Ensure that the existing application runs correctly with the Vite.js build and development server, with no loss in functionality.
- [ ] Conduct thorough testing to confirm that the development and production builds are optimized and error-free.
- [ ] Update documentation to reflect changes in the build and development process for future reference.
- [ ] Organize a knowledge transfer session for the development team on using Vite.js and the improvements it brings.

**Additional Context**
- Consider Vite.js plugins or configurations required for compatibility with React.js features used in the project (such as JSX, state management tools, routing, etc.).
- Pay attention to how environment variables and any backend API integrations are handled in Vite.js.
- Assess any changes needed in the CI/CD pipeline to accommodate Vite.js.
- Review the findings from the existing spike ticket for insights and recommendations specific to our application's transition to Vite.js.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
