### ISSUE TITLE
LCFS - Development of 10 Neutral Supplier Organizations for Testing Environments

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#241]
**Describe the Task**
Create 10 fictional, neutral-named supplier organizations for use in our testing environments. These organizations should be designed with generic attributes to ensure they can be safely used for demonstrations to external stakeholders without revealing sensitive or real data. The names and details of these organizations should be carefully crafted to appear realistic yet remain entirely fictional.

**Purpose**
The purpose of this task is to enhance our testing environments with more realistic data while maintaining a neutral and non-sensitive stance. These fictional supplier organizations will allow for more effective and safe demonstrations and testing, particularly when engaging with external parties. It also ensures that our testing environment remains detached from real-world, sensitive data.

**Acceptance Criteria**
- [ ] Develop 10 fictional supplier organization profiles, including names, addresses, contact details, and other relevant information.
- [ ] Ensure that the naming and details of these organizations do not resemble any real companies or entities to avoid any potential data sensitivity issues.
- [ ] Integrate these fictional organizations into the `/seeders/dev/organizations` script for easy implementation in the development environment.
- [ ] Perform a review to ensure that the added data is correctly formatted and functioning as intended within the testing environment.
- [ ] Conduct a mock demonstration using these supplier profiles to validate their appropriateness for external showcases.

**Additional Context**
- The development of these profiles should consider a variety of organization types to simulate a diverse business environment.
- The information for each organization should be detailed enough to facilitate robust testing scenarios.
- Coordinate with the team to ensure that these fictional organizations are seamlessly integrated into existing and future test cases.

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/241?planning-poker) with Zenhub @AlexZorkin @prv-proton @hamed-valiollahi @kevin-hashimoto
