### ISSUE TITLE
METABASE - Investigate options for creating new instance

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#247]
**Problem Description** 
In order to adequately protect confidential information, Metabase needs to have the ability to restrict access to datasets. This is not possible in CTHUB as non-branch members need to have admin-level permissions for their own needs (ZEVA, ITVR, etc.).  Therefore, we want to investigate options for creating a new instance of Metabase for the business area to use. 

Options include: 
- Setting up a brand new instance of Metabase from scratch
- Cloning the existing instance of Metabase and then removing Clean Transportation Branch data and users

**Solution Needs/Wants**
- [Need] Create our own instance of Metabase
- [Need] Connect TFRS database
- [Want] Not have to recreate user accounts
- [Want] Not have to recreate all of the SQL queries and charts in the current instance of Metabase

**Timebox**
- 30-60 min

**Outcome**
Details describing the outcome of the research 
- What is the recommendation for setting up our own instance of Metabase? Do we create a completely new instance and start from scratch (creating new users, new SQL queries)? Can we clone the existing instance of Metabase to maintain users and queries? 

**Additional Context**
- enter text here
- enter text here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/247?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by prv-proton** [comment]
By copying the pg_dump of metabase data to the new instance we can retrieve all the sqls, models and dashboards. 
- After copying the data ensure to reset the db connection and delete the ZEVA, ITVR and other collections and connections
- New instance will continue to have all the users from the old instance while retaining the passwords too.

**Comment by justin-lepitzki** [comment]
Awesome news on creating our own instance of Metabase! It will be very beneficial to copy these things over.
