### ISSUE TITLE
LCFS - Organization declines a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#250]
**Description:**

Develop the ability for an organization to decline a transfer proposal sent from another organization. 

Note card #220 likely needs to be completed prior to this card. 

- Decline Transfer button is visible when the status of the transfer is Sent
- Decline Transfer button is only visible to Organization 2 (and not the initiating Organization 1)
- Clicking on the button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the view transfer screen
- Clicking on the Decline Transfer button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transfer is highlighted, and (4) the transfer status is changed to Declined.
- A transaction history record is saved to the database and visible in the UI when viewing the transfer: Declined on [Month DD, YYYY] by [User] of [Organization]. This record is based on the user with the Signing Authority role that clicked the Decline Transfer button. 
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- The transfer breadcrumb within the view page is updated with the Declined state; this icon replaces the submitted portion of the breadcrumb; see wireframe)
- With a Declined status, the transfer workflow has ended. Users cannot take further action on this transfer. 

**Data Validation & restrictions:**
Being able to decline a transfer needs to have the following restrictions: 
- Requires the Transfer or Signing Authority role to click on the Decline Transfer button, otherwise greyed out 

**Validation Messaging:**
May be dependent on front-end vs. back-end validation:

- Does not have the Transfer or Signing Authority role (Decline Transfer button): "The Transfer or Signing Authority roles are required to decline a transfer."

**Wireframe:** 
- Decline Transfer button: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001060/simulate/no-panels
- Transfer view page with a Declined status: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001069/simulate/no-panels
- Confirmation alert: [Image](https://github.com/bcgov/lcfs/assets/131904954/1d8f29ce-7d14-4b04-b3bf-b7e17b552f1a)

**Purpose and Benefit to User:**
This feature empowers users to decline transfer proposals that are incorrect or unsuitable, ensuring control over the transfer process and maintaining accuracy in their transaction records.

**Acceptance Criteria:**
- Given I am a user with Transfer or Signing Authority role in Organization #2, when I click on the 'Decline Transfer' button, then I should see a confirmation modal.
- Given I confirm the decline action, when the process completes, then the transfer status should update to 'Declined', and I should be redirected to the updated transaction page.

**Development Checklist:**
- [ ] Implement the 'Decline Transfer' button with visibility and access restrictions based on user roles.
- [ ] Create and integrate the confirmation modal window with the required functionalities.
- [ ] Ensure the transaction history is accurately updated upon the decline action.

**Notes:**
- The development team should ensure the UI changes reflect accurately in both the transfer view and transaction history.
- Thorough testing is required to validate the role-based access control and the accurate update of transfer status and transaction history.
- Collaboration with the UI/UX team is crucial for aligning the development with the provided wireframes.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/250?planning-poker) with Zenhub @prv-proton @kevin-hashimoto @AlexZorkin
