### ISSUE TITLE
LCFS - Organization can rescind a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#251]
**Description:**

Develop the ability for organizations to rescind a transfer.

Note card #220 is likely needs to be completed prior to this card. 

- Rescind button 
- Organization 1 visibility in the following statuses: Sent, Submitted, Recommended
- Organization 2 visibility in the following statuses: Submitted, Recommended
- Must have the Transfer or Signing Authority roles, otherwise button is greyed out
- Clicking on the button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the view transfer screen
- Clicking on the Rescind button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transfer is highlighted, and (4) the transfer status is changed to Rescinded.
- A transaction history record is saved to the database and visible in the UI when viewing the transfer: Rescinded on [Month DD, YYYY] by [User] of [Organization]. This record is based on the user with the Transfer and/or Signing Authority role that clicked the Rescind button. 
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- The transfer breadcrumb within the view page is updated with the Rescind state; this icon is placed in the breadcrumb at the point in which the transfer was rescinded (i.e., replaces the icon for the current status of the transfer at the time it was rescinded; see wireframe)
- With a Rescinded status, the transfer workflow has ended. Users cannot take further action on this transfer. 

**Data Validation & restrictions:**
Being able to rescind a transfer needs to have the following restrictions: 
- Requires the Transfer or Signing Authority role to click on the Rescind Transfer button, otherwise greyed out 

**Validation Messaging:**
May be dependent on front-end vs. back-end validation:

- Does not have the Transfer or Signing Authority role (Rescind Transfer button): "The Transfer or Signing Authority roles are required to rescind a transfer."

**Wireframe:** 
- Rescind button (organization 1): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165000525/simulate/sitemap
- Rescinded transfer (view page): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165000529/simulate/sitemap
- Confirmation alert: [Image](https://github.com/bcgov/lcfs/assets/131904954/fa9e5967-d6fc-4e63-a179-26d7dfc45aa1)

**Purpose and benefit to user:**
Organizations can cancel transfers up until the point the director records or refuses the transfer. This allows the supplier to back out of the transfer before it occurs. It also enables the organization to cancel a transfer in the event the director requires additional information and the organization does not want to (or is unable to) provide it. Allows the supplier to end the transfer and avoid the stigma of the director having to decline it. 

**Acceptance Criteria:**

1. **Rescind Feature Accessibility:**
   - Given I am a user with the Transfer or Signing Authority role, when I navigate to a transfer in 'Sent', 'Submitted', or 'Recommended' status, then I should see an active 'Rescind' button.
   - Given I am a user without the Transfer or Signing Authority role, when I navigate to a transfer, then the 'Rescind' button should be greyed out and inaccessible.

2. **Confirmation Modal Workflow:**
   - Given I have clicked the 'Rescind' button, when the confirmation modal appears, then I should be able to either cancel the action, returning to the transfer view, or confirm the rescind action.
   - Given I confirm the rescind action, when the process completes, then I should see a success message, be redirected to the transaction page, see the transaction highlighted, and observe the transfer status changed to 'Rescinded'.
   

3. **Transaction History Record:**
   - Given a transfer has been rescinded, when I view the transfer details, then I should see a transaction history record indicating the rescind action with the date and user details.
   

4. **Transfer Workflow Termination:**
   - Given a transfer status is 'Rescinded', when I view the transfer, then I should not be able to perform any further actions on this transfer.
   

5. **Data Validation and Messaging:**
   - Given I attempt to click the 'Rescind' button without the appropriate role, when the action is restricted, then I should receive a validation message stating, "The Transfer or Signing Authority roles are required to rescind a transfer."
  

**Development Checklist:**

- [ ] Implement the 'Rescind' button with role-based visibility.
- [ ] Develop the confirmation modal window with cancel and confirm actions.
- [ ] Integrate success message/alert/modal post-rescind action.
- [ ] Ensure redirection and highlighting functionality on the transaction page post-action.
- [ ] Implement transaction history update with appropriate rescind details.
- [ ] Utilize Material UI for success alert as specified.
- [ ] Update the transfer breadcrumb to reflect the Rescind state.
- [ ] Enforce data validation and restrictions for the rescind action.
- [ ] Prepare test cases to cover all acceptance criteria.
- [ ] Conduct thorough QA testing to ensure functionality aligns with specifications.
- [ ] Update relevant documentation to include the new 'Rescind Transfer' feature.

**Notes:**

- Consider any potential impact of the rescind functionality on other areas of the system, particularly in relation to data consistency and user experience.
- Ensure robust error handling and user feedback mechanisms are in place for a seamless user experience.
- Collaboration with UX/UI designers may be necessary to refine the visual and interactive aspects of the new features, based on the wireframes provided.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/251?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Rescind function works, but the success message reads "rescindSucessText". 
This should read "Success"



![Image](https://github.com/bcgov/lcfs/assets/156380046/dd219bdc-2320-4b08-a452-eeca7d836d26)

**Comment by justin-lepitzki** [comment]
Tested w/ issues: 

The rescind button is not visible in all required cases. Right now, the rescind button is only visible/available to Organization 1 when the status of the transfer is Sent. The button is not visible to Organization 1 when the status of the transfer is Submitted or Recommended. The button is not visible at all to Organization 2. Note that there are user role requirements for the visibility of the rescind button, however, users with the correct roles was tested and not working (must have Transfer or Signing Authority roles, otherwise button is greyed out).

**Requirements:**
Organization 1 visibility in the following statuses: Sent, Submitted, Recommended
Organization 2 visibility in the following statuses: Submitted, Recommended

**Comment by Grulin** [comment]
Found the following 3 issues with this card:

1) When Organization 2 selects the 'Rescind' button when the transfer is in a 'submitted' or 'recommended' status, the user is shown a 403 error and the rescind function does not work. Organization 2 in the transfer should be able to rescind a transfer in a 'submitted' or 'recommended' status. Please see screenshots:

Submitted status:

![Image](https://github.com/bcgov/lcfs/assets/156380046/ccd56354-0d3b-4e71-b43d-ed21c9c3f4b3)

Recommended status:

![Image](https://github.com/bcgov/lcfs/assets/156380046/2a15e925-d9aa-4444-9255-46cd7607f2ed)

2) Once an organization has rescinded a transfer and is returned to the transactions table, the transfer is not highlighted for the viewer to easily see.

3) The rescinded icon is not placed in the breadcrumb at the point in which the transfer was rescinded. The rescinded icon shows in the sent status regardless of the transfer status regardless of when the transfer was rescinded.
