### ISSUE TITLE
LCFS - Enhancing Data Management: Server-Side Pagination, Filtering, and Loading for AG-Grid

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#252]
**Describe the Task**
Implement server-side pagination, filtering, and data loading for the ag-Grid tables in our frontend React JS application. This involves enhancing the existing grid functionality to handle large datasets more efficiently by fetching data in segments (pagination), allowing users to filter results based on specific criteria, and managing data loading processes to optimize performance and user experience.

**Purpose**
The primary purpose of this task is to improve the application's scalability and usability. Server-side pagination reduces the load on the client by fetching only a portion of data at a time, enhancing the app's performance, especially when dealing with large datasets. Implementing filtering at the server level allows for more efficient data retrieval, tailored to user needs. Overall, this enhancement aims to provide a smoother, faster, and more responsive user experience.

**Acceptance Criteria**
- [ ] Implement server-side pagination to fetch and display data in manageable chunks, reducing the burden on the client side.
- [ ] Enable server-side filtering to allow users to apply various filters to the dataset, improving data retrieval efficiency.
- [ ] Establish a robust data loading mechanism that handles data fetching, error states, and loading indicators to enhance the user interface experience.
- [ ] Integrate with a Zustand store 'only if necessary' to store local data for table.

**Additional Context**
- This task requires close coordination with the team to ensure proper API endpoints are available for pagination and filtering functionalities.
- Consideration should be given to the current state management approach in the React application to seamlessly integrate these new features.
- Performance testing with large datasets is crucial to validate the efficiency and effectiveness of the implemented features.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/252?planning-poker) with Zenhub @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
