### ISSUE TITLE
LCFS - Transfer graphic shows organization balances and registered status for IDIR users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#255]
**Description:**
The transfer graphic on the view transfer page: 

- displays the organization's balance 
- displays whether the organization is registered or not (yes/no)
- Only visible to IDIR users, and only visible when the status of the transfer is Submitted or Recommended
- Card #229 likely needs to be completed before this card

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001075/simulate/no-panels

**Purpose and benefit to user:**
Provides valuable information to government users when reviewing and making recommendations on transfers. Balances help determine whether the seller will still have enough units to comply with LCFS requirements if the transfer is recorded (approved). Registration information provides an additional check that the organizations meet the legislative requirements to participate in the transferring of units. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, When I am on the transfers page and the transfer status is Submitted or recommended, then the organizations balance and registerd status is shown in each of their respective boxes

**Development Checklist:**
- [ ] pull in the organizations balance and registered status, should have this data already as organization data is pulled.
- [ ] This data is only shown for IDIR users. 

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/255?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
As an IDIR user, the transactions view table does show the status of registration, but does not show the organizations balance. Please include a column that shows the organization's balance in the transactions view table.

Please see current view of table for reference:

![Image](https://github.com/bcgov/lcfs/assets/156380046/0e15a809-b7ae-4432-91ec-e437eca8e9d9)
