### ISSUE TITLE
LCFS - Analyst transfer recommendation to the director

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#256]
**Description:**
Develop the analyst recommendation section on the view transfer page and the ability for the analyst to make a recommendation on a transfer. 

- 'Analyst Recommendation to the Director' heading
- 'Recommend Record' and 'Recommend Refuse' radio buttons
- 'Recommend' button in the bottom right hand corner of the page
- Clicking on the 'Recommend' button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the view transfer screen
- Clicking on the 'Recommend' button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transfer is highlighted, and (4) the transfer status is changed to Recommended.
- A transaction history record is saved to the database and visible in the UI when viewing the transfer: Recommended on [Month DD, YYYY] by [User] of [Organization]. This record is based on the IDIR user with the Government Analyst role that clicked the Recommend button. 
- This recommendation transaction history record is only visible to IDIR users
- The comment free text field (government comments to organizations) is saved to the database, if there is a comment added (see card #261 for development of this feature).
- The two radio buttons are no longer selectable; they are greyed out, with the single selection made
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- The transfer breadcrumb within the view page is updated to the Recommended state for IDIR users only; the transfer remains in the Submitted state for BCeID users

**Data Validation & restrictions:**
- Only IDIR users with the Government Analyst role can make recommendations (select the radio buttons, click on the Recommend button)
- Only one radio button can be selected (either Recommend Record or Recommend Refuse, but not both)
- One of the radio buttons must be selected before the analyst can click on the Recommend button (greyed out until a recommendation is made)

**Validation Messaging:**
May be dependent on front-end vs. back-end validation:
- Does not have the Government Analyst role (Recommend button): "The Government Analyst role is required to make a recommendation to the director."
- Has not selected one of the radio buttons (Recommend button): "A recommendation is required before proceeding."

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001075/simulate/no-panels

**Purpose and benefit to user:**
Provides the necessary functionality for government users to make recommendations to the director 

**Acceptance Criteria:**

- [x] Given I am a Government Analyst with IDIR access, when I navigate to the 'View Transfer' page, then I should see the 'Analyst Recommendation to the Director' heading with 'Recommend Record' and 'Recommend Refuse' radio buttons.
- [x] Given I am a Government Analyst and I select one of the recommendation radio buttons, when I click the 'Recommend' button, then a confirmation modal should appear.
- [x] Given I am on the confirmation modal, when I click the cancel button, then I should return to the 'View Transfer' page without any changes made.
- [ ] Given I am on the confirmation modal and have made a selection, when I click the 'Recommend' button, then a success message should appear, the user should be redirected to the transaction page, the transaction row for the transfer should be highlighted, the transfer status should change to 'Recommended', and the radio buttons should become unselectable.
- [ ] Given a recommendation has been made, when viewing the transfer, then a transaction history record showing the recommendation date, the recommending user, and the organization should be visible.
- [ ] Given a comment has been added in the 'Comment' field, when a recommendation is made, then the comment should be saved to the database and be visible when viewing the transfer.
- [ ] Given I am a user with the Government Analyst role, when I access the transfer page, then I should have the ability to make a recommendation, but this functionality should be restricted to users with the specified role.

**Development Checklist:**
- [ ] Implement the UI for the 'Analyst Recommendation to the Director' section on the 'View Transfer' page.
- [ ] Develop the backend logic to handle the recommendation selection, confirmation modal, success message, redirecting and updating the transaction page, saving transaction history, and saving comments.
- [ ] Ensure data validation and restrictions are in place, such as role verification, radio button selection validation, and update the UI accordingly based on user actions.

**Notes:**
- The category D checkbox will be handled in a different card.
- The comments to the director feature will be handled in a different card.
- The save button functionality will be handled in a different card.

Please ensure that all the elements of the acceptance criteria and development checklist are implemented as described, adhering to the project's coding and design standards.

**Comment by justin-lepitzki** [comment]
Might hold off on closing this ticket until some of the missing components are completed, which are being handled in other cards:
- Transaction history record, including visibility of record (IDIR only)
- Director comments not saving (demo data)
- Transaction row highlight

**Comment by Grulin** [comment]
IDIR user with analyst role is missing 'Recommend Record' and 'Recommend Refuse' radio buttons when recommending a transfer. Please see screenshot:


![Image](https://github.com/bcgov/lcfs/assets/156380046/cc055467-c531-4ad8-95b9-cac00f5c6e64)
