### ISSUE TITLE
LCFS - Categorization prediction prior to approval within the Transaction History section

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#258]
**Description:**
This card is to develop the categorization prediction for transfers that have not yet been approved. This functionality was recently implemented in TFRS and we want to mirror that implementation in the LCFS. 

- predictive text is next to the date of written agreement within the transaction history section (see wireframe)
- visible to all users within government and the two organizations that are party to the transfer
- visible when the transfer has the following statuses: Sent, Submitted, Recommended, Recorded
- not visible when the transfer has the following statuses: Draft, Deleted, Declined, Refused, Rescinded
- this feature predicts the category for the transfer based on the date of written agreement inputted by organization 1 and if the director approves by a certain date window
- this feature should be dynamic in that the prediction should change as time passes. For example, predicting a category A if approved by a future date, but if we pass over that future date prior to the transfer approval, the prediction should update to the new / revised category.

**Transfer categories:**
From the date on which the written agreement to transfer credits was reached between the two suppliers and the date the director approves the transfer.  The Proposal will fall under one of the 3 categories. 

Category A: The agreement to transfer was reached within the last 6 months.
Category B: The agreement to transfer was reached between 6 months to 1 year ago.
Category C: The agreement to transfer was reached more than 1 year ago.

Category D: There is also a Category D checkbox override. This is based on the analyst or director selecting a checkbox which will override the Category A-C date calculation. This decision is based on the value of price per credit. 
- The category D feature is handled in a different card (#257)

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001075/simulate/no-panels

**Purpose and benefit to user:**
This information is requested to provide better context on the price of the transferred units.  Transfer agreements can be for future compliance units over a long period of time. While the price is agreed upon at the date the transfer agreement is completed, the actual transfer may not happen until months or over a year into the future. At the time of execution, the fair market value of compliance units may have changed substantially. Without knowing when the agreement was reached, it may appear that the transfer is for too low of a price (or too high). This information provides relevant context to the price. This information is then reflected in the credit market report as organizations use this info for the purpose of decision making and negotiating transfers. 

**Acceptance Criteria:**

- [ ] Given I am ANY user, When I am viewing the transfers page and when the transfer status is NOT Draft, Deleted, Declined, Refused, Rescinded, then in the Transfer History section, there should be a category given for the transfer.
- [ ] It should show the correct category based on its agreement date
Category A: The agreement to transfer was reached within the last 6 months.
Category B: The agreement to transfer was reached between 6 months to 1 year ago.
Category C: The agreement to transfer was reached more than 1 year ago.

**Development Checklist:**
- [ ] This is done on the client side
- [ ] generated every page load as we would like it to be up to date ("dynamic")
- [ ] reference TFRS since it is already implemented over there

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/258?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton
