### ISSUE TITLE
LCFS - Government users can leave comments to organizations

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#261]
**Description:**

When reviewing, making a recommendation, and recording/refusing a transfer, government users can leave comments to organizations. 

Note that Card #229  likely needs to be completed before this card can be worked on.

- Free text form
- Similar to simplified free text comment field that organization 1 & 2 have when initiating and submitting a transfer
- Includes text disclaimer about who can see the comment
- Comment remains editable to government users until it is recorded/refused
- Editable when it has the following statuses: Submitted, Recommended
- Not editable when the status changes to Recorded, Refused
- Only visible to government users when it is editable (submitted, recommended statuses)
- Becomes visible to organization 1 & 2 when the status changes to Recorded or Refused **and** the field is not blank (i.e., there is text written in the input field)
- Field is optional 
- Save button (see wireframe)
- Clicking on the Save button saves the comment to the database and has it persist (be visible) in the UI
- Clicking on the Save button should trigger a success alert message (from Material UI: https://mui.com/material-ui/react-alert/); the user remains on the same page after clicking the Save button (no redirect).

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001075/simulate/no-panels

**Purpose and benefit to user:**
Enables government communication about the transfer with the organizations. Purposely designed to be a single, unified message from government rather than individual comments from individual government users (like we do in TFRS)

**Acceptance Criteria:**

- [ ] Given I am on a Government Users Role I should be able to add the comment, When I am clicking the save button after adding the comments in the text box, then respective organization and government users should be able to view this comment.
- [ ]  Given I am on a Government Users Role I should be able to add the comment, When I am clicking the save button after adding the comments in the text box, then Government Users should be able to edit the comments.

**Development Checklist:**
- [ ] The development team should ensure the UI changes reflect accurately as per the wireframe.
- [ ] Thorough testing is required to validate the role-based access control and the accurate update of comments.
- [ ] Collaboration with the UI/UX team is crucial for aligning the development with the provided wireframes.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/261?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Tested with issues: 

- Clicking on the save button is taking the user back to the transactions page; it should keep them on the transfer details page (no redirect)
- The material UI success message should then be visible on the transfer details page (right now it is visible on the transactions page as the user is being redirected back to the transactions page when saving)
- The comment is not being saved (not visible in the UI). Since it is not visible in the UI, it is not meeting other requirements of this card: (1) Editable when it has the following statuses: Submitted, Recommended; (2) Not editable when the status changes to Recorded, Refused; (3) Only visible to government users when it is editable (submitted, recommended statuses); and (4) Becomes visible to organization 1 & 2 when the status changes to Recorded or Refused and the field is not blank (i.e., there is text written in the input field). 

Some of the identified issues may be related to the fact that the UI is showing demo data. Regular comments are not saving properly for BCeID users as well, see #493 - Regular comments in the transfer feature are not saving, showing demo data.
