### ISSUE TITLE
TFRS - Error when trying to commit an Admin adjustment using the historical data entry feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#266]
**Describe the Bug**
The system is throwing an error when an IDIR user tries to commit an administrative adjustment transaction using the historical data entry feature within the TFRS dev January release environment. 

This may or may not be related to issue # 2478: https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/tfrs/2748. 

**Expected Behaviour**
A modal window provides a preview of the impact of the transactions in the queue, prior to the user confirming the commitment of the transactions. 

**Actual Behaviour**
The modal window does not appear; instead the system throws an error message. 

Screenshot 1 (transactions in queue): <img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a50a0fa823f09e19571ef700faa5f8a29f8f527/Screenshot%202023-12-12%20Admin-adjust-error-1.png" alt="Screenshot 2023-12-12 Admin-adjust-error-1.png" />

Screenshot 2 (error when trying to commit transactions): <img width="1586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--089e5146de3bde4d81b771cf6aa458ca92a6c319/Screenshot%202023-12-12%20Admin-adjust-error-2.png" alt="Screenshot 2023-12-12 Admin-adjust-error-2.png" />

**Implications**
Unable to apply administrative adjustment transactions.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user
1. Go to 'Historical Data Entry' sub-tab within the Administration page
2. Select 'Admin Adjustment' as the transaction type, fill out the rest of the input fields, and then add the transaction to the queue (by clicking on the 'Add to Queue' button).
3. Click on 'Commit' button

**Comment by hamed-valiollahi** [comment]
I investigated this issue and it looks similar to issue 2748 (POST /api/credit_trades). I used the same code and rebuilt the docker images with the same database. It worked well on my local setup.
