### ISSUE TITLE
TFRS - Wrong label showing when gov analyst recommends a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#275]
**Describe the Bug**

-	This is for the TFRS jan-release branch. 
-	Status of transfer is submitted
-	Government analyst role

Button label currently shows ‘Recommend issuance’

Button label should say ‘Recommend recording transfer’

Note that the ‘Recommend issuance’ label is one that we use for the Initiative Agreement (formerly Part 3 Award) transaction, which is a government analyst initiated transaction. We have previously had issues where changing the labels in one area has caused labels to change in other areas of the app. When fixing this label in the transfer feature, please make sure that the labels in the ‘Initiative Agreement’ feature don’t also change to ‘Recommend recording transfer’. The label in the ‘Initiative Agreement’ feature is supposed to say ‘Recommend issuance’. 

**Steps To Reproduce**
Steps to reproduce the behaviour: 
User/Role: IDIR user, government analyst role, TFRS jan-release branch
1. Go to a transfer with a submitted status
2. Scroll down to see the button labels
3. See error

Screenshot of wrong label in transfer feature: <img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aceb5261f19bcdcc11a7356a3a28be724803a9ec/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1164-2023-12-15-16_17_53.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1164-2023-12-15-16_17_53.png" />

Screenshot of correct label in Initiative Agreement feature (possible clash of labels): <img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2x1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5457af1f5ebfe8d48d3ea4f5241489b20e7ea482/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-add-2023-12-18-13_54_53.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-add-2023-12-18-13_54_53.png" />

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/275?planning-poker) with Zenhub @prv-proton @kevin-hashimoto @hamed-valiollahi

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/275?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton
