### ISSUE TITLE
TFRS - Revise message in confirmation modal window when director is refusing a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#276]
**Describe the task**
When an IDIR user with the director role clicks on the ‘Refuse transfer’ button when viewing a recommended transfer, a confirmation modal window appears that provides the director with additional information from the regulations. 

This task is to revise the message that appears in the confirmation modal window. There are only a few parts of the wording that needs to be changed.  

This is for the TFRS jan-release branch. 

Screenshot of modal window in TFRS jan-release: <img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0p1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f1fb24685427ae3b90f43f57a66b6729f3d7c01/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1164-2023-12-15-16_19_03.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1164-2023-12-15-16_19_03.png" />

**Change 1: revised section number and lower case director label**
Change “Under section 17 of the Low Carbon Fuels Regulation, the Director may…” to “Under section 19 of the Low Carbon Fuels (General) Regulation, the director may…”

**Change 2: word correction / replacement**
In (a) (i) of the message, change the word “transfer” to “transferor”, so that the full sentence says “the transferor will be unable to meet the target set under section 12 [low carbon fuel target] of the Act, or”

**Change 3: word correction / replacement **
In (b) (iii) of the message, change the bullet from (i) to (iii). The bullets for (b) should read in sequence from one to three (i) (ii) (iii). Right now it reads as one (i), two (ii), one (i).
In (b) (iii) of the message, change the word “assessment” to “reassessment”, so that the full sentence says “the director has reason to believe that, if the transfer is recorded, the transferor will have a negative balance on reassessment.” 

We need to revise this message because the regulations were changed as part of regular drafting activities. Now that the regulations are finalized, we need to tweak this section to ensure alignment with the legislation. 

**Purpose**
Align with the finalized regulations

**Acceptance Criteria**
- [ ] first
- [ ] The section number in the message should correctly reference section 19.
- [ ] The word "Director" should be in lowercase as "director."
- [ ] The term "transfer" in (a) (i) should be changed to "transferor."
- [ ] The bullet sequence in (b) should correctly follow as (i), (ii), (iii).
- [ ] The word "assessment" in (b) (iii) should be updated to "reassessment."

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/276?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Kailee-Douglas** [comment]
Test.
