### ISSUE TITLE
LCFS - Implement Pytest Unit Tests for Organization Views in FastAPI Backend

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#303]
**Describe the task**
Develop pytest tests for the FastAPI backend route handler focusing on the organization views. This involves writing tests to validate the functionality of each endpoint, including success, failure, and edge case scenarios.

**Purpose**
The purpose of this task is to ensure the reliability and stability of the organization views endpoints. By implementing thorough testing, we aim to identify and fix bugs, improve code quality, and enhance the overall robustness of the application.

**Acceptance Criteria**
- [ ] Write a test to verify successful retrieval of an organization by ID.
- [ ] Write a test for handling a request to retrieve an organization that does not exist (expecting a 404 response).
- [ ] Write tests for the update organization endpoint, including success and failure scenarios (e.g., updating a non-existent organization).
- [ ] Write tests for the list organizations endpoint, validating the response structure, and pagination logic.
- [ ] Write tests for the get_organization_statuses and get_organization_types endpoints, including scenarios where no statuses or types are found.
- [ ] Write tests for the get_users_for_organization endpoint, ensuring proper retrieval of users and handling of cases with no users.
- [ ] Ensure all tests validate the response status codes, returned data, and error messages where applicable.

**Additional context**
- Review the existing route handler code for necessary mock setups and dependencies.
- Ensure that all tests follow the async conventions used in the existing test suite.
- Collaborate with the development team to understand any specific edge cases or scenarios that need to be tested.

```python
import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from starlette import status

@pytest.mark.anyio
async def test_get_organization_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful organization retrieval
    pass

@pytest.mark.anyio
async def test_get_organization_not_found(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for organization not found scenario
    pass

@pytest.mark.anyio
async def test_update_organization_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful organization update
    pass

@pytest.mark.anyio
async def test_update_organization_failure(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for failure in updating an organization
    pass

@pytest.mark.anyio
async def test_list_organizations_pagination(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for organization list with pagination
    pass

@pytest.mark.anyio
async def test_get_organization_statuses_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful retrieval of organization statuses
    pass

@pytest.mark.anyio
async def test_get_organization_statuses_not_found(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for no organization statuses found scenario
    pass

@pytest.mark.anyio
async def test_get_organization_types_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful retrieval of organization types
    pass

@pytest.mark.anyio
async def test_get_organization_types_not_found(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for no organization types found scenario
    pass

@pytest.mark.anyio
async def test_get_users_for_organization_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful retrieval of users for an organization
    pass

@pytest.mark.anyio
async def test_get_users_for_organization_not_found(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for no users found for an organization scenario
    pass

# Existing tests
# ...

# Add additional tests as needed

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/303?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton
