### ISSUE TITLE
LCFS - Develop Pytest Tests for User Management Endpoints in FastAPI Backend

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#304]
**Describe the task:**
Create pytest tests for the user management endpoints in the FastAPI backend. This includes writing tests for each endpoint (GET, POST, PUT, DELETE) to verify their functionality, including successful operations, error handling, and edge case scenarios.

**Purpose:**
The goal is to ensure the robustness, reliability, and correctness of the user management endpoints. By implementing comprehensive tests, we aim to detect bugs early, uphold code quality, and guarantee that the API behaves as expected under various scenarios.

**Acceptance Criteria:**
- [ ] Write a test to verify the successful retrieval of the current user's information.
- [ ] Write a test for fetching a user by ID, including handling a non-existent user (expecting a 404 response).
- [ ] Write tests for the list users endpoint, including checking the response structure and verifying sort, filter, and pagination functionalities.
- [ ] Write tests for creating a new user, covering both successful creation and failure due to invalid data.
- [ ] Write tests for updating a user, including successful update and failure scenarios (e.g., updating a non-existent user).
- [ ] Write tests for the delete user endpoint, ensuring correct functionality and handling of conditions (like deleting a user who has never logged in).
- [ ] Write tests for fetching a user's roles and user history, including cases where no roles or history entries are found.
- [ ] Ensure all tests validate response status codes, returned data, and error messages where appropriate.

**Additional context:**
- Familiarize with the user management endpoint logic to understand necessary mock setups and dependencies.
- Follow the async conventions used in the existing test suite for consistency.
- Collaborate with the development team for any specific scenarios or edge cases that need to be tested.

```python
import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from starlette import status

@pytest.mark.anyio
async def test_get_current_user_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful retrieval of current user
    pass

@pytest.mark.anyio
async def test_get_user_by_id_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful retrieval of a user by ID
    pass

@pytest.mark.anyio
async def test_get_user_by_id_not_found(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for handling non-existent user ID
    pass

@pytest.mark.anyio
async def test_list_users_pagination(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for user list with sort, filter, and pagination
    pass

@pytest.mark.anyio
async def test_create_user_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful user creation
    pass

@pytest.mark.anyio
async def test_create_user_failure(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for failure in creating a user due to invalid data
    pass

@pytest.mark.anyio
async def test_update_user_success(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for successful user update
    pass

@pytest.mark.anyio
async def test_update_user_failure(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for failure in updating a user
    pass

@pytest.mark.anyio
async def test_delete_user_conditions(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for deleting a user under specific conditions
    pass

@pytest.mark.anyio
async def test_get_user_roles(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for retrieving a user's roles
    pass

@pytest.mark.anyio
async def test_get_user_history(client: AsyncClient, fastapi_app: FastAPI) -> None:
    # TODO: Implement test for retrieving a user's history
    pass

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/304?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
