### ISSUE TITLE
LCFS - Create Cypress E2E Test for User Creation Workflow

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#305]
**Describe the task:**  
Develop an end-to-end test using Cypress for the user creation process in the application. The test should simulate the scenario where an IDIR user logs in and creates a new user through the application's user interface, interacting with the API.

**Purpose:**  
The aim is to ensure the user creation feature works seamlessly from a real user's perspective. This test will help us verify the integration of the frontend with the backend API, authentication flows, and the user interface's behavior in response to user inputs and API responses.

**Acceptance Criteria:**
- [ ] Implement a test that logs in as an IDIR user, and creates a new IDIR user.
- [ ] Implement a test that logs in as an IDIR user, and creates a new IDIR user that fails validation.
- [ ] Implement a test that logs in as an IDIR user, and creates a new organization user.
**Test Steps**
- [ ] Login as an IDIR user from the splash page, there is an existing command for this.
- [ ] After successful login, navigate to the user creation section of the application.
- [ ] Fill out the user creation form with valid data and submit it.
- [ ] Verify that the API call to create a new user is made correctly and succeeds.
- [ ] Confirm that the application UI responds appropriately after user creation (e.g., displaying a success message, redirecting to a specific page).
- [ ] Ensure the test checks for the presence of the newly created user in the user list or database.
- [ ] The test should handle cleanup, like logging out or deleting the test user if necessary.

**Additional context:**
- Provide the test with any necessary environment variables and test data.
- Ensure the test respects the privacy and security of real user data.
- Document the test case clearly, and ensure it can be easily run in different environments (development, staging, etc.).

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/305?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton
