### ISSUE TITLE
LCFS - Refactor Organization Route Handlers to Use Repository Pattern and Dependency Injection

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#306]
**Describe the task:**  
Refactor existing organization route handlers in the FastAPI application to use the repository pattern and dependency injection. This task involves identifying route handlers that directly interact with the database and modifying them to use repository classes for database interactions.

**Purpose:**  
The goal is to enhance the application's architecture by separating concerns, thereby making the codebase more maintainable, scalable, and testable. This approach also streamlines database interaction code, making it more consistent across the application.

**Acceptance Criteria:**
- [ ] Refactor the `export_organizations` endpoint to use an `OrganizationRepository` instead of directly interacting with the database.
- [ ] Update the `get_organization` endpoint to retrieve organization details via the repository pattern.
- [ ] Modify the `update_organization` endpoint to handle data updates through an `OrganizationRepository`.
- [ ] Ensure the `list_organizations` endpoint already using the repository pattern remains unchanged.
- [ ] Verify the `get_organization_statuses` and `get_organization_types` endpoints that use the repository pattern do not require changes.
- [ ] Refactor the `get_users_for_organization` endpoint to fetch users via a repository instead of direct database calls.
- [ ] After refactoring, ensure all endpoints function as expected and pass all existing tests.
- [ ] Update any related documentation to reflect the new repository usage in route handlers.

**Additional context:**
- Test extensively to ensure that the refactoring does not introduce regressions.
- Consider the impact on any frontend components that consume these endpoints, ensuring that API contracts remain consistent.

**Comment by Grulin** [comment]
Nothing to test on the business area side.
