### ISSUE TITLE
LCFS - Standardization of Pydantic Schema Classes for Organization Module

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#307]
**Describe the task:**  
Revise and standardize the Pydantic schema classes in the `organization schema.py` file to enhance clarity, maintainability, and reusability. This involves creating a consistent naming convention, leveraging base classes, and avoiding redundant code. Special attention is needed since these classes are already in use throughout the API.

**Purpose:**  
To improve code readability, reduce duplication, and establish a clear pattern for current and future developers. This will facilitate easier updates and extensions to the schema classes.

**Acceptance Criteria:**
- [ ] Analyze existing Pydantic schema classes in the `organization schema.py` file.
- [ ] Establish a clear naming convention for schema classes (e.g., `OrganizationCreate`, `OrganizationUpdate`, `OrganizationResponse`, etc.).
- [ ] Implement base classes where appropriate to avoid repetition (e.g., `BaseOrganizationSchema`, `BaseAddressSchema`).
- [ ] Refactor existing classes to extend these base classes, reducing code duplication.
- [ ] Ensure all changes maintain backward compatibility with existing API endpoints.
- [ ] Update all references and usages of these classes throughout the application to reflect the new structure.
- [ ] Perform thorough testing to ensure that all endpoints function as expected after refactoring.
- [ ] Update any related documentation to reflect the new schema organization and standards.

**Additional context:**
- Consider using mixins for shared fields across different schemas.
- Review related FastAPI and Pydantic documentation for best practices in schema design.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/307?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Nothing to be tested by business area side.
