### ISSUE TITLE
LCFS - Standardization of Label Management in Frontend

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#308]
**Describe the task:**  
Develop and implement a systematic approach for managing labels in the frontend application. This involves creating a well-organized structure for label constants, considering various user roles and workflow states.

**Purpose:**  
To streamline the process of managing and updating labels, ensuring consistency and ease of maintenance across the application. This will also aid in localization efforts and improve the flexibility of the UI to adapt to different user roles and workflow states.

**Acceptance Criteria:**
- [ ] Review the current implementation of labels in the application.
- [ ] Design a structure for organizing label constants. This could involve grouping labels by features, user roles, workflow states, or a combination of these.
- [ ] Create a centralized system for label management, such as a dedicated directory with multiple files or a single file with structured sections.
- [ ] Implement a naming convention for labels and groups of labels to enhance readability and ease of access.
- [ ] Create a plan to refactor the application to utilize this new structure for label management and review the strategy with the dev team.
- [ ] Ensure that the new system supports easy addition or modification of labels as the application evolves.
- [ ] Document the structure and usage guidelines for the label management system.
- [ ] Test the application thoroughly to ensure all labels display correctly for various user roles and workflow states.

**Additional context:**
- Coordinate with UI/UX and development teams to ensure that the new label management system meets all requirements and is scalable.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/308?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
