### ISSUE TITLE
LCFS - Government users can edit their comments

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#312]
**Description:**
Government users can edit their internal comments that they have previously added within the transfer feature: 

- [Edit] button is visible on previously added comments by that same user (see wireframe)
- Clicking on the edit button allows the user to edit their comment
- User can then save the edited comment or cancel the edits
- If the user saves the edited comment, then a new date/time stamp is displayed to indicate when the edit was made. The date / time of the original comment remains visible.
- Only the date/time of the last edit is displayed in the case where a comment has been edited multiple times.
- Editing a comment does not impact the sorting of comments, which is based on descending order (most recent comment at the top) determined by the comment's original date/time stamp which is always visible in the UI
- There are no restrictions on when government users can add / edit comments. For example, an analyst can add/edit a comment before or after they make a recommendation to the director; they can also / add edit the comment after the transfer has been recorded / refused.

**Related cards / dependencies:**
#259 

**Wireframe:** 
- Example of an edited comment: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112777/simulate/no-panels

**Purpose and benefit to user:**
Allows the government user to change their comment if they discover an error, spelling mistake, or grammatical issue

Based on the information provided, the last three sections of the sprint ticket can be completed as follows:

**Acceptance Criteria:**

- [ ] Given I am a government user, When I click the [Edit] button on a comment I have previously added, then I should be able to edit the content of the comment.
- [ ] Given I am a government user, When I save the edited comment, then the comment should display the new date/time stamp of the last edit while retaining the original date/time stamp.

**Development Checklist:**

- [ ] Implement the visibility of the [Edit] button on comments added by the same government user.
- [ ] Enable the editing feature for comments, allowing users to modify the content.
- [ ] Ensure the system updates and displays the new date/time stamp for the last edit alongside the original date/time stamp on saving the edited comment.

**Notes:**

- It is important to ensure the original date/time stamp of the comment is always visible, regardless of the number of edits.
- The sorting of comments should remain based on the original date/time stamp to maintain chronological order in the conversation.
- Testing should cover scenarios where comments are edited multiple times to ensure the display of date/time stamps is consistent and accurate.
- Editing a comment by removing all text in it would save as an empty text box, but retain the name and date stamp of the user. This allows for deletion of comment, but keeps a record of the user that was involved in commenting. Avoids allowing user to completely delete record of historical comments.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/312?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
When I input an internal comment and select 'add comment', the text box is replaced by a message that says 'error loading comments: Network Error' and the comment is not saved. Please see screenshot for error:



![Image](https://github.com/bcgov/lcfs/assets/156380046/8992d29a-d71a-4d51-9ddd-7fa799195bfe)

**Comment by hamed-valiollahi** [comment]
@Grulin, thanks for reporting the issue! I also couldn't reproduce the issue you mentioned. It could be an internet or server environment issue. Could you please check once more and let me know if it's still there? Then, Alex and I can look into it together. Thank you!
