### ISSUE TITLE
LCFS - Director can return transfer to analyst

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#316]
**Description:**
Develop the ability for the Director to return the transfer to the analyst (i.e., status change): 

- 'Return to Analyst' button visible to Government users with the Director role when the transfer has a status of 'Recommended'
- 'Return to Analyst' button in the bottom right hand corner of the page
- Clicking on the 'Return to Analyst' button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the view transfer screen
- Clicking on the 'Return to Analyst' button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transfer is highlighted, and (4) the transfer status is changed back to Submitted.
- No new transaction history record is created. 
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- The transfer breadcrumb within the view page is updated back to the Submitted state 

**Confirmation Model Messaging:**
Similar to when the Director refuses a transfer, we want to provide a warning message to the Director when they click on the Return to Analyst button. See attached screenshot for formatting and UI styling (e.g., yellow warning background, warning icon)
- You are strongly encouraged to provide an explanation to the analyst as to why the transfer is being returned.
- Are you sure you want to return the transfer to the Analyst? This will change the status of the transfer back to Submitted.

**Wireframe:**

- Director view of recommended transfer: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001091/simulate/no-panels
- Warning message for Director within the confirmation modal window: 
![Image](https://github.com/bcgov/lcfs/assets/131904954/afb7e605-9019-4ebb-8a8c-2e7cac0d4ed3)

**Purpose and benefit to user:**
Ability for the director to return the transfer to the analyst to revise their recommendation and/or provide additional information to the director support the decision to record or refuse the transfer. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, When the status of the transfer is 'Recommended', the 'Return to analyst' button should show
- [ ]  When the 'Return to analyst' button is clicked, a modal should appear
- [ ] The modal should display a confirmation of if the transfer should 'return to analyst'
- [ ] Once confirmed, the transfer status should return to 'submitted' and the breadcrumb should highlight the 'submitted' step

**Development Checklist:**
- [ ] No new history records should be logged
- [ ] Only the status should change. 'Recommended' to 'Submitted'
- [ ] Modal will come from a modal component ( separate ticket )

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/316?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
There is similar functionality in TFRS for creating a new Part 3 Award / Initiative Agreement issuance. To create a new Part 3 Award, a user with the analyst role goes to the File Submissions page and then clicks on the New Initiative Agreement Issuance button (formerly New Part 3 Award) and recommends it to the director. When the director is reviewing the recommended transaction, they can see the Return to Analyst button.

**Comment by Grulin** [comment]
Dependent on completion of #256 before able to test
