### ISSUE TITLE
LCFS - Director refuses a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#317]
**Description:**
Develop the ability for the Director to refuse (i.e., decline) a transfer: 

- Refuse transfer button visible to Government users with the Director role when the transfer has a status of 'Recommended'
- 'Refuse transfer' button in the bottom right hand corner of the page
- Clicking on the 'Refuse transfer' button brings up a confirmation modal window (see section below for more info on confirmation modal)
- Clicking the cancel button in the modal window brings the user back to the view transfer screen
- Clicking on the 'Refuse transfer' button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transfer is highlighted, and (4) the transfer status is changed to Refused.
- The compliance balances of the two organizations does not change. The transfer has reached an end state. 
- A transaction history record is saved to the database and visible in the UI when viewing the transfer: Refused on [Month DD, YYYY] by the Director under the *Low Carbon Fuels Act*. 
- The date in the transaction history record is based on when the user with the Director role refused the transfer. 
- The transaction history is visible to both BCeID and IDIR users
- Success alert from Material UI: https://mui.com/material-ui/react-alert/
- The transfer breadcrumb within the view page is updated to the Refused state (visible to all users)

**Confirmation Model Messaging:**
Similar to TFRS January release, we want to provide a warning message to the Director when they click on the Refuse transfer button. See attached screenshot for formatting and UI styling (e.g., yellow warning background, warning icon)

Under section 19 of the Low Carbon Fuels (General) Regulation, the director may refuse to record a transfer under section 16 of the Act if:
(a)
the director considers that
(i)
the transferor will be unable to meet the target set under section 12 [low carbon fuel target] of the Act, or
(ii)
the intent of the transfer is to avoid compliance with the Act, or
(b)
all of the following apply:
(i)
the director is conducting a reassessment in relation to the transferor;
(ii)
the director has reason to believe that the transferor was issued a number of compliance units as a result of fraud or misrepresentation, and
(iii)
the director has reason to believe that, if the transfer is recorded, the transferor will have a negative balance on reassessment.

You are strongly encouraged to add a comment that provides an explanation as to why the proposed transfer is being refused. The comment will be visible to both organizations involved in the transfer.

- Are you sure you want to refuse this transfer? 

**Wireframe:**

- Director view of recommended transfer (Refuse transfer button): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001091/simulate/no-panels
- View of refused transfer: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112787/simulate/no-panels
- Confirmation model window messaging (from TFRS): ![Image](https://github.com/bcgov/lcfs/assets/131904954/4e2cc241-e098-44e8-a7e3-c4172d19df5c)

**Purpose and benefit to user:**
Ability for the director to refuse (decline) transfers, thus ending the workflow / processing of a transfer. 

**Acceptance Criteria:**

- [ ] Given I am a IDIR Director Role, When I am refusing the transfer, then status should be updated as Refused and a history record to be created.
- [ ] Given I am not a IDIR Director Role, I shouldn't have to the ability or button visible to Refuse

**Development Checklist:**
- [ ] Modal Generic / individual dialog component shall be created as part of a different ticket.
- [ ] Ensure backend and frontend both are implemented.
- [ ] Necessary test cases with good coverage is added using pytest and jest.

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/317?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Please reformat the confirmation model window messaging to the following:

![Image](https://github.com/bcgov/lcfs/assets/156380046/06f95229-7a0d-4050-bc3e-7e7a26ca8c9e)

**Comment by hamed-valiollahi** [comment]
Sure, the changes have been applied.

![Image](https://github.com/bcgov/lcfs/assets/2143103/ec5afbf6-826d-4702-9720-684cda095799)
