### ISSUE TITLE
LCFS - Rework Generic Organization Seeds and User Profiles

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#323]
**Title:** LCFS - Rework Generic Organization Seeds and User Profiles

**Describe the Task:**  
Rework existing database seed scripts to create more generic organizations and user profiles. This involves modifying the current seeding process to ensure that the generated organizations and user profiles are non-specific and generic, suitable for various testing and development scenarios.

**Purpose:**  
The primary purpose of this task is to enhance the flexibility and relevance of the test data across different development and testing environments. By creating more generic organizations and user profiles, developers and testers can more effectively simulate a diverse range of real-world scenarios, leading to more robust and versatile software.

**Acceptance Criteria:**  
- [ ] The seed script generates a range of generic organizations that do not resemble any specific real-world entities.
- [ ] User profiles created by the seed script are generic and diverse, representing a wide range of potential users.
- [ ] The seeded data should be suitable for use in various development and testing scenarios, ensuring broad applicability.

**Additional Context:**  
- Ensuring data privacy and avoiding any resemblance to real organizations or individuals is critical in this rework.
- Collaboration with the QA team might be beneficial to understand the range of scenarios needed for effective testing.

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
