### ISSUE TITLE
LCFS - Implement Backend Service for Director-Approved Transfer Processing in LCFS System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#325]
**Description (Backend Focus):**
Develop backend functionality to support the Director's ability to record (approve) a transfer in the LCFS system. This involves implementing a service method within the FastAPI backend framework, specifically under a designated service class. The method will handle the logic of transferring compliance units between suppliers upon Director approval. This process is initiated by a frontend action where the Director clicks the 'Record transfer' button. Key backend tasks include:

1. Verifying the user role: Ensure only users with the Director role can access and execute this method.
2. Updating transfer status: Change the transfer's status to 'Recorded' once approved.
3. Modifying compliance balances: Adjust the compliance units balances of the transferor and transferee organizations accordingly.
4. Recording transaction history: Save a record of the transaction in the database, noting the date and the Director's involvement under the Low Carbon Fuels Act.
5. The applied transactions need to be created for each supplier
6. Ensuring data consistency and integrity throughout the transaction process.

**Purpose and Benefit to User (Backend Perspective):**
This backend development enables the secure and accurate recording of transfers in the LCFS system, ensuring that only authorized users (Directors) can approve transfers. It maintains the integrity of transaction records and compliance balances, crucial for regulatory compliance and accurate reporting.

**Acceptance Criteria (Backend):**

- [ ] Given I am a user with the Director role, When I click the 'Record transfer' button on the frontend, then the backend should validate my role and process the transfer.
- [ ] Given a transfer is approved by a Director, When the transfer recording process is triggered, then the backend should update the transfer status, adjust compliance balances, and record the transaction history accurately.

**Development Checklist (Backend):**

- [ ] Implement role verification to restrict the transfer recording method to Director users.
- [ ] Develop logic to update the transfer status to 'Recorded' upon Director approval.
- [ ] Code the adjustment of compliance balances for the involved organizations.
- [ ] Create functionality to record the transaction history with the necessary details.
- [ ] Conduct thorough testing to ensure data integrity and correct role-based access.

**Notes:**

- Pay special attention to transactional integrity, ensuring that all parts of the transfer process are completed atomically to maintain data consistency.
- Rigorous testing is required to confirm that the method correctly handles different scenarios, including edge cases and role-based access control. Backend pytests and end to end tests should cover all business logic.
- Ensure thorough logging and error handling for monitoring and troubleshooting purposes.
- Collaboration with frontend developers is essential to ensure seamless integration and triggering of the backend process.

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/325?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing to test

**Comment by justin-lepitzki** [comment]
Need to wait for some work to be completed before we can test balance changes. Currently there is no balance information in LCFS portal, only demo data.
