### ISSUE TITLE
LCFS - Implement Frontend Features for Director's Transfer Approval in LCFS System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#326]
**Description:**
Develop frontend features to enable Directors to approve transfers within the LCFS system. This will involve creating a user interface that allows Directors to record transfers effectively and securely. Key elements include:

1. Displaying the 'Record transfer' button only to Government users with the Director role and when the transfer status is 'Recommended'.
2. Positioning the 'Record transfer' button in the bottom right-hand corner of the page.
3. Implementing a confirmation modal window that appears upon clicking the 'Record transfer' button. Message should ask "Are you sure you want to record this transfer?"
4. Providing a cancel option in the modal window to return the user to the view transfer screen.
5. Handling the process after the 'Record transfer' button in the modal window is clicked: displaying a success message, returning the user to the transaction page, highlighting the transaction row for the transfer, and updating the transfer status to 'Recorded'.
6. Reflecting the compliance balance changes in the UI.
7. Displaying the transaction history record in the UI, including the recording date and the involvement of the director under the *Low Carbon Fuels Act*. Note that for BCeID users we want to display a generic message about the director under the Act whereas for IDIR users we want to display the actual name of the person with the director role that clicked the approve button (see wireframes)
8. Ensuring the transaction history is visible to both BCeID and IDIR users.
9. Updating the transfer breadcrumb on the view page to the 'Recorded' state.

**Purpose and Benefit to User:**
This frontend development will provide a seamless and intuitive interface for Directors to approve transfers. It enhances the workflow efficiency and ensures that the approval process is transparent and accessible to authorized users.

**Wireframes:**
- Recorded transfer (IDIR view): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112777/simulate/sitemap
- Recorded transfer (BCeID view): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112783/simulate/sitemap

**Acceptance Criteria:**

- [x] Given I am a user with the Director role, when I view a transfer with a 'Recommended' status, then the 'Record transfer' button should be visible.
- [ ] Given I click the 'Record transfer' button, when the confirmation modal appears and I confirm the action, then the transfer should be marked as 'Recorded', and the relevant updates should be reflected in the UI.

**Development Checklist:**

- [ ] Implement the visibility and functionality of the 'Record transfer' button based on user role and transfer status.
- [ ] Create the confirmation modal window with appropriate options and integrate it with the transfer action.
- [ ] Manage the UI updates post-transfer approval, including success messages, transaction page redirection, and status updates.
- [ ] Ensure responsive and intuitive design for all relevant components, in line with the provided wireframes.

**Notes:**

- Close collaboration with the backend developer is necessary to ensure proper integration with the backend services.
- Testing is required, especially focusing on role-based access and the correct updating of the UI post-transfer approval.
- Ensure adherence to the design and usability standards as per the wireframes and UI/UX guidelines.

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/326?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
The 'Record transfer' and 'Refuse transfer' buttons are clickable to government users with non-Director roles. Screenshot of a Recommended transfer with a user having the analyst and administrator roles (no Director role): [Screenshot](https://github.com/bcgov/lcfs/assets/131904954/da57c62a-361e-48b3-889b-a9945233f66d). Buttons are clickable for other government roles as well, such as Compliance Manager. 

User with the Director role are seeing two Record buttons: [Screenshot](https://github.com/bcgov/lcfs/assets/131904954/dd77f3c9-dc55-4a57-87b7-761b05aff3c7). Clicking the left side button just takes the user back to the Transactions page; no other action happens to the transfer (e.g., status remains as Recommended). 

Other comments: 
- Transaction history record is not visible in the UI. Showing demo data. I believe #478 will handle viewing this information in the UI. 

- Unable to confirm that balances are actually changing as they are not visible in the UI. Do we need to wait for the completion of some cards, such as #409 #156 ? I see the Organization table for IDIR users is still showing dummy data. This card cannot be marked as complete until we can verify balance changes in the UI, as it is a critical component of this card.

**Comment by prv-proton** [comment]
> 
Record and Refuse buttons configs have been resolved, but other comments remain unresolved.

**Comment by Grulin** [comment]
When viewing a transfer as an IDIR user, the preview balances are not up to date. For example, LCFS Org 6 currently has 50,000 CU but it is showing the preview is currently showing the same balance information as the organization that proposed the transfer. We would like the organization accepting the transfer to have an accurate balance reflected in these previews for the IDIR user to review. Please see screenshot:

![Image](https://github.com/bcgov/lcfs/assets/156380046/1154eba5-87b3-4e08-8906-9d54eeeb0479)


*Can confirm that the balances **are** changing for the two organizations upon director recording of the transfers when logging in on BCeID side for both organizations.
