### ISSUE TITLE
LCFS - Director records a transfer - Frontend UI/UX

### ISSUE THREAD

**Issue by prv-proton** [bcgov/lcfs#327]
**Description:**
Develop the ability for the Director to record (i.e., approve) a transfer:

- Record transfer button visible to Government users with the Director role when the transfer has a status of 'Recommended'
- 'Record transfer' button in the bottom right-hand corner of the page.
- Clicking on the 'Record transfer' button brings up a confirmation modal window.
- Clicking the cancel button in the modal window brings the user back to the view transfer screen.
- Clicking on the 'Record transfer' button in the modal window
1. brings up a success message/alert/modal
2. the user is returned to the transaction page
3. the transaction row for the transfer is highlighted,
4. the transfer status is changed to Recorded.

- The transfer breadcrumb within the view page is updated to the Recorded state (visible to all users).
- Success alert message using Material UI: https://mui.com/material-ui/react-alert/

**Confirmation Modal Messaging:**
- Are you sure you want to record this transfer? 

**Wireframe:**

- Director view of recommended transfer: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165001091/simulate/no-panels
- IDIR user view of recorded transfer: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112777/simulate/no-panels
- BCeID user view of recorded transfer: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165112783/simulate/no-panels
- Confirmation model window messaging example (TFRS): <img width="1693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4136700303182172bddcb3feba5e22ab52d60b20/Screenshot%202024-01-17%20085937.png" alt="Screenshot 2024-01-17 085937.png" />

**Purpose and benefit to user:**
Ability for the director to record (approve) transfers, thus ending the workflow / processing of a transfer. 

**Acceptance Criteria:**

- [ ] 'Record transfer' button is displayed in the correct location for Government users with the Director role.
- [ ]  Clicking on the 'Record transfer' button opens a confirmation modal window.
- [ ]  Clicking the cancel button in the modal window returns the user to the view transfer screen.
- [ ]  Clicking on the 'Record transfer' button in the modal window displays a success message/modal.
- [ ]  The transaction page is updated with the highlighted transaction row and the transfer status changed to Recorded.
- [ ]  The transfer breadcrumb is updated to the Recorded state.
- [ ]  Frontend unit tests cover the functionality of the 'Record transfer' button.
- [ ]  Modal window accessibility is ensured for screen readers and keyboard navigation.
- [ ]  Frontend tests verify the correct display of success messages and the updated UI.

**Development Checklist:**

- [ ]  Implement 'Record transfer' button functionality.
- [ ]  Develop the confirmation modal window.
- [ ]  Implement success message/modal upon recording.
- [ ]  Update the transaction page UI based on recording.
- [ ]  Update the transfer breadcrumb UI.
- [ ]  Integrate Material UI for success alerts.
- [ ]  Write frontend unit tests for 'Record transfer' button functionality.
- [ ]  Ensure modal window is accessible for screen readers and keyboard navigation.
- [ ]  Write frontend tests for success message display and updated UI.

**Comment by justin-lepitzki** [comment]
Duplicate
