### ISSUE TITLE
METABASE - migrate existing metabase data to new instance

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#330]
**Describe the task**

- Card # 247 investigated the migration of metabase data to a new instance: https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/lcfs/247
- From the investigation work, we identified a method for migrating all the sqls, models, and dashboards from the existing instance of Metabase to the new instance

**Migration of Metabase:**

Following observations have been made from local setup of Metabase and migration to new instance.

By copying the pg_dump of metabase data to the new instance we can retrieve all the sqls, models and dashboards.
New instance should be connected to the new db or existing tfrs db where the pg_dump has been copied to.
metabase: image: metabase/metabase:latest ports: - 3001:3000 environment: - MB_DB_TYPE=postgres - MB_DB_DBNAME=tfrs - MB_DB_PORT=5432 - MB_DB_USER=user - MB_DB_PASS=password - MB_DB_HOST=db
After copying the data ensure to reset the database connection and delete the ZEVA, ITVR and other unwanted collections and database connections.
New instance will continue to have all the users from the old instance while retaining the passwords too. Ensure deleting them as an Admin user.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/330?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton
