### ISSUE TITLE
LCFS - Implement frontend features for in reserve compliance units

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#333]
**Description:**
Card #343 develops the backend service for the in reservce compliance units feature. This card is to implement the front end features in the UI.
 
The in reserve balance is always shown in parentheses next to an organization’s compliance balance:
- For BCeID users, the balance is shown in the top banner and on the dashboard.
- For IDIR users, an organization's balance is shown on the dashboard, on the organizations page within the organization table, when processing a transfer (within the graphic), on the transactions page when filtering by organization, and on the organization details page. 

**Wireframe:** <link>

**Purpose and benefit to user:**
Displaying the in reserve balance in the UI informs the user how many compliance units are awaiting the completion of a transaction and/or assessment of a compliance report. It also lets the user know how many compliance units they have available for other uses. 

**Acceptance Criteria:**

- [x] Given I am a BCeID user, when I log in to the system, I should see the in reserve balance in the top banner and on the dashboard.
- [x] Given I am a IDIR user, when I log in to the system, I should see the organization’s balance on the dashboard, on the organizations page within the organization table for each respective organization, when processing a transfer (within the graphic), on the transactions page when filtering by organization, and on the organization details page.

**Development Checklist:**

- [x] Ensure the backend service for the in reserve compliance units feature is already present.
- [x] Develop the front-end features in the UI.
- [x] Ensure that the in reserve balance is always shown in parentheses next to an organization’s compliance balance.
- [x] For BCeID users, display the balance in the top banner and on the dashboard.
- [ ] For IDIR users, display the organization’s balance on the dashboard, on the organizations page within the organization table, when processing a transfer (within the graphic), on the transactions page when filtering by organization, and on the organization details page.

**Notes:**

**Comment by AlexZorkin** [comment]
The majority of this work has been completed in previous tickets so we just need to ensure the requirements are all met.

**Comment by AlexZorkin** [comment]
- There is no org balance for government so "display organization’s balance on the dashboard" doesn't apply to the IDIR side.
- Organization List view is being worked on in a different ticket which will complete the org balance work
- Transfer balance graphics are now working
- Organization filtering is being worked on in the other ticket
- Balances added to organization view for idir users

**Comment by Grulin** [comment]
Test when card #507 and card #543 have been completed.
