### ISSUE TITLE
LCFS- Transaction progress breadcrumb for new transaction page

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#344]
**Description:**

- Add a progress tracking breadcrumb to the new transaction page.
- Statuses to include in breadcrumb for IDIR users: Draft > Recommended > Approved
- Default view for a newly created transaction is that the progress bar is greyed out. Progress will begin tracking when the user saves a draft or recommends the transaction to the director (i.e., at a point when the transaction is created and assigned an ID #). 

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165244297/simulate/sitemap

**Purpose and benefit to user:**

Enables the government analyst user to track the progress of a transaction and understand where it currently resides in terms of processing /completion

**Acceptance Criteria:**

- [x] Given I am a IDIR user, When I am clicking new transaction, then in the new transaction page I should be able to see the progress bar and update the steps as the status is changed.
- [x] Given I am a BCeID user, I shouldn't be able to see the new transaction page.

**Development Checklist:**
- [ ] Add a progress tracking breadcrumb to the new transaction page with the steps Draft, Recommended and Approved for IDIR users.
- [ ] By default progress bar should be greyed out
- [ ] When the user saves the Draft then Draft step is highlighted
- [ ] Ensure the transaction page is visible to government analyst users.

**Notes:**

**Comment by justin-lepitzki** [comment]
@Grulin Added a third bullet for additional clarity around the default view for the breadcrumb. The wireframe captures this but I mention it more explicitly so that the requirements are clear.
