### ISSUE TITLE
LCFS- Director comments to the organization on new transaction page

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#346]
**Description:**
To implement the comment feature on the new transaction page:

- Text input field for director comments (will be visible to both the organization and government upon director approval)
- Field is optional
- Field is collapsible
- By default, the field is collapsed

**Wireframe:**
Collapsed: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165244297/simulate/sitemap

Open for comment:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300444/simulate/sitemap

**Purpose and benefit to user:**
Allows the IDIR user with director or analyst roles to input and edit relevant information about the transaction that will be visible to organization and government.

**Acceptance Criteria:**

- [x] Given I am an IDIR user with director or analyst role, When I navigate to the new transaction page, Then I see a collapsible text input field for director comments.
- [ ] Given I am an IDIR user with director role, When I click on the collapsed comment field, Then the field expands allowing me to input comments.
- [ ] Given I am an IDIR user and I have inputed comments, When the transaction is approved, Then the transaction is visible to the organization and government.
- [ ] Given I am an IDIR user, When I navigate to the new transaction page for the first time or refresh the page, Then the comment field is collapsed by default.

**Development Checklist:**
- [ ] Create a text input field for director comments on the new transaction page. 
- [ ] Ensure the field is optional and does not block form submission if left empty.
- [ ] Implement logic to make the comment field collapsible.
- [ ] By default, the field should be collapsed.
- [ ] Ensure that once director approves transaction, the comments are visible to both the organization and government users.

**Comment by justin-lepitzki** [comment]
@Grulin revised one of the bullets for additional clarity. These transactions will only become visible to the external organization upon approval; wanted to avoid the potential for a developer to misunderstand the bullet to mean it should be visible right away. Unlikely to happen but it doesn't hurt to provide this detail / clarity. 

Original: Text input field for director comments (visible to the organization and government)
Revised: Text input field for director comments (will be visible to both the organization and government upon director approval)

**Comment by Grulin** [comment]
Unable to comment in the 'director comments to the organization' box. It highlights when I select the box, but when I start to type, nothing shows up in the box.

**Comment by Grulin** [comment]
Government comments to organizations (option) box should be collapsed by default. Currently it is expanded when you first open the transfer and expanded still if you refresh the page or navigate away and return. We would like this field to always be collapsed by default unless the user expands it to make a comment.

**Comment by hamed-valiollahi** [comment]
@Grulin, thank you for testing!

I've resolved the issue you mentioned. By default, the director comment is now collapsed on new transaction page. However, in certain cases, such as a transaction in draft status, when you open it from Transaction list, the comment section will expand only if the IDIR user has previously entered something in it. Otherwise, it will remain collapsed.

Thank you!
