### ISSUE TITLE
LCFS- Internal comments feature on new transaction page create update functionality

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#347]
**Description:**
To implement the internal comment feature on the new transaction page (not visible to outside organizations, only visible to government users):

- card #259  & #312  were to develop the internal commenting component that we will want to use in multiple features in the LCFS portal
- card #329 integrates the comment module into the transfers feature
- This card is to implement this component within the new transaction feature, the create and update functionality, but with a slight modification.
- Modification: removal of the add comment button when first creating a new transaction (see wireframe below); comment saves upon saving a draft or recommending transaction (i.e., when the transaction is created / saved to the database and assigned a unique ID#) rather than when clicking the add comment button. This modification is necessary because we cannot save a comment in the database until the transaction gets created, which doesn't happen until the gov't analyst user saves it as a draft or recommends it to the director. 

**Wireframe:**
Initial transaction creation internal comment (does not have a 'new comment' button):
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165244297/simulate/sitemap

Commenting after transaction has been saved (includes the 'new comment' button after the transaction has been created):
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300444/simulate/sitemap

Example of a saved comment from an analyst: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300924/simulate/sitemap

**Purpose and benefit to user:**
Allows the IDIR user to input relevant information about the transaction that will be visible only to government users. Mainly used to support your recommendation of the transaction, such as supporting information or reference # to documents in EDRMS. 

**Acceptance Criteria:**

- [ ] Given I am a IDIR user, When I am on the first step of the new transaction page, then the internal comments component should be shown WITHOUT the 'Add Comment' button
- [ ] Given I am a IDIR user, When I am NOT on the first step of the new transaction page, then the internal comments component should be shown WITH the 'Add Comment' button

**Development Checklist:**
- [ ] use the prebuild comment component
- [ ] no 'Add comment' button on the first step
- [ ] 'Add comment' button on the other steps

**Notes:**
- [ ] may need to modify the comment component to accommodate the conditional button

**Comment by justin-lepitzki** [comment]
@Grulin Looks good. I realized that I pointed you to the incorrect card in our tracking sheet (should have been #329, not #319 which is what I listed originally). I modified this card to point the developer to the creation of this reusable component (#259, 312). We will likely refine #329 in our backlog refinement session; we should modify this card if there are changes that are required for #329, since they are both related to implementing the reusable internal commenting component within different features of the application

**Comment by Grulin** [comment]
The add comment button is gone and I am able to add an internal comment, but nothing happens when I select 'Save draft' or 'Recommend'. Please see screenshot for inspect information:


![Image](https://github.com/bcgov/lcfs/assets/156380046/1c62d0c7-1534-474c-a155-d443edb2bdd4)

The page error seems to be happening even before I type anything in to the internal comments box.

**Comment by hamed-valiollahi** [comment]
@Grulin, thanks, Lindsy, for testing!

Sorry! I had to leave a comment to inform you that some functionalities will be implemented later. They are part of the tickets assigned to Alex for this sprint. The focus of this ticket was to implement mostly the user interface and the base functionalities for the developer who will be working on this feature.

You can assume that the issue will be resolved with the tickets [#349](https://github.com/bcgov/lcfs/issues/349) and [#351](https://github.com/bcgov/lcfs/issues/351).

Thank you

**Comment by Grulin** [comment]
Awesome. Thanks for clarifying, @hamed-valiollahi. I appreciate it. Will move back to on dev and test again once the other tickets are completed.

**Comment by Grulin** [comment]
Now that card #349 and #351 have come down the pipeline, I attempted to test this feature but unfortunately is it missing on the transaction page now:

![Image](https://github.com/bcgov/lcfs/assets/156380046/ebaa3e84-4aab-4840-962f-cfb179e596ad)

**Comment by hamed-valiollahi** [comment]
@Grulin Thanks for testing, Lindsy. I fixed the issue, and the internal commenting feature should now work fine.
