### ISSUE TITLE
LCFS - Edit draft transaction

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#350]
**Description:**
Creating the ability to edit a draft transaction. Once a new transaction is saved as a draft, the user can edit again on the current page or return to the main 'Transactions' page. If a user then clicks on the draft transaction in the transaction table:

- They are taken to the edit transaction screen, which is the same as the new transaction screen but with the user inputted details of the transaction already pre-populated in the different input fields.
- The user is able to change these input values and save as a draft, which will overwrite the previously saved input data.
- The IDIR user is able to recommend the transaction if they have the right role (government analyst).
- The transaction type and transaction ID is visible in the title at the top of the page.
- Only users with the IDIR government analyst role can edit the details of a transaction.

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300444/simulate/sitemap

**Purpose and benefit to user:**
A single IDIR government analyst user or various IDIR government analyst users can edit transactions before recommending them. Allows for others to add additional information to expedite processing or a peer review process if needed.

### Acceptance Criteria

1. **Given** I am an IDIR user with the government analyst role,
   **When** I save a new transaction as a draft,
   **Then** I can edit it again on the current page or return to it from the main 'Transactions' page.
2. **Given** I am an IDIR user with the government analyst role,
   **When** I click on a draft transaction in the transaction table,
   **Then** I am taken to the edit transaction screen, where the details are pre-populated for editing.
3. **Given** I am editing a draft transaction,
   **When** I change input values and select save as a draft,
   **Then** the changes overwrite the previously saved input data.
4. **Given** I am an IDIR user with the government analyst role and editing a draft transaction,
   **When** I have the necessary permissions,
   **Then** I am able to recommend the transaction for further action.
5. **Given** I am on the edit transaction screen,
   **When** I view the screen,
   **Then** the transaction type and ID are visible in the title at the top of the page.
6. **Given** I am a user without the IDIR government analyst role,
   **When** I attempt to edit the details of a transaction,
   **Then** I am unable to make changes or the option to edit is not available.

### Development Checklist

- [ ] **Implement Edit Transaction Screen**
  - Use the same UI components as the 'New Transaction' screen but modify the state to handle pre-populated data.
- [ ] **Data Pre-population**
  - Ensure the edit transaction screen fetches and displays the existing data for the selected draft transaction.
- [ ] **Save/Edit Functionality**
  - Implement functionality to save changes made to a draft transaction, overwriting the previously saved data.
- [ ] **Role-Based Access Control**
  - Confirm only IDIR users with the government analyst role can edit transactions. Implement checks both on the frontend and backend.
- [ ] **UI Indicators for Transaction Type and ID**
  - Display the transaction type and ID prominently at the top of the edit transaction page as a reference for the user.
- [ ] **Testing**
  - Write unit and integration tests covering the new functionalities, including role-based access, data pre-population, and the save/edit process.

### Notes
- Backend adjustments might be required to support fetching, editing, and saving draft transactions, as well as handling permissions for recommending transactions.

**Comment by justin-lepitzki** [comment]
@Grulin looks great!

**Comment by Grulin** [comment]
When editing an initiative agreement transaction, the transaction ID is not showing in the UI:

![Image](https://github.com/bcgov/lcfs/assets/156380046/b5a2249e-6418-451b-883e-fd49bd9f9661)

**Comment by AlexZorkin** [comment]
This was a caching issue that is now fixed.
