### ISSUE TITLE
LCFS - View Transaction page

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#354]
**Description:**
This screen will display various details about a transaction after it is no longer in an editable state (i.e., has been recommended by the analyst). The design of this screen must reflect these changes and provide the necessary information in a clear and accessible manner.

Key Features:

- Transaction details are displayed but are no longer editable.
- Explanatory text regarding the effective date persists.
- The organization's compliance balance is displayed, including in reserve in parentheses
- The progress breadcrumb indicates the blue 'Recommended' stage.
- A description of the pending transaction is prominently displayed, including compliance units, effective date and comments.
- The chosen transaction type and assigned transaction ID are visible at the top of the page.
- An internal comment section for users to view and add comments (handled in a different card #347 )
- A transaction history section showing all relevant transaction activities, stamped with the date and the name of the recommending analyst.
- An effective date left blank will default to date of approval by director

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300924/simulate/sitemap

**Purpose and benefit to user:**
This view screen is essential for IDIR users to monitor and manage pending transactions. It serves as the central interface for the director to review and approve transactions, and for IDIR government analyst users to understand the current status of the transaction.

To complete the sprint ticket for the "View Transaction" page, let's flesh out the Acceptance Criteria and Development Checklist based on the provided details. 

***Acceptance Criteria***

1. **Given** I am an IDIR government analyst, **When** I view a transaction that has been recommended, **Then** I should see the transaction details displayed in a non-editable format, including compliance units, effective date, comments, transaction type, and transaction ID.

2. **Given** I am an IDIR government analyst, **When** I view the transaction screen, **Then** the progress breadcrumb should indicate the 'Recommended' stage in blue. Make sure this component uses status to determine which breadcrumb to highlight, just use dummy data with status equal to Recommended for now.

3. **Given** I am a director, **When** I approve a transaction with an effective date left blank, **Then** the effective date should automatically set to the date of my approval.

4. **Given** I am an IDIR user, **When** I access the transaction view screen, **Then** I should be able to view the transaction history with dates and names of the recommending analysts and add/view internal comments.

5. **Given** I am an IDIR user, **When** I am on the View Transaction page, **Then** I should see explanatory text regarding the effective date if it has been set or if it defaults due to director approval.

***Development Checklist***

- [x] **A. Implement Transaction Details UI:** Ensure the transaction details (compliance units, effective date, comments, transaction type, transaction ID) are displayed as per the wireframe and are not editable.
  
- [x] **B. Progress Breadcrumb Implementation:** Implement the progress breadcrumb UI to reflect the 'Recommended' stage in blue as per the design.

- [x] **C. Effective Date Logic:** Implement logic to default the effective date to the director's approval date if left blank.

- [x] **D. Transaction History Section:** Implement a section to display the transaction history, including dates and names of recommending analysts.

- [x] **E. Role-based Display Logic:** Ensure that the UI elements and functionalities are correctly displayed based on the user's role, especially for directors and government analysts.

- [x] **F. Testing for Accuracy and Up-to-dateness:** Create tests to verify that all displayed information is accurate and reflects the most current data, especially in the transaction history section.

- [x] **G. User Role Management:** Implement and test user role management to ensure correct display of buttons and functionalities for different user roles.

**Notes:**

- The development team should work closely with the UI/UX designers to ensure the screen layout matches the provided wireframe.
- Special attention should be given to user role management to ensure the correct display of buttons and functionalities.
- Testing should include verifying that all information displayed is accurate and up-to-date, especially in the transaction history section.

**Comment by Grulin** [comment]
Hi @airinggov, do you think we need this requirement on this card? It wasn't included in the wireframe, so I'm wondering if we decided against this in later version:

- The organization's compliance balance is displayed, including in reserve in parentheses

**Comment by Grulin** [comment]
A initiative agreement transaction does not show the transaction id number anymore once it has been deleted:

![Image](https://github.com/bcgov/lcfs/assets/156380046/f9e63e07-6d7b-4973-945f-c0bb08857572)

The admin adjustment transaction does show the transaction id number once it's been deleted, so I think we want the IA one to be the same.

**Comment by airinggov** [comment]
When a transaction is approved and the Effective date was left blank it should display the same date shown below as Approved on.

**Comment by AlexZorkin** [comment]
I updated initiative agreement and admin adjustment to set the effective date properly now to the approval date when its left blank by the user.

**Comment by airinggov** [comment]
The Recommend button is available to the Director role but should only be available to the Analyst and Compliance Manager
