### ISSUE TITLE
LCFS - Transactions page throwing unexpected application error

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#362]
**Describe the Bug**
Unexpected application error screen when navigating to the Transactions page. 

Screenshot of error page: 
![Image](https://github.com/bcgov/lcfs/assets/131904954/1cc995fb-6f1f-4e15-b84e-b34744ac7bd1)

Log of console errors: 
[lcfs-dev.apps.silver.devops.gov.bc.ca-1707153662335.log](https://github.com/bcgov/lcfs/files/14169030/lcfs-dev.apps.silver.devops.gov.bc.ca-1707153662335.log)

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user
1. Go to 'Transactions' page on main nav bar
2. See error

**Comment by Grulin** [comment]
Similar error showing, but instead of "FFt is not a function" now it shows "tLt is not a function". Please see screenshot:


![Image](https://github.com/bcgov/lcfs/assets/156380046/cfdccb92-1bfc-4df4-97c4-f504a7f0f89c)
