### ISSUE TITLE
Metabase - Implement last report logic into Exclusion (Allocation) Agreement query

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#363]
**Describe the task**
Implement the latest report logic that is used in the 'Fuel Supply Data' model in Metabase into the 'Exclusion (Allocation) Agreement' SQL query. That is, when more than one exclusion (allocation) report exists for an organization for a particular compliance period, only show the latest report. The latest report is the most recent report, either the original (if no supplemental reports exist) or the latest supplemental (if one or more supplemental reports exist). Note that we also want to exclude reports with the following states/statuses: draft, deleted, rejected. 

This "latest report" logic was implemented in the 'Fuel Supply Data' model that exists in Metabase. We want to mirror this logic in the 'Exclusion (Allocation) Agreement' SQL query (and then turn it into a model). 

**Purpose**
The latest report logic is used to filter out duplicate / multiple reports for an organization within a specific compliance period. Without this logic, the query duplicates reported information by showing all of the reports from an organization for a specific compliance period: original report plus any supplemental reports. This leads to inaccurate data analyses because duplicate entries mean incorrect volumes and transactions. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Metabase link: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/
- 'Exclusion (Allocation) Agreements' SQL query: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/question/274-exclusion-allocation-agreements
- 'Fuel Supply Data' model: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/model/192-fuel-supply-data

**Comment by justin-lepitzki** [comment]
Adding link to query for review: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/question/398-exclusion-allocation-agreements-latest-reports

**Comment by justin-lepitzki** [comment]
Original query for reference: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/question/274-exclusion-allocation-agreements

**Comment by Grulin** [comment]
Reviewed new query to see why supplemental reports were duplicating and if they were all being duplicated. Can confirm the following:

1) All exclusion reports that have one supplemental report are pulling a duplicate entry (of the final report submitted for both). 
2) All exclusion reports that have multiple supplemental reports are pulling the final report the number of times a supplemental report was submitted for that organization/year. For example, if a company submitted one original and 2 supplemental reports, the query is showing 3 identical lines of the data from the final submitted report. 
3) All exclusion reports that only have the original submission (no supplemental reports submitted) are pulling only one line of data. 



![Image](https://github.com/bcgov/lcfs/assets/156380046/9012405e-0ef6-4673-8891-4a0a223b75a5)



Please find attached a highlighted spreadsheet. Yellow highlights represent the first original entry, blue are any duplicated lines of data. 



[Exclusion (Allocation) Agreements review.xlsx](https://github.com/bcgov/lcfs/files/14423161/Exclusion.Allocation.Agreements.review.xlsx)

**Comment by AlexZorkin** [comment]
I added some logic to only pull the latest report in the chain by taking the max traversal number report.

**Comment by Grulin** [comment]
Skimmed new table to see if it matches exclusion reports listed in TFRS. I collapsed all these down to one report per year per company (as they report all these sold and purchased under one exclusion agreement id). Checked 2019 and noticed 4 reports not listed on the Metabase table, but they are listed in TFRS. I searched for a pattern of why these reports might have been excluded from the pull, but can't see anything obvious. 3 out of 4 of them are small reports with one line and small volume. Going to look over 2020 reports now.

**Comment by AlexZorkin** [comment]
I fixed a race condition between report types that was causing some exclusion reports to be excluded from the results.

**Comment by justin-lepitzki** [comment]
@Grulin that's a great idea, to show a similar "current status" column as in the Fuel Supply model. I think we should create a new card for that work. I could even take a look and see if I can figure out how to add it. We should create the card regardless, to track this work.
