### ISSUE TITLE
LCFS - Delete draft transaction

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#365]
**Description:**
The ability to delete a draft transaction:

- When viewing a draft transaction
- There is a Delete Draft button
- Clicking on the button brings up a confirmation modal window
- Clicking on the Cancel button within the modal window takes the user back to the draft transaction
- Clicking on the Delete draft button deletes the draft (i.e., hides it in the UI) and takes the user back to the Transactions page; the transaction is no longer visible in the Transactions table
- A success alert should appear (alert from Material UI: https://mui.com/material-ui/react-alert/)
- Users must have the government analyst role to delete draft transactions
- Once draft is deleted it should change it status in delete in DB and shouldn't display on UI.

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300444/simulate/no-panels

**Purpose and benefit to user:**
IDIR user with the government analyst role can delete draft transaction if they no longer wish to execute the transaction.

**Acceptance Criteria:**

- [x] Given I am a IDIR user with government analyst role, When I am clicking on the delete button for the draft transaction, then this issuance/transaction should be updated with status as deleted.
- [ ] Given I am a IDIR user with government analyst role, When I the transaction is in recommended status then I shouldn't be able to see the delete button.

**Development Checklist:**
- [ ] Update the status of the issuance to delete. Make use of the common status update endpoint.
- [ ] Handle UI to display the delete button based on the transaction status.
- [ ] Handle the mui snackbar to display the appropriate message and navigate back to transactions page.
- [ ]  D. Transaction History Section: Implement a section to display the transaction history, including dates and names of recommending analysts.

 E. Role-based Display Logic: Ensure that the UI elements and functionalities are correctly displayed based on the user's role, especially for directors and government analysts.

 F. Testing for Accuracy and Up-to-dateness: Create tests to verify that all displayed information is accurate and reflects the most current data, especially in the transaction history section.

 G. User Role Management: Implement and test user role management to ensure correct display of buttons and functionalities for different user roles.

**Notes:**

**Comment by Grulin** [comment]
A initiative agreement transaction does not show the transaction id number anymore once it has been deleted:


![Image](https://github.com/bcgov/lcfs/assets/156380046/855f226b-ed35-4112-b326-f7fd139c7648)


The admin adjustment transaction does show the transaction id number once it's been deleted, so I think we want the IA one to be the same.

**Comment by airinggov** [comment]
After deleting the transaction the user should be redirected to the index page.

**Comment by AlexZorkin** [comment]
Deleted records will not show in the transactions list anymore, and after deleting, the user will be directed back to the list view.
