### ISSUE TITLE
LCFS - Implement Frontend Features for Director's Transaction Approval

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#367]
**Description (Front-end focus):**
Develop front-end features to enable users with the director role to approve transactions (e.g., admin adjustment, initiative agreement) within the LCFS portal. This will involve creating a user interface that allows directors to approve transactions effectively and securely. Key elements include:

1. Displaying the 'Approve' button only to IDIR Government users with the 'director' role and when the transaction status is 'Recommended'.
2. Positioning the 'Approve' button in the bottom right-hand corner of the page.
3. Implementing a confirmation modal window that appears upon clicking the 'Approve' button.
4. Providing a cancel option in the modal window to return the user to the view transaction screen.
5. Handling the process after the confirmation button in the modal window is clicked: displaying a success message, returning the user to the transaction page, highlighting the transaction row for the transaction, and updating the transaction status to 'Approved'.
6. Reflecting the compliance balance change in the UI.
7. Displaying the transaction history record in the UI, including the approval date and the involvement of the director under the *Low Carbon Fuels Act*. Note that for BCeID users we want to display a generic message about the director under the Act whereas for IDIR users we want to display the actual name of the person with the director role that clicked the approve button (see wireframes)
8. Updating the transaction breadcrumb on the view page to the 'Approved' state.

**Wireframe:**
Approve button available:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165555412/simulate/sitemap

View once approved:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165555421/simulate/sitemap

**Purpose and Benefit to User:**
This frontend development will provide a seamless and intuitive interface for directors to approve transaction. It enhances the workflow efficiency and ensures that the approval process is transparent and accessible to authorized users.

**Acceptance Criteria:**

- [x] Given I am a Director, when I visit a 'Recommended' transaction page, Then an 'Approve' button should be visible in the bottom right-hand corner.
- [x] Given I am a Director, after clicking the 'Approve' button, when the action is confirmed in the modal window, then the transaction should be marked as 'Approved', with a success message displayed, and the UI updated accordingly.
- [ ] Given I am a Director, when a transaction is approved and I'm viewing the transaction details, then the compliance balance and transaction history should update, showing the approval details relevant to the user's role (BCeID or IDIR).

**Development Checklist:**
- [ ] Develop a modal component for approval confirmation with confirm and cancel options.
- [ ] Ensure the UI reflects the transaction's approved status, updates the compliance balance, and shows the correct transaction history.
- [ ] Conduct role-based access tests and integrate closely with backend services for transaction processing.

**Notes:**

- Issue #366 is for the back-end service for director approving transactions
- Close collaboration with the backend developer is necessary to ensure proper integration with the backend services.
- Testing is required, especially focusing on role-based access and the correct updating of the UI post-transaction approval.
- Ensure adherence to the design and usability standards as per the wireframes and UI/UX guidelines.

**Comment by Grulin** [comment]
After an IDIR director approves a transaction, they should be returned to the "Transactions" table view page and the transaction they just approved should be highlighted.

**Comment by AlexZorkin** [comment]
added this logic.
