### ISSUE TITLE
LCFS - Implement Shell Script for Re-Seeding Dev Database

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#372]
**Description:** Develop a shell script that automates the process of downgrading the development database, upgrading it again with our Alembic DB library, and then re-running the existing seeders. This script will streamline resetting the database to a known good state for testing purposes.

**Purpose and benefit to user:** This tool will significantly improve the development workflow by providing a quick and reliable way to reset the development database to its ready testing state. It will save time for developers and testers by automating the tedious process of database reseeding, making it easier to test new features and bug fixes on a clean slate.

**Acceptance Criteria:**

- [ ] Given I am a developer, When I run the shell script from my local environment, then the development database is downgraded successfully.
- [ ] Given I am a developer, When the database downgrade is complete, then the script automatically upgrades the database using the Alembic DB library.
- [ ] Given I am a developer, When the database upgrade is complete, then the script re-runs the seeders to populate the database with the necessary data for testing.
- [ ] Given I am a developer, When I execute the script, then it completes without errors and the database is in a ready state for testing within a reasonable timeframe.

**Development Checklist:**
- [ ] A. Create the shell script with commands to downgrade the database.
- [ ] B. Integrate Alembic commands into the script to handle database migrations.
- [ ] C. Incorporate existing seeders into the script to repopulate the database after migration.
- [ ] D. Test the script to ensure it works as expected across different environments.
- [ ] E. Document the script usage in the project README for easy access by all team members.

**Notes:**
- Ensure the script is compatible with all operating systems used by the development team.
- Consider adding error handling in the script to manage any issues that arise during the downgrade, upgrade, or seeding processes.
- The script should verify that all steps have been completed successfully before exiting.
- Include a rollback mechanism in case any step of the process fails, to prevent the database from being left in an inconsistent state.

**Comment by Grulin** [comment]
Nothing to test on business area side.
