### ISSUE TITLE
LCFS - Implement Organization Balance Management and Adjustment Functionality

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#374]
**Description:** This enhancement adds functionality to manage organization balances more dynamically, including creating the `organization_balance` table, introducing service methods to get and adjust balances, and updating supplier seeders with initial compliance unit balances. The new service method will allow for both increments and decrements to an organization's balance, accommodating transactions that either add to or subtract from compliance units.

**Purpose and Benefit to User:** This feature streamlines the management of compliance units within the system, providing administrators and automated processes the ability to quickly access and adjust organization balances. This capability is essential for maintaining accurate, up-to-date records of compliance units, improving operational efficiency and user trust in the system.

**Acceptance Criteria:**

- Given I am a route handler, when I query an organization's balance, then the system should return the current balance accurately.
- Given I am a system process, when a transaction is recorded, then the corresponding organization's balance should update accordingly.
- Given I am a system process, when I adjust an organization's balance, then the system should accurately reflect the adjustment in the organization's balance.

**Development Checklist:**

- [ ] A. Create a migration script for the `organization_balance` table including fields for organization_id, compliance_units, create_date, last_transaction_id, and any necessary metadata.
- [ ] B. Implement a `get_organization_balance` service method in the organizations/services.py file to retrieve the current balance of a specified organization.
- [ ] C. Implement an `adjust_balance` service method in the organizations/services.py file to add a specified amount (positive or negative) to the organization's current balance.
- [ ] D. Update supplier seeders to include initial compliance unit balances for various supplier accounts.
- [ ] E. Ensure proper indexing on the `organization_balance` table for efficient data retrieval.
- [ ] F. Write unit tests for both the `get_balance` and `adjust_balance` service methods.
- [ ] G. Implement logic to update the `organization_balance` table upon any transaction, using the `adjust_balance` method to modify the balance as needed.
- [ ] H. Ensure that balance adjustments through the `adjust_balance` method properly log or reference the transaction that caused the adjustment for auditing purposes.

**Notes:**

- The `adjust_balance` method must handle edge cases, such as attempting to decrement a balance below zero (if applicable), and ensure transactions are atomic to maintain data integrity.
- Documentation for the new service methods should clearly outline their usage, parameters, and any side effects to ensure proper integration with the rest of the system.

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
