### ISSUE TITLE
LCFS - Implement i18n Localization for Transfer Components

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#378]
**Description:** This task aims to extend our application's internationalization capabilities to the Transfer components. We will create a `transfer.json` file for English translations in the `assets/locales/en` folder, mirroring the structure used for the organization components. This file will contain all necessary labels and messages related to the Transfer components. We will then update the Transfer components to use these translations through the `react-i18next` library, ensuring all static and dynamic text is localized accordingly.

**Purpose:** To ensure that the Transfer components are accessible to a global audience by supporting multiple languages, starting with English. This will enhance user experience and accessibility by presenting information in the user's preferred language.

**Acceptance Criteria:**

- A `transfer.json` file is created in the `assets/locales/en` folder, containing all relevant English translations for the Transfer components.
- The Transfer components are updated to use the `useTranslation` hook from `react-i18next` to fetch and display localized text.
- Ensure that placeholders, labels, error messages, and any dynamic text in the Transfer components are localized using keys from the `transfer.json` file.
- Verify that changing the language updates the text in the Transfer components dynamically to reflect the selected language's translations.
- Conduct testing to ensure no functionality is broken in the Transfer components post-localization implementation.

**Development Checklist:**

- [ ] A. Create a `transfer.json` file in `assets/locales/en` with all required translations related to the Transfer components.
- [ ] B. Update the TransferDetails component and any other related components to use the `useTranslation` hook for fetching translations.
- [ ] C. Replace all static text in the Transfer components with translation keys, ensuring dynamic values are also handled appropriately.
- [ ] D. Ensure error messages and placeholders in form fields are also localized.
- [ ] E. Perform thorough testing to confirm that all text in the Transfer components is correctly localized and that language switching functions as expected.
- [ ] F. Update documentation to include instructions on how to add new translations or languages for the Transfer components.

**Notes:**

- Review the existing `organization.json` translation file to ensure consistency in naming conventions and translation key structuring for ease of maintenance and coherence.
- Coordinate with the team to ensure that any newly added labels or text in the Transfer components are also added to the `transfer.json` file moving forward.

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
