### ISSUE TITLE
LCFS - Director return transaction to analyst

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#382]
**Description:**
Develop the ability for the director to return a transaction to the analyst (i.e., status change):

- 'Return to analyst' button visible to IDIR Government users with the 'Director' role when the transaction has a status of 'Recommended'
- 'Return to Analyst' button in the bottom right hand corner of the page
- Clicking on the 'Return to analyst' button brings up a confirmation modal window
- Clicking the cancel button in the modal window brings the user back to the view transaction screen
- Clicking on the 'Return to analyst' button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transaction is highlighted, and (4) the transaction status is changed back to 'Draft'.
- No new transaction history record is created.
- Success alert from Material UI
- The transaction breadcrumb within the view page is updated back to the 'Draft' state

**Confirmation Modal Messaging:**
Similar to when the Director refuses a transfer in card #317 , we want to provide a warning message to the Director when they click on the Return to Analyst button for a transaction.

- You are strongly encouraged to provide an explanation to the analyst as to why the transaction is being returned.
- Are you sure you want to return the transaction to the Analyst? This will change the status of the transaction back to a draft state.

**Wireframes:**
- https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165555412/simulate/sitemap
- Example of warning message in confirmation modal window: 
![Image](https://github.com/bcgov/lcfs/assets/131904954/0956c806-17a0-4c32-a59a-9cb4017c5822)

**Purpose and benefit to user:**
Ability for the director to return the transaction to the analyst to revise their recommendation and/or provide additional information to the director support the decision to 'Approve' or 'Return to analyst' again.

### Acceptance Criteria:

1. **Director's Ability to Return Transaction**: Given I am a user with the 'Director' role, when I view a transaction with a status of 'Recommended', then I should see a 'Return to Analyst' button in the bottom right-hand corner of the page.
2. **Confirmation Modal**: Given I have clicked the 'Return to Analyst' button, when the confirmation modal window appears, then I can either cancel the action to stay on the current page or confirm to return the transaction to the analyst.
3. **Success Feedback and Status Change**: Given I confirm the return action in the modal, when the action is processed, then I should see a success message, be returned to the transaction page, the transaction should be highlighted, and its status should be changed back to 'Draft'.
4. **No New Transaction History Record**: Given I return a transaction to the analyst, when the process is completed, then no new transaction history record should be created for this action.
5. **Updated Transaction Breadcrumb**: Given the transaction status is changed back to 'Draft', when I view the transaction, then the breadcrumb on the transaction view page should reflect the 'Draft' state.
6. **Explanation Encouragement**: Given I am returning a transaction, when I interact with the confirmation modal, then I should be encouraged to provide an explanation to the analyst for the return action.

### Development Checklist:

- [x] **UI Implementation**: Ensure the 'Return to Analyst' button is implemented and only visible to users with the 'Director' role for transactions in a 'Recommended' status.
- [x] **Confirmation Modal**: Implement the modal window that appears upon clicking the 'Return to Analyst' button, including options to cancel or confirm the action.
- [x] **Success Message Implementation**: Upon successfully returning the transaction, display a success alert/modal as per Material UI standards.
- [x] **Status Change Logic**: Ensure the system properly changes the transaction status back to 'Draft' upon confirmation and highlights the transaction row.
- [x] **No History Record Creation**: Modify the transaction history logic to ensure that returning a transaction to draft does not create a new transaction history record.
- [x] **Breadcrumb Update**: Ensure the transaction breadcrumb is dynamically updated to reflect the 'Draft' status when a transaction is returned.
- [x] **Encouragement for Explanation**: Include a prompt or field within the confirmation modal to encourage directors to provide an explanation for the return action.

**Comment by airinggov** [comment]
Can we change the modal text alert to say:

It is helpful to provide a reason to the analyst on why the transaction is being returned.

You are strongly encouraged to provide an explanation to the analyst as to why the proposed transaction is being returned.

**Comment by airinggov** [comment]
I don't see the update on the modal text
