### ISSUE TITLE
LCFS - Implement Transactions List View with Real Data

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#409]
**Description:** This card involves the completion of the Transactions List View functionality in our application, ensuring that it is integrated with the backend to load and display real transaction records. The view should dynamically display transactions of various types (e.g., transfers, administrative adjustment, initiative agreements) and route the user to the appropriate detailed view when a transaction is clicked.

**Purpose and benefit to user:** This feature allows users to quickly view and access their transaction history within our application, providing a comprehensive overview of their compliance unit history. By supporting different transaction types and enabling easy navigation to detailed views, we enhance user experience and utility, making compliance management more intuitive and efficient.

**Acceptance Criteria:**

- [x] Given I am a user, When I navigate to the Transactions List View, then I see my real transaction records loaded.
- [x] Given I am a user, When I click on a transaction of type 'transfer', then I am routed to the transfer view with that transaction's details loaded.

**Development Checklist:**
- [ ] Finish backend repository methods to retrieve all transactions and format data including types.
- [ ] Implement frontend logic to display transactions and determine their types.
- [ ] Ensure the frontend correctly routes to the detailed view for a transaction when clicked.
- [ ] Test integration between frontend and backend to ensure accurate data display and routing.
- [ ] Implement lazy loading or pagination if the transaction list is very long to improve performance.

**Notes:**
- Ensure that the backend accurately categorizes each transaction type to facilitate correct frontend routing.
- Include error handling for cases where transaction data cannot be loaded.

**Comment by Grulin** [comment]
This card #409 functions great, except that for the acceptance criteria 'when I navigate to the Transactions List View, then I see my real transaction records loaded' I can see all transactions by all organizations. 

On the BCeID side, view of transactions should be limited only to those transactions involving the organization viewing this transactions table. 

Please see screenshot for example of transactions visible to LCFS Org 1. As a user of Org 1, I am also able to click on these transactions and view them:


![Image](https://github.com/bcgov/lcfs/assets/156380046/3167bf2f-086c-4575-ba02-ceef1146e695)
