### ISSUE TITLE
LCFS - Add Seed Values for Initial Compliance Unit Balances

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#410]
**Description:** This ticket involves creating a new seed file that populates the development database with initial transactions for each organization. These transactions, of the "administrative adjustment" type, should credit each organization's account with 50,000 compliance units. This setup will facilitate testing transfers between organizations with realistic values directly from the database.

**Purpose and benefit to user:** By initializing organization accounts with compliance unit balances, we enable developers and testers to simulate and test transfer functionalities between organizations within our system. This groundwork is essential for validating the application's behavior under real-world conditions, ensuring robustness and reliability of financial features.

**Acceptance Criteria:**

- [ ] Given the seed script has been run, When I check the database, Then each organization has a transaction of 50,000 compliance units of "administrative adjustment" type added.
- [ ] Given the seed script has been executed, When I perform database queries, Then I can verify that the compliance unit balances for each organization reflect the initial credit of 50,000 units.

**Development Checklist:**
- [ ] Develop the seed script to add an "administrative adjustment" transaction for each organization.
- [ ] Ensure each "administrative adjustment" transaction credits the organization's account with 50,000 compliance units.
- [ ] Test the script to ensure it correctly populates the database without errors or conflicts.
- [ ] Document the script's usage in the development setup guide.

**Notes:**
- The script should be idempotent, allowing it to be safely rerun without duplicating transactions.
- Ensure transactions are clearly typed as "administrative adjustments" to differentiate them from user-initiated transactions in the system.

**Comment by justin-lepitzki** [comment]
Nothing for PO/SME to test
