### ISSUE TITLE
LCFS - Spelling error in heading for Compliance Reports for IDIR users

### ISSUE THREAD

**Issue by Kailee-Douglas** [bcgov/lcfs#427]
**Describe the task**
The blue heading for the LCFS Portal for IDIR users says "Complaince reports".

**Purpose**
The reason this needs to be corrected is because the word is misspelled.

**Acceptance Criteria**

Correct spelling error to show "Compliance reports" instead.

**Additional context**
Please see screenshot:

![Image](https://github.com/bcgov/lcfs/assets/132306457/218c4332-f9c9-4163-8b07-96633166f73b)

**Comment by justin-lepitzki** [comment]
Duplicate; closing out.
