### ISSUE TITLE
LCFS - Implement AG Grid input fields for new fuel code entries

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#432]
**Description:**
Create "New fuel code" button, corresponding landing page, and then implement the AG grid variation that is created in #479 (Create Ag Grid variation that allows input rows / data entry). 

**Requirements:**

- Button location: Below the title on the "Fuel codes" landing page.
- Button visibility: Visible to IDIR users with analyst, compliance manager, and director permissions.
- New fuel code page contents: Contains 'Add new fuel code(s)" as title and add AG grid form style for data input (see wireframe).
- Ability to add new rows (add row button): Adding rows in increments (1 row, 5 rows, 10 rows) drop-down option below AG grid.

Fuel code details for AG grid column titles (in order from left to right); format is 'column name | type of data entry | validation requirements':

- Placeholder column for the duplicate code function (developed in #433 ); not an input field
- Prefix | drop-down menu (BCLCF as only option for now) | no input
- Fuel code | input field | numbers only, no decimals (card #434 will add more functionality to this cell), cannot be negative
- Company | free form text | n/a
- Carbon intensity (gCO2e/MJ) | input field | numbers only, max two decimal places, can be positive or negative
- EDRMS # | free form text | n/a
- Last updated | handled in separate card #516 
- Application date | date field | restrict format to yyyy-mm-dd
- Approval date | date field | restrict format to yyyy-mm-dd
- Effective date | date field | restrict format to yyyy-mm-dd
- Expiry date | date field | restrict format to yyyy-mm-dd, date must come after effective date
- Fuel | handled in a separate card #485 
- Feedstock | free form text | n/a
- Feedstock location | free form text | n/a
- Feedstock misc. | free form text | n/a
- Fuel production facility location handled in a separate card #486 
- Facility nameplate capacity | input field | numbers only, no decimals, cannot be negative
- Feedstock transport mode | handled in a separate card #485 
- Finished fuel transport mode | handled in a separate card #485 
- Former company name | free form text | n/a
- Notes | free form text | n/a

**Dependencies:**
[#479 ] is to create the AG Grid variation that allows input rows / data entry

**Wireframe:**
Suggested new design:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165712417/simulate/no-panels

TFRS current design for reference:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164612872/simulate/sitemap

Validation error design for LCFS portal:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165842680/simulate/sitemap

**Purpose and benefit to user:**
Designed to input fuel code information in a table format rather than the form-style sheet used in TFRS. The business area (verification unit) requested the ability to be able to easily enter multiple codes at the same time, often having similar or duplicate information (duplicate row function will be dealt with in a different card #433 ). 

**Acceptance Criteria:**

***New Fuel Code Button:***
- [x] Given the user is on the "Fuel Codes" landing page. 
       When the user views the page. 
       Then the "New Fuel Code" button should be located below the title.

***Button Visibility:***
- [ ] Given the user has analyst, compliance manager, or director permissions.
       When the user views the "Fuel Codes" landing page.
       Then the "New Fuel Code" button should be visible.
***New Fuel Code Page Contents:***
- [ ] Given the user clicks on the "New Fuel Code" button.
       Then the user should be directed to a new page titled "Add new fuel code(s)".
       And the page should contain an AG grid form style for data input.
***Ability to Add New Rows:***
- [ ] Given the user is on the new fuel code page.
       When the user interacts with the AG grid.
       Then the user should be able to add new rows using the "Add Row" button.
       And the user should have the option to add rows in increments of 1, 5, or 10 through a drop-down menu.
***Fuel Code Details:***
- [ ] Given the user is entering data in the AG grid.
       Then the user should see the following column titles in the specified order:
- Placeholder for duplicate code function (non-input field)
- Prefix (drop-down menu with "BCLCF" as the only option)
- Fuel code (input field with numbers only, no decimals)
- Company (free-form text)
- Carbon intensity (input field with numbers only, max two decimal places)
- EDRMS # (free-form text)
- Last updated (handled separately)
- Application date (date field in format yyyy-mm-dd)
- Approval date (date field in format yyyy-mm-dd)
- Effective date (date field in format yyyy-mm-dd)
- Expiry date (date field in format yyyy-mm-dd, must come after effective date)
- Fuel (handled separately)
- Feedstock (free-form text)
- Feedstock location (free-form text)
- Feedstock misc. (free-form text)
- Fuel production facility location (handled separately)
- Facility nameplate capacity (input field with numbers only, no decimals)
- Feedstock transport mode (handled separately)
- Finished fuel transport mode (handled separately)
- Former company name (free-form text)
- Notes (free-form text)

**Development Checklist:**
- [ ] Create the "New Fuel Code" button.
- [ ] Position the button below the title on the "Fuel Codes" landing page.
- [ ] Ensure the button is visible to users with analyst, compliance manager, or director permissions.
- [ ] Develop the new page titled "Add new fuel code(s)".
- [ ] Implement the AG grid form style for data input on the new page.
- [ ] Implement the functionality to add new rows in the AG grid.
- [ ] Provide options to add rows in increments of 1, 5, or 10 via a drop-down menu.
- [ ] Configure the AG grid columns with the specified titles and data entry types.
- [ ] Ensure validation requirements are implemented for each data entry field.
- [ ] Implement the suggested new design based on the provided wireframe.
- [ ] Ensure consistency with the TFRS current design for reference.
- [ ] Implement validation error design for the LCFS portal.
- [ ] Verify that the implementation allows users to input fuel code information in a table format.
- [ ] Confirm that users can easily enter multiple codes at the same time, addressing the need for duplicate row functionality as mentioned in card #433.

**Notes:**
Per team discussion in refinement/planning, some input fields will be handled separately in different cards: 
- #485 
- #486 
- #516

**Comment by justin-lepitzki** [comment]
Split this into four cards. Card 1 needs some new information around back-end tables; card 2/3/4 should be mainly pulling info out of this card into separate cards. 

Card 1: create the back-end tables and add values for drop-down menu (all the drop-down menus can be here), then these drop-down fields can be implemented in the new fuel code page. Includes validation for these input fields. 
Card 2: The rest of the input fields can be created in this second card. Includes validation for these input fields. 
Card 3: Location field - Fuel production facility location functionality
Card 4: Suggestive text input functionality
