### ISSUE TITLE
LCFS - Save draft fuel code

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#435]
**Description:**
Develop the functionality to save a draft fuel code:

- 'Save draft code' button
- All required fields must be completed to successfully save or a validation message appears (see below for required fields)
- Clicking the 'Save draft code' button saves the code in the database, makes it visible in the UI in the main fuel code table, and sets the status of the code to 'Draft'.
- The last update field for the code is populated with the date the code was saved 'yyyy-mm-dd'
- A success alert appears ([Material UI examples](https://mui.com/material-ui/react-alert))
- The user is returned to the 'Fuel codes' page where the fuel code is visible at the top of the fuel code table

**Required fields:**

The following are required fields for saving a draft code: 
- Prefix
- Fuel code
- Company
- Carbon intensity
- EDRMS #
- Application date
- Fuel
- Feedstock
- Feedstock location
- Fuel production facility location

**Wireframes & screenshots:**

Add new fuel code page (wireframe): 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165712417/simulate/sitemap

**Purpose and benefit to user:**
Allows the IDIR user to save a draft of the fuel code to be approved later and/or by a different user.

**Acceptance Criteria:**

- [ ]  Given I am an IDIR user, when I attempt to save a draft fuel code without completing all required fields, then a validation message appears.
- [ ] Given I am an IDIR user, when I click the 'Save draft code' button with all required fields completed, then the code is saved in the database.
- [ ] Given a draft fuel code is successfully saved, when I return to the 'Fuel codes' page, then the saved draft code is visible at the top of the fuel code table.
- [ ] Given a draft fuel code is successfully saved, when I return to the 'Fuel codes' page, then the last update field for the code is populated with the current date in the format 'yyyy-mm-dd'.
- [ ] Given a draft fuel code is successfully saved, when I return to the 'Fuel codes' page, then a success alert appears indicating the code was saved.

**Development Checklist:**
- [ ] Implement validation checks to ensure all required fields are completed before saving the draft code.
- [ ] Develop functionality to save the draft code in the database.
- [ ] Update the status of the saved draft code to 'Draft'.
- [ ] Populate the last update field with the current date in the format 'yyyy-mm-dd' upon saving the draft code.
- [ ] Display a success alert upon successfully saving the draft code.
- [ ] Navigate the user back to the 'Fuel codes' page after saving the draft code.
- [ ] Ensure the saved draft code is visible at the top of the fuel code table on the 'Fuel codes' page.

**Notes:**

**Comment by justin-lepitzki** [comment]
The team estimated #435 as 5 points, then estimated similar cards as either 3 points (#441 ) or 2 points (#436 , #437 ). The #435 card should be completed first.

**Comment by Grulin** [comment]
Card #479 must be completed before user is able to save a draft fuel code (#435 )
