### ISSUE TITLE
LCFS - Sign and Send Transfer without having to save a draft first

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#454]
**Describe the task**

For a BCeID user with the transfer and Signing Authority roles to sign and send a transfer, they are currently required to save the transfer as a draft before the signing declaration is visible and the sign and send button is available (not greyed out). 

BCeID users with the transfer and signing authority roles should be able to complete the signing declaration and the sign and send button should be available (not greyed out) without first saving a draft of the transfer.

Note: It is the Signing Authority role that is required to complete the signing authority declaration and be able to click on the sign and send button. The transfer role is required to create a new transfer; therefore, both roles are required (for different aspects) to create a new transfer and then sign and send it, all without saving a draft. 

Note1: Signing Authority declaration should be visible for all BCeID users, but only the Signing Authority role can complete (check the box) the declaration. 

Please see screenshot for current view:

![Image](https://github.com/bcgov/lcfs/assets/156380046/b12b29b0-ecb7-4c03-b96f-f790d94334fe)

Please see wireframe for what user should see:

https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164927056/simulate/sitemap

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Can you look into a bug on the release branch when trying to sign and send a transfer directly from the new transfer page. There is a server error occurring on save.

**Comment by Grulin** [comment]
Non-responsive sign and send button dealt with in card #489
