### ISSUE TITLE
LCFS - Enhancement of Audit Field Integrity and Automation in Database Models

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#457]
**Description:** Our current implementation of audit fields within our database models lacks the enforcement of proper foreign keys and fails to populate these fields on record creation and updates. This task involves reviewing and updating our base SQLAlchemy model to ensure that `create_user` and `create_date` are automatically set upon the creation of a record, and `update_user` and `update_date` are appropriately updated whenever a record is modified. This enhancement aims to maintain data integrity and provide accurate audit trails for database records.

**Purpose:** The primary goal of this task is to improve the reliability and accuracy of our audit trails. By ensuring that audit fields are correctly populated and linked via foreign keys, we can better track the lifecycle of records, identify who made changes and when, and enhance the overall data integrity within our system. This is crucial for compliance, debugging, and historical data analysis purposes.

**Acceptance Criteria:**
- [ ] Audit fields (`create_user`, `create_date`, `update_user`, `update_date`) are automatically populated on record creation and updates.
- [ ] Foreign key constraints for `create_user` and `update_user` are properly defined and enforced.
- [ ] Existing records with missing or incorrect audit information are identified and a strategy for correction is proposed.
- [ ] Unit tests are updated or added to verify that audit fields are correctly handled on record creation and updates.
- [ ] Documentation is updated to reflect changes in how audit fields are managed.

**Additional context:**
- Consider exploring the use of SQLAlchemy event listeners or default column values to automate the population of these fields.
- Ensure compatibility with the current database schema and any ORM relationships that might be affected by the introduction of foreign keys for audit fields.
- Review the current usage of the base SQLAlchemy model across the project to identify any specific cases where manual intervention might be necessary to correctly apply these changes.

**Comment by justin-lepitzki** [comment]
Nothing for PO/SM to test
