### ISSUE TITLE
LCFS - Historical Data Import from ZenHub to GitHub Projects

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#460]
Other teams have done this work, [documentation and guidance can be found here
](https://bcgov.sharepoint.com/:f:/r/teams/01284/Shared%20Documents/Tools/ZenHub?csf=1&web=1&e=63QjnJ&xsdata=MDV8MDJ8QWxhc2RhaXIuUmluZ0Bnb3YuYmMuY2F8OTUwODgzZDMyNzEzNDU4ZDE0OWYwOGRjYmJlODIzOGJ8NmZkYjUyMDAzZDBkNGE4YWIwMzZkMzY4NWUzNTlhZGN8MHwwfDYzODU5MTg1Mjg5NDY3MTIzMHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MHx8fA%3d%3d&sdata=OHBUT0JiSkUxT1QxNUVnZmNOc3NqUjhYZ2hiR1hIeFJzQU10MTdmOGxrMD0%3d)

Suzanne Woodward can be contacted to be connected with devs that have gone through this work. As a result this is now more a Task than a Research spike.

Just closed cards

**Problem Description**  
**In order to** ensure continuity and maintain historical context after migrating our project board from ZenHub to GitHub Projects, **our team needs to** find a way to import all previously 'closed' tickets from ZenHub into GitHub Projects.

**Solution Needs**
- The solution must accurately import all data associated with closed tickets from ZenHub, including ticket descriptions, comments, labels, and timestamps.
- The import process should preserve the original structure and hierarchy of tickets to maintain context and understand historical project decisions.
- Compatibility with GitHub Projects' features and limitations is non-negotiable, ensuring seamless integration of imported tickets.
- A want, but not a need, is an automated or semi-automated process to facilitate future migrations or data imports.

**Outcome**
- If successful, the outcome will be a detailed plan or a working script/tool capable of importing closed tickets from ZenHub into GitHub Projects without significant data loss or distortion. The direction of work will proceed to implementing the solution across our projects.
- If unsuccessful, we will document the challenges faced and the reasons why the import could not be achieved. The next steps will involve discussing alternative solutions with the team, such as manual data entry or summarizing historical data in a different format that can be added to GitHub Projects.

**Additional Context**
- This spike is critical for maintaining the integrity and continuity of our project's historical data, which is invaluable for new team members and for referencing past decisions and discussions.
- Consideration must be given to GitHub Projects' limitations and data structure differences from ZenHub to ensure a smooth transition.

**Comment by airinggov** [comment]
Historical data appears to be available in Github projects if not it is till available in Github.
