### ISSUE TITLE
LCFS - Transactions widget on IDIR home page for user assigned an 'Analyst' or 'Manager' role

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#476]
**Description:**
Develop the transactions widget on the LCFS portal IDIR home page for a user assigned an 'Analyst' or 'Manager' role. 

- Title of widget is 'Transactions'.
- Next line of widget says 'There are:'

1. The first link available in this widget should read 'Transfer(s) in progress' and include a counter which displays the number of transfers that all organizations have submitted for processing. 

- Transfers with the following statuses should be included in the 'in progress' counter: 'Submitted', 'Recommended'. 
- Statuses that should not be included in the counter are: 'Draft', 'Sent', 'Deleted', 'Declined', 'Rescinded', 'Recorded', 'Refused'.
- When a user selects the 'Transfer(s) in progress' link, this should take the user to the 'Transactions' table on the 'Transactions' page and display only the filtered transactions that are categorized as 'Transfers' and have a 'Submitted' or 'Recommended' status.

2. The next link in this widget should read 'Initiative agreement(s) in progress' and include a counter which displays the number of all initiative agreements that have been submitted.

- The initiative agreement transactions counter should include only transactions with the 'Draft' and 'Recommended' statuses. 
- Statuses that should not be included in the initiative agreement counter are: 'Deleted' and 'Approved'
- When a user selects the 'Initiative agreement(s) in progress' link, this should take the user to the 'Transactions' table on the 'Transactions' page and display only the filtered transactions that are categorized as 'Initiative agreement' and have a 'Draft' or 'Recommended' status.

3. The next link in this widget should read 'Administrative adjustment(s) in progress' and include a counter which shows how many adjustments are in progress for all organizations. 

- The administrative adjustments transactions counter should include only transactions with the 'Draft' and 'Recommended' statuses.
- Statuses that should not be included in the administrative adjustments counter are: 'Deleted' and 'Approved'.
- When a user selects the 'Administrative adjustment(s) in progress' link, this should take the user to the 'Transactions' table on the 'Transactions' page and display only the filtered transactions that are categorized as 'Administrative adjustments' and have a 'Draft' or 'Recommended' status.

4. The final link should be titled 'View all transactions' and when pressed sends the user to the Transactions page with no filter on the table at all. 
- Transaction widget should have all the same style and design features of other pages (Please see wireframe).

**Wireframe:**

https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161899748/simulate/sitemap

**Purpose and benefit to user:**
The purpose of this transaction widget on the home page of LCFS portal is to give IDIR users a quick view of transfers in progress, initiative agreements, and provide a quick link to transactions.

**Acceptance Criteria:**

- [ ] Given I am an Analyst or Manager, when I view the home page, then I should see a 'Transactions' widget titled 'Transactions' with the described links and counters reflecting the current state of transactions across all organizations.
- [ ] Given I am an Analyst or Manager, when I click on the 'Transfer(s) in progress' link in the 'Transactions' widget, then the website should take me to the 'Transactions' page showing only the transactions that are categorized as 'Transfers' and have statuses of 'Submitted' or 'Recommended'.
- [ ] Given I am an Analyst or Manager, when I click on the 'Initiative agreement(s) in progress' link, then the website should take me to the 'Transactions' page displaying only the transactions categorized as 'Initiative agreement' with statuses 'Draft' or 'Recommended'.
- [ ] Given I am an Analyst or Manager, when I click on the 'View all transactions' link, then the website should navigate me to the 'Transactions' page displaying all transactions without any filters applied.

**Development Checklist:**
- [ ] Implement routing from the widget links to the 'Transactions' page with the appropriate filters applied.

**Notes:**

**Comment by justin-lepitzki** [comment]
@Grulin several revisions needed for this one.

1) We add a new item for administrative adjustments in progress. We will need to have @alaigov update the wireframe. This is a fairly new transaction so having an in progress line for it on the IDIR dashboard is a new feature that is needed. 

2) We need to list the specific statuses that would be included for these different "in progress" transactions and which ones are not included. The devs may not understand what is meant by "the number of transfers that organizations have submitted for processing." To clarify requirements for this feature, listing the individual statuses that count / not count will help them develop the correct logic. 

For example, transfers with the following statuses should be included in the "in progress" counter: Submitted, Recommended. Statuses that should **not be included** in the counter are: Draft, Sent, Deleted, Declined, Rescinded, Recorded, Refused. 

3) This card also needs to include the functionality when the user clicks on these individual "in progress" links. Similar to TFRS, when the user clicks on "x transfers in progress" the system should take the user to the transactions page and display the transactions table that is filtered to only show the "in progress" transfers. This same functionality should exist for initiative agreements in progress and admin adjustments in progress.

**Comment by Grulin** [comment]
Edited

**Comment by Grulin** [comment]
Widgets showing up for Analyst IDIR role, but not the Manager IDIR role.

**Comment by hamed-valiollahi** [comment]
> Widgets showing up for Analyst IDIR role, but not the Manager IDIR role.

Thank you for your comment, Lindsy.
Could you please let me know which one represents the manager role?

<img width="1043" alt="Screen Shot 2024-07-25 at 5 54 54 AM" src="https://github.com/user-attachments/assets/e119be1f-6015-4828-ad76-58f19bf91270">

**Comment by Grulin** [comment]
Hi @hamed-valiollahi. The manager role is "Compliance_Manager". Thanks for checking.

**Comment by hamed-valiollahi** [comment]
Hi Lindsy,

Thanks for the clarification. I resolved the issue as part of ticket #764.

As a heads-up, I refined all the cards on the dashboard for performance purposes and easier maintenance. Please consider this when checking ticket #764 and let me know if there are any issues with the cards.
