### ISSUE TITLE
LCFS - Fuel drop-down menu options for new fuel code entries

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#485]
**Description:**
Implement the AG grid variation that is created in [#479 ](Create Ag Grid variation that allows input rows / data entry). Create the back-end tables for drop-down menus for the following columns: Prefix, Fuel type, Feedstock transport mode, and Finished fuel transport mode

**Implement the 'Prefix' drop-down options (restricted to 1 choice):**
- BCLCF

Note: There will be more options for generic fuel codes that will be developed at a later date. For now, there is only 'BCLCFS' as an option

**Implement the 'Fuel' drop-down options (restricted to 1 choice):**
- Biodiesel
- CNG
- Electricity
- Ethanol
- HDRD
- Hydrogen
- LNG
- Other - gasoline category
- Other diesel fuel
- Other - diesel category
- Alternative jet fuel
- Other - jet fuel category
- Propane
- Renewable gasoline
- Renewable naphtha
- Fossil-derived diesel
- Fossil-derived gasoline
- Fossil-derived jet-fuel

Note: The 3 final 'fossil-derived' options listed above should not be available in the fuel code drop-down menu because they are reported in other areas of the compliance report. They are only included here because those reporting areas will rely on this same back-end table / drop-down menu.

**Implement the following 'Feedstock transport mode' options with pill functionality (more that 1 option can be selected):**
- Truck
- Rail
- Marine
- Adjacent
- Pipeline

**Implement the following 'Finished fuel transport mode' options with pill functionality (more that 1 option can be selected):**
- Truck
- Rail
- Marine
- Adjacent
- Pipeline

**Wireframe:**
Suggested new design:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165712417/simulate/no-panels

TFRS current design for reference:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164612872/simulate/sitemap

Validation error design for LCFS portal:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165842680/simulate/sitemap

**Purpose and benefit to user:**
Designed to input fuel code information in a table format rather than the form-style sheet used in TFRS. The business area (verification unit) requested the ability to be able to easily enter multiple codes at the same time, often having similar or duplicate information (duplicate row function will be dealt with in a different card [#433]. This card deals specifically with the fuel types drop-down option.

For the outlined task of creating lookup tables in the database and adjusting the backend to provide these via an API, here’s a detailed plan that includes development requirements and acceptance criteria:

#### Database Creation via Alembic Migration

1. **Create Lookup Tables**:
   - Generate a new Alembic migration script with `alembic revision -m "Create lookup tables for fuel data management"`.
   - Define the table structures in the Alembic upgrade function. Tables to create:
     - **fuel_type**: Stores different types of fuels.
     - **transport_mode_type**: General categorization of transport modes.
     - **feedstock_transport_mode_fuel_code**: Junction table for many-to-many relationships between feedstock transport modes and fuel codes.
     - **fuel_transport_mode_fuel_code**: Junction table for many-to-many relationships between finished fuel transport modes and fuel codes.
     - **fuel_code_prefix**: Stores prefix options for fuel codes.
   - Include foreign keys as necessary based on your relational design, ensuring referential integrity.
   
2. **Sample Alembic Migration Script**:
```python
from alembic import op
import sqlalchemy as sa

def upgrade():
    op.create_table('fuel_type',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('type', sa.String(50), nullable=False))
    
    op.create_table('transport_mode_type',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('mode', sa.String(50), nullable=False))
    
    op.create_table('feedstock_transport_mode_fuel_code',
                    sa.Column('feedstock_mode_id', sa.Integer, sa.ForeignKey('transport_mode_type.id'), primary_key=True),
                    sa.Column('fuel_code_id', sa.Integer, sa.ForeignKey('fuel_type.id'), primary_key=True))
    
    op.create_table('fuel_transport_mode_fuel_code',
                    sa.Column('fuel_mode_id', sa.Integer, sa.ForeignKey('transport_mode_type.id'), primary_key=True),
                    sa.Column('fuel_code_id', sa.Integer, sa.ForeignKey('fuel_type.id'), primary_key=True))
    
    op.create_table('fuel_code_prefix',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('prefix', sa.String(50), nullable=False))

def downgrade():
    op.drop_table('fuel_code_prefix')
    op.drop_table('fuel_transport_mode_fuel_code')
    op.drop_table('feedstock_transport_mode_fuel_code')
    op.drop_table('transport_mode_type')
    op.drop_table('fuel_type')
```

#### Backend API Implementation

3. **Develop `table_options` Endpoint**:
   - Implement a RESTful API endpoint that consolidates and serves the table data. The endpoint should provide structured data that can be easily consumed by the front-end, returning data from all the tables created.
   - Organize the API to return data segregated by table name, each as an array of objects.

### Acceptance Criteria

- **Given** a user requests the `/table_options` endpoint,
  **When** the API is queried,
  **Then** it should return JSON data containing arrays for `fuel_types`, `transport_mode_types`, `feedstock_transport_modes`, `fuel_transport_modes`, and `fuel_code_prefixes` with appropriate data from each table.

- **Given** the database has been updated,
  **When** reviewing the structure in a database management tool,
  **Then** the newly created tables should match the specifications in the Alembic migration script and support the intended relationships.

- **Given** the API endpoint is consumed by the front-end,
  **When** the data is fetched,
  **Then** the front-end should be able to display dropdowns and other UI components using this data without any discrepancies.

- **Given** a user accesses the dropdown for selecting fuel types,
  **When** the dropdown component is interacted with,
  **Then** it should populate dynamically with all entries from the `fuel_type` table without any errors or omissions, ensuring that the user can see and select from a complete list of available fuel types.

- **Given** a user is filling out a form involving transport modes,
  **When** the user clicks on the dropdown for either feedstock transport mode or finished fuel transport mode,
  **Then** the dropdown should display options grouped by transport mode categories, allowing multiple selections where applicable, and these options should reflect the latest data from the `transport_mode_type` table as fetched from the `/table_options` endpoint.

### Notes

- Please refer to the draw.io data model for further details on the table structures and relationships.
- Ensure that the API endpoint is secure and performs well under load, potentially by adding caching mechanisms if necessary.
- Linked to card #432

**Comment by justin-lepitzki** [comment]
This card: 
1. Create the back-end tables for drop-down menus (fuel type) and pills (transport modes x2). 
2. Implement the drop-down menu functionality in the new fuel code page
3. Implement the pills functionality (x2) in the new fuel code page
4. Include validation requirements for these three fields (if applicable)

**Comment by justin-lepitzki** [comment]
The fuel type data model will be used in several other areas of the compliance reporting feature.

**Comment by Grulin** [comment]
The option to choose fossil-derived diesel, fossil-derived gasoline and fossil-derived jet-fuel should be restricted on the front end in this new fuel code table. They will be used in different report functions, but not for fuel codes here.

Also, the "-" between 'jet' and 'fuel' here was a typo. It should just read 'fossil-derived jet fuel'.
