### ISSUE TITLE
LCFS - Fuel production facility location field for new fuel code entries

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#486]
**Description:**

Replace the “Fuel production facility location” field with the following three text input fields:
- Fuel production facility city
- FP facility province/state
- FP facility country

Give IDIR users the ability to input fuel production facility locations in a format that facilitates geographic data analyses, not a free-form text field. For example, we want to be able to plot this data on map or creating a GIS map of facility locations, which would also enable the tracking of fuel supply (i.e., where do we get our fuel from?). In TFRS, this data is currently stored as plain text. Current examples of TFRS inputs include countries, provinces/states, cities, and regions (US Central) with no consistent formatting. 

Consultation with the business area resulted in the need for three location entries: City/Province or State/ Country. 

Use the predictive text function to auto-fill province/state/country based on text input into the city field.

**Dependencies:**
#479 is to create the AG Grid variation that allows input rows / data entry (Completed).

**Wireframe:**
Suggested new design:
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739510

TFRS current design for reference:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164612872/simulate/sitemap

Validation error design for LCFS portal:
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739511?mode=m

**Purpose and benefit to user:**
The benefit to the business area is that we can more accurately identify, confirm, and track where fuel production facilities supplying fuel in B.C. are located. We can also ensure that the input of these location fields are consistent if we implement something more stringent than free-form text input. A map function would add the additional benefit of visualizing where these facilities are located around the world for reporting out purposes. 

**Acceptance Criteria:**

- [ ] Given I am IDIR user, When I navigate to the fuel production facility location input section,
Then I should see three text input fields labeled "Fuel production facility city," "FP facility province/state," and "FP facility country."

- [ ] Given I input data into the "Fuel production facility city" field, When I input text,
Then the system should provide predictive text suggestions for the "FP facility province/state" and "FP facility country" fields based on the input city.

- [ ] Given I input data into all three location fields, When I submit the form,
Then the system should store the data in a format that facilitates geographic data analyses, such as separate fields for city, province/state, and country along with co-ordinates.

**Development Checklist:**

- [ ] Implement three text input fields for "Fuel production facility city," "FP facility province/state," and "FP facility country" in the IDIR system.
- [ ] Integrate predictive text functionality to auto-fill province/state/country based on text input into the city field.
- [ ] Update data storage format to separate fields for city, province/state, and country to facilitate geographic data analyses.

**Notes:**
- Related to card #485 and #432

**Comment by justin-lepitzki** [comment]
Revise this card: 
1. Add 'fuel production facility location' field for new fuel codes; mention related to card #485 #432 
2. Describe the requirements, functionality, and considerations (can use the paragraph listed in the description; might need to add / revise): this field is to input the location of the fuel production facility. Card is about user inputting location; two considerations: we want this information to be inputted in such a format that enables location-based data analyses (plotting locations on a map; not just having it be a free form text field like TFRS), other consideration is that we have to be able to handle foreign address locations that don't necessarily follow conventional North America address formats. 
3. Includes wireframe(s), dependencies, and related cards (include all of the 4 card split)

**Comment by justin-lepitzki** [comment]
Need to discuss this more with the business area to better understand the business requirements. How would the branch use this information? We should discuss with the C&E unit, the economics unit, and the verification team. Once we have this understanding, we will likely need a spike ticket for a dev to investigate solutions that meet business requirements. Upon completion of the spike, we can then create the implementation card.

**Comment by airinggov** [comment]
Migrating production Fuel Code data into this table would help seed the predictive text values.
