### ISSUE TITLE
LCFS - Predictive text function for new fuel code entries

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#487]
**Description:**
For IDIR users entering a new fuel code, apply predictive text functionality to the following fuel code input columns:
- Company
- Feedstock
- Feedstock location
- Feedstock misc.
- Former company
- Fuel production facility city
- FP facility province/state
- FP facility country

These fields should predict text for the user based on the first few letters input the user enters and predictions should be pulled from what has already been saved in the database. For example, for feedstock, if the user types "Cor..." then the system should scan the database and provide a list of selectable options that have already been saved in the database that start with "Cor...", such as Corn, Corn oil, Corn husks, etc.

![Image](https://github.com/bcgov/lcfs/assets/156380046/7817ce6a-2029-4202-8e91-6d46bbeb984e)

**Dependencies:**
#479 is to create the AG Grid variation that allows input rows / data entry

**Wireframe:**
Suggested new design:
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739510?mode=m

TFRS current design for reference:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164612872/simulate/sitemap

Validation error design for LCFS portal:
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165842680/simulate/sitemap

**Purpose and benefit to user:**
The benefit to the IDIR user is that they are able to begin typing an input in these fields and the grid will provide predictions pulled from already used inputs in the database. This increases the chance that users won't accidentally deviate from previously used inputs or make typos. This will also ensure that these entries are done quickly and accurately, and that the data collected from these inputs is more consistent than free-form text inputs. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, when I start typing in the 'Company' field on the new fuel code entry form, then the form should display a dropdown list of companies from the database that match the typed letters.
- [ ] Given I am an IDIR user, when I input letters into the 'Feedstock' field, then the form should present a list of feedstock options that begin with those letters, sourced from previous entries in the database.
- [ ] Given I am an IDIR user, when I enter the initial letters in the 'Feedstock location' field, then the form should autocomplete my text with feedstock locations starting with those letters from the database.
- [ ] Given I am an IDIR user, when I enter the initial letters in the 'Feedstock misc.' field, then the form should autocomplete my text with feedstock misc starting with those letters from the database.
- [ ] Given I am an IDIR user, when I type in the 'Former company' field, then I should see a list of former companies that match the entered prefix, aiding in consistent data entry.

**Development Checklist:**
- [ ] Check if AG Grid directly supports autocomplete functionality or needs custom implementation by reviewing its documentation and community forums.

**Notes:**
Related to #432  , #485 , #486

**Comment by justin-lepitzki** [comment]
1. Describe the suggested text functionality (paragraph included)
2. What fields do we want this functionality to apply to  
3. Mention that this functionality exists in the fuel code feature TFRS, and we are implementing it in the exact same way here.
