### ISSUE TITLE
LCFS - error message when saving a draft transfer (no longer required)

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#490]
**Describe the Bug**
BCeID user receives an error message when trying to save a draft of a new transfer. The draft appears to be saving as it does show up in the transaction table. However, the user is receives an error message in the UI and there are errors in the console. The user is also able to create duplicate transfers if they keep hitting the save draft button. 

Screenshot of error message in UI: [Image](https://github.com/bcgov/lcfs/assets/131904954/6171883f-a9d8-4271-90c6-41b591165d0d)

Screenshot of console errors: [Image](https://github.com/bcgov/lcfs/assets/131904954/923434a4-9d0d-4628-8262-a61c61899c86)

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user, transfers role
1. Go to Transactions page
2. Click on New transfer button
3. Fill out relevant transfer information
4. Click on Save draft button
5. See error

**Comment by Grulin** [comment]
Now getting the message "Draft Transfer successfully created" when transfer is first made and saved, but only the first time 'save' is pressed after creating a transfer:


![Image](https://github.com/bcgov/lcfs/assets/156380046/e6d301f5-d5c8-4f6a-949f-951cf25ef641)


Returning to transfer and selecting 'save' shows the following incorrect success message, which has been noted in card# already:


![Image](https://github.com/bcgov/lcfs/assets/156380046/aec7852d-08e7-4c7d-b4e5-8d47a7729a5d)

**Comment by justin-lepitzki** [comment]
From the team discussion in refinement, we want to change the message to say "Draft saved". It should show this message on the first save and every subsequent save.

**Comment by Grulin** [comment]
Solved with another card
