### ISSUE TITLE
LCFS - Regular comments in the transfer feature are not saving, showing demo data

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#493]
**Describe the Bug**
Regular comments in the transfer feature (visible to everyone) are not saving. Demo data is displayed instead. 

**Expected Behaviour**
Comments should be saved when a transfer is either saved or actioned (next status in the workflow, such as sign & send, sign & submit, etc.)

**Actual Behaviour**
Comments are not being saved and displayed. Demo data is showing instead. 

**Implications**
Feature is not working as needed

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user, transfers & signing authority roles
1. Go to Transactions 
2. Click on New transfer button
3. Input transfer details and text into the comment field
4. Click on Sign & Send
5. Open transfer 
6. See error

Screenshot: 

![Image](https://github.com/bcgov/lcfs/assets/131904954/3641e4db-2aab-4993-8a39-b114f8fe826b)

**Comment by justin-lepitzki** [comment]
Will be completed already

**Comment by Grulin** [comment]
No longer showing the demo data, but still not saving comments the way the feature is intended to. I wrote comments from both organizations and they did not save in draft or after sign and send.

Please see screenshot of what director role sees of transfer before returning to analyst or recording:


![Image](https://github.com/bcgov/lcfs/assets/156380046/8c4d374d-589d-4d48-a348-09d79a6c3cd7)

**Comment by justin-lepitzki** [comment]
This issue will be resolved in Prashanth's work around regular commenting #506
