### ISSUE TITLE
METABASE - Add current status column to the Exclusion (Allocation) Agreement query

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#500]
**Describe the task**
The Exclusion (Allocation) Agreement query is written in SQL. We want to add an additional column to this query that provides the Current Status of the report that these individual row entries of data come from. The Fuel Supply Data model has very similar logic so one may be able to borrow logic from there. 

In the database, the 'Compliance Report Workflow State' table provides the different status IDs. It appears that the database separates out report status based on role (?) as there are different columns for Analyst, Director, Fuel Supplier, Manager statuses. The Fuel Supply Data model combines all of these into a single column and uses labels that align with business logic: 
- Submitted
- Recommended Acceptance - Analyst
- Recommended Rejection - Analyst
- Recommended Acceptance - Manager
- Recommended Rejection - Manager
- Accepted
- Rejected (this might be filtered out in the fuel supply model, not 100% sure)

I believe the Exclusion (Allocation) Agreement query already excludes reports with Draft or Deleted statuses, which we want to maintain this filtering. 

Link to Exclusion (Allocation) Agreement query: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/question/398-exclusion-allocation-agreements-latest-reports

Link to Fuel Supply Data model: https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/model/192-fuel-supply-data

**Purpose**
This column will allow the user to understand which reports have been Accepted vs. which are still being processed. This information will also be helpful when analyzing the data (e.g., only include data from accepted reports, etc.)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Updated the query to use the proposed status logic to output a singular "Current Status" column.
https://tfrs-metabase-prod.apps.silver.devops.gov.bc.ca/question/398-exclusion-allocation-agreements-latest-reports
