### ISSUE TITLE
LCFS - Remove all caps from pills for roles and statuses

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#504]
**Describe the task**
The LCFS portal uses pills in several instances, including status of transfers, status of users (active/inactive), and for roles within the user table. Currently, the labels within these pills are all capitalized. We would like to change this so that only the first letter in the first word capitalized. For example, SIGNING AUTHORITY is changed to Signing authority.

**Screenshot:**
- ![Image](https://github.com/bcgov/lcfs/assets/131904954/5d95d513-b273-48ca-806c-ae3777af2d1f)
- ![Image](https://github.com/bcgov/lcfs/assets/131904954/0b40158d-2977-4669-844c-a306d5e90651)

**Purpose**
Align with the styling preferences elsewhere in the application, where we only capitalize the first letter in the first word of labels. 

**Acceptance Criteria**
- [ ] When viewing tables with pills, the text should not be all caps. ( roles, statuses etc )

**Additional context**
- it should be a simple text change. Otherwise could be what is returned from the db, in that case, we could possibly create a map to its lower case equivalent

**Comment by Grulin** [comment]
On the IDIR side, the 'active' and 'inactive' pills are all lower-case. The first letter of these labels should be capitalized to match the other labels:



![Image](https://github.com/bcgov/lcfs/assets/156380046/0bf21643-81c5-41fe-beba-796a0106174c)

**Comment by hamed-valiollahi** [comment]
Thanks, Lindsy, for testing and reporting the issue! It's very strange because I checked that, and it was okay before I pushed the code. I've fixed it now. Thank you again for testing!

**Comment by Grulin** [comment]
Thanks, @hamed-valiollahi. Looks great.
