### ISSUE TITLE
LCFS - Backend data table to include energy densities needed for calculating compliance units

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#532]
**Context**
Backend data table(s) are needed to store the values that go in to formulas used for calculations in the compliance reporting feature of the LCFS portal. The two formulas used are:

Compliance units:

![Image](https://github.com/bcgov/lcfs/assets/156380046/729c9b96-fdd0-424b-abb3-255ae62dff11)

Target carbon intensity:

![Image](https://github.com/bcgov/lcfs/assets/156380046/9eeeab8b-2ee6-402a-9327-f7c5a0fc9210)

**Reference:**
[Calculating compliance units PDF](https://github.com/bcgov/lcfs/files/15068138/Calculating.compliance.units.2024-02-09.1.pdf)

**Description**
This card is for adding the values for 'Energy Densities' to the data table(s). Energy densities are determined in accordance with the regulations by fuel type and are included in the energy content (EC) portion of the compliance units formula (quantity x energy density = EC). 

There are three fuel types included that allow for custom input by the user to account for the energy density of fuel types we may not be aware of yet (other gasoline, other diesel and other jet). 

The energy densities are formatted by: Fuel type | Units | Quantity Units
*Units and quantity of units input by the user will have to handled in a way that allows for consistency and minimum administrative burden. 

The following inputs should be included in the rows for energy density:

- Fossil-derived gasoline | 34.69 | MJ/L
- Ethanol | 23.58 | MJ/L
- Renewable gasoline | 34.69 | MJ/L
- Renewable naphtha | 34.51 | MJ/L
- Other - gasoline category | user input | user input
- Fossil-derived diesel | 38.65 | MJ/L
- Biodiesel | 35.40 | MJ/L
- HDRD | 37.89 | MJ/L
- Other diesel fuel | 36.51 | MJ/L
- Other - diesel category | user input | user input
- Fossil-derived jet fuel | 37.40 | MJ/L
- Alternative jet fuel | 36.00 | MJ/L
- Other - jet fuel category | user input | user input
- Electricity | 3.60 | MJ/kWh
- Hydrogen | 141.76 | MJ/kWh
- Propane | 25.62 | MJ/L
- CNG | 38.27 | MJ/m3
- LNG | 53.54 | MJ/kg

**Purpose and Benefit to User:**

These values are part of the intended feature that enables the calculations needed in compliance reporting. Energy density is the amount of energy that can be released by a given volume of fuel. LCFS uses volumetric energy density in their formulas. The higher the energy density of the fuel, the more energy may be stored or transported for the same amount of volume. 

**Acceptance Criteria:**

- [ ] Given I am a developer, when I review the data model, then it should accurately accommodate all required values and relationships for energy densities including fuel type, units, and quantity units.
- [ ] Given I am a developer, when I implement the data model changes using an Alembic migration, then the migration should execute without errors and correctly update the database schema to include new energy density entries.
- [ ] Given I am a system administrator, when I check the database after migration, then I should see the new energy density values correctly reflected in the database tables, ensuring that all entries match the predefined values for each fuel type.
- [ ] Given I am an IDIR or BCeID user, when I access the energy density data within the compliance reporting tool, then the displayed values should accurately reflect the latest updates from the database, ensuring that calculations based on these values are correct.

**Development Checklist:**
- [ ] Ensure the data model includes all necessary fields to store energy densities by fuel type, including fields for user inputs where applicable.
- [ ] Develop an Alembic migration script to add or modify the table structure needed for storing energy densities.

**Notes:**

- This is setting up for a future feature that will allow IDIR access to edit the figures in these tables similar to the fuel code feature by using AG Grid.
- Card https://github.com/bcgov/lcfs/issues/485 has a list of Fuel types that can be helpful to building this data table.
- Card #540 has quantity units available and could be helpful for this data table.

**Comment by justin-lepitzki** [comment]
Question for the developers (to ask in refinement): do we need to add the 'other - fuel category' values to the energy density data table(s)? Need to explain the 'other' concept to the devs and how the energy density will be a user input.
