### ISSUE TITLE
LCFS - Backend data table for quantity units assigned to fuel types

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#540]
**Context**
Backend data tables are needed to store the values that go in to formulas used for calculations in the compliance reporting feature of the LCFS portal. The two formulas used are:

Compliance units:

![Image](https://github.com/bcgov/lcfs/assets/156380046/cb791931-1ec8-49b2-81eb-dcfde9fa15d3)

Target carbon intensity:

![Image](https://github.com/bcgov/lcfs/assets/156380046/61b35158-92cb-4b06-af71-f00566d2a1ff)

**Reference:**
[Calculating compliance units PDF](https://github.com/bcgov/lcfs/files/15068247/Calculating.compliance.units.2024-02-09.1.pdf)

**Description:**
This card is needed to assign quantity units to different fuel types as they are chosen in the compliance reporting function. When 
a user is reporting the supply of fuel, the report should display the corresponding unit of measure in the UI. 

Pre-populate the 'Quantity Units' (restricted to 1 choice). The following units are used through out the compliance reports:

- Litres (L)
- Kilograms (kg)
- Kilowatt-hour (kWh)
- Cubic metres (m3)

Assignment of units by fuel type include the following:

Fossil-derived gasoline | L
Ethanol | L
Renewable gasoline | L
Renewable naphtha | L
Fossil-derived diesel | L
Biodiesel | L
HDRD | L
Other diesel fuel | L
Fossil-derived jet fuel | L
Alternative jet fuel | L
Electricity |  kWh
Hydrogen | kWh
Propane |  L
CNG |  m3
LNG |  kg

**Purpose and benefit to user:**
These quantity units are part of the intended feature that enables the calculations needed in compliance reporting. Different parts of the compliance report calculation features requires different quantity units. Pre-populating these based on fuel type limits the data to these units and provides certainty to the user, rather than allowing for endless options that are not used in our calculations. 

**Acceptance Criteria:**

- [ ] as a government user, when viewing the database structure, we should be able to see the units associated with the fuel types
- [ ] as a government user, when accessing the table options api, the units should be returned with it

**Development Checklist:**
- [ ] add a new "units" column to the fuel_type table
- [ ] create an enum for the units to be added the the "units" column for the fuel_type table
- [ ] make sure these units are returned with the table options data endpoint

**Notes:**

**Comment by justin-lepitzki** [comment]
Revise this card to explain that each fuel type has an assigned unit. When reporting the supply of fuel and a use selects a fuel type, we will want to display the corresponding unit of measure in the UI.
