### ISSUE TITLE
LCFS - Make username not be case sensitive when signing up a new IDIR user

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#578]
**Describe the task**
When signing up A. Ring for a new IDIR user account for the LCFS portal, he was not able to sign-in when his IDIR username was all lowercase letters. When his username was changed to all capital letters, he reported he was able to sign-in. Can we make the IDIR username entry field not case sensitive? 

**Purpose**
The value this adds is less login errors for users or initial mapping discrepancies when setting new users up. IDIR usernames can be listed both in all lowercase letters as well as all capital letters when logging in to many systems that require IDIR login. Having a case sensitive restriction on this field when adding users may cause confusion both for the person adding the user and the person being added to the LCFS portal. 

**Acceptance Criteria**
- [x] as an IDIR user, when logging in with any combination of case letters, the user should be able to log in

**Notes**
- identify where the case check happens ( if any )
- could possibly be on the authentication side, not the lcfs platform side.

**Comment by hamed-valiollahi** [comment]
@Grulin, thank you, Lindsy, for reporting the issue. Unfortunately, I couldn't reproduce it. I used both lowercase and capital letters when signing in and also tested different combinations of case letters in the "Edit user" to reproduce the issue but wasn't able to do so. As mentioned in the description, could this issue possibly be on the authentication side, rather than the LCFS platform side?

**Comment by Grulin** [comment]
Hi @hamed-valiollahi. Thanks for looking in to this. I'm not sure if it was an authentication thing. When Al reported the login issue, the only thing I changed between him not being able to login and being able to login was his IDIR user name capitalization. I suppose we could try changing his username back to lower-case and see if he is unable to sign-in then? I'll connect with him.

**Comment by hamed-valiollahi** [comment]
@Grulin, thanks for your comment, Lindsy.

Yes, it's very weird. That's great! Please let me know if the issue still persists; I'll look into it again and will ask Alex to help me if I can't resolve it. Thank you!

**Comment by Grulin** [comment]
Hi @hamed-valiollahi. I did another test with an IDIR user to see if the case sensitive user name issue was still happening. Unfortunately, it is. If I make the username all lower case and the user tries to login in with their user name all upper case letters, they are restricted from logging in. If I make the username all uppercase and the user tries to login with their username in all lower case letters, they are restricted from logging in. The username for logging in should not be case sensitive. Let me know if you have any questions. Thanks!

**Comment by hamed-valiollahi** [comment]
@Grulin Hi Lindsy, Thank you for checking again! I appreciate it. I couldn't reproduce the exact issue but found and fixed a related problem with the email address. I also made the username check case insensitive, which should fix the issue. If it doesn't, please let me know. Thank you!

**Comment by Grulin** [comment]
Hi @hamed-valiollahi! This seems to have fixed it now. Thank you for the changes!

**Comment by hamed-valiollahi** [comment]
@Grulin Hi Lindsy, Great! I'm happy to hear that the issue is resolved. Thank you for testing!
