### ISSUE TITLE
LCFS - Validation / autosave component

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#609]
**Description:** The validation component runs as users input data. It performs a variety of predetermined functions (specific to the page/form it is being used) to ensure the user inputs data without errors. The display changes to a yellow banner with a spinning wheel as it is running, changes to pale red with an exclamation icon when there are issues, and returns to green with a checkmark icon when there are no issues. When a new record validates successfully the autosave function should run to save the new record. Records with errors don't get saved. Validation is only applied to the active row being edited, the first cell in the rows also displays the validation icon: check mark, spinning wheel, exclamation.

**Wireframe:** https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/174100805

**Purpose and benefit to user:** This feature enables the user to enter information without errors and provides feedback to help them when errors are found. It also saves the information to prevent data loss.

Error information is only provided on the red bar. The information should never exceed one line to prevent the bar expanding and contracting, making the page move around creating a very poor user experience. The red bar can be expanded by the user like an accordion to see longer messages.

**Acceptance Criteria:**

- [x] Given I am a user interacting with the validation component,
When I input data into the form/page,
Then the validation component should run predetermined functions to ensure input data without errors.

- [x] Given the validation is running,
When it is performing backend validations on each row,
Then the display should change to a yellow banner with a spinning wheel.

- [x] Given the validation detects issues with the input data,
When there are errors,
Then the display should change to a pale red banner with an exclamation icon as in the wireframe.

- [x] Given the backend and frontend validation is success,
When validation is complete,
Then the autosave function should run to save the new record.

- [ ] Given records with errors,
When validation is complete,
Then the records should not be saved.

- [ ] Given the validation component is active,
When editing a row,
Then only the active row being edited should be subjected to validation.

- [ ] Given the validation component is active,
When editing a row,
Then the first cell in the row should display the validation icon (check mark, spinning wheel, exclamation) accordingly.

- [ ] Given a validation error occurs,
When displaying error information,
Then it should only be shown on the red bar and should not exceed one line to prevent page movement.

- [ ] Given a validation error occurs,
When displaying error information,
Then the red bar should be expandable like an accordion to show longer messages.

**Development Checklist:**

- [ ] Implement predetermined functions for validation specific to the page/form.
- [x] Develop the display changes to reflect validation status (yellow banner with spinning wheel, pale red banner with exclamation icon, green banner with checkmark icon).
- [ ] Integrate autosave function to save new records upon successful validation and ensure records with errors are not saved. 
- [ ] Additionally, implement validation for the active row being edited and display validation icons in the first cell of the rows. Finally, ensure error information is displayed appropriately on the red bar and can be expanded for longer messages.

**Notes:**

**Comment by kevin-hashimoto** [comment]
Note: Autosave functionality will be separated into tickets that require the the autosave functionality. autosave has been removed from this PR

**Comment by AlexZorkin** [comment]
This has been combined with ticket #683
