### ISSUE TITLE
LCFS - Create Sorting and Filtering for Fuel Code Table

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#621]
**Description:**

Enhance the existing Fuel Code Table built with AG Grid by adding sorting and filtering capabilities. Implement backend filtering for each column and integrate it with AG Grid's frontend filtering tools.

**Acceptance Criteria:**

- **Given** the Fuel Code Table is displayed, **when** a user interacts with sorting or filtering options, **then** the table should update accordingly using backend filtering.
- **Given** a column is filtered, **when** the filter is applied, **then** the backend should process the filter and return the filtered results to the frontend.
- **Given** sorting is applied to a column, **when** the sort order changes, **then** the backend should process the sorting and return the sorted results to the frontend.

**Tasks:**

1. **Frontend Setup:**
   - Enable sorting and filtering features in AG Grid for the Fuel Code Table.
   - Configure AG Grid to use custom filtering and sorting functions.

2. **Backend Implementation:**
   - Update the backend to handle filtering and sorting requests for the Fuel Code Table.
   - Implement API endpoints that accept filtering and sorting parameters from the frontend.

3. **Integration:**
   - Connect AG Grid filtering and sorting tools with the backend API.
   - Ensure frontend filtering inputs trigger the corresponding backend API calls.
   - Update AG Grid data based on the responses from the backend.

4. **Testing:**
   - Test the sorting and filtering functionality to ensure it works correctly.
   - Validate that the backend processes filters and sorts accurately and returns the expected results.

5. **Documentation:**
   - Document the filtering and sorting implementation process.
   - Provide instructions for maintaining and updating the sorting and filtering logic.

**Development Checklist:**
- [ ] Sorting and filtering capabilities are already implemented for other parts.

**Notes:**

- Ensure the filtering and sorting logic is efficient and can handle large datasets.
- Test edge cases, such as filtering with multiple criteria and complex sorting scenarios.

**Comment by airinggov** [comment]
My mock-ups show filtering and sorting on all columns but this is not necessary, many fields are likely to require sorting/filtering. Should I try update the mock-ups to indicate this?

**Comment by AlexZorkin** [comment]
This work has already been completed.
