### ISSUE TITLE
LCFS - BUG - Last updated date field, Fuel codes

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#623]
**Describe the Bug**
The Last updated date field should not be user input, it is a system generated value when an action is taken, Save, Approve etc. There is a missing field for Approval date which is a user input field. See screen shots.

**Expected Behaviour**
- Approval date is a user entered field
- Last updated date is a system generated value that is only displayed in display mode, not edit mode.
- There are no default values for any dates, they should all be null by default

**Implications**
- Users are not able to input an Approval date which is required for the fuel code to become active
- Last updated date should not be set by the user as this would not be accurate

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir user
1. Go to Administration /  Fuel code / New fuel code
2. See error

existing error
![Image](https://github.com/bcgov/lcfs/assets/20462387/bc2e08e6-da77-4308-aac6-0135ee8b1407)

proper format
![Image](https://github.com/bcgov/lcfs/assets/20462387/db10ae5a-cc50-46ca-846e-e0db9c4c7f12)

**Comment by airinggov** [comment]
This can wait until after the AG Grid refactor work if that works better.

**Comment by airinggov** [comment]
receiving a 500 error accessing the fuel code page, the new fuel code button also gives an error

**Comment by kevin-hashimoto** [comment]
@airinggov  I believe this should be fixed on dev now. we had a problem with the seeders

**Comment by Grulin** [comment]
Last updated field in the input form for fuel codes is not aligning with the 'Fuel codes' main view table. The 'Last updated' field on the fuel code input page is reflecting today's date for all of the fuel codes in the portal; but, it **is** updating correcting in the 'Last updated' column of the main 'Fuel codes' view table:

![Image](https://github.com/bcgov/lcfs/assets/156380046/ee9415fd-11c2-483b-addb-bec2b10cd50d)

On another note, please ensure that the order of the columns are the same on the fuel code input page and in the main view table. I think we decided the moving the Last updated column further to the left like in the input table.

**Comment by Grulin** [comment]
Looking great @kevin-hashimoto

One final change: Can we please add time in PDT to the  "Last Updated" column in the view table for the fuel codes? Similar to what we have in TFRS for compliance reports. Please let me know if this is possible. Thank you!


![Image](https://github.com/bcgov/lcfs/assets/156380046/96eabc55-d99a-45e9-9c17-798fa7ae9bf2)

**Comment by kevin-hashimoto** [comment]
@Grulin i believe that's possible! I'll explore and push out another patch later today!

**Comment by Grulin** [comment]
@kevin-hashimoto Thank you!
