### ISSUE TITLE
LCFS - In reserve units should not display as a negative value

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#645]
**Description:** As any user of LCFS, In Reserve compliance unit amounts are displayed in brackets after the main balance. This number should not be prefixed with a negative symbol (-).

**Wireframe:** 
![Image](https://github.com/bcgov/lcfs/assets/20462387/ab120ec6-1dd2-4149-a8c4-bb8855415d0c)

**Purpose and benefit to user:** The negative value in unnecessary

**Acceptance Criteria:**

- [ ] Given I am a LCFS user, When I am viewing a supplier compliance unit balance, then the in reserve number in brackets does not have a negative symbol.

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by hamed-valiollahi** [comment]
The same change has also been applied to the organization balance card on the dashboard.

<img width="250" alt="Screen Shot 2024-06-04 at 10 57 04 AM" src="https://github.com/bcgov/lcfs/assets/2143103/7f210958-86fb-43f0-8430-504c537d4ca0">

**Comment by airinggov** [comment]
I guess this isn't a global fix that will apply in all areas. There are still multiple places where this is still showing up with a negative value. I take it we'll need to list every area this number is displayed to fix it everywhere?

**Comment by airinggov** [comment]
I think it is good on the BCeID side but on the IDIR side the following pages need the same fix

Idir transfer
 ![Image](https://github.com/bcgov/lcfs/assets/20462387/49280e5e-2955-45c5-9f8f-d1d0f6075c78)


Idir org index page
![Image](https://github.com/bcgov/lcfs/assets/20462387/72a89006-9eb3-492b-9be8-f7150b6d3039)


Idir org page
![Image](https://github.com/bcgov/lcfs/assets/20462387/2c886611-68da-4ee9-82fc-bdb5279c403a)


 Idir tansaction index
![Image](https://github.com/bcgov/lcfs/assets/20462387/75a83898-97fa-4e38-9cf9-eb02f4d520b3)


 Idir transaction
 ![Image](https://github.com/bcgov/lcfs/assets/20462387/a28b3bb7-d17b-490e-8bcb-e0f721fc9d21)

**Comment by hamed-valiollahi** [comment]
@airinggov Great! Thanks, Al, for checking this and listing the areas to fix. I'll move this ticket to 'In Progress' to make the changes. Thank you!

**Comment by Grulin** [comment]
Fixed in all the places Al noted. Looks great.
