### ISSUE TITLE
LCFS - Transaction format for BCeID users

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#646]
**Description:** BCeID users only see transactions after IDIR users have approved them. The format is different than the IDIR version in that it is displayed in a card.

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165578553?mode=m

**Purpose and benefit to user:**
BCeID see a simple card version of the transaction information. Certain content on the IDIR side should not be displayed.

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, When I am viewing a transaction (Initiative agreement or Administrative adjustment), then I see a simple card version of the information.
- [ ] Given I am a BCeID user, When I am viewing a transaction (Initiative agreement or Administrative adjustment) card, I should see the following information: Compliance units, effective date, comments, approved.

**Comment by airinggov** [comment]
This looks great. Two items to refine.

1. If there are no comments please just hide the Comments label and remove the text No comments provided
![Image](https://github.com/bcgov/lcfs/assets/20462387/1e3192bf-c390-484e-9f5e-eb808b11d621)

2. If there is no Effective date entered then display the Approval date as the Effective date
![Image](https://github.com/bcgov/lcfs/assets/20462387/15f28c7f-385b-4e48-9207-4635d59c0e68)

**Comment by hamed-valiollahi** [comment]
@airinggov Thank you, Al, for testing and reporting these refinement items. I'll apply the changes.

**Comment by Grulin** [comment]
Al's notes were fixed. Looks good.
