### ISSUE TITLE
LCFS - Move Fuel codes to main navigation and Analyst role

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#687]
**Description:** AS an IDIR user I should not have to be in the Administrator role to manage fuels codes.

- Add a 'Fuel codes' tab to main navigation bar between Compliance reporting and Administration.
- This new navigation tab and entire component will be accessible to the Analyst role.
- Remove Fuel code tab from the administration page navigation bar
- Remove access to the Fuel codes component from the Administrator role

**Wireframe:** <link>
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739509?mode=m&zoom=fit-to-width

**Purpose and benefit to user:**
Administration is better refined as being for user management and admin functions. Fuel codes are managed by staff that should not have other admin functions.

**Acceptance Criteria:**
- [x] Given I am a IDIR Administrator I no longer see Fuel codes as an admin option or have access to the component.
- [x] Given I am a IDIR Analyst I have access to the Fuel codes component from the main navigation.

**Development Checklist:**
- [x] A Update the main navigation bar to include a 'Fuel codes' tab between Compliance reporting and Administration.
- [x] B Ensure the 'Fuel codes' tab and its components are accessible to users with the Analyst role.
- [x] C Remove the Fuel codes option from the Administrator role's access.
- [x] D  Implement role-based access control to ensure only Analysts can manage Fuel codes.
- [x] E Test the navigation updates to confirm correct tab placement and access rights.
- [x] F Validate that the Analyst role can fully interact with the Fuel codes component as expected.
- [x] G Verify that the Administrator role no longer sees or can access the Fuel codes option.

**Notes:**

**Comment by AlexZorkin** [comment]
Code changes all look good but there is a bug when trying to add a new fuel code. On selecting the fuel code value, the app get a value error. Can you please investigate this issue.

**Comment by airinggov** [comment]
perfect, nice, thanks
