### ISSUE TITLE
LCFS - Fuel codes CI column location

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#701]
**Description:** Relocate the Carbon intensity (gCO2E/Mj)  and EDRMS# columns to display between the Fuel code and Company columns on both the display and edit tables.

**Wireframe:** 
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/168739514?mode=m

**Purpose and benefit to user:** CI is more important information and is better seen in context to the fuel code.

**Acceptance Criteria:**

- [x] Given I am aa IDIR Analyst, When I am viewing or editing fuel codes, then I see the CI and EDRMS data next to the Fuel code and before the Company/Contact information on both the display and edit tables.

**Development Checklist:**
- [x] A Update the display table layout to move the Carbon Intensity (gCO2E/MJ) column to be placed after the Fuel Code column.
- [x] B Update the display table layout to move the EDRMS# column to be placed after the Carbon Intensity (gCO2E/MJ) column.
- [x] C Update the edit table layout to move the Carbon Intensity (gCO2E/MJ) column to be placed after the Fuel Code column.
- [x] D Update the edit table layout to move the EDRMS# column to be placed after the Carbon Intensity (gCO2E/MJ) column.

**Notes:**

**Comment by Grulin** [comment]
The display table layout for fuel codes still shows the previous column order:

![Image](https://github.com/bcgov/lcfs/assets/156380046/22bdb041-4f71-4038-8bca-55cd6820a803)

Criteria A and B of this card have not been met:
A Update the display table layout to move the Carbon Intensity (gCO2E/MJ) column to be placed after the Fuel Code column.
B Update the display table layout to move the EDRMS# column to be placed after the Carbon Intensity (gCO2E/MJ) column.
