### ISSUE TITLE
LCFS - FSE date range default

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#714]
**Description:** Add a default date range for the FSE calendar select component. Have the start date as Jan 1 of the same year as the compliance report (not current year). Have the end date as Dec 31of the same year.

**Purpose and benefit to user:** This will be the most common date range so will make streamline the data entry.

**Acceptance Criteria:**

- [ ] Given I am a BCeID user with Compliance reporting role, When I am entering FSE, then date range selection component defaults to the full calendar year of the report, e.g. 2024 report: 2024-01-01 to 2024-12-31

**Development Checklist:**
- [ ] A  Ensure the FSE calendar select component can accept and display a default date range.
- [ ] B  Implement logic to determine the correct year based on the compliance report year.
- [ ] C  Set the default start date to January 1 of the report year.
- [ ] D  Set the default end date to December 31 of the report year.
- [ ] E  Update the component to dynamically adjust based on the compliance report year, not the current year.
- [ ] F  Test the component with various report years to ensure correct default date ranges are set.
- [ ] G  Ensure the component is accessible and usable for all BCeID users with the Compliance reporting role.

**Notes:**

- Confirm that the default date range does not override any user-selected dates.
- Verify the behavior when the report year is manually changed by the user.

**Comment by airinggov** [comment]
When a user changes the default date range then uses the duplicate row function it should duplicate the user entered date range, not the full year default.

**Comment by AlexZorkin** [comment]
tested and looks good now

**Comment by airinggov** [comment]
Still getting this error so can't test card

![Image](https://github.com/user-attachments/assets/2d1ea030-f595-4cda-896c-91f6c0dc461f)

**Comment by airinggov** [comment]
Changes to the default date range aren't being saved

**Comment by Grulin** [comment]
The new row (4th row) is not saving, even after all the information is entered and validated. If I return to the view page, this input is still not saved:

![Image](https://github.com/user-attachments/assets/c6a7bba8-c4a2-4964-a458-f82cacccb1d9)
