### ISSUE TITLE
LCFS - FSE, auto-generation of Registration number

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#715]
**Description:**

Card #744 must be done first to implement Organization ID.

Implement functionality to generate a unique registration number upon saving a new FSE based on the following logic:

- Organization ID: Current Organization ID, 4 character alphanumeric ID from the org table
- Postal code: Last 3 characters of PC entered of FSE
- Sequential number: 001-999, this number will reset to 001 for each different postal code change. If the number has existed previously then increment to the next number.
- example: 0055-0B9-001

**Wireframe:** <link>
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/178596806

**Purpose and benefit to user:** Each FSE will have a unique registration number as outlined in the legislation.

**Acceptance Criteria:**

- [ ] As a BCeID user with Compliance reporting role, when I am saving a new FSE row, then the system generates a unique registration number based on the Organization ID, Postal code, and a sequential number.

**Development Checklist:**

- [ ] A  Ensure the system retrieves the current Organization ID from the org table.
- [ ] B  Extract the last 3 characters of the Postal Code entered for the FSE.
- [ ] C  Implement logic to generate a sequential number (001-999) that resets with each different Postal Code.
- [ ] D  Check the existing registration numbers to determine the next available sequential number for the given Postal Code.
- [ ] E  Concatenate the formatted Supplier ID, last 3 characters of the Postal Code, and the sequential number to form the unique registration number.
- [ ] F  Check the newly generated ID against existing registration numbers to determine the ID has never been used before. If it has try the next sequential number (001-999).
- [ ] G  Validate the uniqueness of the registration number before saving the FSE row.
- [ ] H  Handle any potential edge cases, such as missing or improperly formatted Postal Codes.
- [ ] I  Update the database schema if necessary to store the unique registration numbers.
- [ ] J  Test the generation and validation of registration numbers thoroughly, including edge cases.
- [ ] K  Ensure the process is seamless and does not introduce any significant delays in saving the FSE row.

**Notes:**

**Comment by hamed-valiollahi** [comment]
Al decided to use the full postal code in the registration code to avoid issues with FSE equipment having the same second part of the postal code in different locations.
