### ISSUE TITLE
LCFS - Refine "Fuels for other use" AG grid inputs

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#723]
**Describe the task**
To fix 2 minor issues in the "Fuels for other use" AG grid table:

1) Currently the drop-down options in the "Unit" column are showing the units listed in the energy density data table. The drop-down options that should be linked to this column are found in card #540 and include:
Litres (L)
Kilograms (kg)
Kilowatt-hour (kWh)
Cubic metres (m3)

2) Create a new backend table for the already existing "Expected use" column in the "Fuels for other use" table. This table should have the drop-down options "Heating" and 'Other" only. 

**Purpose**
The reason this task is needed is refine the "Fuels for other use" input table to provide the correct units in the "Unit" column and to populate drop-down options for the "Expected use" column. 

**Acceptance Criteria**
- [ ] Given I am a user, when I interact with the "Unit" column, then I can select between the drop-down options from the Unit backend table.
- [ ] Given I am a user, when I interact with the "Expected Use" column, then I can select between "Heating" and "Other".

**Additional context**
- Wireframe: https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/178071427/simulate/sitemap

**Comment by airinggov** [comment]
- 'Expected use' select list still has no options available. 

- 'If other, enter expected use' field should be disabled by default and only enabled when 'Other' is selected from 'Expected Use'

**Comment by airinggov** [comment]
working now
