### ISSUE TITLE
LCFS - Calculate and display fuel volumes for compliance report summary (Line 1 to 3 of the report summary)

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#731]
_Dependant on completion of #717 and #752_ 

![Image](https://github.com/bcgov/lcfs/assets/156380046/50055db1-8ca9-4e33-9fd8-43d8f9f23618)

**Description:**
Implement a feature to display and calculate the volumes of fossil-derived base fuel (non-renewable) and eligible renewable fuel supplied, along with the total volume of tracked fuel supplied for each fuel class (Gasoline, Diesel, Jet Fuel) in the compliance report.

**Wireframe:** [Link](https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/169090266/simulate/sitemap)

Purpose and Benefit to User:
To provide a clear and organized view of fuel volumes for compliance summary purposes, ensuring that the volumes of fossil-derived base fuel and eligible renewable fuel are correctly displayed and calculated.

**Acceptance Criteria:**

- [ ]  Given I am a BCeID user, When I view the compliance report, then I see the total volume of non-renewable fuel supplied for the compliance period in the corresponding cells (G1, D1, J1).
- [ ]  Given I am a BceID user, When I view the compliance report, then I see the total volume of eligible renewable fuel supplied for the compliance period in the corresponding cells (G2, D2, J2).
- [ ]  Given I am a BCeID user, When I view the compliance report, then I see the total volume of tracked fuel supplied in each fuel class (G3, D3, J3).

**Development Checklist:**

- [ ]  Line 1: Calculate and display the total volume of non-renewable fuel supplied in cell G1 (Gasoline Class), D1 (Diesel Class), and J1 (Jet Fuel Class) based on the data reported in “Fuel Supply” and “Fuels for Other Use”. Note: "Allocated supply" values are not considered here because transfers downstream for fossil-derived diesel, gasoline and jet fuel are known as inter-refiner agreements and dealt with between the refineries outside our system.
- [ ]  Line 2: Calculate and display the total volume of renewable fuel supplied in cell G2 (Gasoline Class), D2 (Diesel Class), and J2 (Jet Fuel Class) based on the data reported in “Fuel Supply” and any renewable content included in "Fuels for Other Use" 
- [ ]  Line 3: Calculate and display the total volume of tracked fuel supplied by summing G1+G2, D1+D2, and J1+J2, and display the results in cells G3, D3, and J3 respectively.
- [ ]  Ensure accurate data fetching from the relevant portions of the report for all fuel classes.
- [ ]  Test the calculations to ensure they correctly sum the values and display the results in the appropriate cells.

**Notes:**
- Confirm the data sources for “Fuel Supply”, “Fuels for Other Use”, and “Allocated supply” to ensure accurate calculations.

**Comment by hamed-valiollahi** [comment]
More info on line 2 from Justin:

Eligible renewable fuels reported in 'fuels for other use' are included in the line 2 calculation.
Eligible renewable fuel types are:
(1) for gasoline category = renewable gasoline, ethanol, renewable naphtha;
(2) for diesel category = biodiesel, HDRD, other diesel fuel;
(3) for jet fuel category = alternative jet fuel
