### ISSUE TITLE
LCFS - Calculate and display net volume of eligible renewable fuel supplied (Line 10 of report summary)

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#737]
![Image](https://github.com/bcgov/lcfs/assets/156380046/50055db1-8ca9-4e33-9fd8-43d8f9f23618)

**Description:**
Implement functionality to calculate and display the net volume of eligible renewable fuel supplied for each fuel class (Gasoline, Diesel, Jet Fuel) in the compliance report. This involves summing and subtracting the values from specified cells to provide the net volume for each fuel class.

**Wireframe:** [link](https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/169090266/simulate/sitemap)

**Purpose and benefit to user:**
To provide a clear and accurate calculation of the net volume of renewable fuel supplied in the compliance period for each fuel class, aiding in compliance tracking and reporting.

**Acceptance Criteria:**
- [ ]  Given I am a BCeID user, When I view the compliance report, then cells G10, D10, and J10 display the net volume of renewable fuel supplied for the Gasoline, Diesel, and Jet Fuel classes, respectively.
- [ ]  Given I am a BCeID user, When the formula is applied, then cell G10 correctly calculates the net volume using the formula (G2 + G5 - G6 + G7 + G8 - G9).
- [ ]  Given I am a BCeID user, When the formula is applied, then cell D10 correctly calculates the net volume using the formula (D2 + D5 - D6 + D7 + D8 - D9).
- [ ]  Given I am a BCeID user, When the formula is applied, then cell J10 correctly calculates the net volume using the formula (J2 + J5 - J6 + J7 + J8 - J9).

**Development Checklist:**
- [ ] Implement the calculation formula for the Gasoline class in cell G10: (G2 + G5 - G6 + G7 + G8 - G9).
- [ ]  Implement the calculation formula for the Diesel class in cell D10: (D2 + D5 - D6 + D7 + D8 - D9).
- [ ]  Implement the calculation formula for the Jet Fuel class in cell J10: (J2 + J5 - J6 + J7 + J8 - J9).
- [ ]  Ensure that the calculations are accurate and the results are correctly displayed in the respective cells.
- [ ]  Test the calculations thoroughly to ensure they accurately reflect the net volumes based on the provided formulas.

**Notes:**
- Confirm the data in the referenced cells (G2, G5, G6, G7, G8, G9, D2, D5, D6, D7, D8, D9, J2, J5, J6, J7, J8, J9) is accurate and up-to-date.
- Coordinate with the development team to ensure the formula implementation aligns with the overall compliance reporting structure.

**Comment by Grulin** [comment]
I noted in card #733 already, but line 5 can be a negative value (transferred) or a positive value (received). Negative value should be expressed in parenthesis in the cell on line 5 and calculated in the net as such (pos/neg)

**Comment by airinggov** [comment]
confirmed calculation is correct
