### ISSUE TITLE
LCFS - Calculate and Display Non-Compliance Penalty Payable (Line 11 of report summary)

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#738]
![Image](https://github.com/bcgov/lcfs/assets/156380046/50055db1-8ca9-4e33-9fd8-43d8f9f23618)

**Description:**
Implement functionality to calculate and display the automatic non-compliance penalty payable for each fuel class (Gasoline, Diesel, Jet Fuel) in the compliance report. This involves applying the prescribed penalty rates to the difference between the required and net volume of renewable fuel supplied for each class.

Will need to add total renewable requirement penalty at some point. Will be dealt with in another card. 

**Wireframe:** [link](https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/169090266/simulate/sitemap)

**Purpose and benefit to user:**
To provide users with a clear calculation of the automatic non-compliance penalty payable, ensuring they are aware of the financial implications of not meeting renewable fuel obligations.

**Acceptance Criteria:**
- [ ]  Given I am a BCeID user, When I view the compliance report summary, then cells G11, D11, and J11 display the non-compliance penalty payable for the Gasoline, Diesel, and Jet Fuel classes, respectively.
- [ ]  Given I am a BCeID user, When the formula is applied, then cell G11 correctly calculates the penalty using the formula (G4 - G10) x $0.30.
- [ ]  Given I am a BCeID user, When the formula is applied, then cell D11 correctly calculates the penalty using the formula (D4 - D10) x $0.45.
- [ ]  Given I am a BCeID user, When the formula is applied, then cell J11 correctly calculates the penalty using the formula (J4 - J10) x $0.50.

**Development Checklist:**
- [ ]  Implement the calculation formula for the Gasoline class in cell G11: (G4 - G10) x $0.30.
- [ ]  Implement the calculation formula for the Diesel class in cell D11: (D4 - D10) x $0.45.
- [ ]  Implement the calculation formula for the Jet Fuel class in cell J11: (J4 - J10) x $0.50.
- [ ]  Ensure that the calculations are accurate and the results are correctly displayed in the respective cells.
- [ ]  Test the calculations thoroughly to ensure they accurately reflect the penalty amounts based on the provided formulas.

**Notes:**
- Confirm the data in the referenced cells (G4, G10, D4, D10, J4, J10) is accurate and up-to-date.
- Coordinate with the development team to ensure the formula implementation aligns with the overall compliance reporting structure.

**Comment by Grulin** [comment]
Looks great. Only note is that these values should be shown with a dollar sign in front of it as a dollar value

**Comment by airinggov** [comment]
Line 11 still not displaying with dollar symbol.
