### ISSUE TITLE
LCFS - Calculate and display available compliance unit balance for the compliance period (Line 17 of the compliance report summary)

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#756]
**Description:**
Implement functionality to calculate and display the available compliance unit balance for the compliance period. This involves pulling data from previous compliance reports to account for positive compliance units carried forward, subtracting any future debits recorded in the system, and ensuring the final balance is not negative.

**Wireframe:** [Link](https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/179634499/simulate/sitemap)

**Purpose and benefit to user:**
To provide users with an accurate and clear view of their available compliance unit balance, ensuring they can monitor and manage their compliance obligations effectively. This helps avoid penalties by ensuring users are aware of their unit balance status.

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, When I view the compliance report, then I see the available compliance unit balance displayed in Line 17.
- [ ]  Given I am a BCeID user, When the system pulls data from previous compliance reports, then it accurately adds positive compliance units carried forward year by year and subtracts any future debits recorded in the system.
- [ ]  Given I am a BCeID user, When there is no previous compliance report available, then the system calculates the balance by taking the current positive compliance units reported minus the current negative compliance units reported and displays the remaining balance.
- [ ]  Given I am a BCeID user, When I view Line 17, then the balance displayed is never negative. If the calculation results in a negative balance, the system will instead display zero and trigger an automatic penalty for the current period.

**Development Checklist:**

- [ ]  Implement logic to pull data from previous compliance reports to account for positive compliance units carried forward and subtract any future debits recorded in the system.
- [ ]  Develop a fallback mechanism to calculate the balance using current compliance unit data if no previous report is available.
- [ ]  Ensure the balance displayed in Line 17 is never negative. If the balance is negative, display zero and trigger an automatic penalty.
- [ ]  Test data retrieval, calculation logic, and display to ensure accuracy and proper functionality.

**Notes:**

- Confirm the data retrieval process from previous compliance reports for accurate calculation.
- Ensure the system can handle cases with no previous compliance reports by correctly calculating the balance using current data.

**Comment by Grulin** [comment]
Tested and this is currently still reflecting the balance of the total balance, rather than the available balance for this specific year (I was testing 2024). The available balance should only reflect what is available for this year (2024 for this example).

 This includes:
+ validations or compliance unit balance changes from assessments listed with a 2024 or prior compliance period
-reductions listed with a 2024 or prior compliance period
+compliance units purchased through credit transfers with and effective date on or before March 31st, 2025
-compliance units sold through credit transfer with an effective date on or before March 31st, 2025
+compliance unites issued under IA/P3A with an effective date on or before March 31st, 2025
+/- admin adjustments with an effective date on or before March 31st, 2025
-all future debits (such as transfers or reductions)

**Comment by Grulin** [comment]
Hi @prv-proton. Thanks for reaching out about this. I can give you an example of this that we recently worked on to better illustrate this calculation. You know the query in Metabase that you helped me with that shows the year by year of units remaining? This available balance calculation adds an additional step to that calculation. I'm going to share the example with you directly through Teams, but wanted to document the comment here on the card for future use.

**Comment by prv-proton** [comment]
> Tested and this is currently still reflecting the balance of the total balance, rather than the available balance for this specific year (I was testing 2024). The available balance should only reflect what is available for this year (2024 for this example).
> 
> This includes:
> 
>     * validations or compliance unit balance changes from assessments listed with a 2024 or prior compliance period
>       -reductions listed with a 2024 or prior compliance period
>       +compliance units purchased through credit transfers with and effective date on or before March 31st, 2025
>       -compliance units sold through credit transfer with an effective date on or before March 31st, 2025
>       +compliance unites issued under IA/P3A with an effective date on or before March 31st, 2025
>       +/- admin adjustments with an effective date on or before March 31st, 2025
>       -all future debits (such as transfers or reductions)

Hi @Grulin , for admin adjustments and initiative agreements, should we only consider the approved transactions?

**Comment by Grulin** [comment]
Difficult to test as a front end user because we are limited by how far ahead or behind we can report. Will collaborate with the dev team to figure out how to test if this is working the way it is intended to.
