### ISSUE TITLE
TFRS - Delete duplicate organization #1032

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#771]
**Describe the task**

- Please delete an organization account in TFRS that was created as a duplicate by mistake. Organization ID is #1032. 
- They have submitted a compliance report that should also be deleted #3187
- Any guid attached to user ID #2035 should be deleted to allow for it to be attached to the original organization account still in TFRS, not the accidentally made one. We will request that they resubmit their 2023 compliance report to the correct account. 

**Purpose**
Continue to keep TFRS clean of unnecessary accounts or confuse analysts with any duplicates. 

**Acceptance Criteria**
- [ ] 

**Additional context**

**Comment by AlexZorkin** [comment]
@Grulin For this supplier there is a credit trade validation that was approved August 22, 2023. Should this be cleaned up as well?

**Comment by Grulin** [comment]
Have reached out to the supplier asking them to re-submit their report in the original TFRS account, rather than the newly added one. Have migrated their user account over already.
