### ISSUE TITLE
LCFS - Display result of organization's compliance unit change after assessment (Line 20 of the compliance summary section)

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#779]
**Description:**
Add functionality to display the total balance change in compliance units for the current compliance period. This line will show the number of compliance units added to or subtracted from the organization's balance. This line should reflect a summary of unit change for the compliance report. 
- Please refer to the TFRS Low Carbon Fuel Requirement Summary for this calculation. 

**Wireframe:** [Link](https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/169090266/simulate/sitemap)

**Purpose and benefit to user:**
To provide users with a clear and comprehensive view of their compliance unit change resulting only from the current period, ensuring transparency and accuracy in reporting the final compliance status.

**Acceptance Criteria:**

- [ ]  Given I am a BCeID user, When I view the compliance report, then I see the total balance change for the current compliance period displayed in Line 20.
- [ ]  Given I am a BCeID user, When the system calculates the balance change, then it accurately reflects the number of compliance units added to or subtracted from the organization's balance.
- [ ]  Given I am a BCeID user, When the compliance period ends, then the final balance change is clearly displayed in Line 20.

**Development Checklist:**

- [ ]  Implement logic to calculate the total balance change in compliance units for the current compliance period.
- [ ]  Ensure the system retrieves accurate data to determine the number of compliance units added to or subtracted from the organization's balance.
- [ ]  Display the calculated balance change in Line 20.
- [ ]  Test the calculation logic, data retrieval, and display to ensure accuracy and proper functionality.

**Notes:**

- Confirm the data retrieval process for the required lines.
- Ensure the calculation is accurately implemented and tested for various scenarios.
- Verify the accuracy and clarity of the displayed balance change for users.

**Comment by Grulin** [comment]
This line doesn't seem to be functioning just yet? Is it being held up by one of the other summary lines (maybe line 17 needs to happen first?)

**Comment by hamed-valiollahi** [comment]
> This line doesn't seem to be functioning just yet? Is it being held up by one of the other summary lines (maybe line 17 needs to happen first?)

Thanks for testing!
Yes, you're right, Lindsy! Line 20 is the sum of Line 18 and Line 19, but they are not implemented yet.

**Comment by Grulin** [comment]
Thanks, @hamed-valiollahi. It looks like line 18 is working now, so this is only blocked by line 19 which has been tested with issues. I'll leave this card here for now.

**Comment by hamed-valiollahi** [comment]
Sure, thanks for the update, Lindsy!
