### ISSUE TITLE
LCFS - Fuel export backend data table

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#823]
### Description
- **Objective**: Ensure database schema alignment and extend the backend capabilities to include API endpoints for managing entries in the 'Export fuel' data table.
- **Frontend Interaction**: Users will be able to add, update, and delete records through the frontend interface.

Here's the formatted description of the input form fields for the "Export fuel" feature (same as fuel supply with addition of a date field):

### Input Form Fields:
1. **Export Date**
   - **Input Type**: Date picker
   - **User Interaction**: Can select or type date in yyyy-mm-dd format

2. **Fuel Type**
   - **Input Type**: Drop-down menu
   - **Options**: from lookup table
   - **User Interaction**: No input allowed

3. **Fuel Type Other**
   - **Input Type**: Free form text. 
   - **Condition**: Hidden by default. Appears only if 'Other' is chosen in the 'Fuel Type' drop-down menu.
   - **User Interaction**: Predictive text from existing values.
   - **Notes**: We might consider saving values input here in the Fuel type table with a flag to exclude them from the main drop down. This flag could be removed later to be ‘activated’ in the main list. See card #850 

4. **Fuel Category**
   - **Input Type**: Drop-down menu
   - **User Interaction**: auto-selected locked field if only 1 available category, otherwise user must select, No input allowed

5. **End Use**
   - **Input Type**: Drop-down menu
   - **Options**: from lookup table
   - **User Interaction**: No input allowed

6. **Determining carbon intensity**
   - **Input Type**: Drop-down menu
   - **Options**: from lookup table
   - **User Interaction**: No input allowed

7. **Fuel code**
   - **Input Type**: Drop-down menu
   - **Options**: from lookup table
   - **User Interaction**: Enabled only if Approved fuel code is selected in Determining carbon intensity. No input allowed

8. **Quantity Supplied**
   - **Input Type**: Free form text
   - **Validation**: Numbers only, no decimals, cannot be negative

9. **Units**
   - **Input Type**: Drop-down menu
   - **User Interaction**: auto-selected locked field if only 1 available unit, otherwise user must select, No input allowed

10. **Compliance Units**
   - **Field Type**: Free form text
   - **User Interaction**: None, auto-calculated value, locked field. Calculated using the Quantity Supplied, uses the formula set out in regulation, No input allowed.
   - **Notes**: Value saved in table as we don’t want these being continually calculated. Cannot be positive, must zero or neagative.

11. **CI limit**
   - **Field Type**: Read only text
   - **User Interaction**: None, auto-populated from look-up table based on the year of the report, the Fuel type and Fuel category selected, No input allowed.

12. **CI of fuel**
   - **Field Type**: Read only text
   - **User Interaction**: None, auto-populated from look-up table based on the Fuel type and Determine CI selected, No input allowed.

13. **Energy density**
   - **Field Type**: Read only text
   - **User Interaction**: None, auto-populated from look-up table based on fuel type and Fuel category, No input allowed.

14. **EER**
   - **Field Type**: Read only text
   - **User Interaction**: None, auto-populated from look-up table based on the year of the report, the Fuel type and Fuel category selected, No input allowed.

15. **Energy**
   - **Field Type**: Read only text
   - **User Interaction**: None, auto-calculated based on the Quantity supplied entered by user, uses the formula set out in regulation, No input allowed.

### Development Requirements 
1. **Database Schema Verification**:
   - **Check Existing Tables**: Verify that the existing database schema for 'Export fuel' aligns with the new requirements. Ensure that all fields are correctly defined and match the needs of the input forms and API endpoints.

2. **Create API Endpoints**:
   - **POST /fuels/export-fuel**: Endpoint to add a new row to the database. Accepts JSON payload with details for a new entry and performs validation checks.
   - **PUT /fuels/export-fuel/{id}**: Endpoint to update an existing row. Validates the input against existing schema and updates the database if valid.
   - **DELETE /fuels/export-fuel/{id}**: Endpoint to delete an existing row based on the provided unique identifier.

3. **Input Validation**:
   - Ensure that 'Quantity Supplied' is a non-negative number with no decimals.
   - Validate that dropdown menu selections are among the predefined options.
   - Conditional input validation for 'Fuel Type Other' to ensure it is active only when 'Other' is selected in the 'Fuel Type' dropdown.

4. **Testing**:
   - Develop unit tests to ensure that each endpoint correctly handles various input scenarios.
   - Implement integration of tests to verify the interaction between the frontend and backend.

### Acceptance Criteria
- **Schema Validation**: The existing database schema must match the requirements for the new data entries.
- **Functionality**: Each endpoint correctly handles create, update, and delete operations.
- **Validation**: All input is validated before database insertion; proper error messages are returned for invalid inputs.
- **Frontend Integration**: The frontend should correctly display the updated data table upon successful operations and provide feedback on any error.

**Comment by Grulin** [comment]
Hi @airinggov. To answer your question about if end uses for the export schedule, section 17 (1) (b) (ii)  of the technical regulation states that the end use of an export should be reported if relevant to calculating the issuance of debits under the Act: 

_(ii)if the end use of the fuel is relevant to the calculation of compliance units under section 17 [export of fuel] of the Act, a list of the end uses for which the fuel was reportably supplied and the amount of the fuel reportably supplied for each those end uses;_

I also found this in the documenting new Act concepts document that Justin had. Hopefully this helps the devs with the formula for debits issued upon export:

Compliance units=(TCI* EER-(RCI+UCI)) x ((Q*ED))/1,000,000
where,
	TCI = target carbon intensity (formerly carbon intensity or CI limit)
	EER = energy effectiveness ratio
	RCI = recorded carbon intensity (formerly CI fuel)
	UCI = additional carbon intensity attributable to use
	Q = quantity or volume of fuel supplied
	ED = energy density

Exported fuel receives compliance units in accordance with the compliance unit formula above multiplied by negative one, but only if the resulting value is negative compliance units (debits).

**Compliance units for exported fuel=Compliance units* (-1)**
