### ISSUE TITLE
LCFS - Fuel export input form

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#824]
**Description:**
As a fuel supplier, I must report fuel that I marketed or supplied in B.C. and then exported out of the province.

The Fuel export form is nearly identical to the Fuel supply form with an additional date field at the beginning for the Export date. The final Compliance unit calculation will also be amended to include the following ensuring a negative value.

- Compliance units for exported fuel=Compliance units∗ (−1)

Compliance units=(TCI* EER-(RCI+UCI)) x ((Q*ED))/1,000,000
where,
TCI = target carbon intensity 
EER = energy effectiveness ratio
RCI = recorded carbon intensity (CI of Fuel = (RCI+UCI))
UCI = additional carbon intensity attributable to use (CI of Fuel = (RCI+UCI))
Q = quantity or volume of fuel supplied
ED = energy density

**Wireframe:** https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/182448170?mode=m

**Purpose and benefit to user:**
To ensure accurate and compliant reporting.

**Acceptance Criteria:**
- [ ] Given I am a fuel supplier, When I am selecting an Export date, then I can choose from a calendar widget or type ina date in yyyy-mm-dd format.
- [ ] Given I am a fuel supplier, When I am selecting a fuel type, then I can only choose from a predefined list pulled from a look-up table.
- [ ] - [ ] Given I am a fuel supplier, When I am selecting a fuel type, Units is auto-populated from look-up table based on Fuel type selected, as locked field or a select list when multiple options available, no user input 
- [ ] Given I am a fuel supplier, When I select 'Other' in the fuel type, then the Fuel type other field is enabled.
- [ ] Given I am a fuel supplier, When I enter a value in the Fuel type other field, then the value is stored in the Fuel type table with a flag for future activation.
- [ ] Given I am a fuel supplier, When I select a fuel type, then the Fuel category is auto-populated based on the selected fuel type.
- [ ] Given I am a fuel supplier, When I select Determining carbon intensity if I select Approved fuel code, then the Fuel code field is enabled. Fuel codes are pulled from the Fuel codes table. 
- [ ] Given I am a fuel supplier, When I enter the quantity supplied, then the value is restricted to numbers only with no decimals or negative values.
- [ ] Given I am a fuel supplier, When I enter Energy density, then the value cannot be negative and is restricted to two decimal places. This field is only enabled when Fuel type ‘Other’ is selected.
- [ ] Given I am a fuel supplier, As I complete the report, then Compliance units, Target CI, CI of fuel, Energy density, EER, and Energy are auto-calculated or auto-populated based on the entered data and look-up tables. TFRS can be used as a high-fidelity prototype that shows how fields are populated as the user enters data.

**Development Checklist:**

- [ ] Enable Fuel type other field when 'Other' is selected and save entered values in the Fuel types table with a flag to indicate ‘Other’. Tagged fuels won’t be displayed in the regular Fuel types select list. They will be used as predictive text in the Fuel type other field.
- [ ] Enable Energy density field for user input when Fuel type 'Other' is selected
- [ ] Auto-populate Fuel category based on the selected Fuel type.
- [ ] Enable Fuel code field when an Approved fuel code is selected. If only one code auto populate the field as locked or if multiple implement a select list.
- [ ] Restrict quantity supplied to numbers only, no decimals or negative values.
- [ ] Restrict energy density input to positive numbers with two decimal places.
- [ ] Auto-calculate and auto-populate Compliance units, Target CI, CI of fuel, Energy density, EER, and Energy based on entered data and look-up tables.

**Notes:**
- The Fuel type other field should have predictive text based on previously entered values. Fuel type Other can have an associated fuel code.
- Ensure all auto-populated and auto-calculated fields are accurate and consistent with regulatory requirements.

**Comment by airinggov** [comment]
I think the Compliance unit calculation may just need the (*-1) added to complete the calculation. Positive values are not possible for export, it must be zero or a negative result.

**Comment by Grulin** [comment]
I will add to this:

I think we should display the total result of the calculation (including the final *-1) in the compliance unit cell/column for exports regardless of if they are positive or negative, but only the negative result rows should be included in the summary total (line 19). 

For example, 

if the supplier has 4 export lines resulting in compliance units like this:
line 1= 100
line 2 = -200
line 3 = 100
line 4 = -300

Only line 2 and 4  would be included in the line 19 summary as -500. This is because we do not issue positive units (credits) for exported fuel, but suppliers should still be encouraged to report these fuels in the export schedule. It's only in the export summary line that the negative values from this schedule are included.

**Comment by airinggov** [comment]
Closing this card. Will create a new card to address the calculation preferences after more discussion.
