### ISSUE TITLE
LCFS - Import production Fuel code data into dev

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#828]
**Describe the task**
Import Fuel code data from the TFRS production database into the LCFS dev database

**Purpose**
This will help provide more realistic testing. The data is not sensitive information.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by airinggov** [comment]
Fuel codes don't appear in dev

**Comment by hamed-valiollahi** [comment]
Thank you, Al, for testing the ticket.

I’ve already implemented the solution, and the fuel code data is ready to be imported. However, after Alex reviewed my PR, he mentioned that we shouldn't import the data just yet. Here’s his comment:

> We will have to figure out the proper order of operation on these table migrations so we can ensure that create_user, and update_user entries are transferred correctly. Something to think about later.

I apologize for not mentioning this in the ticket before testing.

**Comment by airinggov** [comment]
Thanks Hamed, makes sense. Could we just insert my IDIR into these fields on the DEV site? When we import data into PROD we'll need to use the proper data.

**Comment by hamed-valiollahi** [comment]
Of course! I’ve imported the fuel code data into the dev environment. Thanks, Al!
