### ISSUE TITLE
LCFS - Allocation agreement input form predictive text of Legal name

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#875]
**Description:** 
As a BCeID user the Allocation agreement input form should provide predictions of Legal name of transaction partner. As I type in the field it should start giving options after typing three characters. If I select one of these options the Address field should be auto-filled from the company info 'Address for service'.

**Wireframe:**
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/180146525?mode=m

**Purpose and benefit to user:**
This helps keep data integrity and consistency. 

**Acceptance Criteria:**

- [ ] Given I am a BCeID, When I am filling out the Legal name of transaction partner field, there should be predictive text that lists companies. This field is also free form.
- [ ] Given I am a BCeID, When I am filling out the Legal name of transaction partner field and choosing a suggested company, the address field should be auto-filled from the company info 'Address for service'. This field is also free form and will allow edits to predicted text although edits here will not impact the original value. Address for service should comprise of the fields: Street address, Address other, City, Province, Country and Postal code.

**Comment by airinggov** [comment]
I'm not getting any predictive text appearing

**Comment by hamed-valiollahi** [comment]
> I'm not getting any predictive text appearing

Hi Al, I tested it on dev, and it works. You can start typing 'lcfs', and you'll see suggestions after entering 3 characters.

**Comment by airinggov** [comment]
Ah right, looks good, I was using wrong company info

**Comment by hamed-valiollahi** [comment]
Great! Thanks for testing the ticket, Al 👍
