### ISSUE TITLE
LCFS - Port Organization Django DB Models to SQLAlchemy Models in FastAPI

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#89]
**Describe the task**
Port the Django database models for organization, organization address, organization type, and organization status to SQLAlchemy models in FastAPI.

**Purpose**
The purpose of this task is to migrate the existing Django database models to SQLAlchemy models in FastAPI. This will enable the application to utilize SQLAlchemy's features and benefits, such as improved performance, database abstraction, and compatibility with different database backends.

**Acceptance Criteria**
 - [ ]  Create SQLAlchemy models for organization, organization address, organization type, and organization status.
 - [ ]  Make sure to use SQLAlchemy's declarative base class for defining the models. 
 - [ ]  Map the SQLAlchemy models to the corresponding database tables.
 - [ ]  Define the relationships and foreign keys between the models.
 - [ ]  Implement CRUD (Create, Read, Update, Delete) operations for the organization model.
 - [ ]  Ensure the SQLAlchemy models and database operations are correctly integrated into the existing FastAPI application.
 - [ ] Test the functionality of the ported models by creating, reading, updating, and deleting records in the organization, organization address, organization type, and organization status tables.
 - [ ]  Ensure all tests pass successfully.
 - [ ]  Update the documentation or code comments as necessary to reflect the changes made during the porting process.

**Additional context**
The existing Django database models should serve as a reference for creating the SQLAlchemy models.Pay attention to the table relationships and foreign keys when designing the models. It's recommended to follow the existing coding style and conventions in the FastAPI project.

**Comment by kcabhar** [comment]
No need for testing as this is set up for new LCFS
