### ISSUE TITLE
LCFS - Refine the renewable requirement summary section to exclude certain fuel types

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#895]
**Describe the task**
Refine the Renewable requirement summary section of the compliance report to ensure that certain fuel types are excluded from the calculations. Specifically, lines 1, 2, 5, 6, and 7 should not include the following fuel types: Electricity, Hydrogen, Propane, CNG (Compressed Natural Gas), and LNG (Liquefied Natural Gas), as these are not subject to the renewable requirement under the Low Carbon Fuels Act. Instead, these fuel types are only subject to the low carbon fuel requirement.

**Purpose**
To ensure the Renewable requirement summary accurately reflects the fuel types that are subject to the renewable requirement and correctly distinguishes those that are only subject to the low carbon fuel requirement, in compliance with the Low Carbon Fuels Act.

**Acceptance Criteria**

- [ ]  Line 1 does not include Electricity, Hydrogen, Propane, CNG, and LNG.
- [ ]  Line 2 does not include Electricity, Hydrogen, Propane, CNG, and LNG.
- [ ] Line 5 does not include Electricity, Hydrogen, Propane, CNG, and LNG.
- [ ]  Line 6 does not include Electricity, Hydrogen, Propane, CNG, and LNG.
- [ ]  Line 7 does not include Electricity, Hydrogen, Propane, CNG, and LNG.
- [ ]  The summary clearly indicates that these fuel types are only subject to the low carbon fuel requirement.
- [ ]  The summary is reviewed to ensure alignment with the Low Carbon Fuels Act.

**Additional context**

**Comment by dhaselhan** [comment]
@Grulin How do we filter Line 5 (notional transfers)? Currently notional transfers do not have a fuel type associated to them only a category.

**Comment by dhaselhan** [comment]
@Grulin For the last requirement "The summary clearly indicates that these fuel types are only subject to the low carbon fuel requirement." Where in the UI do we want to indicate which types are subjected?
