### ISSUE TITLE
LCFS - Refine line 6 of the compliance report summary conditions

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#896]
**Describe the task**
Update line 6 of the "Compliance Report Summary" section to allow for input under the following condition:
a) When an organization has supplied specific types of renewable fuels, categorized as:

- Gasoline Category: Renewable Gasoline, Ethanol, Renewable Naphtha.
- Diesel Category: Biodiesel, HDRD (Hydrotreated Renewable Diesel), Other Diesel Fuel.
- Jet Fuel Category: Alternative Jet Fuel.

and 

b) When an organization has exceeded the renewable volume requirement on line 4 of the summary

**Purpose**
To enhance line 6 of the "Compliance Report Summary" to allow a supplier to retain a surplus of renewable fuel content, up to 5% of line 4, provided that they have exceeded the renewable requirement specified on line 4 of the summary. 

**Acceptance Criteria**

- [ ]  Line 6 allows for input only when the organization has exceeded the renewable requirement specified on line 4 of the summary.
- [ ]  Line 6 provides an option for suppliers to retain a surplus of renewable fuel content, up to a certain percentage.
- [ ]  Ensure input fields are correctly categorized and validated for compliance reporting purposes.
- [ ]  The updated line 6 is reviewed and confirmed to meet regulatory requirements and aligns with the Low Carbon Fuels Act.

**Additional context**
Validate that exceeding the renewable requirement on line 4 triggers the input availability and retaining options on line 6.

**Comment by Grulin** [comment]
Card #895 should be completed first

**Comment by dhaselhan** [comment]
@Grulin Do I need to exceed the requirements by the amount I am going to retain? e.g. Required (line 4) is 1,000 and I exceed it (line 5) with 1,020. Can I still enter 50 in line 6 or is line 6 capped at 20? (e.g. Line 6 is capped at the minimum of Line 5 - Line 4 or 5% of line 4)
