### ISSUE TITLE
LCFS - Implement User Authentication with Keycloak in FastAPI Project

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#90]
**Describe the task**
Implement user authentication using Keycloak in the new FastAPI project.

**Purpose**
The purpose of this task is to enable user authentication in the FastAPI project by integrating it with Keycloak. Keycloak provides a robust and secure authentication and authorization solution, allowing users to authenticate using various identity providers and enabling fine-grained access control to the application's resources.

**Acceptance Criteria**
- [ ] Integrate the FastAPI project with Keycloak for user authentication.
- [ ] Implement the necessary endpoints and logic in the FastAPI project to handle user registration, login, and logout.
- [ ] Secure the project's API endpoints to require authentication for accessing protected resources.
- [ ] Implement authorization checks to restrict access to specific endpoints based on user roles or permissions.
- [ ] Write tests to verify the functionality of the user authentication and authorization mechanisms.
- [ ] Ensure all tests pass successfully.
- [ ] Update the documentation or code comments as necessary to reflect the changes made during the implementation.

**Additional context**
The Keycloak documentation should be consulted to understand the required configuration and API endpoints for integrating Keycloak with the FastAPI project. It is recommended to use appropriate Keycloak client libraries or SDKs for easier integration.

**Comment by kcabhar** [comment]
Alex estimates 2 going into Klefki

**Comment by AlexZorkin** [comment]
Initial round of work complete and merged to repo.
