### ISSUE TITLE
LCFS - Implement User Roles and Permissions in FastAPI System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#91]
**Describe the task**
Implement user roles and permissions in the new FastAPI system. This involves creating the necessary database tables (Role, UserRole) in PostgreSQL and porting them from the existing Django models. Additionally, various permissions need to be implemented throughout the application.

**Purpose**
The purpose of this task is to establish a role-based access control system in the FastAPI system, allowing fine-grained control over user permissions. By implementing user roles and permissions, the application can control user access to specific features, actions, or resources based on their assigned roles.

**Acceptance Criteria**
- [ ] Create the required database tables (Role, UserRole) in PostgreSQL to manage user roles and permissions.
- [ ] Port the Django models for Role and UserRole to SQLAlchemy models in the FastAPI system.
- [ ] Define the relationships and foreign keys between the role and user models.
- [ ] Research existing role management solutions in FastAPI and suggest the best approach to use for wrapping backend methods with permissions.
- [ ] Implement the necessary endpoints and logic to assign roles to users.
- [ ] Implement a mechanism to enforce permissions throughout the application based on user roles.
- [ ] Write a test endpoint that features the required appropriate permissions for accessing or modifying a resource.
- [ ] Write tests to verify the functionality of the role and permission management system.
- [ ] Ensure all tests pass successfully.
- [ ] Update the documentation or code comments as necessary to reflect the changes made during the implementation.

**Additional context**
The existing Django models for Role and UserRole should serve as a reference for creating the SQLAlchemy models. Consider using SQLAlchemy's declarative base class for defining the models. Pay attention to the table relationships and foreign keys when designing the models. It's recommended to follow the existing coding style and conventions in the FastAPI project. The specific permissions required in different parts of the application should be identified and implemented according to the application's access control requirements.

**Comment by kcabhar** [comment]
Prashanth estimates 3 going into Klefki

**Comment by prv-proton** [comment]
updated reivew comments
