### ISSUE TITLE
LCFS - Port and Enhance Credit Trade Related Tables with Compliance Units in FastAPI System

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#92]
**Describe the task**
Port the following tables related to Credit Trades from the existing system to the FastAPI system: CreditTrade, CreditTradeComment, CreditTradeHistory, CreditTradeStatus, CreditTradeZeroReason, and CreditTradeType. Additionally, implement a new feature called Compliance Units, which changes the way credits and debits are handled to be one unit rather than separate entities.

**Purpose**
The purpose of this task is to migrate the Credit Trade related tables from the existing system to the FastAPI system while incorporating the new feature of Compliance Units. Compliance Units enhance the credit trading functionality by unifying credits and debits into a single unit, providing a more streamlined and efficient process.

**Acceptance Criteria**
- [ ] Create SQLAlchemy models for the CreditTrade, CreditTradeComment, CreditTradeHistory, CreditTradeStatus, CreditTradeType, CreditTradeZeroReason, and ComplianceUnit tables.
- [ ] Map the SQLAlchemy models to the corresponding database tables.
- [ ] Define the relationships and foreign keys between the models as per the existing system.
- [ ] Implement CRUD operations for the CreditTrade model that existed in the previous applicaiton.
- [ ] Implement CRUD operations for the CreditTradeComment model, enabling the management of trade-related comments.
- [ ] Modify the credit and debit handling mechanism in the CreditTrade model to utilize compliance units instead of separate entities.
- [ ] Ensure the SQLAlchemy models and database operations are correctly integrated into the existing FastAPI application.
- [ ] Test the functionality of the ported models and compliance units by performing various credit trade operations.
- [ ] Ensure all tests pass successfully.
- [ ] Update the documentation or code comments as necessary to reflect the changes made during the porting process.

**Additional context**
The existing system's database schema and Django models for the Credit Trade related tables should be referred to when creating the SQLAlchemy models. Pay attention to the existing credit and debit handling mechanism and modify it to incorporate compliance units. Compliance units unify credits and debits, providing a more efficient and streamlined process. Consider the impact on existing workflows and adjust them accordingly. It's recommended to follow the existing coding style and conventions in the FastAPI project.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/92?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745
