### ISSUE TITLE
LCFS - Recommend Record and Recommend Refuse visible to Director

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#921]
* Log in as director
* View a transfer in the submitted status that has not been recommended

Expected:
Director cannot take any actions on the report until is is recommended

Actual:
Director can see radio buttons for recommend / refuse, but no save button and buttons do nothing

**Comment by Grulin** [comment]
When signed in as a director, I can still see the radios buttons for "Recommend record" and "Recommend refuse". This should not be the case. For transfer in "Submitted" status, the director should have no action available. Currently in the Portal, the director sees this:
![Image](https://github.com/user-attachments/assets/13d4a836-abc8-4cd9-88bc-9c3b17fde9ea)

In TFRS, the director can view a submitted transfer, but take no action until an analyst has recommended recording the transfer. This is what the director screen of a submitted transfer looks like in TFRS:
![Image](https://github.com/user-attachments/assets/e5278bf2-0ad5-43c2-a15e-e0c93e320ea3)
