### ISSUE TITLE
LCFS - Transaction table view order

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#927]
**Describe the task**
Implement a feature that allows transactions to be filtered in the view table with the most recent transaction appearing at the top. This task involves modifying the transaction view table to sort the transactions in descending order based on the date and time of the transaction, including when there is a status change in the transfer. Please re-order by last updated. 

**Purpose**
To enhance user experience by ensuring that users can quickly view the most recent transactions without needing to manually sort or scroll through older data.

**Acceptance Criteria**

- [ ] The transaction view table should automatically display transactions sorted by the most recent date and time in descending order.
- [ ] The sorting should be applied by default whenever the user accesses the transaction view table.
- [ ] Users should be able to change the sorting order if desired, but the default should always be the most recent transactions at the top.
- [ ] Changes should persist across sessions unless manually altered by the user.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Grulin** [comment]
Not sure if this is working for every test account and every transaction status. For example, I did this one and the status changed, but the transaction still ended up in the middle of the table:

![Image](https://github.com/user-attachments/assets/ef0b3b2c-abe4-4154-8da2-14d1984e7f17)

How we want this feature to work is that if a status change happens (in this example, the transaction was rescinded) the transaction moves to the top of this view table as filtered by the "Lastest Update" column. Please let me know if you have any additional questions.

**Comment by dhaselhan** [comment]
As per your screenshot looks like you are currently sorting by the ID column. If the user has a set another kind of sorting (such as ID) this is currently saved on the browser and it will remember the sorting. The easiest way to test this would be Incognito mode.

**Comment by Grulin** [comment]
@dhaselhan you are correct, this is working! Good catch. Thank you
