### ISSUE TITLE
LCFS - Update Fuel Code PyTests and Align Test Filenames

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#938]
**Purpose:**  
To ensure the Fuel Code API tests are up to date with the latest changes in the Fuel Code API files and that each test file matches the corresponding file it is testing in the `fuel_code/` directory.

**Acceptance Criteria:**
- [ ] Review the current Fuel Code API files to identify changes in methods and logic.
- [ ] Update the test files to reflect the correct methods and signatures from the latest API code.
- [ ] Ensure mock data and assertions align with the current API implementation.
- [ ] Verify all Fuel Code API tests pass after updates.
- [ ] Rename test files to match the corresponding API files in the `fuel_code/` directory.

**Additional Context:**
- The previous test files might include references to outdated methods, which should be updated to reflect the latest API logic.
- Test logic should be rewritten to account for any changes in method arguments or return values.
- Ensure all test filenames align one-to-one with the corresponding API files for better organization.

**Comment by prv-proton** [comment]
@RebekahRFord , after code merge some of the functionalities were broken, working on fixing it.
https://github.com/bcgov/lcfs/pull/1063
