### ISSUE TITLE
LCFS - Integrate Modernized ReactJS Frontend with LCFS FastAPI Backend

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#95]
**Describe the task**
This task involves integrating a modernized ReactJS frontend into the existing LCFS repository, which currently has a FastAPI backend. This entails creating a new ReactJS project, ensuring that it uses the latest versions of ReactJS and associated libraries, setting up test libraries, and configuring webpack for bundling and optimization.

**Purpose**
The primary purpose of this task is to establish a modern, maintainable, and efficient frontend for the LCFS project. With the latest versions of ReactJS and its libraries, we can leverage improved performance, features, and security enhancements. This also allows for easier scaling and development in the future.

**Acceptance Criteria**
- [ ] Set up a new ReactJS project with the latest versions of ReactJS and associated libraries.
- [ ] Ensure React is accessible and able to be read by a screen reader (criteria added June 22, after card reviewed)
- [ ] Implement test libraries to facilitate automated testing of the ReactJS frontend.
- [ ] Integrate the newly created ReactJS frontend into the existing LCFS repository.
- [ ] Establish a clear and smooth interaction between the ReactJS frontend and FastAPI backend.
- [ ] Test the frontend functionality to confirm successful integration and correct working with the FastAPI backend.

**Additional context**
- During the integration process, maintain focus on creating a project that follows best practices and is easy to maintain and scale.
- The task's success relies not just on technical implementation, but also on ensuring that the new ReactJS project aligns with the existing architecture and coding conventions of the LCFS repository.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/95?planning-poker) with Zenhub @tim738745 @prv-proton @jig-patel @AlexZorkin

**Comment by kcabhar** [comment]
Alex estimates 2 going into Klefki

**Comment by AlexZorkin** [comment]
Initial round of work complete and merged to repo.
