### ISSUE TITLE
LCFS - TFRS teardown, BCeID

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#959]
**Description:**  

This work should be done in a new branch.

https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/187861186
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/187861187
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/187861188

![Image](https://github.com/user-attachments/assets/eef7e47f-26a6-4b79-850c-35cc30a58351)

Remove specific widgets, information, and roles from the dashboard, header, navigation bar, and various user pages:
- Remove from the dashboard:
  - All left column widgets
  - Transactions widget (center column)
  - File submissions widget (center column)
- Remove from the header:
  - Credit information
- Remove from the main navigation bar:
  - Transactions
  - File Submissions
  - Help icon link
- Remove from the Organization Details page:
  - Compliance Units and In Reserve info (top right)
- Remove from the User, Edit User, and Roles pages:
  - File Submission role
  - Credit Transfers role

**Purpose and benefit to user:**  
Streamlines the user interface by eliminating redundant or unnecessary elements from various parts of the platform, leading to a more focused and efficient experience for users.

All components being removed / turned off should be able to be reactivated easily if required later.

**Acceptance Criteria:**  
- [ ] All widgets in the left column of the dashboard are removed.
- [ ] The "Transactions" widget is removed from the center column of the dashboard.
- [ ] The "File submissions" widget is removed from the center column of the dashboard.
- [ ] "Credit information" is removed from the header.
- [ ] The "Transactions" and "File Submissions" links are removed from the main navigation bar.
- [ ] The "Compliance Units" and "In Reserve" information is removed from the top right of the Organization Details page.
- [ ] The "File Submission" and "Credit Transfers" roles are removed from the User, Edit User, and Roles pages.
- [ ] The email Notifications component and pages should be retained

**Development Checklist:**  
- [ ] Remove all widgets from the left column of the dashboard.
- [ ] Remove the "Transactions" widget from the center column of the dashboard.
- [ ] Remove the "File submissions" widget from the center column of the dashboard.
- [ ] Remove the "Credit information" from the header.
- [ ] Remove the "Transactions" and "File Submissions" links from the main navigation bar.
- [ ] Update the Organization Details page to remove the "Compliance Units" and "In Reserve" info from the top right.
- [ ] Update the User, Edit User, and Roles pages to remove the "File Submission" and "Credit Transfers" roles.

**Notes:**  
- Ensure that removing these elements does not affect any other dependencies or related functionalities.
- All components being removed / turned off should be able to be reactivated easily if required later.

**Comment by Grulin** [comment]
Similar to the IDIR view, I am not able to see this change made in the TFRS dev environment. Has this change possibly not been pushed through yet to test? Please let me know. Thank you.

**Comment by hamed-valiollahi** [comment]
> Similar to the IDIR view, I am not able to see this change made in the TFRS dev environment. Has this change possibly not been pushed through yet to test? Please let me know. Thank you.


Thanks, Lindsy, for testing and reporting the issue. As far as I know, in the future, we need to tear down the TFRS. Please correct me if I'm mistaken.

There are a few front-end environmental variables that we can turn on to disable front-end features. I'm not sure if we need to do that immediately. Should we? As far as I know, Alex is the best person to decide on that.

Here are the variables. Currently, they are all set to `false`, which means the features are all visible:

```
'tear_down.bceid.widgets.balance': false,
'tear_down.bceid.widgets.feedback': false,
'tear_down.bceid.widgets.website': false,
'tear_down.bceid.widgets.creditTransactions': false,
'tear_down.bceid.widgets.fileSubmissions': false,
'tear_down.bceid.header.creditInformation': false,
'tear_down.bceid.navigation.transactions': false,
'tear_down.bceid.navigation.fileSubmissions': false,
'tear_down.bceid.navigation.helpLink': false,
'tear_down.bceid.organization.creditInformation': false,
'tear_down.bceid.organization.roles.fileSubmission': false,
'tear_down.bceid.organization.roles.creditTransfers': false,
'tear_down.idir.widgets.balance': false,
'tear_down.idir.widgets.creditTransactions': false,
'tear_down.idir.widgets.fileSubmissions': false,
'tear_down.idir.navigation.transactions': false,
'tear_down.idir.navigation.fileSubmissions': false,
'tear_down.idir.navigation.helpLink': false,
'tear_down.idir.organizations.tableColumns.complianceUnits': false,
'tear_down.idir.organizations.tableColumns.inReserve': false,
'tear_down.idir.organization.creditInformation': false
```

Apologies for not informing you! I thought it was a code change meant for future use.

**Comment by airinggov** [comment]
Thanks Hamed, we'll have to test this beforehand but we can schedule that maybe for our Bug session if we ever get around to that. I assume it is pretty easy to flip these flags.
