### ISSUE TITLE
LCFS - BUG - Allocation agreements

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#968]
**Describe the Bug**

1. If a user selects a Fuel code, but then changes the Determining carbon intensity setting to something else the fuel code selection should be cleared. Right now it just disables the cell with the fuel code still displayed. (Fuel supply form works properly as an example)
2. The CI value should only have 2 decimal place.

![Image](https://github.com/user-attachments/assets/89ff05c8-8f9e-4082-9923-faaf5360cc0a)

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user
1. Go to an Allocation agreement in a compliance report
2. Add a fuel code but then change the Determining carbon intensity selection to something else

**Comment by Grulin** [comment]
The CI of fuel decimal place seems to be limited to 2 places in the input form, but is still not limited on the view of the compliance report once a row has been saved:
![Image](https://github.com/user-attachments/assets/ae664cb7-bb67-4a9b-8295-8d4014fd629b)

The fuel code clears now when you change the determining carbon intensity, but the form does not save. Will make a different card to address this issue.
