### ISSUE TITLE
LCFS - BUG- Notional transfer and report page

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#971]
**Describe the Bug**
Can we remove the trailing gray bar in these areas?

Notional transfer input form
![Image](https://github.com/user-attachments/assets/ec4e30ce-f247-4a3d-8ef3-d8f4ed2f9221)

report main page
![Image](https://github.com/user-attachments/assets/fff4fabb-a8a0-4ff6-a194-c920cbab288e)

**Comment by Grulin** [comment]
This grey bar has been removed from the main report page, but is still visible on the input page for notional transfers and fuels for other use  :

![Image](https://github.com/user-attachments/assets/81d866f8-3e6d-42b5-a6c3-55fd1fd65708)
![Image](https://github.com/user-attachments/assets/e467c7e6-3e34-4ee9-a748-74273e6dd9b7)

**Comment by dhaselhan** [comment]
Grey bars should be fixed on other tables, ready for a re-test.
