### ISSUE TITLE
LCFS - BUG - Validation alert, screen real estate

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#973]
**Describe the Bug**
Can we reserve the screen real estate for the validation/error alert? Presently when the bar disappears the table bumps up. This would be on all schedules and forms with validation.

Relocate alert to directly under the table (above New row and Save button).

![Image](https://github.com/user-attachments/assets/671abaef-fd28-4eb3-be3d-bfbb3d2978ac)

**Expected Behaviour**

**Comment by hamed-valiollahi** [comment]
Thanks for reporting the issue, Lindsy! It's now resolved.
