### ISSUE TITLE
LCFS - User Management Integration and Component Update

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#98]
**Describe the task**
The task involves integrating User Management views from a frontend ReactJS project into a new repository while aligning with the FastAPI system. It also involves modernizing the codebase by updating any User Management class-based components to functional-based components.

**Purpose**
This task aims to integrate User Management into the frontend of our application, using modern ReactJS conventions and aligning with the FastAPI backend system for improved functionality and streamlined code maintenance.

**Acceptance Criteria**
- [ ] Identify and include necessary User Management views in the new repository.
- [ ] Convert any User Management class-based components to functional-based components.
- [ ] Integrate User Management views with appropriate backend API endpoints.
- [ ] Validate functionality of integrated User Management views through various operations.
- [ ] Ensure all User Management tests pass successfully.
- [ ] Update documentation and code comments to reflect the integration process and component updates.

**Additional context**
- Prioritize maintaining a coherent and modern codebase during integration and conversion processes.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/98?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by AlexZorkin** [comment]
closed for redundancy
