### ISSUE TITLE
LCFS - Deployment - Setup ClamAV and S3 buckets

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/lcfs#984]
- ClamAV deployed in Tools namespace ready for use
- Three S3 Bucket created in Dell ECS, one for dev, test and prod
- Provide the connection details for both ClamAV and Dell ECS

**Comment by kuanfandevops** [comment]
@dhaselhan We have the S3 buckets created on Object Stored which managed by our mid-tier team. 
Five argument will be provided for S3 connection:
ACCESS_KEY_ID, SECRET_ACCESS_KEY, ENDPOIN, BUCKET and DOCS_PATH 
Two ClamAV arguments:
CLAMAV_HOST and CLAMAV_PORT

You can name the variables and they will be provided as environment variables for backend

**Comment by kuanfandevops** [comment]
@dhaselhan 

The following environment variables have been added to backend.

  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: lcfs-object-storage-dev
        key: BUCKET
  - name: S3_USER_ID
    valueFrom:
      secretKeyRef:
        name: lcfs-object-storage-dev
        key: USER_ID
  - name: S3_KEY
    valueFrom:
      secretKeyRef:
        name: lcfs-object-storage-dev
        key: KEY
  - name: S3_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: lcfs-object-storage-dev
        key: ENDPOINT
  - name: S3_DOCS_PATH
    value: lcfs-docs
  - name: CLAMAV_HOST
    value: lcfs-clamav-dev.d2bd59-dev.svc.cluster.local
  - name: CLAMAV_PORT
    value: 3310

**Comment by kuanfandevops** [comment]
The dev build should work. But the pr build doesn't until I can spin up a saperate minio instance for each pr as I don't want to store the docs for pr testing on object storage.

**Comment by kuanfandevops** [comment]
The pr build is fixed. A minio instance will be spinning up for each pr build and acts as S3 storage.
