### ISSUE TITLE
LCFS - Add prefixes to transactions in Excel download

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#988]
**Describe the task**
Add transaction prefixes to the Excel file download from the Transactions page. Currently, the ID column in the exported Excel file does not include prefixes such as:

- "AA" for Admin Adjustment
- "IA" for Initiative Agreement
- "CT" for Credit Transfer
- "CR" Compliance Report

These prefixes are essential because the transaction numbers repeat for each type of transaction, and the prefixes help distinguish the type of transaction associated with each ID.

**Purpose**
To ensure that transaction IDs in the Excel download are complete and accurate by including prefixes that identify the type of transaction. This will improve clarity and prevent confusion when reviewing transactions, especially when multiple types share the same numeric sequence.

**Acceptance Criteria**

- [ ]  The ID column in the Excel file download from the Transactions page includes the appropriate prefixes:
- "AA" for Admin Adjustments
- "IA" for Initiative Agreements
- "CT" for Credit Transfers
- "CR" Compliance Report
- [ ] Prefixes are correctly applied to the corresponding transaction IDs in the exported Excel file.
- [ ] The updated file format is reviewed and confirmed to ensure that all relevant transactions are accurately labeled.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Grulin** [comment]
I see the correct assignment of the transaction type in the "type" column, but we would like the prefix to be added to the ID number in the "ID column" for this Excel Sheet. For example, you can see in the screen shot that their are 2 transactions with a #10 ID number. One of these should be AA10 because it's an admin adjustment and the other should be CT10 because it is a credit transfer:
![Image](https://github.com/user-attachments/assets/fce38c2a-45de-45f7-b981-6342766007ef)

**Comment by dhaselhan** [comment]
Blocked on #1048
