### ISSUE TITLE
LCFS - Organization Management Integration and Component Update

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#99]
** This ticket needs to be re-worked once wireframes are available.

**Describe the task**
This task involves integrating Organization Management views from a frontend ReactJS project into a new repository. It further requires updating any Organization Management class-based components to functional-based components, in line with modern ReactJS conventions.

**Purpose**
This task is designed to integrate Organization Management into the frontend of our application, providing a seamless user experience, aligning with the FastAPI backend system, and adopting modern coding practices for easier code maintenance.

**Acceptance Criteria**
- [ ] Identify and include necessary Organization Management views in the new repository.
- [ ] Convert any Organization Management class-based components to functional-based components.
- [ ] Integrate Organization Management views with appropriate backend API endpoints.
- [ ] Validate functionality of integrated Organization Management views through various operations.
- [ ] Ensure all Organization Management tests pass successfully.
- [ ] Update documentation and code comments to reflect the integration process and component updates.

**Additional context**
- Emphasis should be placed on maintaining a clean, efficient, and modern codebase during the integration and conversion processes.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/99?planning-poker) with Zenhub @AlexZorkin @jig-patel

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/99?planning-poker) with Zenhub @prv-proton

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/lcfs/99?planning-poker) with Zenhub @tim738745

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
