### ISSUE TITLE
LCFS - IDIR user with a director role dashboard widget counter

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#992]
**Describe the Bug**
IDIR users with a director role are currently unable to see the count of recommended transfers, Initiative Agreement (IA) agreements, Admin Adjustments, and recommended Compliance Reports from managers on the "Director Review" widget on the dashboard. 

This widget is intended to provide an overview of transfers, reports, and transactions that require director-level approval or recording, but it is not functioning as intended. 

Additionally, the widget title "Director Review" should use a lowercase "r" in "review" to align with design standards.

**Expected Behaviour**
- The Director Review widget should display the count of:
- Recommended Transfers
- IA Agreements
- Admin Adjustments
- Recommended Compliance Reports from managers
- The title of the widget should be "Director review" (with a lowercase "r").

**Actual Behaviour**
- The widget is not showing any counts for the relevant items, preventing directors from easily accessing information on what requires their attention.
- The title currently reads "Director Review" with an uppercase "R" in "review," which does not conform to design standards.

**Implications**
- Directors are unable to see at-a-glance counts of the transfers, reports, and transactions that require their review and approval, reducing the efficiency of the dashboard.
- The inconsistency in the title formatting does not adhere to the design standards, affecting visual consistency.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: Log in as an IDIR user with a Director role.

1. Navigate to the Dashboard.
2. Look at the Director Review widget and observe that the counts for Recommended Transfers, IA Agreements, Admin Adjustments, and Recommended Compliance Reports are not displayed.
3. Notice that the widget title reads "Director Review" instead of "Director review".

**Comment by airinggov** [comment]
I'm not getting any counts, all are appearing 0 even though there should be numbers.

**Comment by hamed-valiollahi** [comment]
Hi Al, Thank you for testing and reporting the issue. It was caused by a difference in environments. I created a PR to fix it.

**Comment by Grulin** [comment]
The Compliance report link is showing a count of "1" which is correct, there is a compliance report awaiting director review, but when I select the link, the filter is not showing the report that has a "recommended by manager" status:
![Image](https://github.com/user-attachments/assets/39a4296b-a73a-4fa6-aa05-5c659caeb966)

**Comment by Grulin** [comment]
Blocked from testing as there seems to be a filtering error stuck on the IDIR ride for transactions. 

Also, the transactions view table is not defaulting to "all organizations". Tested in all 3 IDIR roles

**Comment by hamed-valiollahi** [comment]
Thanks, Lindsy, for testing and reporting the issue!
I fixed it. There was a minor issue: a line that calls the API had been removed, probably by mistake. Everything is working fine now, and the changes are now live on dev.

**Comment by hamed-valiollahi** [comment]
Not sure why the "Director Review" widget links have stopped working and are not showing the correct transactions or compliance reports when clicked! Previously, it was working fine. I'll look into this issue right away and resolve it. I'll let you know as soon as I test it on the dev env.

**Comment by Grulin** [comment]
Hi @hamed-valiollahi Thanks for the fix. This is working great now!
