### ISSUE TITLE
LCFS - Bug when trying to update inputs in line 6 and 8 of the compliance report summary

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#997]
**Describe the Bug**
When attempting to remove or change inputs on lines 6 and 8 of the Compliance Report Summary, a "Status code 422" error appears. 

Additionally, if changes are made to the schedules that affect the renewable fuel supply or requirement, lines 6 and 8 do not update accordingly. The inputs in lines 6 and 8 persist as they were initially entered, even if the requirements have changed based on updated fuel supply data in the schedules. 

While it is important for these lines to persist when the report is left and reopened in the same session, they should also automatically update when relevant changes are made and be resaved with the new conditions for line availability, the maximum amount allowed, and the amount input.

**Expected Behaviour**
- Lines 6 and 8 should allow users to remove or change inputs without encountering a "Status code 422" error.
- When changes are made in the schedules that impact the renewable fuel supply or requirement, lines 6 and 8 should automatically update to reflect the new conditions.
- Line availability, the maximum amount allowed, and the amount input should update dynamically when changes in other schedules affect them.
- Inputs on lines 6 and 8 should persist if the report is left and reopened, but they should also resave correctly with the updated data when changes are made.

**Actual Behaviour**
![Image](https://github.com/user-attachments/assets/2790627f-ee7a-442b-a054-1825467594c6)

- Users receive a "Status code 422" error when attempting to remove or change inputs on lines 6 and 8.
- Inputs on lines 6 and 8 do not automatically update when changes are made to the renewable fuel supply or requirement in other schedules.
- Lines 6 and 8 persist with outdated information, even when the conditions in the schedules have changed.

**Implications**
- Users are unable to accurately update lines 6 and 8 based on changing fuel supply and requirement data.
- The system does not reflect changes in renewable fuel supply, leading to potential inaccuracies in the Compliance Report Summary.
- Users are encountering errors that prevent them from effectively managing their compliance reporting.

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. User/Role: Navigate to the Compliance Report Summary as a BCeID user.
2. Attempt to remove or change an input on line 6 or 8.
3. Observe the "Status code 422" error that appears.
4. Make changes in the schedules that affect the renewable fuel supply or requirement.
5. Check lines 6 and 8 and observe that they do not update based on the changes made in the schedules.

**Comment by dhaselhan** [comment]
How should the lines update based on the schedules? e.g my original renewable requirement was 1000, so I defer 40 (4%), then I change the quantity to 500, should the input show 20 (the new maximum) or 0?

**Comment by Grulin** [comment]
I think it should reset to "0" like it does in TFRS. Perhaps we should also add the pop-up that TFRS gives when you changes values. It says this:
![Image](https://github.com/user-attachments/assets/c30a5860-93dd-4e71-a3c1-0feec6cbb009)

I can make a separate card for the pop-up if that's what we want to do, so for now, I'd say reset both 6 and 8 to zero if changes are made to the renewable requirement (line 4). Thanks for catching this!

**Comment by dhaselhan** [comment]
As discussed with Lindsy, the pop up will be its own card we do later. Logic is now updated that if the fuel requirements change for a certain category, it will reset lines 6/8 to 0 for that category.
