### ISSUE TITLE
LCFS - In reserve compliance units are not showing properly

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#998]
**Describe the Bug**
The feature that reflects in reserve compliance units in parentheses in the top right-hand corner of an organization's Compliance Unit Balance is not functioning correctly. This feature is supposed to display any pending transfers as in reserve amounts, which ensures that these units are not included in the organization's total or available balance within the compliance period. Currently, this feature is not working, causing in reserve units to not be properly reflected.

**Expected Behaviour**
- The in reserve compliance units should be displayed in parentheses in the top right-hand corner of an organization's Compliance Unit Balance.
- This feature should reflect any pending transfers as in reserve, ensuring that these units are not included in the total or available balance within the compliance period.

**Actual Behaviour**
- The in reserve compliance units are not being reflected in parentheses as intended.
- Pending transfers are not correctly shown as in reserve, leading to potential inaccuracies in the organization's compliance unit balance.

**Implications**
- Organizations are unable to accurately track their available compliance units and may unintentionally fall short of their compliance unit obligations.
- The system does not account for in reserve units, which could result in overestimation of an organization's compliance unit balance, causing confusion and potentially leading to non-compliance.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. User/Role: Navigate to an organization's Compliance Unit Balance with a BCeID user account
2. Initiate a pending transfer.
3. Observe that the in reserve compliance units are not reflected in parentheses in the top right-hand corner of the balance.
4. Confirm that these units are still included in the total balance instead of being marked as in reserve.

**Comment by dhaselhan** [comment]
Talked to Lindsy, in TFRS only Submitted Transfers show as in reserve, but not Submitted Compliance Reports. The decision was made to keep the behavior this way, so I removed compliance reports from the ticket.
